{
  "hash": "fd72497c2019434f8aa75d764ca4ae9e",
  "result": {
    "engine": "knitr",
    "markdown": "# Sparse testing: which hybrids go to which locations {#sec-sparse}\n\n\n\nA hybrid programme's first field stage concentrates most of its selection\npressure where it has the least information. It typically has thousands of\ntestcrosses, seed for one or two plots of each, a handful of locations, and\nalmost no replication. The previous chapter (@sec-mating) asked **which crosses**\nto make from two pools. This one asks the next question: given the crosses,\n**which locations should each one be planted in?**\n\n*Sparse testing* is the answer the literature has converged on. Not every hybrid\nis grown at every location. Different subsets go to different environments, and\nthe missing hybrid x environment cells are *predicted*, not discarded, with a\nrelationship matrix connecting what the field left unconnected. In @sec-mating\nthe sparsity was in the female x male grid. Here it is in the hybrid x\nenvironment grid. Real programmes face both at once, the joint problem\n@sec-mating-open lists as its second gap.\n\nThe chapter covers the quantitative basis, the history and a taxonomy of the\ndesigns, the validation schemes used to judge them, and the empirical record\nacross crops, including its main controversy. It then measures the question\nwith a simulation that the primary literature had not run. The results it\ndefends:\n\n1. **At a fixed number of plots, spreading them over more locations beats\n   concentrating them.** Spreading two plots per hybrid over ten locations\n   instead of two raises accuracy by 0.06 to 0.09, with no extra plots.\n2. **The choice among sparse layouts matters little, except at extreme\n   sparsity.** At that point, a layout that puts *both pools in every location*\n   helps the hybrids that were never tested.\n3. **What connects a sparse trial is parent coverage, not shared hybrids.** With\n   a relationship matrix in the model, the best layouts share *no* hybrid\n   between some location pairs. This suggests one way to reconcile the\n   contradictory published advice on overlap between environments.\n4. **Prediction survives sparsity better than estimation.** The BLUP stays\n   undispersed down to one location per hybrid. Variance components stop being\n   reportable earlier, and the SCA variance is biased upward even in the\n   complete design.\n\n::: {.callout-note}\n## Where the numbers come from\n\nThere are three sources, kept apart throughout.\n\n- **Live** results are computed at render time with `R/17_sparse_testing.R`:\n  - allocation generators;\n  - connectivity diagnostics;\n  - a base-R mixed-model solve with **known** variance components, checked\n    against a literal GLS oracle (`ref_sparse_blup()`).\n- **Cached** results come from a separate study and are not reproducible from\n  this repository. That study estimated components by REML with `sommer` on\n  2,630 fits, ran a two-stage scenario, and added an AlphaSimR genomic layer.\n  Its tables are in `book/data/sparse_*.csv`.\n- **In-repo** results come from `Rscript book/scripts/regenerate.R sparse`,\n  which reruns the phenotypic core with known components\n  (`sparse_core_sweep.csv`). That sweep also adds an experiment the cached\n  study did not run (@sec-sparse-overlap). The two are compared in\n  @sec-sparse-reproduce.\n\nThe literature numbers are from six primary papers: @li2026, @atanda2022,\n@werner2025, @lubanga2025, @gonzalezdieguez2026 and @hildaono2026. Each one was\nread in full. **@werner2025 is a preprint that has not been peer reviewed.**\n:::\n\n## The allocation problem of stage 1 {#sec-sparse-problem}\n\n### The economics of the first stage\n\nStage 1 is where a plot costs least and a decision is worth most. In CGIAR\nprogrammes most of the selection pressure is applied on a few research stations,\noften as visual selection in unreplicated nurseries [@werner2025;\n@atlin2022]. Two shifts have changed this stage:\n\n- **Genotyping is no longer the bottleneck. Phenotyping is.** The cost of a\n  marker has fallen steadily for two decades, while the cost of a yield plot has\n  not [@lorenz2013].\n- **Doubled haploids reversed the constraint.** A programme now makes more\n  candidates than it can evaluate [@longin2006b]. Allocating plots, not\n  creating variation, has become the limiting factor.\n\nWhat is left is the classical trade-off. More genotypes at fewer locations buys\nselection intensity and costs accuracy. Fewer genotypes at more locations does\nthe opposite. At stage 1 the scarce resource is the plot, so the question is not\n*how much to test* but *how to spread what can already be tested* [@li2026].\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A two-pool hybrid pipeline. Population improvement (left) feeds product development (right). Candidate numbers fall by an order of magnitude per stage while plots per candidate rise. Sparse testing applies where the plots per candidate are fewest: the first testcross trial.](04f-sparse-testing_files/figure-typst/fig-sparse-pipeline-1.svg){#fig-sparse-pipeline fig-align='center'}\n:::\n:::\n\n\n### The breeder's equation as the decision criterion\n\nThe gain per unit time,\n\n$$\n\\Delta G_t = \\frac{i \\, r \\, \\sigma_A}{t},\n$$\n\nhas four terms. A trial design moves at least three of them together:\n\n- **intensity $i$**, through the number of candidates;\n- **accuracy $r$**, through plots, locations, and how well the locations sample\n  the target population of environments (TPE);\n- **cycle length $t$**, when parents can be recycled from stage 1.\n\nWhat a gain measured on a research station is worth depends on the genetic\ncorrelation between the selection environment and the TPE [@atlin2000;\n@atlin2001]. No design is better in the abstract. A design is better according\nto whichever term limits that programme [@werner2025trends;\n@riedelsheimer2013].\n\n::: {.callout-tip}\n## Box 1 -- Where each term of the breeder's equation meets the trial design\n\n| Term | Design decision that moves it |\n|---|---|\n| $i$ (intensity) | number of candidates tested at a fixed plot budget |\n| $r$ (accuracy) | plots per candidate, locations per candidate, use of a relationship matrix |\n| $r$ (relevance) | how well the chosen locations sample the TPE |\n| $\\sigma_A$ | indirectly: which parents are recycled, and how related they are (@sec-ocs) |\n| $t$ | whether stage-1 GCA predictions are good enough to recycle parents immediately |\n:::\n\n## Foundations {#sec-sparse-foundations}\n\n### The hybrid model: GCA, SCA, and what sparsity threatens\n\nThe value of the single cross between female $i$ and male $j$ splits as\n\n$$\ng_{ij} = \\mathrm{GCA}^f_i + \\mathrm{GCA}^m_j + \\mathrm{SCA}_{ij}\n$$\n\n[@sprague1942]. @sec-heterosis-gca-sca derives this split from allele\nfrequencies. Its consequence for this chapter is that a line's GCA includes\ndominance effects weighted by the *opposite* pool's frequencies. A GCA is\ntherefore specific to the tester pool, not a property of the line alone\n[@gonzalezdieguez2021; @legarra2023]. The ratio $\\sigma^2_{SCA}/\\sigma^2_{GCA}$\nis a design parameter. It grows with the mean degree of dominance and with how\nclose the pools are. In simulated maize it was 0.05, 0.23 and 0.50 for mean\ndominance degrees of 0.1, 0.5 and 0.9 [@gonzalezdieguez2026].\n\nGCA survives sparsity better than SCA because it is mostly additive and more\nstable across environments. @li2026 recovered GCA from a prediction-completed\n50 % trial with correlations of 0.94 to 0.97 against the complete data. Over the\nsame scenarios, phenotypic prediction accuracy was 0.43 to 0.59. **What stage 1\nneeds to estimate is GCA, and GCA is the part of the model most robust to missing\ncells.** That is the underlying reason sparse testing works in hybrids.\n\n::: {.callout-tip}\n## Quick glossary\n\n- **GCA**: a line's average performance in crosses with the opposite pool.\n- **SCA**: the deviation of a particular cross from the sum of its parents' GCAs.\n- **Mid-parent heterosis**: the hybrid's advantage over the mean of its parents\n  (@sec-heterosis).\n- **Heterotic pool**: a group of lines bred to cross well with another group.\n- **Tester**: a line of the opposite pool used to evaluate candidates.\n- **TPE**: the target population of environments the product is sold into.\n:::\n\n### Hybrid relationship matrices\n\nWith female and male relationship matrices $\\mathbf{A}_f$ and $\\mathbf{A}_m$,\nthe three hybrid terms are distributed as\n\n$$\n\\mathrm{GCA}^f \\sim N(\\mathbf 0, \\mathbf A_f\\sigma^2_{f}), \\quad\n\\mathrm{GCA}^m \\sim N(\\mathbf 0, \\mathbf A_m\\sigma^2_{m}), \\quad\n\\mathrm{SCA}   \\sim N(\\mathbf 0, (\\mathbf A_f\\otimes\\mathbf A_m)\\sigma^2_{s})\n$$\n\n[@bernardo1994; @bernardo1996; @technow2012]. The practical point is that\n**the hybrid itself never needs genotyping**: its covariance is a Kronecker\nproduct of the parental matrices. Replacing pedigree $\\mathbf A$ by marker $\\mathbf G$\n[@vanraden2008] gives the genomic version (@sec-genomic-prediction). There are\ntwo ways to write the additive and dominance effects: the \"biological\" form and\nthe \"statistical\" form, which is orthogonal at the population's frequencies.\nPool-specific marker effects are a third option [@vitezica2013;\n@gonzalezdieguez2021]. All of them lead to the same covariance structure.\n\n**The relationship matrix is what makes a sparse design analysable.** It is the\nonly link between cells that the field did not link. A hybrid with no plot gets\na BLUP only because its parents are related to parents that do have plots.\nWithout it, a sparse design yields comparisons that are not fair.\n\n### Multi-environment trials and mixed models\n\nHow many parameters the between-environment covariance spends ranges widely:\n\n- identity, diagonal, or compound symmetry;\n- heterogeneous AR(1);\n- unstructured;\n- factor-analytic [@smith2001; @smith2005; @kelly2007; @smith2018].\n\nFactor-analytic models carry most of the information of the unstructured matrix\nat a fraction of its parameters, and extend directly to genomic relationships\n[@oakey2016; @tolhurst2019; @burgueno2012]. Reaction-norm and marker x\nenvironment models are cheaper alternatives [@jarquin2013; @lopezcruz2015].\nOnly *crossover* G x E changes selection decisions. A scale effect does not.\n\n**In a sparse design the between-environment covariance stops being a\nstatistical detail and becomes part of the design.** It decides how much one\nenvironment can tell us about another. Two-stage analyses that carry the\nfirst-stage error forward are now as efficient as one-stage ones\n[@piepho2012; @endelman2023]. Unreplicated trials still need spatial correction\nand checks [@robbins2012; @cullis2006].\n\n::: {.callout-tip}\n## Box 2 -- Which heritability to report in a sparse trial\n\n| Quantity | Formula | What it answers | Behaviour under sparsity |\n|---|---|---|---|\n| Plot-level $h^2$ | $\\sigma^2_G / (\\sigma^2_G + \\sigma^2_{GE} + \\sigma^2_e)$ | how informative one plot is | design-independent; it is what the simulations below fix |\n| Entry-mean $H^2$ | $\\sigma^2_G / (\\sigma^2_G + \\sigma^2_{GE}/L + \\sigma^2_e/(rL))$ | how informative an entry mean is, if every entry had $L$ locations and $r$ reps | undefined when entries have different $L$, i.e. in every sparse design |\n| Generalised (Cullis) $H^2$ | $1 - \\overline{\\mathrm{PEV}} / (2\\sigma^2_G)$ for pairwise differences [@cullis2006; @piepho2007] | how well the analysed design ranks entries | the right one: it uses the actual PEVs |\n\nThe entry-mean formula silently assumes balance. In a sparse trial, report\nCullis'.\n:::\n\n## What sparse testing is, and where it came from {#sec-sparse-what}\n\n### Definition and genealogy\n\n**Definition.** A trial is sparse when not every genotype is evaluated in every\nenvironment *and* the missing cells are predicted rather than discarded. The idea\ndeveloped in four steps:\n\n1. **Incomplete blocks and lattices.** These already accepted partial\n   evaluation *within* a location.\n2. **Partially replicated designs (p-rep) and augmented p-rep.** These replaced\n   replication of each entry with replicated checks and partial replication\n   [@cullis2006; @williams2011].\n3. **The genomic relationship replacing replication** [@endelman2014]. With\n   markers, the replicated unit is no longer the genotype but the haplotype,\n   shared among relatives.\n4. **Genomic sparse testing across environments, formalised** [@jarquin2020].\n   The design was later framed explicitly as a balanced incomplete block design\n   in which the block is the environment [@montesinoslopez2023].\n\n**Farm-as-incomplete-block** is the limiting case. Each farmer's field is an\nincomplete block holding a handful of entries, and the TPE is sampled through\nhundreds of them [@werner2025trends; @werner2025; @atlin2001].\n\nSparse testing is not a new method. It is incomplete-block design applied at\nthe scale of many environments, made workable by genomic relationships acting as\nthe connecting mechanism. The classical theory of incomplete blocks therefore\ncarries over.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The genealogy of sparse testing, drawn as genotype (rows) x environment (columns) matrices; dark = observed. From the complete trial, to incomplete blocks within locations, to p-rep (a few entries and checks replicated), to genomic sparse testing (each entry in a subset of environments, connected through relationships), to farm-as-incomplete-block (many environments, very few entries each).](04f-sparse-testing_files/figure-typst/fig-sparse-genealogy-1.svg){#fig-sparse-genealogy fig-align='center'}\n:::\n:::\n\n\n### A taxonomy of sparse designs\n\nThe designs can be classified along three independent axes.\n\n**Axis of sparsity.**\n\n- *Environments*: the classical case.\n- *Testers*: sparse testcrossing (@sec-sparse-testcross).\n- *Female x male combinations*: the incomplete factorials of @sec-mating-sparse.\n- Any combination of these.\n\n**Overlap structure.**\n\n- full overlap, with a common core in every environment;\n- no overlap;\n- partial overlap, with a fixed core plus entries unique to each environment;\n- unrestricted random allocation;\n- restricted random allocation, for example keeping full-sibs out of the same\n  location [@werner2025];\n- allocation optimised against a formal criterion [@isidroysanchez2021;\n  @fernandezgonzalez2023].\n\n**Replicated unit.** Genotype, family, or haplotype.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(5)\ncore6 <- function(n_core) {               # a common core + unique entries\n  M <- matrix(0L, 32, 6); M[seq_len(n_core), ] <- 1L\n  rest <- setdiff(1:32, seq_len(n_core))\n  M[cbind(rest, rep_len(1:6, length(rest)))] <- 1L; M\n}\ntax <- list(\"Complete\"          = sparse_alloc(8, 4, 6, strategy = \"complete\"),\n            \"Full overlap core\" = { M <- matrix(0L, 32, 6); M[1:10, ] <- 1L; M },\n            \"Core + unique\"     = core6(5),\n            \"No overlap\"        = core6(0),\n            \"Random, k = 2\"     = sparse_alloc(8, 4, 6, 2, \"random\"),\n            \"Parentage, k = 2\"  = sparse_alloc(8, 4, 6, 2, \"parentage\"))\nop <- par(mfrow = c(1, 6), mar = c(1, 0.5, 2.2, 0.5))\nfor (nm in names(tax)) {\n  image(t(tax[[nm]][32:1, ]), col = c(\"grey95\", \"#1b6ca8\"), zlim = c(0, 1), axes = FALSE,\n        main = sprintf(\"%s\\n(%d plots)\", nm, sum(tax[[nm]])), cex.main = 0.8)\n  box(col = \"grey60\")\n}\npar(op)\n```\n\n::: {.cell-output-display}\n![Six allocations of the same 8 x 4 factorial (32 hybrids, rows; male index fastest) to six locations (columns), each with the same number of plots except 'complete'. The last three are generated by the package's `sparse_alloc()`. 'Parentage' puts every female and every male in every location.](04f-sparse-testing_files/figure-typst/fig-sparse-taxonomy-1.svg){#fig-sparse-taxonomy fig-align='center'}\n:::\n:::\n\n\n| Design | Sparsity axis | Overlap | Example | Reference |\n|---|---|---|---|---|\n| Full overlap (common core only) | environments | full | Li et al. \"CV1\" allocation | @li2026 |\n| Random cells, $\\ge 1$ per genotype | environments | random | Li et al. \"CV2\"; Jarquin's allocation schemes | @li2026; @jarquin2020 |\n| Balanced by genotype (one environment each) | environments | none | Li et al. \"CV3\"; Lubanga NOL | @li2026; @lubanga2025 |\n| Core + unique entries | environments | partial | Li et al. \"CV5\"; Atanda overlap series | @li2026; @atanda2022 |\n| Restricted random, full-sibs apart | environments | random | farm-as-incomplete-block | @werner2025 |\n| One tester per line, sibs across testers | testers | none at line level | sparse testcrossing | @gonzalezdieguez2026 |\n| Incomplete factorial | female x male | partial | sparse factorials | @seye2020; @lorenzi2022 |\n\n: The taxonomy mapped onto the designs in the literature. Different names often describe the same structure. {#tbl-sparse-taxonomy}\n\n::: {.callout-warning}\n## A naming collision to watch for\n\n@li2026 use **\"CV1\" to \"CV5\" as names of allocation strategies**, not of the\nclassical validation schemes of @sec-sparse-validation. Their \"CV1\" is the\nfull-overlap *design*. It is not the \"new genotype\" *validation* of\n@burgueno2012. Reading the two literatures together without noticing this\nproduces wrong comparisons.\n:::\n\n## Validation schemes: what each one answers {#sec-sparse-validation}\n\nThe classical schemes are defined by two questions. Has the genotype been\nobserved anywhere? Has the environment been observed for anyone?\n[@burgueno2012; @jarquin2020]\n\n- **CV2**: the genotype is observed in some environments and missing in others.\n  The task is to *complete the table*.\n- **CV1**: the genotype is new, never observed anywhere. The task is to *predict\n  an unseen candidate*.\n- **CV0**: the environment is new (next year, say) and the genotypes are known.\n  The task is to *extrapolate to an untested environment*.\n- **CV00**: both the genotype and the environment are new. This is the hardest\n  case, and the most realistic for long-run decisions.\n\nCV2 will always look better than CV1. Comparing accuracies across papers that\nuse different schemes is therefore a common and serious error [@li2026;\n@nguyen2023]. The correlation is not the only metric:\n\n- top-$x$ % coincidence: top 20 % by a Smith-Hazel index in @atanda2022, top 50\n  % in @li2026;\n- mean squared error [@lubanga2025];\n- Kendall's $\\tau$ [@hildaono2026];\n- PEV and reliability, and the dispersion slope $b_1$ of truth on prediction.\n\nAt stage 1 the operationally relevant number is the **rate of wrongly discarded\nsuperior candidates**. The correlation is only a proxy for it.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The four validation schemes as a 2 x 2 by whether the genotype (rows) and the environment (columns) were observed. Blue: training cells. Orange: the cells to be predicted.](04f-sparse-testing_files/figure-typst/fig-sparse-cv-1.svg){#fig-sparse-cv fig-align='center'}\n:::\n:::\n\n\n::: {.callout-tip}\n## Box 3 -- CV0, CV1, CV2 and CV00\n\n|  | Environment observed | Environment new |\n|---|---|---|\n| **Genotype observed** | **CV2**: fill a missing cell. *\"How does hybrid H do at location L, where it was not planted?\"* | **CV0**: *\"How will the known hybrids do next year?\"* |\n| **Genotype new** | **CV1**: *\"How good is a hybrid that was never planted?\"* In this chapter's simulation, 20 % of hybrids per replicate | **CV00**: *\"How good will an untested hybrid be next year?\"* |\n\nIn the simulation below, `acc_cv1` and `acc_cv2` are measured exactly in this\nsense.\n:::\n\n## The empirical record across crops {#sec-sparse-evidence}\n\n@tbl-sparse-primary puts the six primary studies side by side. There are two\nmaize studies, one of which is a simulation of reciprocal recurrent selection.\nThe others cover wheat, cassava and potato, and one simulates a self-pollinated\ncrop. Supporting studies cover wheat [@crespoherrera2021; @sukumaran2018],\nsugarcane [@garciaabadillo2024], soybean [@persa2023], tropical maize\n[@atanda2021] and potato [@proma2026].\n\n\n::: {#tbl-sparse-primary .cell layout-align=\"center\" tbl-cap='The six primary studies. \\'Observed\\' is the share of genotype x environment cells (or the equivalent) with data.'}\n\n```{.r .cell-code}\nknitr::kable(ps[, c(\"study\", \"crop\", \"genotypes\", \"environments\", \"observed\",\n                    \"model\", \"accuracy\", \"conclusion\")],\n             col.names = c(\"Study\", \"Crop\", \"Genotypes\", \"Environments\", \"Observed\",\n                           \"Model\", \"Accuracy\", \"Conclusion\"))\n```\n\n::: {.cell-output-display}\n\n\n|Study                         |Crop                         |Genotypes     |Environments             |Observed                   |Model                                                   |Accuracy                                                          |Conclusion                                                                       |\n|:-----------------------------|:----------------------------|:-------------|:------------------------|:--------------------------|:-------------------------------------------------------|:-----------------------------------------------------------------|:--------------------------------------------------------------------------------|\n|Li et al. 2026                |maize                        |264           |6 locations x 1 year     |16.7-83.3%                 |multi-environment GBLUP (reaction norm best)            |0.418 (full overlap) vs 0.479-0.504                               |Diminishing returns past ~50% of cells; full overlap is the worst allocation     |\n|Atanda et al. 2022            |spring wheat                 |280           |6 selection environments |16.4-58.9% per environment |GBLUP / PBLUP, XFA G x E, AR1 x AR1 spatial             |+42% to +989% from 0 to 50% overlap                               |Substantial overlap of lines between environments recommended                    |\n|Werner et al. 2025 (preprint) |simulated selfer             |2000          |1-440 locations          |p-rep 0.1 on 2,200 plots   |GBLUP with GRM, restricted randomisation                |sparse 4.32-4.48 vs conventional 2.84-3.67                        |Every sparse scheme beat every conventional one; most of the gain by 5 locations |\n|Lubanga et al. 2025           |cassava                      |435           |5 location-years         |10.8-20.0% per environment |reaction norm, E + L + G + G x E                        |max 0.53 (dry matter) / 0.47 (yield)                              |More overlap HURT at fixed training size; 20% of records suffice                 |\n|Gonzalez-Dieguez et al. 2026  |maize hybrids, simulated RRS |1200 per pool |1-1200 testers           |1 testcross per line       |pool-specific additive + dominance RRBLUP               |+3/11/23% GCA accuracy with 10 testers (low/mid/high dominance)   |Plateau at 5-10 testers; 3-5 recommended                                         |\n|Hild Aono & Chawade 2026      |potato                       |256           |3 location-years         |10-66%                     |BGLR with genomic and image-derived environment kernels |0.995-0.997 (image kernel) vs 0.612-0.798 (genomic), pairs at 50% |Image kernel wins from ~30% completeness; possible information leakage           |\n\n\n:::\n:::\n\n\nThe anchor numbers are as follows.\n\n- **Maize** [@li2026]. Mean accuracy was 0.418 under full overlap and 0.479 to\n  0.504 under every other allocation. Returns diminish beyond about 50 %\n  coverage: going from 50 % to 67 % cost 33 % more phenotyping and returned 3.5\n  to 5.4 % accuracy. Top-50 % coincidence was above 61.9 % in all 25 strategies.\n- **Wheat** [@atanda2022]. Going from 0 to 50 % common lines raised predictive\n  ability by 42 % to 989 %, depending on the environment. Plot $h^2$ was 0.18 in\n  the worst environment. Genetic correlations between environments in the same\n  year ranged from $-0.04$ to $0.67$.\n- **Cassava** [@lubanga2025]. With 20 % of records per environment, predictive\n  ability was moderate (maxima of 0.53 for dry matter and 0.47 for fresh root\n  yield). Phenotyping cost could be cut by up to 80 %.\n- **Potato** [@hildaono2026]. For pairs of environments at 50 % completeness,\n  $r^2$ was 0.995 to 0.997 with an image-derived environment kernel, against\n  0.612 to 0.798 with the genomic kernel. Section @sec-sparse-phenomics covers\n  the caveat.\n\nThe common denominator is the **genetic correlation between environments, and\nthe size and diversity of the training set**. Together they explain most of the\nspread. In @atanda2022, the environment with low heritability and weak\ncorrelations stayed poorly predicted under every design. In @li2026, plant\nheight was the trait with the strongest between-environment correlations\n(0.36 to 0.67) and the best predicted. Grain yield had no strong correlations\nand was predicted worst. Modelling G x E explicitly helped in every study that\ntested it [@lubanga2025; @li2026]. **Cutting phenotyping by 50 to 80 % without\nlosing accuracy is feasible. The exact cut depends on the programme's own\nbetween-environment correlations, and does not transfer between programmes.**\n\n## The minimum-overlap controversy {#sec-sparse-overlap}\n\nThe literature disagrees openly on how much overlap is needed:\n\n- @atanda2022 conclude that \"a substantial overlap of lines between\n  environments\" is needed.\n- @crespoherrera2021 suggest 30 to 50 common lines.\n- @persa2023 report a gain with as few as 10.\n- @lubanga2025 find that **more overlap made prediction worse**: predictive\n  ability fell and MSE rose monotonically with the number of overlapping\n  genotypes, and the fully non-overlapping design was the best.\n- @li2026 sit in between. Full overlap was the worst design, and the four\n  partial or non-overlapping designs tied.\n- @werner2025 and @gonzalezdieguez2026 do without overlap altogether. All of\n  their connectivity comes from relationships.\n\n**A proposed reconciliation, offered here as a hypothesis.** The designs are not\ncomparable because they confound overlap with the size and diversity of the\ntraining set:\n\n- In @lubanga2025 the training set per environment is fixed in size. More\n  overlap therefore means *fewer distinct genotypes observed*.\n- In @atanda2022 more overlap means a *larger* calibration set per environment,\n  growing from 46-47 lines to as many as 165.\n\nA second factor is family structure. Families of 1 to 9 individuals\n[@atanda2022] give the relationship matrix little to work with, so physical\noverlap has to carry the connection. Families of 20 to 50 [@werner2025;\n@gonzalezdieguez2026] let the relationship matrix carry all of it.\n\nThe first half of the hypothesis is testable directly with the package. The\nexperiment uses four locations and a training set **fixed at 80 hybrids per\nlocation** out of 400. A fraction of the 80 is a core common to all four\nlocations, and the rest are unique to each location. Family size runs from\nunrelated lines to half-sib families of 10 (`regenerate.R sparse`, part c; 30\nreplicates per point; known components; plot $h^2 = 0.4$).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nov <- subset(core, part == \"overlap\")\nfs <- sort(unique(ov$family_size))\ncols <- c(\"grey40\", \"#1b9e77\", \"#d95f02\")[seq_along(fs)]\nop <- par(mar = c(4.2, 4.2, 3.2, 1))\nplot(NA, xlim = c(0, 1), ylim = range(ov$acc_all + c(-2, 2) * ov$acc_all_se),\n     xlab = \"Overlap: fraction of each location's plots in the common core\",\n     ylab = \"Accuracy, all hybrids\")\nfor (i in seq_along(fs)) {\n  d <- ov[ov$family_size == fs[i], ]; d <- d[order(d$overlap), ]\n  lines(d$overlap, d$acc_all, type = \"b\", pch = 19, col = cols[i])\n  arrows(d$overlap, d$acc_all - 2 * d$acc_all_se, d$overlap, d$acc_all + 2 * d$acc_all_se,\n         angle = 90, code = 3, length = 0.03, col = cols[i])\n}\nd0 <- ov[ov$family_size == fs[1], ]; d0 <- d0[order(d0$overlap), ]\naxis(3, at = d0$overlap, labels = d0$n_distinct, cex.axis = 0.8)\nmtext(\"distinct hybrids observed\", 3, line = 2, cex = 0.8)\nlegend(\"bottomleft\", bty = \"n\", lwd = 2, col = cols,\n       legend = ifelse(fs == 1, \"unrelated lines\", paste(\"half-sib families of\", fs)))\npar(op)\n```\n\n::: {.cell-output-display}\n![Accuracy over all 400 hybrids against the fraction of each location's 80 plots taken by a core common to all four locations, by half-sib family size. The training size is held fixed, so more overlap means fewer distinct hybrids observed (top axis). Bars are two standard errors over 30 replicates. In-repo sweep, known variance components.](04f-sparse-testing_files/figure-typst/fig-sparse-overlap-1.svg){#fig-sparse-overlap fig-align='center'}\n:::\n:::\n\n\n\n\nWith the training size held fixed, accuracy falls as overlap rises: it is\n0.023 to 0.059 lower under full overlap than under\nnone, 1.6 to 4.7 standard\nerrors of the difference depending on family size. The cause is the confound, not overlap\nas such. Every hybrid moved into the common core is one fewer distinct hybrid\nobserved (top axis). This is the @lubanga2025 pattern, reproduced with the\nmechanism exposed.\n\nThe second half of the hypothesis is **not** supported at this scale. The\nfamily-size curves cross, and they differ by no more than two standard errors.\nIn hindsight the reason is structural. In a female x male factorial every line\nis already the parent of 20 hybrids, so the factorial carries much of the\nconnectivity before any relationship *among lines* is added. Half-sib families\nadd relatively little on top of that. In a line-breeding programme like\n@atanda2022, each entry is its own genotype and no parent links them, so\nfamily structure should matter far more. This experiment cannot test that\ncase. The experiment also holds the training size fixed, so it does not reproduce\n@atanda2022's design, in which more overlap also meant a larger calibration set\nand the two effects pull in opposite directions.\n\n**What to do with this.** The right question is not \"how many common\ngenotypes?\". It is \"how much *effective* connectivity does the design have,\ncounting both physical overlap and relationships?\". Physical overlap and genomic\nrelationships are partial substitutes [@windhausen2012]. In a hybrid factorial,\nshared parents already supply much of the relationship side.\n\n## Connectivity and checks {#sec-sparse-connectivity}\n\nConnectivity is not the same as overlap. Two designs with the same number of\ncommon genotypes can be connected very differently, depending on *how* those\ngenotypes are distributed. Hybrids add a dimension. There is female x male\nconnectivity, the subject of @sec-mating-connectivity. There is genotype x\nlocation connectivity. And there is **female x male x location**, for which no\nmetric is agreed. That is an open gap (@sec-sparse-limits). The available tools\nare:\n\n- the rank of the incidence matrix;\n- the PEV of pairwise contrasts, and the reliability derived from it;\n- the connected components of the genotype-environment graph.\n\n**Checks** do three jobs:\n\n- anchor connectivity;\n- estimate within-environment error in unreplicated trials, as in the augmented\n  design of @li2026;\n- control spatial trend [@cullis2006; @williams2011].\n\nRestricted randomisation is a cheap connectivity tool. @werner2025 kept\nfull-sibs apart within a location, but did not measure the restriction against\nunrestricted randomisation. @sec-sparse-results does measure a structured\nlayout against unrestricted randomisation.\n\n**Connectivity can be checked before planting.** Compute it at the planning\nstage, rather than finding out from a model that does not converge.\n\n::: {.callout-tip}\n## Box 4 -- Computing the connectivity of a design before planting it\n\n1. Build the genotype x environment incidence matrix.\n2. Check the connected components of the bipartite graph. Every location should\n   share hybrids, or at least parents, with every other.\n3. Compute the mean PEV of the target values under the intended model, with\n   provisional variance components.\n4. Convert it to reliability, $1 - \\overline{\\mathrm{PEV}}/\\sigma^2_G$.\n5. Compare candidate designs on the same metric.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(8)\nnF <- 20; nM <- 20; L <- 6\nAf <- relmat_halfsib(nF, 5); Am <- relmat_halfsib(nM, 5)\nvc <- sparse_vc(0.3)\nrecipe <- function(M) {\n  cn  <- sparse_connectivity(M, nF, nM)                       # steps 1-2\n  # PEV does not depend on y, so any phenotype vector will do (steps 3-4).\n  cells <- which(M == 1L, arr.ind = TRUE)\n  ph  <- data.frame(y = 0, hyb = cells[, 1], loc = cells[, 2])\n  pev <- sparse_blup(ph, nF, nM, L, vc, Af, Am)$pev\n  c(plots = sum(M), fem_cover = cn$fem_cover, disconnected_pairs = cn$frac_disconn,\n    reliability = 1 - mean(pev) / vc$Vg)\n}\nfmt(rbind(complete_2loc = recipe(sparse_alloc(nF, nM, 2, strategy = \"complete\")),\n          random_k2     = recipe(sparse_alloc(nF, nM, L, 2, \"random\")),\n          parentage_k2  = recipe(sparse_alloc(nF, nM, L, 2, \"parentage\"))), 3)\n```\n\n::: {.cell-output-display}\n\n|              | plots| fem_cover| disconnected_pairs| reliability|\n|:-------------|-----:|---------:|------------------:|-----------:|\n|complete_2loc |   800|         1|                  0|       0.625|\n|random_k2     |   800|         1|                  0|       0.703|\n|parentage_k2  |   800|         1|                  0|       0.705|\n\n:::\n:::\n\n\nAll three designs cost 800 plots. Spreading them over six locations raises\nreliability *before a single plot is sown*. The PEV depends only on the design\nand the components, not on the data. That makes it a design tool and not only\nan evaluation metric.\n:::\n\n## Sparse testcrossing and the number of testers {#sec-sparse-testcross}\n\nThe central idea of @gonzalezdieguez2026 is to treat the tester as an\n\"environment\". Each line is crossed to **one** tester, but full-sibs go to\n*different* testers. What gets evaluated against several testers is therefore\nthe haplotype, not the genotype. This removes a real logistical constraint. The\nmore accurate alternative, an incomplete factorial among candidates\n(@sec-mating-sparse), needs hand pollination at scale and synchronised\nflowering between pools.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Sparse testcrossing. A biparental cross yields 20 DH lines; each line is crossed to one of four testers, so the family -- not the line -- meets every tester. The relationship matrix connects the full-sibs, and through them the four testers.](04f-sparse-testing_files/figure-typst/fig-sparse-testcross-1.svg){#fig-sparse-testcross fig-align='center'}\n:::\n:::\n\n\n| Testers (1,200 testcrosses per pool) | Gain in GCA accuracy over 1 tester | Gain in hybrid genetic gain, cycle 15 |\n|---|---|---|\n| 2, medium dominance | +5.3 % | -- |\n| 10, low / medium / high dominance | +3 % / +11 % / +23 % | +3 % / +6 % / +11 % |\n| 2 to 10, medium dominance | +0.7 % on top of the 2-tester gain | -- |\n\n: Sparse testcrossing in @gonzalezdieguez2026: accuracy and gain against a single tester at an equal number of testcrosses. Every sparse layout beat the single tester, and gains plateau at 5 to 10 testers; 3 to 5 is the practical recommendation. {#tbl-sparse-testers}\n\nThe advantage is largest in early cycles, while the pools are still close. That\ndoes **not** confine the method to emerging programmes. Real commercial pools sit\nat a minimum Nei distance of 0.17 [@legarra2023] and an $F_{ST}$ of 0.223\n[@kadoumi2025], which corresponds to cycles 2 to 4 of the simulation.\n\nA useful side effect is that sparse testcrossing *slowed the erosion of\nwithin-pool variance*. It stops selection from piling onto closely related lines\nthat happen to nick with one tester. The authors recommend combining it with\noptimum contribution selection (@sec-ocs; @santantonio2020hoc).\n\nThe deterministic tradition reaches the same order of magnitude by another route\n[@longin2006c]. The advocates of incomplete factorials [@seye2020; @lorenzi2022;\n@lorenzi2024; @melchinger2023b] reach a different conclusion. In\n@gonzalezdieguez2026, an approximate incomplete factorial matched 3 to 5\ntesters, with much heavier logistics. Two costs were not modelled. Five testers\nneed ten isolation blocks. And in many public programmes hand pollination is\nalready routine, which lowers the extra cost of the factorial.\n\n::: {.callout-tip}\n## Box 5 -- Choosing testers: theory against practice\n\nThe classical recommendation is a *low-performing* tester, or one carrying\nrecessive alleles at the loci of interest. Such a tester discriminates among\ncandidates best [@hull1945; @rawlings1962]. Commercial practice uses *elite*\ntesters, chosen for seed production and *per se* performance, because the\ntestcross may itself become a product. The consequence follows from\n@sec-heterosis-gca-sca: GCA is measured *against the tester's allele\nfrequencies*. An elite tester carries the favourable allele at many loci and\nshrinks the visible differences there, so a few elite testers sample the\nopposite pool's frequencies poorly. Several testers spread across the pool,\nthe sparse-testcross recipe, sample them better [@longin2006c; @dejong2023].\n:::\n\n## What sparsity does to variance components and to the BLUP {#sec-sparse-components}\n\nTwo questions are often merged in the literature, and they should be kept\nseparate:\n\n1. Do the predictions stay accurate?\n2. Do the variance-component estimates stay unbiased?\n\nThe second is barely covered. **None of the six primary studies reports bias in\n$\\sigma^2_{GCA}$, $\\sigma^2_{SCA}$ or $\\sigma^2_{GE}$ under sparsity.** The\nindirect evidence is thin:\n\n- In @hildaono2026 the G x E term *degraded* prediction under high sparsity,\n  because there were too few individuals to estimate it. The authors recommend\n  dropping it in that regime.\n- In @li2026 propagating prediction uncertainty barely changed the GCA estimates\n  (correlation 0.9974 to 0.9998 with the point estimates). That is a sensitivity\n  of GCA, not of the variance components.\n\nTwo diagnostics separate the questions.\n\n- **The dispersion slope $b_1$**, from regressing truth on prediction. $b_1 = 1$\n  means no scale bias. $b_1 < 1$ means the predictions are too spread out, and\n  $b_1 > 1$ means they are over-shrunk.\n- **PEV and reliability.** These can be computed *before* any data exist\n  (Box 4), so they serve as design tools.\n\nAccuracy and estimation quality do not degrade at the same rate.\n**A design can rank candidates well and still estimate the SCA and G x E\nvariances badly** [@cullis2006; @piepho2007; @smith2018; @tolhurst2019]. The\nsimulation of @sec-sparse-results measures this directly. That is the gap in\nthe primary literature it was designed to fill.\n\n## Sparse testing with phenomics {#sec-sparse-phenomics}\n\nPhenomic data pose a specific problem. Markers can be read from a seedling\nwhatever happens in the field. Sensor data exist only for plots that were\nactually grown, so they cannot serve as a covariate for an individual that was\nnever observed. There are three ways out:\n\n- multi-trait models with image indices as secondary traits;\n- kernel regression on the indices;\n- the proposal of @hildaono2026: use the images to build an **environment**\n  kernel.\n\nThe environment kernel is built in three steps. A PCA of the image traits is\nrun *within each environment*. The first-component eigenvector of each\nenvironment is extracted. The kernel entries are the correlations between those\neigenvectors.\n\nThe image kernel matched or beat the genomic kernel from about 30 to 33 %\ncompleteness, reaching $r^2 = 0.997$ on pairs of environments. Below about 20 %\nthe genomic kernel was preferable again. **The authors warn of possible\ninformation leakage**, because the kernel came from the same trial that supplied\ntraining and validation. The result should be reported with that caveat.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Building an environment kernel from images, after Hild Aono and Chawade (2026). The dashed box marks where training and validation share information -- the leakage the authors flag.](04f-sparse-testing_files/figure-typst/fig-sparse-phenomics-1.svg){#fig-sparse-phenomics fig-align='center'}\n:::\n:::\n\n\nThe approach is attractive for programmes without routine genotyping. It is also\npromising for maize, where sensor phenotyping exists but has not been tested in\nthis arrangement with hybrids. It connects to envirotyping. When locations are\nclose together, coarse-grid weather covariates discriminate poorly, and images\ncapture differences that the weather data miss [@costaneto2020; @crossa2021;\n@rincent2017]. NIRS-based phenomic prediction in maize points the same way, in a\nnon-sparse setting [@desalvio2024].\n\n**Sensor data enter sparse testing as descriptors of environments, not of\ngenotypes.** This inversion solves the availability problem. In programmes that\ngenotype little, it can partly replace the genomic matrix.\n\n## Simulation as a sizing tool {#sec-sparse-simulation}\n\n### Why simulate before designing\n\nNone of the published numbers transfers directly to another programme. Each one\ndepends on the between-environment correlations, the family structure, the\n$\\sigma^2_{SCA}/\\sigma^2_{GCA}$ ratio and the heritability of the programme that\nproduced it, and the authors say so themselves [@werner2025;\n@gonzalezdieguez2026]. A simulation can do three things an experiment cannot:\n\n- it knows the true values;\n- it can rerun the programme a hundred times;\n- it can isolate one factor at a time.\n\nThe tools exist. AlphaSimR covers the genetics [@gaynor2021; @sec-alphasimr],\nFieldSimR covers plots and G x E [@werner2024], and `sommer` or BGLR fit the\nmodels [@covarrubiaspazaran2016]. Staged-allocation theory provides the\ndeterministic cross-check [@mi2014; @longin2006b]. **Simulation does not replace\nthe experiment. It replaces guessing at the design of the experiment.**\n\n### Realistic parameters: what the literature supplies\n\n\n::: {#tbl-sparse-parameters .cell layout-align=\"center\" tbl-cap='Reference parameters from the six primary studies. \\'Derived\\' marks a value computed from reported components rather than reported directly.'}\n\n```{.r .cell-code}\nknitr::kable(lp[, c(\"parameter\", \"value\", \"source\", \"derived\")],\n             col.names = c(\"Parameter\", \"Value\", \"Source\", \"Derived\"))\n```\n\n::: {.cell-output-display}\n\n\n|Parameter                                              |Value                                                 |Source                                    |Derived |\n|:------------------------------------------------------|:-----------------------------------------------------|:-----------------------------------------|:-------|\n|Plot heritability                                      |0.10 (founder population)                             |Werner et al. 2025 (simulation)           |no      |\n|Plot heritability (worst environment)                  |0.18                                                  |Atanda et al. 2022 (wheat)                |no      |\n|Broad-sense H2 over all hybrids                        |0.30                                                  |Gonzalez-Dieguez et al. 2026 (simulation) |no      |\n|Entry-mean H2                                          |0.76-0.87                                             |Li et al. 2026 (maize)                    |no      |\n|Entry-mean H2                                          |0.61-0.87                                             |Lubanga et al. 2025 (cassava)             |no      |\n|Broad-sense H2 (maximum)                               |~0.67                                                 |Hild Aono & Chawade 2026 (potato)         |no      |\n|s2SCA / s2GCA at cycle 1                               |0.05 / 0.23 / 0.50 for mean dominance 0.1 / 0.5 / 0.9 |Gonzalez-Dieguez et al. 2026              |no      |\n|s2GxE / (s2G + s2GxE)                                  |0.56                                                  |Werner et al. 2025                        |no      |\n|Crossover share of G x E variance                      |0.53                                                  |Werner et al. 2025                        |no      |\n|Mean genetic correlation between TPE locations         |0.60                                                  |Werner et al. 2025                        |no      |\n|Genetic correlation between locations (plant height)   |0.36-0.67                                             |Li et al. 2026 (maize)                    |no      |\n|Genetic correlation between environments (grain yield) |none strong detected                                  |Li et al. 2026 (maize)                    |no      |\n|Genetic correlation between environments (same year)   |-0.04 to 0.67                                         |Atanda et al. 2022 (wheat)                |no      |\n|s2_env / s2_g (grain yield)                            |8.1                                                   |Li et al. 2026 (maize; 1.13 / 0.14)       |yes     |\n|Genotypes tested                                       |264-2000                                              |all six studies                           |no      |\n|Locations                                              |2-440                                                 |all six studies                           |no      |\n|Testers                                                |1-1200                                                |Gonzalez-Dieguez et al. 2026              |no      |\n|Cells observed                                         |10-83%                                                |all six studies                           |no      |\n\n\n:::\n:::\n\n\nTwo features of real data a simulation must respect:\n\n1. **Environmental variance exceeds genetic variance by an order of magnitude.**\n   For maize grain yield, $\\sigma^2_{env}/\\sigma^2_g \\approx 8.1$ [@li2026].\n2. **Between-environment correlations for yield are often weak.** Scenarios\n   should be anchored on measured parameters, not chosen for numerical\n   convenience.\n\n### What the simulation finds {#sec-sparse-results}\n\n**The model.** The study simulated a female x male factorial of single crosses,\ntested with **one plot per hybrid x location cell**. The phenotype is\n\n$$\ny = \\mu + \\text{loc} + \\mathrm{GCA}^f + \\mathrm{GCA}^m + \\mathrm{SCA}\n  + \\mathrm{GCA}^f{\\times}\\text{loc} + \\mathrm{GCA}^m{\\times}\\text{loc}\n  + \\mathrm{SCA}{\\times}\\text{loc} + e .\n$$\n\nThe target is the value in the TPE, $\\mathrm{GCA}^f + \\mathrm{GCA}^m +\n\\mathrm{SCA}$. In every replicate, **20 % of the hybrids get no plot at all.**\nThese are the CV1 hybrids, predicted only through relationships.\n\n**The calibration** is `sparse_vc()`:\n\n- $\\sigma^2_f = \\sigma^2_m = 1$ and $\\sigma^2_{SCA} = 0.25$;\n- every interaction with location is half its main effect;\n- plot $h^2$ of 0.20 or 0.40.\n\nThese choices imply a genetic correlation between locations of\n$V_G/(V_G+V_{GE}) = 0.667$. That sits inside the 0.36 to 0.67 measured in\nmaize [@li2026] and close to the 0.60 of @werner2025. The SCA:GCA ratio of 0.25\nlies among the values in @gonzalezdieguez2026, and the two heritabilities\nbracket @werner2025's 0.10 and the 0.30 of @gonzalezdieguez2026.\n\n**The four strategies**, all at the same cost of $k$ locations per hybrid:\n\n- *complete*;\n- *random*: each hybrid goes to $k$ locations drawn at random;\n- *optimised blocks*: an exchange algorithm on the mixed-model coefficient\n  matrix, with replicated checks;\n- *parentage*: the factorial is cut into cyclic groups, each holding every\n  female and every male, and groups are dealt to locations so that **every\n  location receives both whole pools**.\n\nThe last is `sparse_alloc(strategy = \"parentage\")`.\n\n**Validation of the estimator.** Before any comparison, the estimator was checked\non the complete design, where REML must recover the true components\n(@tbl-sparse-validation).\n\n\n::: {#tbl-sparse-validation .cell layout-align=\"center\" tbl-cap='Component recovery by REML in the COMPLETE design (20 x 20 hybrids, 6 locations, 30 replicates per heritability; cached). The residual target is $\\sigma^2_{SCA\\times L} + \\sigma^2_e$, because with one plot per cell the two are confounded.'}\n\n```{.r .cell-code}\nv <- val; v$component <- sub(\"s2\", \"s2_\", v$component)\nknitr::kable(fmt(v[, c(\"h2_plot\", \"component\", \"true\", \"mean_est\", \"relbias_pct\", \"se_relbias_pct\", \"t\")], 3),\n             col.names = c(\"Plot h2\", \"Component\", \"True\", \"Mean estimate\", \"Rel. bias %\", \"SE %\", \"t\"))\n```\n\n::: {.cell-output-display}\n\n\n| Plot h2|Component |  True| Mean estimate| Rel. bias %|  SE %|     t|\n|-------:|:---------|-----:|-------------:|-----------:|-----:|-----:|\n|     0.2|s2_f      | 1.000|         1.026|        2.63|  7.88|  0.33|\n|     0.2|s2_m      | 1.000|         0.964|       -3.57|  6.70| -0.53|\n|     0.2|s2_s      | 0.250|         0.350|       39.94| 18.50|  2.16|\n|     0.2|s2_fl     | 0.500|         0.540|        7.97|  6.13|  1.30|\n|     0.2|s2_ml     | 0.500|         0.499|       -0.13|  6.04| -0.02|\n|     0.2|s2_res    | 8.000|         7.962|       -0.48|  0.53| -0.90|\n|     0.4|s2_f      | 1.000|         0.979|       -2.15|  6.07| -0.35|\n|     0.4|s2_m      | 1.000|         1.008|        0.79|  6.77|  0.12|\n|     0.4|s2_s      | 0.250|         0.303|       21.31| 20.91|  1.02|\n|     0.4|s2_fl     | 0.500|         0.488|       -2.31|  3.16| -0.73|\n|     0.4|s2_ml     | 0.500|         0.496|       -0.70|  3.77| -0.19|\n|     0.4|s2_res    | 2.375|         2.364|       -0.44|  0.73| -0.61|\n\n\n:::\n:::\n\n\nEvery component except SCA is recovered without detectable bias\n($|t| \\le 1.3$). $\\sigma^2_{SCA}$ is biased upward even here, by\n+39.9 %\nand\n+21.3 %.\nThat is the expected direction for a small component (11 % of $V_G$) estimated\nby a procedure bounded below at zero. **The bias is a baseline, not an effect of\nsparsity.** Every later SCA number has to be read against it.\n\nThe grid has 2,630 fits:\n\n- 100 and 400 hybrids;\n- 2, 4, 6 and 10 locations;\n- nominal sparsity from 20 % to 100 %;\n- two heritabilities;\n- 15 replicates per cell.\n\n#### 1. The cutting margin is wide, and wider at higher heritability\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nop <- par(mfrow = c(1, 2), mar = c(4.2, 4.2, 2, 1))\nd <- subset(s4, h2_plot == 0.4 & strategy %in% c(\"parentage\", \"complete\"))\nLs <- sort(unique(d$nLoc)); lc <- hcl.colors(length(Ls), \"Dark 3\")\nplot(NA, xlim = range(d$n_plots_mean), ylim = range(d$acc_all_mean),\n     xlab = \"Plots\", ylab = \"Accuracy, all hybrids\", main = \"Cost-accuracy, h2 = 0.4\", cex.main = 0.9)\nfor (i in seq_along(Ls)) {\n  e <- d[d$nLoc == Ls[i], ]; e <- e[order(e$n_plots_mean), ]\n  lines(e$n_plots_mean, e$acc_all_mean, type = \"b\", pch = ifelse(e$strategy == \"complete\", 1, 19), col = lc[i])\n}\nlegend(\"bottomright\", bty = \"n\", col = lc, lwd = 2, legend = paste(Ls, \"locations\"), cex = 0.8)\nsp <- subset(s4, k == 2 & strategy %in% c(\"complete\", \"random\"))\nplot(NA, xlim = c(2, 10), ylim = range(sp$acc_all_mean), xlab = \"Locations sharing the 2 plots per hybrid\",\n     ylab = \"Accuracy, all hybrids\", main = \"Same 800 plots, spread wider\", cex.main = 0.9)\nfor (h in c(0.2, 0.4)) {\n  e <- sp[sp$h2_plot == h, ]; e <- e[order(e$nLoc), ]\n  lines(e$nLoc, e$acc_all_mean, type = \"b\", pch = 19, lty = ifelse(h == 0.2, 2, 1))\n}\nlegend(\"bottomright\", bty = \"n\", lty = c(1, 2), pch = 19, legend = c(\"plot h2 = 0.4\", \"plot h2 = 0.2\"), cex = 0.8)\npar(op)\n```\n\n::: {.cell-output-display}\n![Left: accuracy against plots for 400 hybrids at plot h2 = 0.4, one curve per number of locations (parentage and complete designs; complete marked with an open circle). Right: accuracy at a FIXED cost of two plots per hybrid, spread over 2 to 10 locations, random allocation, both heritabilities. Cached study, REML components, 15 replicates.](04f-sparse-testing_files/figure-typst/fig-sparse-frontier-1.svg){#fig-sparse-frontier fig-align='center'}\n:::\n:::\n\n\n\n\nTake 400 hybrids at $h^2 = 0.4$. The complete design over ten locations (3,200\nplots) reaches an accuracy of 0.941. The **cheapest allocation\nwithin 5 % of that** is the parentage design with 2 locations per\nhybrid. It uses 640 plots, 20 % of the\nbudget, and reaches 0.897, which is 95.3 % of the\nreference. Coincidence with the true top 5 % falls only from 70.0 %\nto 65.7 %. At $h^2 = 0.2$ the requirement roughly doubles to half\nthe cells. @tbl-sparse-minimal lists every scenario.\n\n\n::: {#tbl-sparse-minimal .cell layout-align=\"center\" tbl-cap='Cheapest allocation within 5 % and within 10 % of the accuracy of the complete design at the largest number of locations in each scenario. Cached study.'}\n\n```{.r .cell-code}\nm <- mn; m$within <- ifelse(m$minimal_5, \"5 %\", \"10 %\")\nm <- m[order(m$nHyb, m$h2_plot, m$sca_level, m$nLoc, m$within), ]\nknitr::kable(fmt(m[, c(\"nHyb\", \"h2_plot\", \"sca_level\", \"nLoc\", \"within\", \"strategy\", \"k\",\n                       \"n_plots_mean\", \"acc_all_mean\", \"acc_rel\", \"cost_rel\")], 3),\n             row.names = FALSE,\n             col.names = c(\"Hybrids\", \"Plot h2\", \"SCA\", \"Locations\", \"Within\", \"Strategy\", \"k\",\n                           \"Plots\", \"Accuracy\", \"Rel. accuracy\", \"Rel. cost\"))\n```\n\n::: {.cell-output-display}\n\n\n| Hybrids| Plot h2|SCA  | Locations|Within |Strategy         |  k|    Plots| Accuracy| Rel. accuracy| Rel. cost|\n|-------:|-------:|:----|---------:|:------|:----------------|--:|--------:|--------:|-------------:|---------:|\n|     100|     0.2|low  |         4|10 %   |parentage        |  3|  240.000|    0.779|         0.903|       0.3|\n|     100|     0.2|low  |         4|5 %    |complete         |  4|  320.000|    0.825|         0.958|       0.4|\n|     100|     0.4|low  |         6|5 %    |random           |  4|  320.000|    0.887|         0.951|       0.4|\n|     100|     0.4|low  |        10|10 %   |parentage        |  2|  160.000|    0.856|         0.917|       0.2|\n|     400|     0.2|low  |         6|10 %   |random           |  2|  640.000|    0.816|         0.904|       0.2|\n|     400|     0.2|low  |        10|5 %    |random           |  5| 1600.000|    0.874|         0.967|       0.5|\n|     400|     0.4|high |        10|10 %   |random           |  2|  640.000|    0.825|         0.901|       0.2|\n|     400|     0.4|high |        10|5 %    |optimised_blocks |  5| 1599.867|    0.884|         0.966|       0.5|\n|     400|     0.4|low  |         4|10 %   |optimised_blocks |  2|  639.667|    0.859|         0.912|       0.2|\n|     400|     0.4|low  |        10|5 %    |parentage        |  2|  640.000|    0.897|         0.953|       0.2|\n\n\n:::\n:::\n\n\n#### 2. At fixed cost, spreading plots over locations beats concentrating them\n\n\n\nThis is the most actionable result (@fig-sparse-frontier, right). Each hybrid\nkeeps **two plots**, the cost of a complete two-location trial. At\n$h^2 = 0.4$, accuracy rises from 0.831 with both plots in the same\ntwo locations to 0.860, 0.883 and\n0.892 as those plots are spread across 4, 6 and 10 locations. At\n$h^2 = 0.2$ it rises from 0.733 to 0.819. Not one\nextra plot is spent. The gain saturates between six and ten locations, so the\npractical advice is to add locations up to about six before adding plots per\nhybrid. This is the replication-against-breadth trade-off of @lorenz2013,\n@atlin2022 and @werner2025, now measured for hybrids with GCA and SCA.\n\n#### 3. Among sparse designs the choice matters little, except at extreme sparsity\n\n\n::: {#tbl-sparse-contrasts .cell layout-align=\"center\" tbl-cap='Contrasts against random allocation. Paired by replicate in the fast layer (791 pairs; 385 with k <= 2) and in the genomic layer (32 pairs). acc_cv1: hybrids never tested; acc_cv2: missing cells of tested hybrids. Cached study.'}\n\n```{.r .cell-code}\ncc <- ct[ct$metric %in% c(\"acc_all\", \"acc_cv1\", \"acc_cv2\") & ct$subset %in% c(\"all\", \"k<=2\"), ]\nknitr::kable(fmt(cc[, c(\"layer\", \"contrast\", \"metric\", \"subset\", \"n\", \"diff\", \"se\", \"p\")], 4),\n             row.names = FALSE,\n             col.names = c(\"Layer\", \"Contrast\", \"Metric\", \"Subset\", \"n\", \"Difference\", \"SE\", \"p\"))\n```\n\n::: {.cell-output-display}\n\n\n|Layer   |Contrast                  |Metric  |Subset |   n| Difference|     SE|      p|\n|:-------|:-------------------------|:-------|:------|---:|----------:|------:|------:|\n|fast    |parentage - random        |acc_all |all    | 791|     0.0051| 0.0029| 0.0773|\n|fast    |optimised_blocks - random |acc_all |all    | 791|     0.0011| 0.0028| 0.7018|\n|fast    |parentage - random        |acc_cv1 |all    | 791|     0.0086| 0.0039| 0.0260|\n|fast    |optimised_blocks - random |acc_cv1 |all    | 791|     0.0018| 0.0043| 0.6698|\n|fast    |parentage - random        |acc_cv2 |all    | 791|     0.0077| 0.0026| 0.0031|\n|fast    |optimised_blocks - random |acc_cv2 |all    | 791|     0.0060| 0.0023| 0.0103|\n|genomic |parentage - random        |acc_all |all    |  32|     0.0226| 0.0086| 0.0137|\n|genomic |optimised_blocks - random |acc_all |all    |  32|     0.0152| 0.0098| 0.1296|\n|genomic |parentage - random        |acc_cv1 |all    |  32|     0.0139| 0.0092| 0.1410|\n|genomic |optimised_blocks - random |acc_cv1 |all    |  32|     0.0111| 0.0135| 0.4197|\n|fast    |parentage - random        |acc_cv1 |k<=2   | 385|     0.0187| 0.0069| 0.0070|\n|fast    |optimised_blocks - random |acc_cv1 |k<=2   | 385|    -0.0012| 0.0079| 0.8810|\n\n\n:::\n:::\n\n\n\n\nOver the whole grid, the parentage design beats random allocation on untested\nhybrids by +0.0086 $\\pm$ 0.0039\n(p = 0.026). That is real and small. Restricted to\n$k \\le 2$ locations per hybrid, the advantage roughly doubles, to\n+0.0187 $\\pm$ 0.0069\n(p = 0.007). The optimised blocks show nothing there\n(-0.0012 $\\pm$ 0.0079). In the\ngenomic layer, with marker relationships and real dominance, the parentage\nadvantage on overall accuracy is +0.023\n$\\pm$ 0.009 (p = 0.014).\n\nNone of the six primary studies compared a structured allocation with a random\none. @li2026 found their structured schemes tied with each other. @werner2025\nused restricted randomisation without a random control. This result answers\nthat open question for the hybrid case. The structure matters when plots are\nscarce, and only for the hybrids the field never saw.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na <- aggregate(acc_all ~ strategy + nLoc + p_real, gl, mean)\nop <- par(mar = c(4.2, 4.2, 1, 1))\nplot(NA, xlim = range(a$p_real), ylim = range(a$acc_all), xlab = \"Share of cells observed\",\n     ylab = \"Accuracy, all hybrids\")\nfor (s in names(strat_col)) for (L in unique(a$nLoc)) {\n  e <- a[a$strategy == s & a$nLoc == L, ]; e <- e[order(e$p_real), ]\n  if (nrow(e)) lines(e$p_real, e$acc_all, type = \"b\", pch = ifelse(L == 4, 19, 17),\n                     lty = ifelse(L == 4, 1, 2), col = strat_col[s])\n}\nlegend(\"bottomright\", bty = \"n\", cex = 0.8, col = c(strat_col, \"black\", \"black\"),\n       lty = c(1, 1, 1, 1, 1, 2), pch = c(NA, NA, NA, NA, 19, 17),\n       legend = c(names(strat_col), \"4 locations\", \"8 locations\"))\npar(op)\n```\n\n::: {.cell-output-display}\n![Genomic layer (AlphaSimR genomes, marker relationships, 8 replicates): accuracy against the share of cells observed, by strategy and number of locations. Cached study.](04f-sparse-testing_files/figure-typst/fig-sparse-genomic-1.svg){#fig-sparse-genomic fig-align='center'}\n:::\n:::\n\n\n#### 4. Parent coverage, not shared hybrids, carries the connectivity\n\n\n\nConsider ten locations with two per hybrid at $h^2 = 0.4$. The best design there\nis the parentage design, with accuracy 0.897.\nIts harmonic-mean concurrence, the number of hybrids a pair of locations\nshares, is **0.000**: some pairs of\nlocations share no hybrid at all. This is structural. Twenty groups at two\nlocations each touch at most 20 of the 45 location pairs. Random allocation\nshares hybrids between almost every pair (harmonic mean\n5.466) and is less accurate. What the\nparentage design keeps is **parent coverage**. The mean fraction of females\npresent per location is 0.999, against\n0.965 for random allocation.\n\nOnce a relationship matrix is in the model, what carries connectivity is\nrepresenting both pools in every location, not repeating the same hybrids across\nlocations. Put this together with @sec-sparse-overlap and it reads as one\naccount of the @atanda2022 versus @lubanga2025 disagreement. Shared hybrids are\none way to connect environments. Shared parents are another, cheaper one, and\nin a hybrid factorial the shared parents come for free.\n\n#### 5. The BLUP is not dispersed; the SCA variance is not recoverable\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmed <- aggregate(cbind(relbias_s2f_mean, relbias_s2fl_mean, relbias_s2s_mean, relbias_h2_mean) ~ k, sc, median)\nop <- par(mfrow = c(1, 2), mar = c(4.2, 4.2, 1, 1))\nmatplot(med$k, 100 * med[, -1], type = \"b\", pch = 19, lty = 1,\n        col = c(\"#1b9e77\", \"#7570b3\", \"#d95f02\", \"grey30\"),\n        xlab = \"Locations per hybrid, k\", ylab = \"Median relative bias (%)\")\nabline(h = 0, lty = 3)\nlegend(\"topright\", bty = \"n\", cex = 0.8, pch = 19, col = c(\"#1b9e77\", \"#7570b3\", \"#d95f02\", \"grey30\"),\n       legend = c(\"GCA (female)\", \"GCA x location\", \"SCA\", \"plot h2\"))\nplot(jitter(sc$k, 0.4), pmin(pmax(sc$bias_all_mean, 0.5), 1.5), pch = 19, cex = 0.6,\n     col = adjustcolor(ifelse(sc$frac_conv < 1, \"#d95f02\", \"grey30\"), 0.7),\n     xlab = \"Locations per hybrid, k\", ylab = \"Dispersion slope b1\", ylim = c(0.5, 1.5))\nabline(h = 1, lty = 2)\nlegend(\"topright\", bty = \"n\", cex = 0.8, pch = 19, col = c(\"grey30\", \"#d95f02\"),\n       legend = c(\"all fits converged\", \"some fits did not\"))\npar(op)\n```\n\n::: {.cell-output-display}\n![Left: median relative bias of REML components and of plot h2 by locations per hybrid k, over all cached scenarios. Right: the dispersion slope b1 (truth on BLUP), one point per scenario; the dashed line is no dispersion bias. Scenarios with k = 1 and incomplete REML convergence produce the outliers (axis clipped at 0.5-1.5).](04f-sparse-testing_files/figure-typst/fig-sparse-estimates-1.svg){#fig-sparse-estimates fig-align='center'}\n:::\n:::\n\n\n\n\n**Prediction holds up.** Where every REML fit converged, the dispersion slope\nstays within 0.845 to 1.076\nacross the grid. With $k \\ge 4$ it stays within\n0.942 to 1.057. Sparsity costs\naccuracy but adds **no dispersion bias**, as long as the components are\nestimable. The GCA variance, the GCA x location variance and plot $h^2$ have\nmedian biases near zero at every $k$.\n\n**$\\sigma^2_{SCA}$ is the exception.** Its median relative bias is\n+12 % at $k = 4$,\n+30 % at $k = 2$, and\n+220 % at $k = 1$. Much of this is present in the\ncomplete design too (@tbl-sparse-validation), so it is mainly a problem of\nidentifying a small component, and sparsity makes it worse. A programme that\nneeds a reliable SCA is in product development, not population improvement. It\ncannot fix the problem by adding coverage to a stage-1 trial.\n\n**The hidden cost is convergence.** REML converged in 100.0 % of fits with\nfour locations per hybrid, 97.0 % with three, 88.5 % with two, and only\n**42.6 % with one**. That is 411 non-convergences\nin 2630 fits.\n\n::: {.callout-important}\n## Box -- Why REML does not converge when each hybrid sees one location\n\nWith $k = 1$ each hybrid contributes a single plot in a single location. The\ndata then carry no within-hybrid information to separate a hybrid's GCA from its\nGCA x location deviation. The likelihood is flat along that ridge. The algorithm\nwalks to the boundary of the parameter space and stops without meeting its\ncriterion. The BLUPs from those fits are still usable. They come from solving\nthe mixed-model equations at the current components, which is exactly what\n`sparse_blup()` does with known ones. **The variance estimates are not usable,\nand should not be reported.** Predicting well and estimating well are different\nachievements. At $k = 1$ a trial can still do the first.\n:::\n\n#### 6. Two stages: test every candidate sparsely rather than a subset densely\n\n\n\nThe two-stage scenario works as follows:\n\n- A pool of 400 candidate hybrids is available.\n- Stage 1 tests $N_1$ of them sparsely and keeps the top $q$ by BLUP.\n- Stage 2 tests the survivors densely in new locations.\n- The final analysis is joint.\n\nThe metric is the realised gain: the mean *true* value of the ten hybrids\nfinally chosen, in genetic standard deviations. Under 700 total plots, the gain\nis 1.358 when stage 1 tests 100 candidates,\n1.778 for 200, and 2.148 for\nall 400. Across all budgets, efficiency relative to an oracle that\nselects on the truth rises from 0.585 to\n0.935. The share of the true top 5 % captured rises from\n19.8 % to 72.1 %.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na  <- aggregate(cbind(gain_sd_units, gain_max_sd_units) ~ N1 + plots_total, ts, mean)\ncl <- c(\"100\" = \"#d95f02\", \"200\" = \"#7570b3\", \"400\" = \"#1b9e77\")\nop <- par(mar = c(4.2, 4.2, 1, 1))\nplot(NA, xlim = range(a$plots_total), ylim = c(0, max(a$gain_max_sd_units)), log = \"x\",\n     xlab = \"Total plots (log scale)\", ylab = \"Realised gain (genetic SD)\")\no <- aggregate(gain_max_sd_units ~ plots_total, a, mean); o <- o[order(o$plots_total), ]\nlines(o$plots_total, o$gain_max_sd_units, col = \"grey60\", lwd = 3)\nfor (n in names(cl)) {\n  e <- a[a$N1 == as.numeric(n), ]; e <- e[order(e$plots_total), ]\n  lines(e$plots_total, e$gain_sd_units, type = \"b\", pch = 19, col = cl[n])\n}\nlegend(\"bottomright\", bty = \"n\", col = c(cl, \"grey60\"), lwd = c(1, 1, 1, 3), pch = c(19, 19, 19, NA),\n       legend = c(paste(\"N1 =\", names(cl)), \"oracle\"), cex = 0.85)\npar(op)\n```\n\n::: {.cell-output-display}\n![Realised gain (true value of the 10 hybrids finally selected, genetic SD units) against total plots, by the number of candidates tested in stage 1; mean over replicates and stage-2 settings at each budget. The grey line is the oracle that selects on the truth. Cached study.](04f-sparse-testing_files/figure-typst/fig-sparse-twostage-1.svg){#fig-sparse-twostage fig-align='center'}\n:::\n:::\n\n\nWith a fixed budget, **stage 1 should cover every candidate with few plots\neach, not a subset with many.** The best combinations among the cached settings\nused four stage-1 locations at 50 % sparsity, eight stage-2 locations, and kept\nthe top 10 to 20 %.\n\n#### Limitations of the simulation\n\nThe simulation has six limitations.\n\n1. **One plot per cell.** $\\sigma^2_{SCA\\times L}$ is confounded with plot error,\n   and the residual estimates their sum. Within-location replication was not\n   simulated.\n2. **G x E is full-rank and symmetric in the fast layer, and rank one in the\n   genomic layer.** Neither layer has the factor-analytic structure of real\n   trials or a crossover/non-crossover split [@burgueno2012; @werner2025].\n3. **The pools are symmetric and unselected.** There are no cycles of reciprocal\n   recurrent selection, so the simulation says nothing about long-run pool\n   trajectories (@sec-cycles) or about unbalanced pools.\n4. **Cost is counted in plots, not money.** Opening a location costs more than\n   adding plots to an existing one. The advice to spread plots assumes the\n   marginal location is moderately priced (@sec-mating-cost has the cost\n   structure).\n5. **The grid is reduced.** It has 15 replicates, no 200-hybrid level, and the\n   high-SCA block run separately. The two-stage layer has 4 replicates and the\n   genomic layer 8.\n6. **Components are checked by mean bias only.** No per-replicate confidence\n   intervals were computed.\n\n## Practical recommendations by stage {#sec-sparse-recommendations}\n\n**Stage 1 (first agronomic testcross trial).**\n\n- Give priority to the number of candidates and the number of locations over\n  replication. Keep the plots per hybrid fixed and widen the locations, up to\n  about six (result 2).\n- Use 3 to 5 testers in sparse testcrossing, with full-sibs spread across\n  testers.\n- Use low partial replication (p-rep of 0.1 to 0.2), with checks replicated in\n  every block.\n- When plots per hybrid fall to one or two, use a layout that puts both pools in\n  every location (results 3 and 4).\n- The estimation target is GCA. Do not expect a reliable SCA at this stage\n  (result 5).\n\n**Stage 2 (pre-commercial hybrids).**\n\n- Test fewer candidates, and raise replication and environmental coverage.\n- Keep a common core large enough to estimate the between-environment genetic\n  correlations.\n- The estimation target is now specific performance and stability, so SCA and\n  G x E matter.\n\n**Decisions that span both stages.**\n\n- Genotype the parents, not the hybrids.\n- Check connectivity before planting (Box 4).\n- Match the between-environment covariance to the amount of data. Do not force\n  an unstructured matrix on a very sparse design.\n- Advance on GBLUP rather than BLUE when heritability is low to moderate and\n  locations are few [@atanda2022; @endelman2014].\n\n**What not to do.**\n\n- Put everything in one location, however many candidates that allows. It gave\n  the most variable gain in @werner2025, with replicates of negative gain.\n- Use one tester at stage 1 when there is infrastructure for three.\n- Transfer a sparsity percentage from another crop or programme without your own\n  simulation.\n- Fit a G x E term under extreme sparsity [@hildaono2026].\n\n**The right sparse design changes from stage to stage because the parameter of\ninterest changes**: GCA in stage 1, specific performance and stability in\nstage 2.\n\n::: {.callout-tip}\n## Box 6 -- A checklist for designing a sparse trial\n\n1. Define the TPE and the market segment.\n2. Estimate the genetic correlations between candidate locations from historical\n   data.\n3. Fix the budget in plots.\n4. Choose the axis of sparsity: environments, testers, or both.\n5. Fix the number of testers.\n6. Fix the partial-replication rate.\n7. Choose the checks and how often they appear.\n8. Generate the allocation by restricted randomisation or a formal criterion.\n   Where plots per hybrid are fewest, keep both pools in every location.\n9. Compute connectivity and the expected PEV before planting (Box 4).\n10. Simulate the design with the programme's own parameters (`sparse_vc()`,\n    `sparse_simulate()`, `sparse_blup()`).\n11. Fix the analysis model and the covariance structure *a priori*.\n12. Fix the decision metric and the cut-off *a priori*.\n:::\n\n## Limitations of the evidence, and perspectives {#sec-sparse-limits}\n\nThe authors of the primary studies declare their own limitations:\n\n- @li2026: a narrow genetic base and a single year.\n- @atanda2022: no way to identify the optimal overlap, and families of 1 to 9.\n- @werner2025: no cost model, and no hybrid structure.\n- @lubanga2025: a training set that was not optimised.\n- @gonzalezdieguez2026: no G x E, no epistasis, no diversity management, and the\n  logistic cost ignored.\n- @hildaono2026: possible information leakage, and very similar environments.\n\nAs a research agenda, the open gaps are these.\n\n- **SCA estimation, and prediction of specific hybrids, under sparsity.** This\n  chapter's simulation shows the variance component is not recoverable at stage\n  1. The accuracy of specific unseen crosses is still unmeasured.\n- **A three-dimensional connectivity metric**, female x male x location. It\n  would join @sec-mating-connectivity to Box 4.\n- **The long-run effect on pool divergence and within-pool variance**, in\n  interaction with optimum contribution selection (@sec-cycles; @sec-ocs;\n  @santantonio2020hoc).\n- **Phenomics-assisted sparse testing in maize hybrids.**\n- **Pools unequal in size and breeding level**, which is the usual commercial\n  case.\n- **Cost-accuracy frontiers in money**, including isolation blocks and hand\n  pollination.\n- **The rate of wrongly discarded candidates** as the evaluation metric, in\n  place of the correlation.\n- **Prospective empirical validation.** Almost all the evidence for sparse\n  testing comes from resampling complete data or from simulation, not from\n  trials designed sparse from the start [@alemu2024; @crossa2017].\n\nSparse testing changes the stage-1 question. It is no longer \"which genotypes\ncan I evaluate well?\". It becomes \"which haplotypes can I evaluate well, and\nagainst what sample of the opposite pool?\". The evidence is sufficient to adopt\nsparse designs at stage 1 with confidence. It is not sufficient to prescribe a\nuniversal sparsity level. That decision remains specific to each programme, and\nshould be sized by the programme's own simulation.\n\n## Reproducibility and assumptions {#sec-sparse-reproduce}\n\n`regenerate.R sparse` reruns the phenotypic core of the cached study with\n`R/17_sparse_testing.R`. The scale and calibration are the same: 20 x 20\nhybrids, half-sib families of four, and 20 % of hybrids untested. There are two\ndifferences:\n\n- the variance components are **known**, not estimated by REML;\n- the parentage allocation's exchange search minimises the number of\n  disconnected location pairs before the harmonic concurrence. The cached\n  study's criterion returned $-\\infty$ for any disconnected start, which left\n  its search no gradient.\n\n\n::: {#tbl-sparse-reproduce .cell layout-align=\"center\" tbl-cap='In-repo sweep (known components, 30 replicates) against the cached study (REML, 15 replicates), on overall accuracy for 400 hybrids. `z` is the difference in standard errors of the difference.'}\n\n```{.r .cell-code}\ncr <- subset(core, part %in% c(\"spread\", \"k1\"))\ncr$cached <- mapply(function(L, k, s, h) {\n  x <- s4$acc_all_mean[s4$nLoc == L & s4$k == k & s4$strategy == s & s4$h2_plot == h]\n  if (length(x)) x[1] else NA\n}, cr$nLoc, cr$k, cr$strategy, cr$h2_plot)\ncr$cached_se <- mapply(function(L, k, s, h) {\n  x <- s4$acc_all_se[s4$nLoc == L & s4$k == k & s4$strategy == s & s4$h2_plot == h]\n  if (length(x)) x[1] else NA\n}, cr$nLoc, cr$k, cr$strategy, cr$h2_plot)\ncr$z <- (cr$acc_all - cr$cached) / sqrt(cr$acc_all_se^2 + cr$cached_se^2)\ncr <- cr[order(cr$h2_plot, cr$k, cr$nLoc, cr$strategy), ]\nknitr::kable(fmt(cr[, c(\"h2_plot\", \"nLoc\", \"k\", \"strategy\", \"acc_all\", \"cached\", \"z\", \"b1\")], 3),\n             row.names = FALSE,\n             col.names = c(\"Plot h2\", \"Locations\", \"k\", \"Strategy\", \"In-repo acc.\", \"Cached acc.\",\n                           \"z\", \"In-repo b1\"))\n```\n\n::: {.cell-output-display}\n\n\n| Plot h2| Locations|  k|Strategy  | In-repo acc.| Cached acc.|      z| In-repo b1|\n|-------:|---------:|--:|:---------|------------:|-----------:|------:|----------:|\n|     0.2|         4|  1|parentage |        0.711|       0.692|  0.690|      0.957|\n|     0.2|         4|  1|random    |        0.726|       0.702|  1.075|      0.962|\n|     0.2|         6|  1|parentage |        0.760|       0.720|  1.911|      1.031|\n|     0.2|         6|  1|random    |        0.728|       0.727|  0.036|      0.976|\n|     0.2|        10|  1|parentage |        0.749|          NA|     NA|      0.953|\n|     0.2|        10|  1|random    |        0.742|          NA|     NA|      0.990|\n|     0.2|         2|  2|complete  |        0.773|       0.733|  1.741|      1.019|\n|     0.2|         4|  2|parentage |        0.814|       0.781|  1.821|      1.015|\n|     0.2|         4|  2|random    |        0.822|       0.762|  4.064|      1.009|\n|     0.2|         6|  2|parentage |        0.816|       0.811|  0.297|      0.999|\n|     0.2|         6|  2|random    |        0.807|       0.816| -0.592|      1.006|\n|     0.2|        10|  2|parentage |        0.823|       0.820|  0.221|      0.982|\n|     0.2|        10|  2|random    |        0.810|       0.819| -0.473|      1.004|\n|     0.4|         4|  1|parentage |        0.845|       0.808|  2.189|      1.032|\n|     0.4|         4|  1|random    |        0.830|       0.817|  0.603|      0.999|\n|     0.4|         6|  1|parentage |        0.841|       0.844| -0.256|      0.976|\n|     0.4|         6|  1|random    |        0.845|       0.836|  0.627|      0.994|\n|     0.4|        10|  1|parentage |        0.858|          NA|     NA|      1.023|\n|     0.4|        10|  1|random    |        0.865|          NA|     NA|      0.986|\n|     0.4|         2|  2|complete  |        0.818|       0.831| -1.229|      1.003|\n|     0.4|         4|  2|parentage |        0.870|       0.862|  0.744|      1.027|\n|     0.4|         4|  2|random    |        0.872|       0.860|  0.959|      1.014|\n|     0.4|         6|  2|parentage |        0.866|       0.887| -1.997|      1.005|\n|     0.4|         6|  2|random    |        0.864|       0.883| -1.827|      0.990|\n|     0.4|        10|  2|parentage |        0.891|       0.897| -0.801|      1.021|\n|     0.4|        10|  2|random    |        0.887|       0.892| -0.558|      0.999|\n\n\n:::\n\n```{.r .cell-code}\ndk <- tapply(cr$acc_all - cr$cached, cr$k, mean, na.rm = TRUE)\n```\n:::\n\n\nAt $k = 2$ the two sources agree within sampling error. The mean difference is\n+0.006, and the gain from spreading the same plots over\nmore locations reproduces. At $k = 1$ the known-component values are higher by\n+0.017 on average. That is the cost of estimating the\ncomponents where REML mostly fails to converge (result 5). The in-repo dispersion\nslopes all sit near 1. The in-repo sweep does **not** resolve the\nparentage-versus-random difference at $k = 1$: its 30 unpaired replicates per\ncell have standard errors near 0.01, the same size as the effect. The paired\ncontrast of @tbl-sparse-contrasts, on 385 pairs, is the evidence for result 3.\n\nThe live functions are verified in `tests/testthat/test-sparse.R`:\n\n- `sparse_blup()` equals the literal GLS form of `ref_sparse_blup()` to\n  $10^{-8}$, including untested hybrids, and so do its PEVs.\n- Every allocation puts each hybrid in exactly $k$ locations.\n- The parentage design covers both pools in every location.\n- The dispersion slope of the known-component BLUP averages 1.\n\nThe cached numbers carry the assumptions listed in the limitations of the\nsimulation (@sec-sparse-results). Treat them as reproducible findings of that\nconfiguration, not as constants.\n\n## Where this connects {#sec-sparse-connects}\n\n- @sec-mating chose *which crosses* to make. This chapter chose *where to plant\n  them*. The joint problem, sparse in crosses and in environments at once, is\n  @sec-mating-open's second gap.\n- The GCA/SCA decomposition and the tester-frequency argument behind Box 5 are\n  derived in @sec-heterosis-gca-sca.\n- The relationship matrices that make sparse designs analysable are those of\n  @sec-genomic-prediction.\n- The staged-trial trade-off of @sec-programme is the line-breeding version of\n  result 6.\n- Spreading testers and parents to slow within-pool erosion is the same concern\n  as @sec-ocs and @sec-cycles. Sparse testcrossing does by design what a\n  diversity constraint does by optimisation.\n",
    "supporting": [
      "04f-sparse-testing_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}