{
  "hash": "2601e251f14289549f3a285a0a1fc552",
  "result": {
    "engine": "knitr",
    "markdown": "# How few hybrids are enough? Mating designs for a two-pool programme {#sec-mating}\n\n\n\nEvery chapter before this one took the hybrids as given. @sec-alphasimr made a\ncommercial cross at the end of a reciprocal scheme, @sec-simulating-crosses\nderived populations from crosses already chosen, and the selection problems of\nthe Optimisation part all start from a list of hybrids with predicted values.\nNone of them asks where that list came from.\n\nIt comes from a crossing plan, and the crossing plan is the most constrained\ndecision a hybrid programme makes. Two pools of 200 candidate lines each define\na factorial of 40,000 single crosses. A field holds 1,000 to 3,000 plots. Every\nhybrid programme is therefore choosing a **sample** of a factorial whose cells\nare overwhelmingly empty, and the classical tester -- every candidate crossed to\none or two lines of the opposite pool -- is one sample among many. This chapter\ntreats the choice of sample as the design problem it is, and defends three\nresults:\n\n1. **At equal field size, a connected sparse factorial among the candidates\n   estimates general combining ability better than a tester design**, at every\n   budget studied, by 0.08 to 0.13 correlation points.\n2. **The analysis matters more than the design.** Analysed by least squares, the\n   sparsest factorials are the worst designs in the study; analysed by BLUP, they\n   are among the best. The penalty for the wrong estimator is the largest single\n   effect measured.\n3. **Genomic information buys inference about lines that were never crossed, not\n   better estimates for lines that were.** Where every candidate is in the field,\n   genomic kernels did not raise GCA accuracy; where only a quarter of them were,\n   they did.\n\nThe running example throughout is one simulated maize programme: two heterotic\npools, 200 doubled-haploid candidates per pool, a field of 1,000 to 3,000 hybrid\nplots, and a winter nursery that must physically produce the seed of every cross\nthat enters the field.\n\n::: {.callout-note}\n## Where the numbers come from\n\nTwo sources, and the chapter keeps them apart. **Live** results are computed at\nrender time with the base-R design functions of `R/16_mating_design.R` -- design\ngenerators, the connectivity diagnostic, least-squares and BLUP estimators with\nknown variance components, and the cost model. **Cached** results come from a\nseparate study (`sparsex`) that founded the pools in AlphaSimR, estimated\nvariance components by REML, fitted genomic kernels and swept 24 designs x 3\nplot budgets x 30 replicates x 3 models. That sweep needs AlphaSimR and an\nexternal REML check against `sommer`, and is not reproducible from this\nrepository; its tables are in `book/data/mating_*.csv` and its figures in\n`book/figs/mating_*.png`. The phenotypic core of it *is* reproduced in-repo\n(`Rscript book/scripts/regenerate.R mating`), and the two are compared in\n@sec-mating-reproduce.\n:::\n\n## Why the crossing plan is the binding decision {#sec-mating-binding}\n\nThe crossing plan, not the statistical model and not the marker platform, sets\nthe ceiling on what a hybrid programme can learn in a cycle. Which lines can be\nranked, whether specific combining ability is estimable at all, how many plots\neach hybrid can occupy, whether untested combinations can be predicted -- every\none of these is fixed the moment the nursery plan is written. A mixed model fitted\nafterwards can only extract what the plan put there.\n\nThe arithmetic is unforgiving. A 200 x 200 factorial against 1,000 to 3,000 plots\nis a sampling fraction of 2.5 to 7.5 % at one plot per hybrid, and below 2 % once\nreplication is required. Three decisions are usually conflated inside \"the\ntesting plan\", and it pays to separate them:\n\n- **which lines** enter the field at all -- every candidate, or a subset chosen\n  by some criterion;\n- **which crosses** among those lines are made -- to a common tester, to each\n  other in a sparse pattern, or in complete blocks;\n- **how many plots** each cross receives -- replicates and locations.\n\nThe organising question of the chapter follows: *for a fixed budget, which\nsample of the factorial maximises the accuracy of combining-ability estimates\nand the selection response they support?* And one constraint is stated now,\nbecause it is the one most often forgotten: **a crossing plan is not a matrix,\nit is a nursery.** Each filled cell is a pollination that must yield enough seed\nfor its plots.\n\nThe three canonical samples drawn over the same grid make the difference visible\nbefore any statistics. The plans below are produced by the package's generators,\nat 40 x 40 so that individual cells can be seen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(3)\ngrids <- list(\"Tester, k = 2\"     = design_tester(40, 40, k = 2),\n              \"Circulant, c = 4\"  = design_circulant(40, 40, c = 4),\n              \"NC II, 10 x 10 sets\" = design_nc2(40, 40, 10, 10))\nop <- par(mfrow = c(1, 3), mar = c(1, 1, 2.2, 1))\nfor (nm in names(grids)) {\n  M <- matrix(0, 40, 40)\n  M[cbind(grids[[nm]]$parent1, grids[[nm]]$parent2)] <- 1\n  image(t(M[40:1, ]), col = c(\"grey96\", \"#1b6ca8\"), axes = FALSE,\n        main = sprintf(\"%s  (%d crosses)\", nm, nrow(grids[[nm]])), cex.main = 0.9)\n  box(col = \"grey60\")\n}\npar(op)\n```\n\n::: {.cell-output-display}\n![Three samples of the same 40 x 40 factorial, drawn by the package's own generators. Rows are pool-A lines, columns pool-B lines, a filled cell is a cross that goes to the field. Left: two testers per pool (156 crosses). Centre: a circulant sparse factorial with four crosses per line (160 crosses). Right: North Carolina Design II as four disconnected 10 x 10 blocks (400 crosses).](04e-mating-design_files/figure-html/fig-mating-grids-1.png){#fig-mating-grids fig-align='center' width=1350}\n:::\n:::\n\n\nThe tester fills two full columns and two full rows: every line meets the same\npartners, so lines are compared on a common background but the background is\nnarrow. The circulant design spreads the same number of crosses as thin diagonals:\nevery line meets different partners, every line is crossed exactly four times,\nand -- the property that the next section shows to matter -- every line is linked\nto every other through a chain of shared partners. NC II fills more cells than\neither and still cannot compare a line in the first block with a line in the\nsecond.\n\n## Combining ability as an estimation problem {#sec-mating-estimation}\n\nGeneral and specific combining ability are properties of a *reference population\nof crosses*, and a design estimates them only to the extent that it samples that\npopulation. @sprague1942 defined them; @griffing1956 drew the distinction between\nfixed-effect inference about a specific set of parents and random-effect inference\nabout the population they were drawn from; @comstock1948 designed the North\nCarolina layouts to separate their variances, and @comstock1949 built reciprocal\nrecurrent selection on them -- the direct ancestor of the two-pool programme.\n\n### The model\n\nAt the level of a cross mean, the two-pool model is\n\n$$\\bar y_{ij} = \\mu + g^A_i + g^B_j + s_{ij} + \\bar e_{ij},\n  \\qquad \\mathrm{Var}(\\bar e_{ij}) = \\sigma^2_e / r_{ij},$$\n\nwith $g^A$, $g^B$ the GCA of the pool-A and pool-B parent, $s_{ij}$ the SCA of\nthe pair, and $r_{ij}$ the plots the cross received. @sec-heterosis-gca-sca derived\nexactly this decomposition from allele frequencies, for the heterosis part of the\nhybrid value, and showed that a pool-A line's GCA is an average effect\n*evaluated at pool B's frequencies*. With an additive effect $a_k$ added to the\ndominance deviation $d_k$, the general combining ability of pool-A line $i$ is\n\n$$g^A_i = \\sum_k \\bigl[a_k + d_k (1 - 2p_{Bk})\\bigr]\\,\\delta u_{ik},$$\n\nthe classical structure of @stuber1966 for a cross between two populations. The\nadditive part adds a term and changes nothing else, which is quick to confirm: the\nrow effects of a complete factorial of genotypic values equal\n`cU %*% a` plus the `gca_A` of `heterosis_gca_sca()`, with no second\nimplementation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(7)\nm  <- 300\npA <- runif(m, 0.1, 0.9); pB <- runif(m, 0.1, 0.9)\nU  <- matrix(rbinom(30 * m, 1, rep(pA, each = 30)), 30)   # 30 inbred lines, pool A\nV  <- matrix(rbinom(25 * m, 1, rep(pB, each = 25)), 25)   # 25 inbred lines, pool B\na  <- rnorm(m, 0, 0.3); d <- rnorm(m, 0.2, 0.2)\n# Genotypic value of every single cross: a(u + v - 1) + d * heterozygosity\nG  <- outer(seq_len(30), seq_len(25), Vectorize(function(i, j)\n        sum(a * (U[i, ] + V[j, ] - 1) + d * (U[i, ] + V[j, ] - 2 * U[i, ] * V[j, ]))))\ncs <- heterosis_gca_sca(U, V, d)\ngcaA_formula <- drop(sweep(U, 2, colMeans(U)) %*% a) + cs$gca_A\nc(max_abs_diff = max(abs((rowMeans(G) - mean(G)) - gcaA_formula)))\n#> max_abs_diff \n#>  2.04281e-14\n```\n:::\n\n\nResult. The row effects of the complete factorial and the closed form agree to\nmachine precision. Interpretation. \"True GCA\" in this chapter is always this\nquantity -- the row and column effects a breeder would estimate by growing every\nhybrid without error -- and every accuracy reported is a correlation with it, over\n**all** candidates of a pool, crossed or not.\n\n### Four quantities that control a design\n\nTable: The four quantities of a two-pool mating design, their closed forms and what controls them. {#tbl-mating-quantities}\n\n| Quantity | Closed form | Controlled by |\n|---|---|---|\n| Rank of the GCA design matrix $[\\mathbf 1 \\mid Z_A \\mid Z_B]$ | $n_A' + n_B' - (\\text{connected components})$ | which crosses are made: the bipartite graph |\n| Residual df for SCA at cross-mean level | $n_{\\text{crosses}} - \\text{rank}$ | crosses per line; zero for one tester per pool |\n| LS sampling error of a GCA estimate, $c$ crosses per line | $\\sigma^2_{s}/c + \\sigma^2_e/(c\\,r)$ | $c$ buys down both terms, $r$ only the second |\n| LS accuracy of a GCA estimate | $\\rho = \\sqrt{\\sigma^2_g / (\\sigma^2_g + \\sigma^2_s/c + \\sigma^2_e/(c\\,r))}$ | the same, as a correlation |\n\nThe third row is the quantitative form of the argument of @sprague1942 for using\nmore than one tester, and the fourth is its square root as an accuracy: the\nsquare root of the heritability of a testcross mean [@hallauer2010]. Both\ndescribe **least squares**. A shrinkage estimator on a connected design borrows\ninformation across lines and exceeds them, which is why @sec-mating-analysis\nexists.\n\nThe cached run validated the third and fourth rows against simulation in the\ncomplete 200 x 200 factorial, for $k = 1, 2, 4, 8$ testers and $r = 1, 2$ plots:\n\n\n::: {#tbl-mating-v4 .cell layout-align=\"center\" tbl-cap='Least-squares GCA accuracy in a k-tester design: simulated (30-replicate mean, testers resampled) against the closed form. Cached from the `sparsex` validation suite, check V4.'}\n\n```{.r .cell-code}\nv4 <- subset(val, grepl(\"^V4\", check))\nfmt(data.frame(design = sub(\"cor\\\\(ghat_LS, GCA\\\\), \", \"\", v4$quantity),\n               simulated = v4$observed, closed_form = v4$expected,\n               rel_error_pct = 100 * v4$rel_error), 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|design  | simulated| closed_form| rel_error_pct|\n|:-------|---------:|-----------:|-------------:|\n|k=1 r=1 |     0.394|       0.391|         0.826|\n|k=1 r=2 |     0.499|       0.503|        -0.840|\n|k=2 r=1 |     0.509|       0.515|        -1.094|\n|k=2 r=2 |     0.639|       0.635|         0.534|\n|k=3 r=1 |     0.593|       0.592|         0.108|\n|k=3 r=2 |     0.713|       0.710|         0.500|\n|k=4 r=1 |     0.646|       0.647|        -0.119|\n|k=4 r=2 |     0.758|       0.758|        -0.065|\n|k=8 r=1 |     0.772|       0.768|         0.520|\n|k=8 r=2 |     0.855|       0.855|         0.075|\n\n</div>\n:::\n:::\n\n\nThe largest relative error is 1.1 %. The\nexpression is a reliable description of least squares on a tester design, and\nthe cost optimiser of @sec-mating-cost uses it for that reason -- knowing it is\nconservative for anything shrunk.\n\n### Connectivity, in one paragraph {#sec-mating-connectivity}\n\n::: {.callout-important}\n## The rank rule\n\nA mating design is a bipartite graph: pool-A lines on one side, pool-B lines on\nthe other, an edge for every cross. GCA contrasts are estimable **within** a\nconnected component of that graph and **not between** components, so the rank\nof the GCA design matrix is $n_A' + n_B' - (\\text{components})$, one lost\nconstraint per component. That is the formal content of what breeders call \"ties\nbetween sets\", and it was settled long ago: @weeks1964 gave the criterion for an\n$N$-way classification and @fernando1983 an algorithm for the connected subsets\nof a two-way one.\n:::\n\n`design_diagnostics()` computes both sides of the rule independently -- the\nnumerical rank by QR, the components by union-find over the graph -- so a\ndisagreement would be a bug, not a modelling choice:\n\n\n::: {#tbl-mating-connectivity .cell layout-align=\"center\" tbl-cap='Connectivity and estimability of five designs on the 200 x 200 running example. `rank_gca` is the numerical rank of the GCA design matrix; `rank_expected` is the graph prediction; `df_sca` is what is left at cross-mean level to separate SCA from error.'}\n\n```{.r .cell-code}\nset.seed(2026)\nplans <- list(\"tester k=1\"        = design_tester(n, n, 1),\n              \"tester k=2\"        = design_tester(n, n, 2),\n              \"random sparse c=2\" = design_random_sparse(n, n, 2),\n              \"circulant c=2\"     = design_circulant(n, n, 2),\n              \"circulant c=5\"     = design_circulant(n, n, 5),\n              \"NC II 10x10 sets\"  = design_nc2(n, n, 10, 10))\ndiag_tab <- do.call(rbind, lapply(names(plans), function(nm) {\n  d <- design_diagnostics(plans[[nm]], n, n)\n  data.frame(design = nm, crosses = d$n_crosses,\n             untested = 2 * n - d$lines_A - d$lines_B,\n             components = d$components, rank_gca = d$rank_gca,\n             rank_expected = d$rank_expected, df_sca = d$df_sca)\n}))\nstopifnot(all(diag_tab$rank_gca == diag_tab$rank_expected))\ndiag_tab\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|design            | crosses| untested| components| rank_gca| rank_expected| df_sca|\n|:-----------------|-------:|--------:|----------:|--------:|-------------:|------:|\n|tester k=1        |     399|        0|          1|      399|           399|      0|\n|tester k=2        |     796|        0|          1|      399|           399|    397|\n|random sparse c=2 |     400|       53|         11|      336|           336|     64|\n|circulant c=2     |     400|        0|          1|      399|           399|      1|\n|circulant c=5     |    1000|        0|          1|      399|           399|    601|\n|NC II 10x10 sets  |    2000|        0|         20|      380|           380|   1620|\n\n</div>\n:::\n:::\n\n\nResult. The rank equals the graph prediction in every row. The NC II layout --\ntwenty disconnected 10 x 10 blocks -- has rank 380, not 399:\ntwenty components, twenty lost constraints. The random sparse design at two\ncrosses per line leaves 53 candidates with no cross at all\nand splits the rest into 11 components; the circulant\ndesign with the same number of crosses is a single component with every line\ncrossed exactly twice. One tester per pool is connected and has **zero** residual\ndf: $n_A + n_B - 1$ crosses for $n_A + n_B - 1$ GCA parameters. The GCA model is\nsaturated and SCA is not merely imprecise, it is not identifiable.\n\nWhat \"not estimable\" means is checked directly. A contrast between two lines of\nthe same NC II block lies in the row space of the design matrix; a contrast\nbetween lines of different blocks does not:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnc <- plans[[\"NC II 10x10 sets\"]]\nl_within  <- c(0, 1, -1, rep(0, 2 * n - 2))           # A1 - A2, same block\nl_between <- c(0, 1, rep(0, 9), -1, rep(0, 2 * n - 11)) # A1 - A11, next block\nrbind(within  = unlist(design_estimable(nc, n, n, l_within)),\n      between = unlist(design_estimable(nc, n, n, l_between)))\n#>         estimable rel_residual\n#> within          1 3.831056e-16\n#> between         0 2.236068e-01\n```\n:::\n\n\nThe within-block residual is rounding error; the between-block residual is\n0.224, a contrast\nnowhere near the row space. Any least-squares ranking that crosses block boundaries\nin this design is a statement about the analyst's centring convention, not about\nthe lines.\n\nBLUP does rank across blocks, and in the simulations below NC II scores well on\nall-lines accuracy. It can, because a random-effects model supplies the missing\nconstraint from its prior: every block's lines are assumed drawn from the same pool\ndistribution, so every block mean is shrunk to the same value. That assumption is\nexactly true in a simulation that assigns lines to blocks at random, and exactly\nwhat fails when blocks are families, years or breeders' sub-programmes with real\nmean differences. Disconnection is not repaired by the estimator; it is replaced by\nan assumption, and the assumption should be stated.\n\n### SCA and the cross-level residual are the same thing in cross means\n\nOne more property of the model must be stated before any variance component is\nreported. Each cross has its own SCA, so in cross-mean data $s_{ij}$ and\n$\\bar e_{ij}$ occupy exactly the same position: only their sum\n$\\sigma^2_s + \\sigma^2_e / r$ is identified. The cached study separated them by\nfixing $\\sigma^2_e$ from the within-cross plot variance of stage 1 and estimating\n$\\sigma^2_s$; an independent REML implementation (`sommer`) estimated a residual\nscale instead and put $\\sigma^2_s$ at zero, and the two agreed on the **sum** to\n2e-06 relative error. A reported\n$\\sigma^2_{SCA}$ from cross means is only as good as the external plot-error\nestimate it was separated with. `fit_gca()` in this package sidesteps the question\nby taking the components as known, and weights each cross mean by\n$1/(\\sigma^2_s + \\sigma^2_e/r)$ for exactly this reason.\n\n## The classical tester approach {#sec-mating-tester}\n\nThe tester design answers the sampling problem by collapsing one margin of the\ntable. Each candidate is crossed to $k$ testers of the opposite pool, and in the\nusual reciprocal arrangement each pool's candidates are tested against the other's\ntesters, giving $k(n_A + n_B) - k^2$ crosses. The topcross method goes back to\n@jenkins1932, the argument for general versus specific combining ability to\n@sprague1942 and @hull1945, and the modern treatment of tester choice is\n@hallauer2010.\n\n### What a tester is for, and what it trades\n\nA tester is a **deliberate variance trade**. It buys cheap seed production and\nperfect connectivity -- every line tied to every other through the common testers\n-- at the price of confounding a line's GCA with its SCA *to the testers used*,\nand of a training set that covers the relationship space of the opposite pool\nvery thinly. The testcross mean of line $i$ estimates $g^A_i$ plus the mean of $k$\nSCA deviations, so its error variance carries $\\sigma^2_s/k$ and\n$\\sigma^2_e/(k r)$. Adding testers buys down both terms; adding replicates buys\ndown only one. That is why the allocation literature treats tester number as a\ndecision variable jointly with lines, locations and stages [@longin2006c], and why\nit is not interchangeable with replication.\n\nThe closed form and its least-squares simulation on the running example, with the\ntruth redrawn in every replicate so that tester SCA is resampled as the theory\nassumes:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\ntester_mc <- do.call(rbind, lapply(c(1, 2, 3, 4, 8), function(k) {\n  do.call(rbind, lapply(1:2, function(r) {\n    acc <- replicate(12, {\n      tr <- simulate_factorial(n, n, vc$A, vc$B, vc$S)\n      p  <- design_tester(n, n, k)\n      p$reps <- r\n      p  <- simulate_cross_means(p, tr, s2e)\n      f  <- fit_gca(p, n, n, vc$A, vc$B, vc$S, s2e, \"ls\")\n      mean(c(cor(f$gA, tr$gA), cor(f$gB, tr$gB)))\n    })\n    data.frame(k = k, r = r, acc = mean(acc), se = sd(acc) / sqrt(length(acc)))\n  }))\n}))\nkk <- seq(1, 8, by = 0.1)\nplot(NA, xlim = c(1, 8), ylim = c(0.3, 0.9), xlab = \"testers per pool, k\",\n     ylab = \"GCA accuracy (all 200 lines)\", las = 1)\ncols <- c(\"#1b6ca8\", \"#b2182b\")\nfor (r in 1:2) {\n  lines(kk, gca_accuracy_theory(kk, r, (vc$A + vc$B) / 2, vc$S, s2e),\n        col = cols[r], lwd = 2)\n  d <- tester_mc[tester_mc$r == r, ]\n  arrows(d$k, d$acc - 2 * d$se, d$k, d$acc + 2 * d$se, angle = 90,\n         code = 3, length = 0.03, col = cols[r])\n  points(d$k, d$acc, pch = 19, col = cols[r])\n}\nlegend(\"bottomright\", c(\"1 plot per testcross\", \"2 plots per testcross\"),\n       col = cols, lwd = 2, pch = 19, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![GCA accuracy of a k-tester design against the number of testers, at one and two plots per testcross. Lines: the closed form of @tbl-mating-quantities. Points: least-squares estimates from `fit_gca()` on the 200 x 200 running example, mean of 12 replicates with the truth redrawn each time; bars are two standard errors.](04e-mating-design_files/figure-html/fig-mating-testers-1.png){#fig-mating-testers fig-align='center' width=1050}\n:::\n:::\n\n\nResult. The simulated least-squares accuracies sit on the closed form at every\n$k$ and both replication levels, which is the in-repo counterpart of the cached\ncheck V4. The returns to testers diminish fast: going from one to two testers at\none plot raises accuracy from\n0.38 to\n0.5; going from\nfour to eight adds\n0.12.\nInterpretation. Here the plot error, $\\sigma^2_e \\approx$ 42.6 at a\nsingle-plot heritability of 0.3, dwarfs $\\sigma^2_s =$ 2.899, so testers and\nreplicates are nearly interchangeable *in this simulation*. In material where SCA\nis 20 to 30 % of the genetic variance [@giraud2017; @lorenzi2024] the $\\sigma^2_s/k$\nterm is no longer negligible and testers buy strictly more than replicates.\n@sec-heterosis-step6 gives the finite-population version of the same curve, with\n$k$ testers drawn without replacement from the $n_B$ available.\n\n### Choice of tester\n\nThe long-standing debate is between broad-base testers, elite inbreds and elite\nsingle crosses. The theoretical argument against a high-performing tester is\n@smith1986's: for many loci with substantial dominance, favourable dominant alleles\ncarried by a good tester *mask* the candidate's alleles, reducing the variance\namong testcrosses and with it the correlation between testcross and line value. A\ngood tester discriminates less. The counter-argument is operational: an elite\ntester produces hybrids that are themselves candidate products, so the testcross\ntrial doubles as a product trial in the background where the line will actually\nbe sold [@hallauer2010]. Programmes have resolved the tension by staging --\ndiscriminating testers early, elite testers late, single-cross evaluation last --\nand the number of testers per stage turns out to be among the highest-leverage\nparameters of the whole scheme: replacing a 4-1-1 tester plan with a 2-2-1 plan,\nwith doubled haploids and higher selection intensity, raised gain per dollar by\n43.1 % and cut the cost of a unit of gain by 28.5 % in a simulated African maize\nprogramme [@chaingeni2025].\n\n### What testers cannot deliver\n\nThree limitations recur, and the simulation adds numbers to two of them.\n\n**No SCA in the reference population.** With $k = 1$ the GCA model is saturated\nand $\\sigma^2_{SCA}$ is not identifiable at all (`df_sca` = 0 in\n@tbl-mating-connectivity). With $k \\ge 2$ it is identified, but the cached REML\nestimates of the SCA:GCA ratio were inflated by +14.8 % at $k = 2$ and +12.8 % at\n$k = 4$, against +0.3 % for a circulant factorial with three crosses per line. A\ntester design estimates SCA *with the testers*, not in the population of crosses\nthe programme will sell.\n\n**Testcross ranking is not single-cross ranking.** Comparing testcross progeny\ntests with randomly paired single-cross tests, @burdo2021 found that the top 25\nlines on testcross yield and on single-cross yield coincided for only 48 % of\nlines in the Stiff Stalk pool and 11 % in the Iowa Dent pool -- almost disjoint\nselections -- rising to 56 % in both with genomic prediction.\n\n**A thin training set.** All hybrids of a candidate share one or two partners, so\nthe design explores a narrow slice of the hybrid relationship space. Testcross\nwas the worst of the designs compared as a training set for predicting the\nsingle crosses of a full diallel [@fritscheneto2018], and simulation agrees that\nthe deficit grows with the SCA share [@seye2020].\n\n### When the tester is still right\n\nNone of this makes testers obsolete. They remain the right answer when seed\nproduction rather than plot capacity binds -- a tester cross is made in bulk in an\nisolation block or on a male-sterile female, a sparse factorial needs many small\nhand pollinations (@sec-mating-cost) -- when the candidate set is so large that\nthe first screen must be cheap per line, in programmes that cannot fit a mixed\nmodel (@sec-mating-analysis), and in the first cycle of a new pool, where there is\nno relationship information to exploit. @gonzalezdieguez2026 make the case for a\nhybrid of the two logics: three to five testers allocated *sparsely* across\nfamilies rather than every tester crossed to every line.\n\n## Sparse and incomplete factorials {#sec-mating-sparse}\n\nOnce candidates are crossed to *each other* rather than to a common tester, the\ndesign becomes a sparse bipartite graph, and two things matter: how many crosses\neach line gets, $c$, and whether the graph is connected. Which particular partners\nare drawn matters much less.\n\n### The design family\n\nThe classical theory is the partial diallel of @kempthorne1961: each parent\ncrossed to a fixed number $s$ of others, with the sampling variances of the\ngenetic components derived as functions of $s$. Its two-pool analogue is the\nincomplete factorial, each pool-A line crossed to $c$ of the $n_B$ pool-B lines.\nThe members studied here:\n\n- **random sparse** -- $c \\cdot n_A$ cells drawn at random. Lines receive a\n  Binomial number of crosses, some none; the graph may be disconnected.\n- **circulant (round-robin)** -- pool-A line $i$ crossed to pool-B lines\n  $(i - 1 + o) \\bmod n_B + 1$ for $c$ offsets $o$. With $n_A = n_B$ every line in\n  both pools has exactly $c$ crosses, and choosing offsets with\n  $\\gcd(n_B, \\Delta o) = 1$ guarantees one component. `design_circulant()` nudges\n  the last offset until that holds.\n- **NC II in sets** -- complete $a \\times b$ factorials on disjoint line sets\n  [@comstock1948]; deliberately disconnected.\n- **criterion-optimised** -- greedy exchange towards A-optimality, D-optimality or\n  CDmean [@rincent2012]; **relationship-guided** -- partners chosen to minimise\n  genomic similarity between parents. Both appear in the cached sweep only.\n\n### How sparse is sparse enough -- the published evidence\n\nRemarkably sparse, provided the design is structured and analysed well. The most\ninformative single data point is operational rather than simulated: a commercial\nwinter oilseed rape programme ran 4,000 hybrids over 61 unreplicated trials\ncovering **1.67 % of all mother x father combinations**, and a GCA + SCA model\nstill reached accuracies of 0.63, 0.84 and 0.80 for yield, oil and protein after a\nfurther 50 % of the observations were artificially removed [@thomsen2026]. Across\nmaize, wheat and rice, training sets of 2 to 13 % of the hybrid set sufficed for\ngenomic prediction [@guo2019]. A 363-hybrid dent x flint factorial predicted an\nindependent 951-hybrid factorial as well as or better than tester designs at\nequal numbers of hybrids and lines [@lorenzi2022]; NC II was the best and\ntestcross the worst training set for predicting a full diallel\n[@fritscheneto2018]; and in simulation the factorial's advantage grew with the\nSCA share [@seye2020].\n\nThe design principle that emerges is to **spend the hybrid budget on parents, not\non depth per parent** -- up to the point where $c$ is so small that connectivity\nand within-line precision fail. Where that point lies depends on heritability and\nSCA share. For hybrids with both parents untested at $c = 1$, @melchinger2023\nreported attainable accuracies of 0.50 to 0.65 at $h^2 = 0.4$ and 0.70 to 0.85 at\n$h^2 = 0.8$, the low end belonging to the high-SCA scenario, and found raising $c$\nfrom 1 to 4 helped most exactly there.\n\n### Sparse versus tester, at equal plot budget\n\nThe cached sweep puts every design at the same three plot budgets and scores GCA\naccuracy over all 200 candidates per pool, analysed by phenotypic BLUP:\n\n![GCA accuracy against the number of distinct hybrids in the field, one line per design family, panelled by plot budget. Cached from the `sparsex` sweep: 30 replicates per cell, phenotypic BLUP, accuracy over all 200 candidates per pool.](figs/mating_acc_vs_hybrids.png){#fig-mating-acc-hybrids width=100%}\n\n\n::: {#tbl-mating-h2h .cell layout-align=\"center\" tbl-cap='Best tester against best sparse factorial (circulant or random) at each plot budget, phenotypic BLUP. `z` is the difference in standard errors of the difference; anything above 3 is resolved by 30 replicates.'}\n\n```{.r .cell-code}\nsparse_fam <- c(\"sparse_circulant\", \"sparse_random\")\nh2h <- do.call(rbind, lapply(split(bl, bl$budget_plots), function(d) {\n  t <- subset(d, family == \"tester\");       t <- t[which.max(t$acc_gca_all), ]\n  s <- subset(d, family %in% sparse_fam);   s <- s[which.max(s$acc_gca_all), ]\n  data.frame(plots = d$budget_plots[1],\n             best_tester = t$scenario, tester_hybrids = round(t$n_crosses),\n             tester_acc = t$acc_gca_all,\n             best_sparse = s$scenario, sparse_hybrids = round(s$n_crosses),\n             sparse_acc = s$acc_gca_all,\n             difference = s$acc_gca_all - t$acc_gca_all,\n             z = (s$acc_gca_all - t$acc_gca_all) /\n                 sqrt(s$se_acc_gca_all^2 + t$se_acc_gca_all^2))\n}))\nfmt(h2h, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     | plots|best_tester | tester_hybrids| tester_acc|best_sparse        | sparse_hybrids| sparse_acc| difference|      z|\n|:----|-----:|:-----------|--------------:|----------:|:------------------|--------------:|----------:|----------:|------:|\n|1000 |  1000|tester k=2  |            796|      0.537|circulant c=5      |           1000|      0.661|      0.125| 16.970|\n|2000 |  2000|tester k=4  |           1584|      0.677|circulant c=10     |           2000|      0.784|      0.107| 22.457|\n|3000 |  3000|tester k=4  |           1584|      0.746|random sparse c=10 |           2000|      0.827|      0.082| 21.904|\n\n</div>\n:::\n:::\n\n\nResult. The sparse factorial wins at every budget, by\n0.125, 0.107 and\n0.082, each more than 16 standard errors.\nAt 1,000 plots the relationship-guided design with five crosses per line is\nmarginally ahead of the circulant one\n(0.662,\na difference well inside the noise); it is excluded from the table only so that\nthe comparison is between designs that need no markers. Interpretation. Two\nfeatures of the table are mechanical and worth naming. The best tester never uses\nmore than 1,584 crosses because $k = 4$ is the largest tester set swept, and at\n3,000 plots it can only add replication, which buys down $\\sigma^2_e$ but not\n$\\sigma^2_s$. And the sparse winner at 3,000 plots is random rather than circulant\nbecause at $c = 10$ connectivity is no longer in question and the layouts converge.\n\nThe smallest fields that reach a given accuracy:\n\n\n::: {#tbl-mating-fewest .cell layout-align=\"center\" tbl-cap='Fewest distinct field hybrids, over all designs and budgets, whose phenotypic-BLUP GCA accuracy reaches each target. Costs use the placeholder levels of @sec-mating-cost.'}\n\n```{.r .cell-code}\nfewest <- do.call(rbind, lapply(c(0.60, 0.65, 0.70, 0.75, 0.80), function(tg) {\n  d <- subset(bl, acc_gca_all >= tg)\n  d <- d[order(d$n_crosses, d$budget_plots), ][1, ]   # ties: the smaller field\n  data.frame(target = tg, design = d$scenario, plots = d$budget_plots,\n             hybrids = round(d$n_crosses), pct_factorial = 100 * d$n_crosses / n^2,\n             accuracy = d$acc_gca_all, se = d$se_acc_gca_all,\n             cost = round(d$cost_total))\n}))\nfmt(fewest, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| target|design                  | plots| hybrids| pct_factorial| accuracy|    se|   cost|\n|------:|:-----------------------|-----:|-------:|-------------:|--------:|-----:|------:|\n|   0.60|circulant c=2           |  1000|     400|         1.000|    0.608| 0.003|  67800|\n|   0.65|relationship-guided c=3 |  2000|     600|         1.499|    0.722| 0.004|  93261|\n|   0.70|relationship-guided c=3 |  2000|     600|         1.499|    0.722| 0.004|  93261|\n|   0.75|relationship-guided c=5 |  2000|     999|         2.497|    0.764| 0.004| 102292|\n|   0.80|relationship-guided c=5 |  3000|     999|         2.497|    0.815| 0.002| 132193|\n\n</div>\n:::\n:::\n\n\nResult. Four hundred hybrids -- 1 % of the factorial -- reach\n0.608; about 600 (1.5 %) reach\n0.722; about 1,000 (2.5 %) reach\n0.815. Interpretation. This confirms the order of\nmagnitude of the operational and published sampling fractions [@thomsen2026;\n@guo2019] and adds the part they leave implicit: the fraction is set by the\naccuracy target, not by a universal threshold.\n\n### Crosses per line, and structure versus randomness\n\n![GCA accuracy against crosses per line $c$, separating circulant (structured) from random sparse layouts. Cached from the `sparsex` sweep.](figs/mating_acc_vs_c.png){#fig-mating-acc-c width=100%}\n\nThe literature leaves one comparison open: structured against random layouts at\nmatched $c$ [@weeks1964 and @fernando1983 supply the tools; no retrieved design\npaper reports the connectivity of the layout it used]. The sweep closes it at\n2,000 plots:\n\n\n::: {#tbl-mating-matched-c .cell layout-align=\"center\" tbl-cap='Circulant against random sparse at matched crosses per line, 2,000 plots, phenotypic BLUP.'}\n\n```{.r .cell-code}\nmc <- subset(bl, budget_plots == 2000 & family %in% sparse_fam)\nmc <- merge(subset(mc, family == \"sparse_circulant\")[, c(\"x_axis\", \"acc_gca_all\", \"se_acc_gca_all\")],\n            subset(mc, family == \"sparse_random\")[, c(\"x_axis\", \"acc_gca_all\", \"se_acc_gca_all\")],\n            by = \"x_axis\", suffixes = c(\"_circ\", \"_rand\"))\nmc <- data.frame(c = mc$x_axis, circulant = mc$acc_gca_all_circ,\n                 random = mc$acc_gca_all_rand,\n                 difference = mc$acc_gca_all_circ - mc$acc_gca_all_rand,\n                 z = (mc$acc_gca_all_circ - mc$acc_gca_all_rand) /\n                     sqrt(mc$se_acc_gca_all_circ^2 + mc$se_acc_gca_all_rand^2))\nfmt(mc, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  c| circulant| random| difference|     z|\n|--:|---------:|------:|----------:|-----:|\n|  2|     0.633|  0.602|      0.031| 6.392|\n|  3|     0.727|  0.689|      0.037| 8.706|\n|  5|     0.759|  0.740|      0.018| 4.120|\n| 10|     0.784|  0.773|      0.011| 3.155|\n\n</div>\n:::\n:::\n\n\nResult. The circulant layout is ahead at every $c$, and the gap shrinks as $c$\ngrows, from 0.031 at $c = 2$ to\n0.011 at $c = 10$; all four gaps exceed three standard errors\nof the difference. Interpretation. This is what @tbl-mating-connectivity predicts:\nat $c = 2$ the random layout leaves lines uncrossed and splits the rest into many\ncomponents, so its advantage is pure connectivity, and connectivity stops being\nbinding once every line has enough partners. **A sparse factorial should be\nbuilt, not sampled.**\n\n### What is lost\n\nSCA is weakly estimated at low $c$. The circulant design with $c = 2$ has exactly\n1 residual degree of freedom at cross-mean level\n(@tbl-mating-connectivity) -- enough to fit a model and not enough to estimate a\nvariance component -- and the cached REML recovered the SCA:GCA ratio there with\na +34.4 % error, the largest in the sweep. The recommendation therefore splits by\nobjective: $c = 2$ to rank lines, $c \\ge 3$ before any statement about SCA\nvariance.\n\nSparsity in crosses also interacts with sparsity in environments. A parallel\nliterature, mostly from CIMMYT, allocates entries to subsets of environments and\npredicts the unobserved line-by-environment cells [@jarquin2020; @atanda2021;\n@atanda2022; @montesinoslopez2023]. When the genetic correlation between\nmanagements is as low as 0.37 [@atanda2021], a line observed only in one is weakly\ninformative about the other. A design observing 2 % of the hybrid factorial and\n30 % of the environment cells within that observes well under 1 % of the\ninformation space, and the two sparsities have not been studied together for\nhybrids (@sec-mating-open).\n\n## The analysis is part of the design {#sec-mating-analysis}\n\nA sparse factorial is only a good design if it is analysed with a shrinkage\nestimator. This section exists because the single largest effect in the study is\nnot a design effect at all.\n\nThe demonstration is live: one replicate of the running example at 2,000 plots,\nthe same data analysed both ways.\n\n\n::: {#tbl-mating-ls-blup .cell layout-align=\"center\" tbl-cap='One replicate of the 200 x 200 running example at 2,000 plots: the same phenotypes analysed by least squares and by BLUP with known variance components.'}\n\n```{.r .cell-code}\nset.seed(99)\nls_blup <- do.call(rbind, lapply(c(\"tester k=2\", \"circulant c=2\", \"circulant c=5\"),\n  function(nm) {\n    tr <- simulate_factorial(n, n, vc$A, vc$B, vc$S)\n    p  <- simulate_cross_means(design_reps(plans[[nm]], 2000), tr, s2e)\n    acc <- sapply(c(\"ls\", \"blup\"), function(meth) {\n      f <- fit_gca(p, n, n, vc$A, vc$B, vc$S, s2e, meth)\n      mean(c(cor(f$gA, tr$gA), cor(f$gB, tr$gB)))\n    })\n    data.frame(design = nm, crosses = nrow(p), plots_per_cross = mean(p$reps),\n               least_squares = acc[[\"ls\"]], blup = acc[[\"blup\"]],\n               blup_advantage = acc[[\"blup\"]] - acc[[\"ls\"]])\n  }))\nfmt(ls_blup, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|design        | crosses| plots_per_cross| least_squares|  blup| blup_advantage|\n|:-------------|-------:|---------------:|-------------:|-----:|--------------:|\n|tester k=2    |     796|           2.513|         0.649| 0.658|          0.008|\n|circulant c=2 |     400|           3.000|         0.186| 0.627|          0.441|\n|circulant c=5 |    1000|           2.000|         0.590| 0.757|          0.166|\n\n</div>\n:::\n:::\n\n\nResult. On the tester design the two estimators agree to within\n0.008. On the circulant design with two\ncrosses per line, least squares collapses to\n0.19 while BLUP reaches\n0.63 on the same data. The cached sweep, averaged over 30\nreplicates, reproduces the pattern across all 24 designs:\n\n\n::: {#tbl-mating-ls-sweep .cell layout-align=\"center\" tbl-cap='BLUP advantage over least squares by design, 2,000 plots, ordered by size. Cached `sparsex` sweep, 30 replicates per cell.'}\n\n```{.r .cell-code}\nlsb <- merge(subset(sm, model == \"LS\"   & budget_plots == 2000)[, c(\"scenario\", \"n_crosses\", \"acc_gca_all\")],\n             subset(sm, model == \"BLUP\" & budget_plots == 2000)[, c(\"scenario\", \"acc_gca_all\")],\n             by = \"scenario\", suffixes = c(\"_ls\", \"_blup\"))\nlsb$advantage <- lsb$acc_gca_all_blup - lsb$acc_gca_all_ls\nlsb <- lsb[order(-lsb$advantage), ]\nnames(lsb) <- c(\"design\", \"hybrids\", \"least_squares\", \"blup\", \"advantage\")\nlsb$hybrids <- round(lsb$hybrids)\nrownames(lsb) <- NULL\nfmt(lsb, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|design                       | hybrids| least_squares|  blup| advantage|\n|:----------------------------|-------:|-------------:|-----:|---------:|\n|circulant c=2                |     400|         0.134| 0.633|     0.498|\n|circulant c=3                |     600|         0.255| 0.727|     0.472|\n|circulant c=5                |    1000|         0.541| 0.759|     0.218|\n|random sparse c=2            |     400|         0.417| 0.602|     0.185|\n|random sparse c=3            |     600|         0.587| 0.689|     0.102|\n|A-optimal c=3                |     600|         0.626| 0.726|     0.100|\n|100 lines/pool c=5 (random)  |     500|         0.484| 0.579|     0.095|\n|relationship-guided c=3      |     600|         0.635| 0.722|     0.087|\n|100 lines/pool c=5 (cdmean)  |     500|         0.490| 0.573|     0.084|\n|circulant c=10               |    2000|         0.707| 0.784|     0.077|\n|random sparse c=5            |    1000|         0.689| 0.740|     0.051|\n|NC II 10x10 sets             |    2000|         0.737| 0.768|     0.031|\n|50 lines/pool c=5 (random)   |     250|         0.373| 0.397|     0.024|\n|relationship-guided c=5      |     999|         0.740| 0.764|     0.023|\n|50 lines/pool c=5 (cdmean)   |     250|         0.350| 0.369|     0.018|\n|random sparse c=10           |    2000|         0.756| 0.773|     0.016|\n|100 lines/pool c=10 (random) |    1000|         0.598| 0.612|     0.015|\n|100 lines/pool c=10 (cdmean) |    1000|         0.593| 0.605|     0.012|\n|tester k=4                   |    1584|         0.670| 0.677|     0.007|\n|tester k=3                   |    1191|         0.663| 0.667|     0.005|\n|tester k=2                   |     796|         0.653| 0.657|     0.004|\n|50 lines/pool c=10 (random)  |     500|         0.437| 0.440|     0.003|\n|50 lines/pool c=10 (cdmean)  |     500|         0.414| 0.417|     0.002|\n|tester k=1                   |     399|         0.544| 0.545|     0.001|\n\n</div>\n:::\n:::\n\n\nResult. The penalty for least squares is\n0.498 accuracy points at circulant $c = 2$ and\n0.472 at $c = 3$; for the four tester designs it is\n0.001 to\n0.007. Testers are robust to\na naive analysis; sparse factorials are not.\n\nInterpretation. At low $c$ each GCA estimate rests on two or three cross means,\neach carrying a full $\\sigma^2_s + \\sigma^2_e/r$ of noise, and the unshrunken\nestimate is dominated by it. BLUP borrows strength across the connected graph: a\nline's partners are themselves estimated from *their* partners, and the shrinkage\ntowards zero is proportional to how little each line was observed. That the\ncirculant design loses more to least squares than the random one at the same $c$\nis not a contradiction of the previous section. The circulant design's partners\nare each other's partners in long chains, which is exactly what BLUP exploits and\nleast squares cannot.\n\nThe practical consequence is unconditional: **a programme that cannot or will not\nfit a mixed model should not move to a sparse factorial** -- the design's advantage\nis entirely conditional on the estimator. The literature that motivated BLUP of\nsingle crosses [@bernardo1994; @bernardo1996] and the allocation tools that assume\nit [@endelman2014; @mi2014] take this for granted; the design literature, in the\nreview behind this chapter, never states it.\n\n## Genomic information for deciding which crosses to make {#sec-mating-genomic}\n\nGenomic information changes the question from *how well can I estimate the lines I\ncrossed?* to *which crosses should I make, and what can I say about the ones I\ndid not?* Its value is in extrapolation and in the choice of what to field, not in\nimproving estimates for lines that are already there.\n\n### From relatedness to hybrid prediction\n\nThe idea that untested single crosses can be predicted from tested ones through\nmarker relatedness is @bernardo1994's: random subsets of 10 to 30 hybrids from a\n54-hybrid factorial, and RFLP relationships recovering single-cross performance.\n@bernardo1996 scaled it to operational data, with correlations of 0.43 to 0.76 for\nyield in heterotic patterns with more than 100 tested crosses. The modern version\nmodels hybrid value as pool-specific additive kernels for GCA plus a dominance or\nproduct kernel for SCA [@technow2012; @massman2012; @technow2014]; @sec-genomic-prediction\nis where this book fits those models, and @sec-hybrid-cv where it validates them\nby masking hybrids.\n\nThe kernel the cached sweep used for SCA follows from the algebra of\n@sec-mating-estimation: $s_{ij} = -2\\sum_k d_k\\,\\delta u_{ik}\\,\\delta v_{jk}$ is linear\nin the *elementwise product* of the two parents' centred genotypes, so the natural\nSCA kernel is the linear kernel on that product. It is **not** the Hadamard\nproduct of the two pool kernels, which adds cross-locus terms the model does not\ncontain.\n\n### The T0 / T1 / T2 hierarchy\n\nThe standard currency for comparing designs is the split of untested hybrids by how\nmany of their parents appear in the training set: both (T2), one (T1), neither (T0).\nGrain-yield accuracies of 0.91, 0.85 and 0.77 with 300 training hybrids\n[@technow2014], 0.92, 0.88 and 0.80 under a GCA model on the Hohenheim series\n[@gonzalezdieguez2021], and 0.28 to 0.77 with the ordering\nT2 > T1-female > T1-male > T0 [@kadam2016b]. The hierarchy also explains why a\ntester is a poor training set: it generates only T1-type information for new\nlines, because the tester is always a tested parent and the candidate never is.\n\nThese figures share a property that must be stated: they come from material with\nstrong family structure, where an untested line has close relatives in the\ntraining set. @technow2019 found the advantage of a better training-set composition\nshrank from 0.15 accuracy points for well-connected hybrids to 0.06 for T0 under a\ndivergent heterotic structure. **Published T0 accuracies are not\nprogramme-independent**, and the simulated counter-example below makes the point\nconcrete.\n\n### The negative result\n\n![Genomic against phenotypic BLUP by design (left) and the genomic accuracy for hybrids whose parents were never crossed (right). Cached from the `sparsex` sweep, 2,000 plots.](figs/mating_genomic_tlevel.png){#fig-mating-genomic width=100%}\n\n\n::: {#tbl-mating-gblup .cell layout-align=\"center\" tbl-cap='Genomic (GBLUP) against phenotypic BLUP on all-lines GCA accuracy, 2,000 plots, the six largest differences. `z` in standard errors of the difference. `T0` is genomic accuracy for hybrids with neither parent crossed, defined only where some lines were left out.'}\n\n```{.r .cell-code}\ngb <- merge(subset(sm, model == \"GBLUP\" & budget_plots == 2000)[, c(\"scenario\", \"n_linesA_tested\", \"acc_gca_all\", \"se_acc_gca_all\", \"acc_T0\")],\n            subset(sm, model == \"BLUP\"  & budget_plots == 2000)[, c(\"scenario\", \"acc_gca_all\", \"se_acc_gca_all\")],\n            by = \"scenario\", suffixes = c(\"_g\", \"_p\"))\ngb <- data.frame(design = gb$scenario, lines_tested = gb$n_linesA_tested,\n                 phenotypic = gb$acc_gca_all_p, genomic = gb$acc_gca_all_g,\n                 difference = gb$acc_gca_all_g - gb$acc_gca_all_p,\n                 z = (gb$acc_gca_all_g - gb$acc_gca_all_p) /\n                     sqrt(gb$se_acc_gca_all_g^2 + gb$se_acc_gca_all_p^2),\n                 T0 = gb$acc_T0)\ngb <- gb[order(-gb$difference), ]\nrownames(gb) <- NULL\nfmt(head(gb, 6), 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|design                      | lines_tested| phenotypic| genomic| difference|      z|     T0|\n|:---------------------------|------------:|----------:|-------:|----------:|------:|------:|\n|50 lines/pool c=5 (cdmean)  |         50.0|      0.369|   0.386|      0.017|  4.524|  0.136|\n|50 lines/pool c=10 (cdmean) |         50.0|      0.417|   0.428|      0.012|  4.248|  0.146|\n|circulant c=10              |        200.0|      0.784|   0.778|     -0.005| -1.457|     NA|\n|random sparse c=5           |        198.9|      0.740|   0.731|     -0.009| -1.719| -0.103|\n|random sparse c=10          |        200.0|      0.773|   0.762|     -0.011| -3.045|     NA|\n|50 lines/pool c=5 (random)  |         50.0|      0.397|   0.386|     -0.011| -1.110|  0.099|\n\n</div>\n:::\n:::\n\n\nResult. Genomic kernels raised all-lines GCA accuracy in\n2 of 24 designs, both of them reduced line sets of\n50 per pool chosen by CDmean (+0.017 and\n+0.012, each beyond 3 standard errors). In every design that\nfielded all 200 candidates, the genomic model was level with or slightly below the\nphenotypic one. Genomic T0 accuracy where it is defined on more than a handful of\nlines was 0.1 to\n0.15; the negative value in\nthe random sparse rows is computed over the few lines the random draw happened to\nleave uncrossed and means nothing.\n\nInterpretation. Two separate statements. First, when every candidate is phenotyped\nin a connected design, the marker kernel has little to add to what the crosses\nalready say, and a misspecified SCA kernel (equal $d^2$ at every locus) costs a\nlittle. Second, the T0 accuracies are an order of magnitude below the published\n0.77 to 0.80, because the simulated candidates are **unrelated doubled haploids\nfrom two pools diverged for 100 generations**, with no family structure to carry\ninformation from a tested line to an untested sibling. That is the condition under\nwhich genomics transfers least, and it is the condition of a programme sampling\nnew, unrelated material. The genomic model earns its place where the phenotypic\nmodel has nothing to say at all -- lines outside the field -- and where the field\nholds only a fraction of the candidates, by deciding **which** lines go in:\nCDmean selection of the line set is where the gain appeared.\n\n### Which hybrids to phenotype, and which crosses to make\n\nOnce prediction is in place the design question becomes which cells to observe to\ncalibrate it. CDmean [@rincent2012] beat random sampling and PEVmean for inbred\ncalibration sets because it accounts for the redundancy among related individuals;\nfor hybrids, sets built by clustering, network analysis and mating-scheme\nconsiderations beat both [@guo2019], which suggests that the structure that matters\nfor a hybrid training set is bipartite. A genomics-guided pre-selection that\ndiscarded 70 % of candidate single crosses retained 85 to 95 % of the top 5 % in a\ntropical maize programme [@fritscheneto2021].\n\nA different question is which crosses to *make* to produce the next generation of\nlines. The usefulness criterion adds the within-cross selection differential to the\npredicted mean, and selecting on it added 0.14 genetic standard deviations of gain\nat 1 % selected per cross [@lehermeier2017]; within-cross variance is usable for\nranking but the marker model's estimate was biased downward by 28 to 60 %\n[@lian2015]. At the portfolio level, optimal cross selection chooses a *set* of\ncrosses under a constraint on diversity: 15 to 78 % more long-term gain than\ntruncation selection in @gorjanc2018, and more again once within-family variance\nenters the objective [@allier2019]. Constrained mate allocation with a mating\npermission matrix [@kinghorn2011] is what makes optimising a crossing list over a\n200 x 200 candidate space, subject to nursery constraints, computationally\nroutine.\n\nThe long-term caution is this book's own: cross selection controls inbreeding and\nthe divergence of the pools, and a design chosen once should not be held fixed\nacross cycles. @lorenzi2024 observed the SCA share move between 0 and 30 % from one\nselection cycle to the next, so the variance structure every design calculation in\nthis chapter assumes is not stationary.\n\n### What the simulation adds to the literature\n\nTable: Where the simulated programme confirms, refines or contradicts the published expectation. {#tbl-mating-crosscheck}\n\n| Published expectation | Simulated result | Verdict |\n|---|---|---|\n| Sparse factorials beat testers as training sets [@seye2020; @lorenzi2022; @fritscheneto2018] | Sparse beats tester on GCA accuracy over all candidates at every budget, by 0.08 to 0.13 (@tbl-mating-h2h) | Confirms, and extends beyond the training-set role |\n| Spend on parents, $c$ = 2 to 4 [@melchinger2023] | Supported for ranking; $c = 2$ leaves 1 residual df and inflates SCA:GCA by +34 %; the optimiser picks $c$ = 3 to 5 | Refines: $c = 2$ to rank, $c \\ge 3$ to estimate variances |\n| Sampling fractions of 1 to 5 % suffice [@thomsen2026; @guo2019] | 1 % gives 0.61, 1.5 % gives 0.72, 2.5 % gives 0.82 (@tbl-mating-fewest) | Confirms the order of magnitude; the fraction follows the accuracy target |\n| T0 penalty ~0.1 to 0.15 below T2 [@technow2014; @gonzalezdieguez2021] | Genomic T0 accuracy 0.10 to 0.15 *in absolute terms* | Tension: published values rest on family structure |\n| Genomic kernels improve hybrid evaluation | Gain only in 2 of 24 designs, both reduced CDmean line sets (@tbl-mating-gblup) | Refines: the gain is extrapolation and line choice |\n| Structured vs random layouts at matched $c$ not compared | Circulant ahead at every $c$, all four gaps resolved (@tbl-mating-matched-c) | Closes the gap |\n| Testers lose SCA information [@hallauer2010; @burdo2021] | $k = 1$: SCA not identifiable; $k$ = 2, 4 inflate SCA:GCA by +15 %, +13 % | Confirms and quantifies |\n| *Not in the retrieved literature* | Least squares instead of BLUP costs 0.50 at $c = 2$, under 0.01 for testers (@tbl-mating-ls-sweep) | New, and the largest effect in the study |\n\n## Seed production and the cost of a crossing plan {#sec-mating-cost}\n\nThe crossing plan has to be made in a nursery. Treating hybrid seed production as\na scalar cost term -- as the published cost models do [@marulanda2016;\n@longin2015] -- hides the constraint that actually binds sparse designs: the seed\nquantity per cross limits how many plots and locations each hybrid can occupy.\n\n### Three cost centres\n\nA mating design has three cost centres that scale differently. **Making** the\ncrosses -- pollinations, ears, nursery rows, isolation blocks -- scales with the\nnumber of distinct crosses. **Testing** them scales with crosses x locations x\nreplicates. **Genotyping** scales with the number of lines, not crosses, which is\nthe structural reason genomics favours designs with many lines and few crosses\neach. A tester design makes few crosses with much seed each; a sparse factorial\nmakes many crosses with little seed each. The two can occupy the same plots and\nneed completely different nurseries.\n\n`cross_cost()` writes the accounting chain from plots back to the nursery: seed\nneeded per cross is plots x seed per plot; ears are that over seed per ear, never\nfewer than an insurance minimum; pollinations are ears over pollination success;\nfemale rows follow from the pollinations each pool-A parent carries, male rows from\nthe pollinations each pool-B parent serves, several per plant. Four designs at the\nsame 2,000 plots:\n\n\n::: {#tbl-mating-cost .cell layout-align=\"center\" tbl-cap='The cost vector of four designs at an equal budget of 2,000 plots. **Every monetary and biological level is an illustrative placeholder** (`cross_cost_par()`); the structure is the contribution, the numbers are not.'}\n\n```{.r .cell-code}\nset.seed(8)\ncost_plans <- list(\"tester k=4\"       = design_tester(n, n, 4),\n                   \"circulant c=5\"    = design_circulant(n, n, 5),\n                   \"circulant c=10\"   = design_circulant(n, n, 10),\n                   \"NC II 10x10 sets\" = design_nc2(n, n, 10, 10))\ncost_tab <- do.call(rbind, lapply(names(cost_plans), function(nm) {\n  cc <- cross_cost(design_reps(cost_plans[[nm]], 2000), n, n)\n  data.frame(design = nm, t(cc[c(\"crosses\", \"plots\", \"pollinations\",\n                                 \"nursery_rows\", \"genotyped\", \"total\")]))\n}))\ncost_tab\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|design           | crosses| plots| pollinations| nursery_rows| genotyped|  total|\n|:----------------|-------:|-----:|------------:|------------:|---------:|------:|\n|tester k=4       |    1584|  2000|         4752|          552|       400| 108504|\n|circulant c=5    |    1000|  2000|         3000|          400|       400| 102300|\n|circulant c=10   |    2000|  2000|         6000|          600|       400| 112200|\n|NC II 10x10 sets |    2000|  2000|         6000|          600|       400| 112200|\n\n</div>\n:::\n:::\n\n\nResult. Under this accounting the four plans cost within\n10 % of each other.\nThe cheapest is the circulant design with five crosses per line, because it makes\nthe fewest distinct crosses (1000) and spends the rest of the\nplots on replicates, which need more seed per cross but no more pollinations: the\ntwo-ear insurance minimum already produces enough seed for two plots. The ten-cross\ndesigns make twice as many crosses and need\n6000 pollinations against 3000.\n\nInterpretation. The tester is **not** cheaper here, and that is a property of the\nmodel, not of testers. `cross_cost()` charges every cross as hand pollinations, so\nit cannot credit the bulk production -- an isolation block, a male-sterile female\n-- that makes a tester cross cheap in practice, and the tester's 1,584 crosses each\npay the insurance minimum. That missing term is gap 1 of @sec-mating-open, and it is\nthe term a real programme must add before comparing designs on cost. The column\nthat matters for a sparse factorial is the other one: seed per cross caps\nreplication, so a plan at one ear per cross has no seed for a second plot.\nOperational sparse designs such as @thomsen2026 are unreplicated for exactly this\nreason.\n\n::: {.callout-warning}\n## The cost levels are placeholders\n\nEvery monetary and biological level in `cross_cost_par()` -- seed per plot, seed\nper ear, pollination success, pollen uses per male plant, the price of a plot, a\nrow, a pollination and a genotype -- is an order of magnitude for a public maize\nprogramme, not a costed figure. The *structure* -- which quantity multiplies which,\nwhich capacity binds -- is what this section offers. Re-parameterise before any\nnumber below means anything for a real programme.\n:::\n\n### Budget-constrained optimisation\n\nThe cached optimiser searched over lines tested per pool, design family, $k$ or\n$c$, plots per cross and whether to genotype every candidate, subject to field,\nnursery and money constraints, and maximised expected response\n$R = i\\,\\rho\\,\\sigma_{GCA}$ -- not accuracy. That distinction is the trade-off:\nraising $c$ raises $\\rho$ but, at fixed budget, lowers the number of lines tested\nand with it the selection intensity $i$. It scores $\\rho$ with the least-squares\nclosed form, so it is conservative for sparse designs.\n\n![Left: expected response per unit cost by design. Right: the best feasible configuration at each total budget. Cached from the `sparsex` optimiser; cost levels are placeholders.](figs/mating_gain_per_cost.png){#fig-mating-gain-cost width=100%}\n\n![The optimiser's budget frontier. Cached from the `sparsex` optimiser.](figs/mating_frontier.png){#fig-mating-frontier width=100%}\n\n\n::: {#tbl-mating-frontier .cell layout-align=\"center\" tbl-cap='The best feasible configuration at each total budget. Response in genetic units of GCA, summed over the two pools. Placeholder cost levels.'}\n\n```{.r .cell-code}\nff <- subset(front, feasible)\nbest <- do.call(rbind, lapply(split(ff, ff$budget), function(d) d[which.max(d$resp), ]))\nbest <- best[, c(\"budget\", \"design\", \"n_test\", \"c_or_k\", \"reps\", \"n_crosses\",\n                 \"n_plots\", \"cost_total\", \"resp\", \"resp_per_1000\")]\nrownames(best) <- NULL\nfmt(best, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| budget|design | n_test| c_or_k| reps| n_crosses| n_plots| cost_total|  resp| resp_per_1000|\n|------:|:------|------:|------:|----:|---------:|-------:|----------:|-----:|-------------:|\n|  60000|sparse |    150|      5|    1|       750|     750|      59225| 6.050|         0.102|\n|  80000|sparse |    200|      3|    2|       600|    1200|      75300| 6.789|         0.090|\n| 100000|sparse |    200|      3|    3|       600|    1800|      93300| 7.365|         0.079|\n| 125000|sparse |    200|      3|    4|       600|    2400|     111300| 7.714|         0.069|\n| 150000|sparse |    200|      5|    3|      1000|    3000|     132300| 8.086|         0.061|\n| 200000|sparse |    200|      5|    3|      1000|    3000|     132300| 8.086|         0.061|\n\n</div>\n:::\n:::\n\n\nResult. A sparse factorial is on the frontier at every budget, and no tester\nconfiguration is optimal anywhere in the grid. The optimum moves from\n150 lines per pool at $c = 5$ and one plot per cross\nat the smallest budget to all 200 lines at $c = 5$ and\n3 plots per cross at the largest, where the 3,000-plot field\ncap binds and further money buys nothing. Response per 1,000 currency units falls\nfrom 0.102 to\n0.061. Interpretation. Once the field is full,\nthe next unit of money belongs in a larger candidate set -- more lines to select\namong -- not in more plots per cross.\n\nThe published allocation results agree in direction. A training population of 500\nat one replicate was only 4 % more accurate than 125 at four, and a second\nreplicate added 0.09 correlation points [@lorenz2013]; selection gain levels off\nquickly with budget, so additional money is better spent on more populations than on\ndeeper testing [@riedelsheimer2013]; and the optimum number of testers, locations and\nstages is a joint decision [@longin2006b; @longin2006c; @mi2014; @marulanda2016].\n\n## A decision framework {#sec-mating-decision}\n\nThe chapter collapses into a procedure a breeder can apply in a planning meeting.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A decision procedure for the crossing plan of a two-pool programme. Each question is answered by a section of this chapter.](04e-mating-design_files/figure-html/fig-mating-decision-1.png){#fig-mating-decision fig-align='center' width=1350}\n:::\n:::\n\n\n1. **Can you fit a mixed model, and do you have markers?** If neither, use testers:\n   they are the only design robust to least squares (@tbl-mating-ls-sweep). Choose\n   $k$ from the curve of @fig-mating-testers.\n2. **How many candidates must be ranked, and can the field hold a cross for each?**\n   If it can hold $c \\ge 2$ crosses per candidate, prefer a connected sparse\n   factorial (@tbl-mating-h2h).\n3. **Choose $c$ from the objective.** $c = 2$ ranks lines; $c \\ge 3$ is required\n   before any statement about SCA variance; $c \\approx 5$ is where the optimiser sits\n   at realistic budgets (@tbl-mating-frontier). Build the layout, do not sample it,\n   and confirm with `design_diagnostics()` that it is one component.\n4. **Choose the line set, not just the crosses.** When the field cannot hold every\n   candidate, CDmean-type selection of which lines to field is where genomic\n   information paid, and GBLUP is the only route to the lines left out\n   (@tbl-mating-gblup).\n5. **Check the nursery before committing:** ears, rows and isolation blocks, not just\n   plots (@tbl-mating-cost).\n6. **Re-optimise every cycle.** The variance structure moves [@lorenzi2024], and so\n   does the diversity of the pools (@sec-mating-connects).\n\n## Open problems {#sec-mating-open}\n\nFive gaps remain, each defined by the evidence that would close it.\n\n1. **Seed production as an explicit constraint.** No retrieved study models seed\n   yield per pollination, isolation capacity or seed per plot inside the\n   optimisation of a mating design; cost models carry hybrid-seed production as a\n   scalar [@marulanda2016; @longin2015]. `cross_cost()` gives the structure; the\n   levels are missing.\n2. **Joint sparsity in crosses and environments.** The cross-sparsity literature\n   [@lorenzi2022; @melchinger2023] holds the environment design fixed; the\n   environment-sparsity literature [@jarquin2020; @atanda2022; @montesinoslopez2023]\n   works with line or testcross entries. @thomsen2026 is the closest to a joint\n   treatment, and it is observational.\n3. **Connectivity reported, structured layouts compared.** The tools are seventy\n   years old [@weeks1964; @fernando1983]; design papers rarely report the\n   connectivity of the layouts they use. @tbl-mating-matched-c closes the matched-$c$\n   comparison in simulation only.\n4. **Tropical maize.** Under-represented relative to its share of breeding effort;\n   @fritscheneto2021 and @chaingeni2025 are the main exceptions.\n5. **Multi-cycle validation.** The long-term consequences of genomics-driven cross\n   selection for pool divergence are modelled [@gorjanc2018; @allier2019;\n   @melchinger2023b] but not validated over real cycles, and the non-stationary SCA\n   share of @lorenzi2024 is the warning case.\n\n## Reproducibility and assumptions {#sec-mating-reproduce}\n\n**What runs live.** Every table and figure above built from `design_*()`,\n`design_diagnostics()`, `fit_gca()`, `cross_cost()` or `gca_accuracy_theory()` is\ncomputed at render, from base R, at the full 200 x 200 scale. The package's tests\n(`tests/testthat/test-mating.R`) assert the rank rule for every design family,\nthe NC II estimability result, the $k = 1$ saturation, the Sprague-Tatum error\nvariance by Monte Carlo, and that BLUP converges to least squares as the GCA\nvariance grows.\n\n**What is cached.** The 24-design x 3-budget sweep, the REML variance components,\nthe genomic results and the optimiser frontier come from the external `sparsex`\nstudy, whose validation suite of 37 checks (closed form against AlphaSimR's own\ngenotypic values to $6 \\times 10^{-14}$; the sampling-variance and accuracy\nexpressions to 1.5 %; in-house REML against `sommer` to $10^{-5}$; the rank rule\nfor every family) all passed. The phenotypic core of that sweep is re-run in-repo\nby `Rscript book/scripts/regenerate.R mating`, with the package's i.i.d. model and\nthe variance components held at their true values:\n\n\n::: {#tbl-mating-reproduce .cell layout-align=\"center\" tbl-cap='The in-repo reproduction (`mating_core_sweep.csv`: i.i.d. model, known components, 30 replicates) against the cached `sparsex` sweep (AlphaSimR founders, REML components), at 2,000 plots.'}\n\n```{.r .cell-code}\ncr <- subset(core, budget_plots == 2000)\ncr <- reshape(cr[, c(\"scenario\", \"method\", \"acc_mean\")], idvar = \"scenario\",\n              timevar = \"method\", direction = \"wide\")\nca <- merge(subset(sm, budget_plots == 2000 & model == \"LS\")[, c(\"scenario\", \"acc_gca_all\")],\n            subset(sm, budget_plots == 2000 & model == \"BLUP\")[, c(\"scenario\", \"acc_gca_all\")],\n            by = \"scenario\", suffixes = c(\"_ls\", \"_blup\"))\nrep_tab <- merge(cr, ca, by = \"scenario\")\nrep_tab <- data.frame(design = rep_tab$scenario,\n                      ls_inrepo = rep_tab$acc_mean.ls, ls_cached = rep_tab$acc_gca_all_ls,\n                      blup_inrepo = rep_tab$acc_mean.blup, blup_cached = rep_tab$acc_gca_all_blup)\nfmt(rep_tab[order(rep_tab$blup_inrepo), ], 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |design             | ls_inrepo| ls_cached| blup_inrepo| blup_cached|\n|:--|:------------------|---------:|---------:|-----------:|-----------:|\n|9  |tester k=1         |     0.550|     0.544|       0.551|       0.545|\n|7  |random sparse c=2  |     0.420|     0.417|       0.600|       0.602|\n|2  |circulant c=2      |     0.145|     0.134|       0.637|       0.633|\n|10 |tester k=2         |     0.654|     0.653|       0.658|       0.657|\n|11 |tester k=4         |     0.671|     0.670|       0.677|       0.677|\n|3  |circulant c=3      |     0.219|     0.255|       0.710|       0.727|\n|8  |random sparse c=5  |     0.697|     0.689|       0.749|       0.740|\n|4  |circulant c=5      |     0.506|     0.541|       0.757|       0.759|\n|6  |random sparse c=10 |     0.760|     0.756|       0.775|       0.773|\n|1  |circulant c=10     |     0.615|     0.707|       0.776|       0.784|\n|5  |NC II 10x10 sets   |     0.756|     0.737|       0.780|       0.768|\n\n</div>\n:::\n:::\n\n\nResult. The two agree on every qualitative claim of the chapter: sparse ahead of\ntester at equal plots, circulant ahead of random at low $c$, and a least-squares\npenalty that is large at low $c$ and negligible for testers. They are not expected\nto agree to the third decimal: the cached run founded its pools in a coalescent\nsimulation with linkage and finite QTL, estimated its components by REML, and\nscored against the realised factorial; the in-repo run draws i.i.d. effects and\ngives the estimator the true components.\n\n**Assumptions, stated in the chapter rather than a footnote.**\n\n- **Thirty replicates per cell.** The median standard error of a cell mean was\n  about 0.004, so differences below about 0.018 accuracy points are inside the noise;\n  every comparison quoted above clears three standard errors of the difference\n  unless it says otherwise.\n- **One trait, one marker density** (1,000 markers), no epistasis, no selection\n  during line development, no spatial trend, no missing plots.\n- **Genotype x location is folded into plot error.** An extra location and an extra\n  replicate are treated as equivalent, which is exact under that assumption and\n  optimistic when G x L variance is large.\n- **Unrelated candidate panel.** The DH lines come from two pools diverged for 100\n  generations, with no family structure, which is why genomic T0 accuracy is low.\n- **Placeholder costs.** Every level in `cross_cost_par()`.\n- **Integer budgets.** Replication is `floor(plots / crosses)` capped at three, with\n  the remainder spread at random, so \"budget\" is not a continuous axis: a one-tester\n  design with 399 crosses stops at 1,197 plots.\n\n## Where this connects {#sec-mating-connects}\n\nThe crossing plan decides **which lines are seen**, and that makes it a diversity\ndecision before it is a statistical one. A design that fields 50 lines per pool\nselected by CDmean ranks those 50 and predicts the other 150 at a T0 accuracy of\n0.1 -- so the next cycle's parents will in practice come from the 50, and the\nloss of gene diversity that @sec-stages tracks across the pipeline starts in the\nnursery plan, not at selection. A sparse factorial that crosses every candidate is\nthe design that keeps the whole candidate set in contention.\n\n@sec-heterosis-gca-sca is where the GCA and SCA estimated here were derived from\nallele frequencies, and @sec-heterosis-step6 is the finite-tester version of\n@fig-mating-testers; both show that the SCA:GCA ratio driving every design choice\nin this chapter falls as the pools diverge, so the number of testers and the\ncrosses per line a programme needs are not constants of the crop.\n@sec-genomic-prediction fits the hybrid prediction models this chapter's genomic\nresults rest on. @sec-combinatorial and @sec-advanced take the hybrids a crossing\nplan produced and select among them under the diversity constraint; @sec-ocs is\nthe same optimal-contribution machinery that, applied to crosses rather than\nhybrids, becomes the optimal cross selection of @gorjanc2018. And @sec-cycles is\nwhere the consequence of holding a design fixed while the pools drift is played\nout over many cycles.\n",
    "supporting": [
      "04e-mating-design_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}