{
  "hash": "59647226316346299ff54e9389f7786a",
  "result": {
    "engine": "knitr",
    "markdown": "# Diversity across cycles {#sec-cycles}\n\n\n\n@sec-case-study will end with a list of things its numbers cannot tell you, and\nthe last item on it is the one that matters most: *one cycle, not a trajectory. A\none-cycle constraint is not a multi-cycle policy.*\n\nEvery result in this book so far has been a single round of hybrid selection. But\nnobody pays an index cost for diversity in order to have more diversity. They pay\nit because of what next cycle can do with it, and that argument has been taken on\nfaith for eleven chapters. This chapter runs the programme forward and checks.\n\n## The cycle\n\nSelection happens at the hybrid level, on $A \\times B$ crosses. Recycling happens\n*within* pool. That asymmetry is the whole design, and getting it backwards would\nquietly destroy the thing @sec-heterosis says the programme is selling: a doubled\nhaploid derived from an $A \\times B$ hybrid is a blend of both pools, and a\nprogramme that recycled hybrids would merge its heterotic groups within a few\ncycles.\n\nWhat crosses the pool boundary is *information* -- which lines proved themselves\nin hybrid combination -- and never germplasm.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![One cycle. Hybrids are evaluated across the pool boundary; lines are recycled inside it. The usage weights are the only channel between the two, and they are what `line_weights()` returns.](11b-diversity-across-cycles_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=1350}\n:::\n:::\n\n\n`run_cycles()` is the loop. The assumptions it runs under, stated once:\n\n**C1. Loci are unlinked.** Every marker segregates independently, so no linkage\ndisequilibrium builds up and there is no Bulmer effect on the genic side. This is\nthe same abstraction @sec-simulating-crosses already makes; @sec-sizing is where\nlinkage is modelled properly, and `build_map()`/`meiosis()` are there if this ever\nhas to change.\n\n**C2. Recycling is by doubled haploid.** Two parents are drawn within pool with\nprobability proportional to usage, and one DH is derived per pair. Because the\nlines are inbred, `(GL[i, ] + GL[j, ]) / 2` lies in $\\{0, 0.5, 1\\}$ and a single\nBernoulli draw per locus is an *exact* gamete, not an approximation.\n\n**C3. Pool sizes are constant.** 25 lines per pool, every cycle. A real programme\nvaries this, and the variation is itself a diversity decision.\n\n**C4. Marker effects are fixed.** The same $\\boldsymbol{\\beta}$ throughout, so the\nindex is comparable across cycles and gain accumulates on the founding cycle's\nscale. No new mutation, no changing selection target, no genotype-by-environment.\n\n**C5. The base $p_0$ is frozen at cycle 0** and carried forward. This is the\nsubject of the next section.\n\n**C6. The pool is closed** unless a germplasm injection is scheduled.\n\n**C7. The index is known without error.** @sec-choosing Finding 5 measures what\nrelaxing this does within a cycle; the effect compounds across cycles and is not\nmodelled here. Every gain figure below is therefore an optimistic ceiling, for\nall budgets equally.\n\n**C8. Selection is on the hybrid only.** No per-se line selection, no stage\nstructure. @sec-stages is where the multi-stage version lives.\n\n## Freezing $p_0$, and what happens if you do not\n\n`build_ctx()` sets `p0 <- colMeans(X)` on every call. Run it fresh each cycle and\nthe drift lens is re-anchored to the population it is supposed to be measuring\ndrift *away from*, which reports approximately zero loss forever while the pool\nerodes underneath.\n\nThe demonstration needs two generations and nothing else:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsim <- simulate_pools(n_A = 25, n_B = 25, m = 2000, seed = 1)\np0  <- colMeans(sim$X)                       # the founding base, frozen here\nGL5 <- sim$GL\nset.seed(7)\nfor (t in 1:5) {                              # five generations of drift\n  GL5 <- rbind(next_pool(GL5[1:25, ], rep(1, 25), 25),\n               next_pool(GL5[26:50, ], rep(1, 25), 25))\n}\nped5 <- expand.grid(a = 1:25, b = 25 + 1:25)\nX5   <- (GL5[ped5$a, ] + GL5[ped5$b, ]) / 2\n\ndrift <- function(X, base) {\n  p <- colMeans(X); k <- base > 1e-6 & base < 1 - 1e-6\n  mean((p[k] - base[k])^2 / (base[k] * (1 - base[k])))\n}\nc(frozen_p0   = drift(X5, p0),\n  reanchored  = drift(X5, colMeans(X5)))\n#>  frozen_p0 reanchored \n#> 0.08693168 0.00000000\n```\n:::\n\n\nThe second number is zero by construction: a population is never drifted from\nitself. Five generations of real drift have been reported as none.\n\n:::: {.callout-important}\n## This is the most common way to get a multi-cycle report wrong\n\n@sec-genomic-era named it as the single most frequent error in applying `F_hom`\nand `F_drift`, and @sec-case-study repeats it in the operational checklist.\n`run_cycles()` therefore takes `p0` once and overwrites it on every rebuilt\ncontext. It is one assignment, and every drift number in this chapter depends on\nit.\n::::\n\n## The trajectory\n\nThree budgets, fifteen cycles, five seeds each. `alpha_max = Inf` is the\nunconstrained programme: it takes the best hybrids it can find and accepts\nwhatever that costs.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Mean index of the selected hybrids, in founding-cycle standard deviations, averaged over five seeds. The unconstrained programme leads for eight cycles and then stops climbing. Neither constrained programme has stopped by cycle 15.](figs/cycles_gain.png){fig-align='center' width=336}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Cumulative gain by budget. The columns cross between cycle 5 and cycle 12.\n\n| cycle| alpha <= 0.005| alpha <= 0.02| unconstrained|\n|-----:|--------------:|-------------:|-------------:|\n|     0|           1.16|          1.45|          1.73|\n|     3|           4.05|          4.38|          5.13|\n|     5|           5.47|          6.05|          6.81|\n|     8|           7.40|          8.44|          8.42|\n|    10|           8.66|          9.68|          9.00|\n|    12|           9.89|         10.72|          9.36|\n|    15|          11.14|         11.88|          9.55|\n\n\n:::\n:::\n\n\nThe unconstrained run wins the first eight cycles and loses every cycle after\nthat. By cycle 15 the $\\alpha \\le 0.02$ programme is\n2.33 standard deviations ahead --\n24% more gain, from\na programme that gave up\n17% of its gain in\nyear one.\n\nThe mechanism is visible in the diversity panel:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Left: gene diversity of the selection. Right: F_drift against the frozen founding base. The unconstrained programme spends nearly its whole diversity endowment by cycle 8 and has little left to convert afterwards.](figs/cycles_diversity.png){fig-align='center' width=336}\n:::\n:::\n\n\nThe unconstrained programme is not out-selected. It is out of material. Its\n$F_{\\text{drift}}$ reaches\n0.41 by cycle 8\nand only 0.457 by\ncycle 15 -- it has converted almost everything it had into gain, early, and then\nhas nothing to convert.\n\n### It is not an artefact of the cheap selector\n\nThe trajectories above use a greedy sweep, which is what makes fifteen cycles by\nfive seeds by three budgets affordable. @sec-combinatorial's differential\nevolution finds slightly better plans per cycle. Re-running one seed with it:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Seed 1, greedy against differential evolution. The crossover survives, and is wider under DE.\n\n| cycle| 0.020 de| 0.020 greedy| unconstrained de| unconstrained greedy|\n|-----:|--------:|------------:|----------------:|--------------------:|\n|     0|     1.39|         1.37|             1.53|                 1.53|\n|     4|     5.53|         5.98|             5.22|                 6.60|\n|     8|     8.44|         9.56|             7.40|                 9.08|\n|    12|    10.47|        11.73|             7.99|                 9.84|\n\n\n:::\n:::\n\n\nThe crossover reproduces. Under DE the constrained programme is ahead by\n2.48\nat cycle 12, against\n1.89\nunder greedy. The cheap selector understates the case rather than manufacturing it.\n\nThere is a second thing in that table worth not glossing over: DE reaches a\n*lower* absolute index than greedy by cycle 12 in both columns, despite finding a\nbetter plan in every individual cycle. It uses more of the budget each time --\n$\\alpha = 0.0200$ against greedy's $0.0177$ at cycle 0 -- and spends the\ndifference out of the next cycle's inheritance. **Per-cycle optimality is not\nmulti-cycle optimality.** This is one seed and should be read as a flag rather\nthan a result, but it is the same trade the whole chapter is about, one level up.\n\n## The rate of inbreeding, and what $N_s$ is not\n\n@sec-case-study's checklist says to regress $\\log(1 - F)$ on cycle and check that\nit is linear, because curvature means a non-constant rate. Doing it:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrate <- do.call(rbind, lapply(unique(traj$budget), function(b) {\n  d <- aggregate(F_drift ~ cycle, traj[traj$budget == b, ], mean)\n  f <- lm(log(1 - F_drift) ~ cycle, d[-1, ])\n  data.frame(budget = b, dF_per_cycle = -coef(f)[[\"cycle\"]],\n             Ne = 1 / (-2 * coef(f)[[\"cycle\"]]), R2 = summary(f)$r.squared)\n}))\nfmt(rate, 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|budget        | dF_per_cycle|      Ne|     R2|\n|:-------------|------------:|-------:|------:|\n|unconstrained |       0.0292| 17.1146| 0.8534|\n|0.020         |       0.0358| 13.9841| 0.9931|\n|0.005         |       0.0265| 18.8898| 0.9976|\n\n</div>\n:::\n:::\n\n\nThe diagnostic fires, and it fires on the unconstrained run: $R^2 =$\n0.853 against\n0.998 for the tightest budget. The\nunconstrained rate is not constant because it is decelerating -- there is\nprogressively less left to lose. Read naively its fitted $\\Delta F$ is the\n*lowest* of the three, which is exactly backwards; the fit is meaningless for a\nsaturating series, and the $R^2$ column is what says so.\n\n:::: {.callout-warning}\n## $N_s$ does not project this\n\n@sec-ns insists that the status number is a static descriptor and not a drift\nprojection. Here is the size of the discrepancy: $N_s$ computed on the selected\nhybrids averages\n0.67 across all of these runs, while the realised effective\nsize implied by the drift they actually accumulated is between\n14 and 19.\n\nThey are not the same quantity and are not off by a constant. Report $N_s$ as a\ndescriptor of a plan, and measure $\\Delta F$ from the trajectory.\n::::\n\n## Choosing a budget for a horizon\n\nEvery seed crosses over, and the cycle at which it happens is the useful number:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Cycle at which each budget overtakes the unconstrained programme.\n\n| seed| alpha <= 0.02| alpha <= 0.005|\n|----:|-------------:|--------------:|\n|    1|             8|             11|\n|    2|            12|             15|\n|    3|            10|             12|\n|    4|             7|             10|\n|    5|             5|              9|\n\n\n:::\n:::\n\n\nThe tighter budget always crosses later and always ends higher. That is the whole\ntrade, and it makes the choice of $\\alpha_{\\max}$ a function of the planning\nhorizon rather than a matter of taste:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Reading the crossover as a budget rule. These cycle numbers are specific to this population size and selection intensity; the shape is what transfers.\n\n|Planning horizon    |Budget                |Why                                                             |\n|:-------------------|:---------------------|:---------------------------------------------------------------|\n|3 cycles or fewer   |do not constrain      |the crossover has not happened yet; the constraint is pure cost |\n|about 5 to 8 cycles |alpha ~ 0.02          |the looser budget has crossed and the tighter one has not       |\n|10 cycles or more   |alpha ~ 0.005 to 0.02 |both have crossed; the tighter budget is still climbing         |\n|indefinite          |constrain, and inject |no closed budget holds forever -- see below                     |\n\n\n:::\n:::\n\n\nThe caveat matters more than the numbers. `n_sel = 60` out of 625 candidates from\n25 + 25 lines is a small, intensely selected programme, and the crossover arrives\nsooner the harder the selection is. What transfers is the shape: an unconstrained\nprogramme leads early, saturates, and is passed.\n\n## The per-line cap, at last measurable\n\n@sec-combinatorial carries `max_use` through every selector, defaulting to `NULL`\neverywhere, because within a single cycle a usage cap only costs index. Across\ncycles it is buying something, and this is where it can be seen. Same budget\n($\\alpha \\le 0.02$), same seeds, three caps:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: The per-line usage cap across fifteen cycles.\n\n|max_use | cycle|  index|    GD| F_drift| max_line|\n|:-------|-----:|------:|-----:|-------:|--------:|\n|3       |     0|  0.491| 0.329|   0.005|      3.0|\n|6       |     0|  1.305| 0.323|   0.025|      6.0|\n|none    |     0|  1.446| 0.324|   0.030|     12.4|\n|3       |     5|  2.423| 0.296|   0.104|      3.0|\n|6       |     5|  5.788| 0.270|   0.194|      6.0|\n|none    |     5|  6.047| 0.272|   0.210|     15.4|\n|3       |    10|  4.058| 0.268|   0.185|      3.0|\n|6       |    10|  9.216| 0.233|   0.316|      6.0|\n|none    |    10|  9.677| 0.233|   0.348|     15.4|\n|3       |    15|  5.532| 0.247|   0.250|      3.0|\n|6       |    15| 11.268| 0.210|   0.395|      6.0|\n|none    |    15| 11.877| 0.207|   0.431|     16.4|\n\n\n:::\n:::\n\n\n`max_use = 6` costs\n5%\nof cycle-15 gain and holds $F_{\\text{drift}}$ to\n0.395 against\n0.431, while the uncapped\nprogramme leans on one line\n16 times in its final\ncycle. `max_use = 3` is too tight: it halves the gain and is not compensated.\n\nNote *which* lens the cap moves. Gene diversity at cycle 15 is essentially the\nsame with the cap and without it\n(0.21 against\n0.207), because $\\alpha$ is\nalready pinning that. The difference shows up in $F_{\\text{drift}}$, which is the\nlens @sec-genomic-era established the constraint does *not* pin. The cap is a\nhandle on the uncontrolled lens, which is exactly why it is worth having in\naddition to the budget and not instead of it.\n\nThis changes no default. `max_use` remains `NULL` throughout the package.\n\n## Injection, and what it costs\n\nNo closed budget holds indefinitely: all three trajectories are still losing\ndiversity at cycle 15, only at different rates. @sec-plant-literature and\n@sec-case-study both prescribe periodic germplasm injection, and\n@sec-backcross is the machinery that performs it -- introgression is how new\nmaterial enters an elite pool without dragging the rest of the genome with it.\n\nReplacing six of the twenty-five lines in each pool with founding-generation\nmaterial at cycle 8:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: One injection event at cycle 8, against the same programme left closed.\n\n|regime   | cycle|  index|    GD| F_drift|\n|:--------|-----:|------:|-----:|-------:|\n|closed   |     7|  7.697| 0.255|   0.270|\n|injected |     7|  7.697| 0.255|   0.270|\n|closed   |     8|  8.440| 0.246|   0.301|\n|injected |     8|  6.469| 0.283|   0.182|\n|closed   |    10|  9.677| 0.233|   0.348|\n|injected |    10|  7.865| 0.270|   0.233|\n|closed   |    12| 10.722| 0.222|   0.385|\n|injected |    12|  9.391| 0.254|   0.291|\n|closed   |    15| 11.877| 0.207|   0.431|\n|injected |    15| 11.283| 0.234|   0.364|\n\n\n:::\n:::\n\n\nThe cost is immediate and the return is slow. Gene diversity jumps from\n0.246 to\n0.283 and\n$F_{\\text{drift}}$ falls by\n40%,\nbut the index drops\n1.97\nstandard deviations on the spot, and **has not repaid by cycle 15**\n(11.28 against\n11.88).\n\nThat is the honest result and it should not be dressed up. Within this horizon\ninjection buys a restored resource and not more gain; it is the same trade as the\ndiversity budget itself, at a longer wavelength and a steeper entry price. The\nrun that would repay it is longer than fifteen cycles, and the founders used here\nare the programme's own -- unadapted material from a genebank would cost\nconsiderably more.\n\n## What the corpus supports\n\n@sec-corpora's screened corpora hold 687\nplant and 324\nanimal records, of which a substantial block concerns recurrent selection and\nlong-term gain: two-part and rapid-cycling programme designs, optimal cross\nselection evaluated over cycles rather than within one, and simulation studies of\nthe long-term effects of genomic selection on both gain and variance.\n\nThe qualitative shape found here -- early advantage to unconstrained selection,\nsaturation, then a crossover -- is the standard finding in that literature.\n@gorjanc2018 optimise cross selection explicitly for long-term gain in two-part\nprogrammes and report the same tension between per-cycle and multi-cycle\noptimality that the DE comparison above ran into. @allier2019 separate the\nshort-term and long-term components directly. @wientjes2022 track what genomic\nselection does to additive variance over many generations, which is the mechanism\nbehind the saturation seen here, and @doublet2019 measure the diversity cost in\nthree dairy cattle breeds where the cycles have actually been run.\n@rutkoski2019 is the counterpart caution: realised rates of gain are harder to\nestimate from an operating programme than a simulation makes them look.\n@muller2018 is the closest thing in the corpus to the selection criterion used\nhere, chosen for its effect on later cycles rather than the current one. What\n@sec-plant-literature listed as unestablished was something narrower and remains\nso: nobody has published the crossover *for a $\\theta$-constrained hybrid maize\nprogramme measured against a same-size resampling baseline*. This chapter\ndemonstrates it in simulation, under C1-C8, which is not the same as establishing\nit in an operating programme.\n\n## Where this connects\n\n@sec-heterosis argued that what builds a heterotic pattern is divergence aligned\nwith dominance, and that selection on cross performance is the only process in the\nprogramme that searches for it. This chapter is that process running. The\n$GD_{BS}$ column of `cycles_trajectory.csv` rises in every run -- the pools do\nseparate under reciprocal selection, as they should -- while $GD$ within them\nfalls, which is the trade @sec-catalogue's partition was built to expose.\n\n@sec-case-study is the single cycle, in operational detail. Read it as cycle 0 of\nthis chapter, and read its final checklist -- freeze $p_0$, keep the per-stage\nledger, check $\\log(1 - F)$ for curvature, plan germplasm injection -- as the four\nthings this chapter has now shown the consequences of skipping.\n",
    "supporting": [
      "11b-diversity-across-cycles_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}