{
  "hash": "4e7cd7d89d571d0d8fd7405ef6d5c0c0",
  "result": {
    "engine": "knitr",
    "markdown": "# Introgressing several genes by backcrossing {#sec-backcross}\n\n\n\n@sec-sizing sized a segregating population for *diversity*: the objective was to\nsample as much of the cross as possible. This chapter is the mirror image.\nA donor line carries $k$ genes worth having and an elite line carries everything\nelse worth having, and the job is to move the $k$ genes across while\n**throwing the rest of the donor away**. Here donor genome is contamination, and\nthe only diversity that is wanted is the $k$ target loci themselves.\n\nThe operation is marker-assisted backcrossing (MABC). The numbers below come\nfrom a simulator of it: a marker grid at 5 cM on ten maize chromosomes\n(1670 cM), one selected plant advanced per generation, $k = 1$ to $4$ recessive\ntargets from a single donor, carried to BC3. It ships with the\npackage -- the engine and the selection index are `R/08_mabc.R`, the experiment\ndriver is `inst/scripts/run_mabc.R` -- and @sec-bc-running shows how to run it.\n\n## The operation, in one diagram\n\nBefore any sizing question can be asked, the crossing operations have to be\nunambiguous -- which plant is pollinated by which, and what is genotyped at each\nstep.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The MABC operation. Left column: the cross made in each generation. Right column: what is genotyped and selected on, and the population size that criterion demands. The recurrent parent E re-enters at every backcross; the fork at the bottom is the fixation step, where doubled haploids and selfing differ by more than an order of magnitude in plants required.](04b-backcross-introgression_files/figure-html/fig-bc-flow-1.png){#fig-bc-flow fig-align='center' width=1500}\n:::\n:::\n\n\nTwo features of that diagram do all the work in the rest of the chapter. The\nrecurrent parent re-enters at every backcross, so donor content halves every\ngeneration *whether or not anyone selects for it*; and the fork at the bottom is\nwhere the plant numbers explode, because fixation asks for a homozygote and\nbackcrossing never does.\n\n## The model\n\n**Two states, one haplotype.** The recurrent parent is a fully homozygous\ninbred, so the gamete it contributes is invariant and only the donor-derived\nhaplotype has to be tracked: a binary vector over 334 markers. Meiosis is a\nper-interval Bernoulli switch with Haldane's\n\n$$\nr = \\tfrac{1}{2}\\bigl(1 - e^{-2d/100}\\bigr),\n$$\n\nwhich is exact for this chain precisely because Haldane is memoryless (see the\nlimitation in @sec-bc-assumptions).\n\n**Donor dosage and IBD are different quantities.** Donor and elite already share\na fraction $s$ of the genome by descent -- they are both maize, and often both\nfrom the same heterotic group. Donor genome inside a shared tract costs nothing.\nSo with $D$ the donor dosage,\n\n$$\n\\text{IBD}_E = 1 - (1 - s)\\,D, \\qquad \\text{IBD}_E + \\text{donor-specific} = 1 .\n$$\n\nBoth identities hold exactly in the simulator and are asserted in its test\nbattery. Everything below uses $s = 0.6$.\n\n**Coupling phase.** All $k$ targets come from one donor, on the same haplotype.\nTwo consequences, and the second is easy to get wrong. Linked targets travel\n*together*, so linkage drag is the **union** of the donor segments, not their\nsum. And conditional on both flanking targets being donor-derived, an *even*\nnumber of crossovers is forced in the interval between them, so the probability\nthat they sit in one continuous donor segment is not $e^{-L}$ but\n\n$$\nP_{\\text{same}} = \\frac{e^{-L}}{\\bigl(1 + e^{-2L}\\bigr)/2},\n\\qquad L = d/100 \\text{ Morgans}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata.frame(d_cM = c(20, 60, 400),\n           naive = exp(-c(20, 60, 400) / 100),\n           conditional = p_same_segment(c(20, 60, 400)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| d_cM|     naive| conditional|\n|----:|---------:|-----------:|\n|   20| 0.8187308|   0.9803280|\n|   60| 0.5488116|   0.8435507|\n|  400| 0.0183156|   0.0366190|\n\n</div>\n:::\n:::\n\n\nAt 20 cM that is 0.98 against a naive 0.82. Published stacking simulations get\nthis wrong often enough that it is worth stating separately.\n\n::: {.callout-important}\n## If the alleles come from different donors, none of this applies\n\nCoupling phase is an assumption, not a convenience. Two linked targets in\nrepulsion, from two donors, cannot both be recovered without a recombinant in\nthe interval, and the cost explodes. That programme needs an intercross between\nthe donors before any backcrossing starts, and this model does not describe it.\n:::\n\n## Three criteria, and only one of them binds\n\nA conversion programme is usually written with three success conditions at BC3:\ndo not lose the genes, recover the recurrent parent, and do not drag a chunk of\ndonor chromosome along with each target. They are not remotely equal in cost.\n\n**Not losing the genes** is exact and cheap. A plant is foreground-positive with\nprobability $q = (1/2)^k$, so $n$ plants fail with probability $(1-q)^n$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata.frame(genes = mb_sz$genes, q = mb_sz$q_foreground,\n           n_BC_per_gen = vapply(mb_sz$q_foreground, n_for_count, integer(1)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| genes|      q| n_BC_per_gen|\n|-----:|------:|------------:|\n|     1| 0.5000|            5|\n|     2| 0.2500|           11|\n|     3| 0.1250|           23|\n|     4| 0.0625|           47|\n\n</div>\n:::\n:::\n\n\nFewer than 50 plants per generation at four genes, and that is the whole\nforeground problem.\n\n**Recovering the elite is free by BC3.** With no background selection at all,\nexpected donor dosage after 3 backcrosses is $(1/2)^{4}\n= 0.0625$, so\n\n$$\n\\text{IBD}_E = 1 - (1 - s)\\,(1/2)^{4} = 0.975\n$$\n\nat $s = 0.6$ -- comfortably above a 90% target before a single background\nmarker is scored.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: IBD with the elite at BC3, s = 0.60. The 90% target was met in 40 of 44 cells of the whole grid; where it was not, the failure was losing the genes, not the background.\n\n| genes| N = 20| N = 80| N = 200| N = 400|\n|-----:|------:|------:|-------:|-------:|\n|     1|  0.984|  0.995|   0.997|   0.998|\n|     2|  0.970|  0.985|   0.990|   0.992|\n|     3|  0.956|  0.973|   0.980|   0.984|\n|     4|  0.944|  0.954|   0.969|   0.975|\n\n\n:::\n:::\n\n\nThat leaves **linkage drag** -- the donor chromosome still attached to each\ntarget -- as the only criterion that a large population can buy. It is the\ncriterion the rest of the chapter is about.\n\n::: {.callout-note}\n## The reframing\n\nAn index that spends its decisive stage on background recovery is spending it on\nthe criterion that was already satisfied. This is not a hypothetical: it was the\ndefect the technical review found in the first version of this simulator, and\ncorrecting it reverses the headline conclusion. The next section is that\ncorrection.\n:::\n\n## Which selection index\n\nFour policies, all applied to foreground-positive plants only:\n\n| Key | Rule |\n|---|---|\n| `bg` | minimise background donor content |\n| `rec12` | recombinant selection in BC1-BC2 only (classical practice), then background |\n| `rec_bg` | recombinant selection throughout, **background** decides among survivors |\n| `rec_drag` | recombinant selection throughout, **linkage drag** decides, background breaks ties |\n\n`rec_bg` is the natural-looking two-stage rule: truncate on drag, then pick the\ncleanest background among the survivors. Stage 2 discards stage 1. The plant\nwith the least drag survives the truncation and then loses to a sibling that\nhappens to carry less donor genome somewhere irrelevant.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Paired comparison (common random numbers, 300 replicates, s = 0.60) of the two-stage background-priority index against the drag-priority index. Bars are Clopper-Pearson 95% intervals. The criterion is drag <= 30 cM per gene AND IBD >= 0.90 at BC3.](04b-backcross-introgression_files/figure-html/fig-bc-index-1.png){#fig-bc-index fig-align='center' width=1350}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Left block: background-priority. Right block: drag-priority. Same seeds, same shared-IBD backbone.\n\n| genes| N/gen| drag cM|   IBD| P(both)| drag cM|   IBD| P(both)|\n|-----:|-----:|-------:|-----:|-------:|-------:|-----:|-------:|\n|     3|    80|    78.7| 0.972|   0.723|    64.6| 0.962|   0.930|\n|     3|   150|    68.8| 0.979|   0.813|    49.4| 0.966|   0.997|\n|     3|   250|    65.7| 0.982|   0.860|    41.5| 0.968|   1.000|\n|     3|   400|    59.0| 0.984|   0.930|    36.0| 0.969|   1.000|\n|     4|    80|   138.9| 0.956|   0.340|   130.2| 0.952|   0.417|\n|     4|   150|   120.9| 0.965|   0.530|   105.7| 0.958|   0.737|\n|     4|   250|   107.9| 0.971|   0.667|    87.6| 0.960|   0.923|\n|     4|   400|   103.9| 0.973|   0.767|    75.3| 0.961|   0.987|\n\n\n:::\n:::\n\n\nThe trade is 1.1 percentage points\nof IBD for\n19.2 cM of drag, and since the IBD\nconstraint was met in every replicate with margin, it is free. Four genes reach\n0.987 at\n400\nplants per generation. Under the background-priority index the same cell reaches\n0.767,\nwhich is what produced the original -- and wrong -- conclusion that the ceiling\nis unreachable at four genes and the programme must be extended to BC4-BC5 or\nsplit in two. **The wall was a property of the index, not of maize.**\n\n## How long to keep selecting recombinants\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Linkage drag at BC3 (left) and probability of meeting the ceiling (right) under the four policies, s = 0.60. Solid = 1 gene, dashed = 3 genes. Extending recombinant selection into BC3 costs no extra plants, only the flanking markers on plants that are being genotyped anyway.](figs/mabc_policies.png){#fig-bc-policies fig-align='center' width=405}\n:::\n:::\n\n\nClassical practice stops recombinant selection after BC2, on the reasoning that\nBC3 is for background clean-up. By BC3 the background needs no clean-up, and the\nexpected distance to the nearest crossover from a target shrinks as $1/g$ with\ngeneration $g$ -- so BC3 is the generation where a plant buys the *most* drag\nreduction. Both of the free changes in @fig-bc-policies point the same way:\ngenotype the flanking markers in BC3 as well, and let drag decide.\n\n## Allocating a fixed budget across BC1, BC2 and BC3\n\nGiven a total number of plants to grow, how should they be split between the\nthree backcrosses?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![P(criterion met) against the share of a fixed budget spent early, for 1 and 3 genes, binned by total plants. Front-loading BC1 is the worst use of a fixed budget.](04b-backcross-introgression_files/figure-html/fig-bc-alloc-1.png){#fig-bc-alloc fig-align='center' width=1350}\n:::\n:::\n\n\nA paired re-run at a fixed budget of 360 plants, three genes, makes the ordering\nexplicit:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: 360 plants, 3 genes, s = 0.60. Left block: background-priority index. Right block: drag-priority.\n\n|BC1/BC2/BC3 | drag cM| P(both)|    lo|    hi| drag cM| P(both)|    lo|    hi|\n|:-----------|-------:|-------:|-----:|-----:|-------:|-------:|-----:|-----:|\n|300/40/20   |    93.0|   0.448| 0.385| 0.512|    75.6|   0.656| 0.594| 0.715|\n|120/120/120 |    72.6|   0.772| 0.715| 0.823|    53.5|   0.988| 0.965| 0.998|\n|20/150/190  |    78.7|   0.640| 0.577| 0.700|    58.9|   0.876| 0.829| 0.914|\n|40/120/200  |    74.3|   0.748| 0.689| 0.801|    58.1|   0.940| 0.903| 0.966|\n|200/120/40  |    79.7|   0.680| 0.618| 0.737|    59.3|   0.932| 0.893| 0.960|\n\n\n:::\n:::\n\n\nThe balanced schedule wins under both indices, and\n300/40/20 -- the intuitive \"cast a wide net\nearly\" schedule -- is the worst. The mechanism is the $1/g$ shrinkage again: a\nplant grown in BC3 is offered a much shorter donor segment to trim than a plant\ngrown in BC1, so it converts into drag reduction far more efficiently.\n\n## Fixing the stack: selfing against doubled haploids\n\nBackcrossing only ever asks for a heterozygote. Fixation asks for a homozygote\nat all $k$ targets, and that is where the plant numbers move by an order of\nmagnitude. Selfing a BC3F1 gives $q = (1/4)^k$; a doubled haploid derived from a\nBC3F1 gamete is homozygous everywhere, so it carries all $k$ targets with\n$q = (1/2)^k$.\n\nAnd the requirement is not one plant but 3, which is a *cumulative\nbinomial* $P(\\text{Bin}(n, q) \\ge 3) \\ge 0.95$, not\n$1 - (1-q)^n$:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Plants or lines needed for 3 fixed individuals at P = 0.95.\n\n| genes| q (selfing)| BC3F2 plants| q (DH)| DH lines|\n|-----:|-----------:|------------:|------:|--------:|\n|     1|     0.25000|           23| 0.5000|       11|\n|     2|     0.06250|           99| 0.2500|       23|\n|     3|     0.01562|          401| 0.1250|       49|\n|     4|     0.00391|         1610| 0.0625|       99|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Points: simulation. Dashed: the cumulative binomial. Log scale. Each extra gene multiplies the BC3F2 requirement by four.](04b-backcross-introgression_files/figure-html/fig-bc-f2-1.png){#fig-bc-f2 fig-align='center' width=1200}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Analytical sizing by stage, log scale. The two blue bars are backcross generations; red is fixation by selfing; green is fixation by doubled haploids.](figs/mabc_sizing.png){#fig-bc-sizing fig-align='center' width=387}\n:::\n:::\n\n\nAt four genes that is\n1610 BC3F2 plants against 99 DH lines,\na factor of\n16.3. For maize, where DH is\nroutine, the alarming number is not the real bottleneck.\n\n**Without DH there is a staggered alternative.** Do not ask one generation to\nfix everything. Select BC3F2 plants homozygous for two targets and heterozygous\nfor the other two (roughly 330 plants), then close out the remaining two at\nBC3F3 (roughly 100). Two stages of hundreds instead of one of thousands, at the\ncost of one generation.\n\n## Running the simulation {#sec-bc-running}\n\nEverything above is reproducible from the package. The engine and the decision\nlayer are in `R/08_mabc.R`; the experiment driver that produced the cached\ntables is `inst/scripts/run_mabc.R`.\n\n**One programme, interactively.** Build a map, place the targets, draw the\ndonor-elite sharing, and run the three backcrosses:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmap <- build_map(maize_chr_len, spacing_cM = 5)\nw   <- marker_weights(map)\ntg  <- target_indices(map, k = 3)              # the first three of maize_targets\nsh  <- make_shared_ibd(map, s = 0.60, mw = w, target_idx = tg)\n\npr <- run_bc_program(n_sched = c(120, 120, 120), s = 0.60,\n                     strategy = \"rec_drag\", map = map, opt = mabc_opt,\n                     tg = tg, w = w, shared = sh)\nfmt(pr$traj, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| gen|   ibd|  dose|  drag| n_fg| ibd_pop_mean|fail  |\n|---:|-----:|-----:|-----:|----:|------------:|:-----|\n|   1| 0.878| 0.251| 162.5|   13|        0.891|FALSE |\n|   2| 0.934| 0.127|  97.5|   12|        0.925|FALSE |\n|   3| 0.951| 0.094|  70.0|   15|        0.952|FALSE |\n\n</div>\n:::\n:::\n\n\n`n_sched` is the schedule, one entry per backcross, so `c(300, 40, 20)` and\n`c(120, 120, 120)` are the two allocations compared above. Passing the same\n`shared` mask to two calls is what makes a comparison between selection indices\npaired rather than confounded with the donor-elite pair.\n\n**Comparing indices on common random numbers.** Reset the seed before each\nstrategy so the two programmes see the same meioses:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndrag_of <- function(strategy) {\n  set.seed(7)\n  run_bc_program(c(120, 120, 120), 0.60, strategy, map, mabc_opt, tg, w,\n                 shared = sh)$traj$drag[mabc_opt$n_bc]\n}\nc(rec_bg = drag_of(\"rec_bg\"), rec_drag = drag_of(\"rec_drag\"))\n#>   rec_bg rec_drag \n#>       60       45\n```\n:::\n\n\nA single replicate is noise; the tables above are 300 of these per cell, which\nis the driver's job.\n\n**The analytical sizing needs no simulation at all.** It is a cumulative\nbinomial, so it is exact and instant:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsizing_table(k_max = 4, flank_cM = 5, P = 0.95, n_keep = 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| genes| q_foreground| n_BC_1plant| n_BC_1rec|      q_F2| n_F2_1plant| n_F2_3plants|   q_DH| n_DH_3lines|\n|-----:|------------:|-----------:|---------:|---------:|-----------:|------------:|------:|-----------:|\n|     1|       0.5000|           5|       125| 0.2500000|          11|           23| 0.5000|          11|\n|     2|       0.2500|          11|       251| 0.0625000|          47|           99| 0.2500|          23|\n|     3|       0.1250|          23|       503| 0.0156250|         191|          401| 0.1250|          49|\n|     4|       0.0625|          47|      1006| 0.0039063|         766|         1610| 0.0625|          99|\n\n</div>\n:::\n:::\n\n\n**The full scans, from the shell.** The driver runs the whole grid -- four\npolicies by four gene numbers by eleven population sizes by three values of $s$,\nplus the allocation grid and the BCnF2 stage -- and writes the CSVs, the nine\nfigures and a self-contained HTML report:\n\n```sh\nRscript inst/scripts/run_mabc.R --test              # 35 checks, ~10 s\nRscript inst/scripts/run_mabc.R --quick --out=DIR   # reduced grid, ~30 s\nRscript inst/scripts/run_mabc.R --out=report/mabc   # the full run, ~3 min\n```\n\nThe cached tables this chapter reads are the full run's\n`results_uniform.csv`, `results_allocation.csv`, `results_bcnf2.csv` and\n`analytical_sizing.csv`, copied into `book/data` as `mabc_*.csv`; the header of\nthe driver lists the copy commands.\n\n**Pointing it at your own programme.** Three things change and nothing else:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. your map\nmap <- build_map(my_chr_len_cM, spacing_cM = 5)\n\n# 2. your targets -- same columns as maize_targets\nmy_targets <- data.frame(gene = c(\"A\", \"B\"), chr = c(1, 5),\n                         pos_cM = c(40, 110), label = c(\"A\", \"B\"))\ntg <- target_indices(map, k = 2, targets = my_targets)\n\n# 3. your criteria\nopt <- utils::modifyList(mabc_opt,\n                         list(n_bc = 4, drag_per_gene = 20, target_ibd = 0.95))\n```\n:::\n\n\n`s` -- how much of the genome your donor and your elite already share -- is the\nparameter worth measuring rather than assuming. It scales the whole cost: at\n$s = 0.7$ most of the donor genome that survives is free, at $s = 0$ none of it\nis.\n\n## Assumptions, and what is not modelled {#sec-bc-assumptions}\n\nThese matter more than usual here, because unlike the diversity chapters this\none is used to decide field area.\n\n**No crossover interference (material, and it cuts against the results above).**\nMeiosis is Haldane, so crossovers are independent between intervals. Maize has\nstrong positive interference. For the event this simulation depends on most -- a\ndouble recombinant in the two 5 cM intervals flanking a target, which is what\nturns a long donor segment into a short one -- Haldane gives\n$2.26 \\times 10^{-3}$ against $4.90 \\times 10^{-4}$ under a coincidence model.\n**The model over-produces tight recombinants by about 4.6x**, so every\npopulation size quoted for close-in trimming is a lower bound. Note the\ndirection: the index correction makes the problem easier, interference makes it\nharder, and they do not cancel in any principled way. The correct fix is a\ncrossover-position sampler -- chiasmata as a stationary gamma renewal process\nwith shape $\\nu$ -- which reduces to Haldane exactly at $\\nu = 1$ and so is\nbackward compatible; maize estimates put $\\nu$ near 3.\n\n**One plant advanced per generation.** Real programmes advance 3-10 and cross\neach to the recurrent parent. Every probability in this chapter is therefore a\n**single-lineage** probability: it understates achievable progress and it\nremoves lineage-level variance from every distribution shown.\n\n**Uniform recombination rate, no distortion, no genotyping error.** Maize has\n5-10x rate variation and strongly suppressed pericentromeric regions; a target\nin a cold region carries drag no feasible population will trim. Gametophyte\nfactors shift the foreground frequency away from $1/2$. Map positions here are\nillustrative and not pinned to a named consensus map -- and IBM-type maps must\nbe rescaled before use, exactly as in @sec-sizing.\n\n**Triploid endosperm genetics is not modelled.** The illustrative targets are\nendosperm genes. The endosperm is 2 maternal : 1 paternal, so a recessive kernel\nphenotype does not appear on the ear of a heterozygous plant: phenotypic\nconfirmation lags the genotype by one generation, and xenia means it requires a\nself-pollination, not open pollination.\n\n**The gene set is illustrative, not a breeding recommendation.** `sh2` and `bt2`\nencode the two subunits of the same enzyme, so stacking both is largely\nredundant -- dropping one turns the hard case ($k = 4$) into the comfortable one\n($k = 3$). `o2` alone gives opaque endosperm, not QPM: the hardness modifiers\nare polygenic, unlinked and unmodelled here, which changes the problem class\nfrom \"stack $k$ Mendelian genes\" to \"stack $k$ genes plus a QTL background\".\n\n::: {.callout-warning}\n## Two statistical habits this chapter had to be repaired for\n\n**Select on the interval, not the point estimate.** The first version of the\nsizing tables took the first grid point whose *point estimate* crossed 0.95.\nWith 30-150 replicates the standard error is 0.02-0.09, so that is a winner's\ncurse: the tables were non-monotone in $N$ (0.97, 0.97, then 0.93 at a larger\n$N$), which is a monotone quantity reading noise. Selection is now on the\nClopper-Pearson lower bound, and intervals are reported everywhere.\n\n**Never type a number into the prose.** Every figure in the original narrative\nwas a string constant written against an earlier configuration; re-runs put the\ntrue values outside the reported confidence intervals, and the same document\ncontradicted itself in three places. Every number in this chapter is\ninterpolated from the cached tables at render time. @sec-verification says which\ntable each one comes from.\n:::\n\n## Where this connects\n\n@sec-sizing sized a population to *keep* diversity; this chapter sized one to\ndiscard it everywhere except at $k$ loci. The two share their machinery -- the\nsame map, the same Haldane meiosis, the same distinction between what is\nsegregating and what is fixed -- and they share the lesson that dominates both:\n**size for the objective that binds.** In @sec-sizing that meant not sizing for\ngene diversity, which saturates early. Here it means not sizing for background\nrecovery, which is already satisfied at BC3, and putting the plants into the one\ncriterion that a population can actually buy.\n\nThe converted lines this chapter produces re-enter the pool the rest of the book\noptimises over. A conversion programme run for its own sake reduces diversity by\nconstruction: it makes an elite line into a near-copy of itself. If several\nconversions are run in parallel off the same recurrent parent, the resulting\nlines are close to each other.\n\nThat has been asserted for a chapter and a half. It is cheap to measure, and the\nsize of it is the argument. Eight BC3 conversions off one recurrent parent,\nagainst eight unrelated elite lines, put through the kernel of @sec-coancestry:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(11)\nm_c  <- 2000\nelite <- matrix(rbinom(40 * m_c, 1, 0.5), 40, m_c)   # unrelated elite lines\nrec   <- elite[1, ]                                   # one recurrent parent\ndonor <- elite[40, ]\nibd   <- expected_ibd(3, 0.5)                         # recurrent genome at BC3\n\nconv <- t(sapply(1:8, function(i)\n  ifelse(rbinom(m_c, 1, ibd) == 1, rec, donor)))\n\ncost <- data.frame(\n  panel = c(\"8 BC3 conversions, one recurrent parent\", \"8 unrelated elite lines\"),\n  theta = c(mean(molecular_coancestry(conv)),\n            mean(molecular_coancestry(elite[1:8, ]))))\ncost$GD <- 1 - cost$theta\nfmt(cost, 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|panel                                   |  theta|     GD|\n|:---------------------------------------|------:|------:|\n|8 BC3 conversions, one recurrent parent | 0.9714| 0.0286|\n|8 unrelated elite lines                 | 0.5617| 0.4383|\n\n</div>\n:::\n:::\n\n\nThe converted panel carries about\n0.07\ntimes the gene diversity of the unrelated one -- not a marginal erosion but a\ndifferent order of magnitude, and it follows directly from\n`expected_ibd(3, 0.5) =` 0.969. Conversion is *designed* to make lines\nidentical everywhere except the target, and it succeeds.\n\nTwo consequences for the rest of the book. A conversion programme must be counted\nagainst the diversity budget of @sec-ocs rather than run alongside it, because\n$\\theta$ cannot distinguish eight conversions from one line entered eight times.\nAnd @sec-stages' per-line usage cap is the mechanism that already handles this:\ncapping how often a line is used caps how often its near-copies are, provided\nthe conversions are recognised as near-copies rather than entered as eight\nindependent parents.\n\n::: {.callout-warning}\n## Do not enter a converted panel as independent lines\n\nThe failure mode is administrative, not statistical. Conversions arrive with\ndistinct line codes and distinct pedigree entries, so a pipeline that trusts the\ncodes will treat them as eight parents. The coancestry matrix will not, and\n@sec-choosing's recommendation to compute $\\theta$ on markers rather than on\npedigree is what protects against exactly this.\n:::\n",
    "supporting": [
      "04b-backcross-introgression_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}