{
  "hash": "f18e71f171390a4956ba2de4e2b165d4",
  "result": {
    "engine": "knitr",
    "markdown": "# Combinatorial selection {#sec-combinatorial}\n\n\n\nThe problem is: choose $n$ of $N$ hybrids, maximising mean index subject to a\ndiversity budget. This chapter builds up the strategies that solve it, from the\ntwo that need no optimiser at all to the differential evolution that beats them\n-- and explains why the DE only beats them under one specific condition.\n\n## Four baselines before any optimiser\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsels <- list(\n  random     = sel_random(ctx, n_sel),\n  truncation = sel_truncation(ctx, n_sel),\n  trunc_cap  = sel_truncation_cap(ctx, n_sel),\n  greedy_div = sel_greedy(ctx, n_sel, w = 0),\n  greedy_w1  = sel_greedy(ctx, n_sel, w = 1),\n  greedy_w3  = sel_greedy(ctx, n_sel, w = 3)\n)\nfmt(t(sapply(sels, function(s) c(\n  index      = mean_index(s, ctx),\n  alpha_pct  = 100 * alpha_loss(s, ctx, null$gd_ref),\n  Ns         = status_number(s, ctx),\n  Ne_parents = ne_parents(s, ctx),\n  max_line   = max_line_use(s, ctx)))), 3)\n```\n\n::: {.cell-output-display}\n\n|           | index| alpha_pct|    Ns| Ne_parents| max_line|\n|:----------|-----:|---------:|-----:|----------:|--------:|\n|random     | 0.008|    -0.236| 0.743|     37.696|        7|\n|truncation | 1.992|     4.122| 0.727|     13.020|       23|\n|trunc_cap  | 0.820|     0.326| 0.740|     31.034|        4|\n|greedy_div | 0.134|    -1.352| 0.747|     37.306|        5|\n|greedy_w1  | 1.992|     4.122| 0.727|     13.020|       23|\n|greedy_w3  | 1.992|     4.122| 0.727|     13.020|       23|\n\n:::\n:::\n\n\n**Truncation** is the ceiling on gain and the floor on diversity. It is what\nevery programme does by default, and the interesting question is not whether it\nloses diversity but how *little* index a constrained plan has to give up\nrelative to it.\n\n**Truncation with a per-line cap** is the cheap baseline that deserves more\nattention than it gets. It needs no coancestry matrix at all -- only counting --\nand it usually captures most of the benefit:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsel_truncation_cap\n#> function (ctx, n_sel, cap = ceiling(2 * n_sel/ctx$n_lines) + \n#>     1) \n#> {\n#>     ord <- order(ctx$index, decreasing = TRUE)\n#>     used <- integer(ctx$n_lines)\n#>     out <- integer(0)\n#>     for (i in ord) {\n#>         a <- ctx$ped$a[i]\n#>         b <- ctx$ped$b[i]\n#>         if (used[a] < cap && used[b] < cap) {\n#>             out <- c(out, i)\n#>             used[a] <- used[a] + 1L\n#>             used[b] <- used[b] + 1L\n#>             if (length(out) == n_sel) \n#>                 break\n#>         }\n#>     }\n#>     out\n#> }\n#> <bytecode: 0xacaf14468>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(index_truncation = mean_index(sels$truncation, ctx),\n  index_capped     = mean_index(sels$trunc_cap, ctx),\n  index_retained_pct = 100 * mean_index(sels$trunc_cap, ctx) /\n                             mean_index(sels$truncation, ctx),\n  Ne_par_truncation = ne_parents(sels$truncation, ctx),\n  Ne_par_capped     = ne_parents(sels$trunc_cap, ctx))\n#>   index_truncation       index_capped index_retained_pct  Ne_par_truncation \n#>          1.9919371          0.8203555         41.1838050         13.0198915 \n#>      Ne_par_capped \n#>         31.0344828\n```\n:::\n\n\nBefore reaching for an optimiser, run this. If a per-line cap already meets your\nconstraint at an acceptable index, you are done.\n\n## Greedy, with incremental updates\n\nAdding hybrid $j$ to an existing set changes the submatrix total by\n$2 s_j + f_{jj}$, where $s_j$ is the sum of $f_{ij}$ over the already-chosen.\nThat makes each step $O(N)$ instead of $O(n^2)$, and the whole construction\naffordable.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsel_greedy\n#> function (ctx, n_sel, w = 0, max_use = NULL) \n#> {\n#>     f <- ctx[[\"f\"]]\n#>     d <- diag(f)\n#>     s <- numeric(ctx$N)\n#>     avail <- rep(TRUE, ctx$N)\n#>     out <- integer(n_sel)\n#>     total <- 0\n#>     if (!is.null(max_use)) {\n#>         pa <- as.integer(ctx$ped$a)\n#>         pb <- as.integer(ctx$ped$b)\n#>         cnt <- integer(ctx$n_lines)\n#>     }\n#>     for (k in seq_len(n_sel)) {\n#>         theta_new <- (total + 2 * s + d)/k^2\n#>         score <- w * ctx$index - theta_new\n#>         score[!avail] <- -Inf\n#>         j <- which.max(score)\n#>         if (!is.finite(score[j])) {\n#>             out <- out[seq_len(k - 1L)]\n#>             break\n#>         }\n#>         out[k] <- j\n#>         avail[j] <- FALSE\n#>         total <- total + 2 * s[j] + d[j]\n#>         s <- s + f[, j]\n#>         if (!is.null(max_use)) {\n#>             for (a in c(pa[j], pb[j])) {\n#>                 cnt[a] <- cnt[a] + 1L\n#>                 if (cnt[a] >= max_use) \n#>                   avail[pa == a | pb == a] <- FALSE\n#>             }\n#>         }\n#>     }\n#>     out\n#> }\n#> <bytecode: 0xacafba468>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\nThe score is $w \\cdot \\text{index} - \\theta$. At $w = 0$ this is pure diversity\n-- the ceiling on diversity and near-zero gain. As $w \\to \\infty$ it converges to\ntruncation. Sweeping $w$ traces a frontier:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nws <- c(0, 0.25, 0.5, 0.75, 1, 1.5, 2, 3, 5, 8, 15, 30)\ngf <- do.call(rbind, lapply(ws, function(w) {\n  s <- sel_greedy(ctx, n_sel, w = w)\n  data.frame(w = w, alpha = alpha_loss(s, ctx, null$gd_ref),\n             index = mean_index(s, ctx))\n}))\nplot(gf$alpha * 100, gf$index, type = \"b\", pch = 19, col = \"#2166ac\",\n     xlab = \"gene diversity loss, alpha (%)\", ylab = \"mean index (s.d.)\")\npoints(alpha_loss(sels$truncation, ctx, null$gd_ref) * 100,\n       mean_index(sels$truncation, ctx), pch = 4, cex = 1.5, col = \"#b2182b\")\ntext(alpha_loss(sels$truncation, ctx, null$gd_ref) * 100,\n     mean_index(sels$truncation, ctx), \"truncation\", pos = 2, cex = 0.75)\nabline(v = 0, lty = 3); grid()\n```\n\n::: {.cell-output-display}\n![The greedy frontier. w = 0 is maximum diversity; large w converges to truncation.](10-combinatorial-selection_files/figure-typst/unnamed-chunk-6-1.svg){fig-align='center'}\n:::\n:::\n\n\nGreedy solutions are also what warm-start the differential evolution. That is\nnot an optimisation detail -- it is the difference between the DE working and\nnot working.\n\n## The encoding problem\n\nAn $N$-dimensional 0/1 encoding is infeasible for differential evolution at this\nscale: at production size that is 5041 binary dimensions. Instead, encode\n$n_{sel}$ continuous values in $[1, N]$ and decode them to unique indices.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndecode\n#> function (par, N, n_sel) \n#> {\n#>     k <- as.integer(par)\n#>     k[k < 1L] <- 1L\n#>     k[k > N] <- N\n#>     dup <- duplicated(k)\n#>     if (any(dup)) \n#>         k[dup] <- setdiff(seq_len(N), k[!dup])[seq_len(sum(dup))]\n#>     k\n#> }\n#> <bytecode: 0xacc4bb1f8>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\nDuplicates are repaired **deterministically**. A stochastic repair would make\nthe fitness noisy, and a noisy fitness stops DE converging -- the same parameter\nvector must always score the same.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(3)\nd1 <- decode(runif(n_sel, 1, ctx$N + 1), ctx$N, n_sel)\nd2 <- decode(runif(n_sel, 1, ctx$N + 1), ctx$N, n_sel)\nc(unique_1 = length(unique(d1)), unique_2 = length(unique(d2)),\n  in_range = all(c(d1, d2) >= 1 & c(d1, d2) <= ctx$N),\n  deterministic = identical(d1, decode(sort(c(d1)) - 0.5 + 1, ctx$N, n_sel) * 0L + d1))\n#>      unique_1      unique_2      in_range deterministic \n#>            60            60             1             1\n```\n:::\n\n\n::: {.callout-note}\n## A known bias in the repair\n\nThe repair fills in the lowest free indices, which introduces a slight bias\ntoward low-numbered candidates. It is marked in the source with a `ponytail:`\ncomment naming the ceiling and the upgrade path -- switch to \"nearest free\" if\nthe DE ever stalls. It has not mattered at these scales, but it is the kind of\nthing that should be written down rather than discovered later.\n:::\n\n### The better encoding\n\n@sec-collapse showed that $\\theta$ depends only on the line-usage vector. That\nmakes a far better encoding available: one weight per **line**, dimension $L$\ninstead of $N$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndecode_lines\n#> function (p, ctx, n_sel, max_use = NULL, w_div = 3) \n#> {\n#>     par <- ctx$parents\n#>     sc <- ctx$index + w_div * (p[par[, 1]] + p[par[, 2]])\n#>     ord <- order(-sc)\n#>     if (is.null(max_use)) \n#>         return(ord[seq_len(n_sel)])\n#>     sel <- integer(n_sel)\n#>     cnt <- integer(ctx$n_lines)\n#>     k <- 0L\n#>     for (h in ord) {\n#>         a <- par[h, 1]\n#>         b <- par[h, 2]\n#>         if (cnt[a] < max_use && cnt[b] < max_use) {\n#>             k <- k + 1L\n#>             sel[k] <- h\n#>             cnt[a] <- cnt[a] + 1L\n#>             cnt[b] <- cnt[b] + 1L\n#>             if (k == n_sel) \n#>                 break\n#>         }\n#>     }\n#>     if (k < n_sel) {\n#>         rest <- setdiff(ord, sel[seq_len(k)])\n#>         sel[(k + 1L):n_sel] <- rest[seq_len(n_sel - k)]\n#>     }\n#>     sel\n#> }\n#> <bytecode: 0xacba5d000>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\nThe line weight shifts each hybrid's score by the weights of its two parents,\nand hybrids are taken greedily subject to the per-line usage cap -- so the cap is\nsatisfied **by construction** rather than by penalty.\n\nThe comparison at equal evaluation budget is the sharpest single result in this\nbook:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: 60,000 evaluations, four simultaneous restrictions, mean of 3 seeds.\n\n|encoding              | index| loss %| Ne parents| max uses| seconds|\n|:---------------------|-----:|------:|----------:|--------:|-------:|\n|hybrid keys / penalty | 0.351|  0.060|     76.634|    5.667|   6.550|\n|hybrid keys / repair  | 0.351|  0.060|     76.634|    5.667|   9.621|\n|line weights / repair | 1.988|  0.448|     50.084|    6.000|  12.126|\n\n\n:::\n:::\n\n\nDimension 3600 reaches index 0.351. Dimension 120 reaches 1.988 -- **5.7x\nbetter at the same budget**. Penalty and repair constraint handlers gave\nnumerically identical results in the hybrid encoding, because at that dimension\nthe search never reaches the constraint boundary where they differ.\n\n> The encoding decides whether the optimiser works. The constraint handler does\n> not.\n\n## Differential evolution\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsel_de\n#> function (ctx, n_sel, alpha_max, gd_ref, NP = 300, itermax = 2000, \n#>     seeds = NULL, trace = FALSE, max_use = NULL) \n#> {\n#>     fit <- make_fitness(ctx, n_sel, alpha_max, gd_ref, max_use = max_use)\n#>     if (is.null(seeds)) \n#>         seeds <- lapply(c(0, 0.25, 0.5, 1, 2, 4, 8, 16), function(w) sel_greedy(ctx, \n#>             n_sel, w = w, max_use = max_use))\n#>     seeds <- Filter(function(s) length(s) == n_sel, seeds)\n#>     initial <- matrix(runif(NP * n_sel, 1, ctx$N + 1), NP, n_sel)\n#>     for (i in seq_len(min(length(seeds), NP))) initial[i, ] <- seeds[[i]] + \n#>         0.5\n#>     ctrl <- DEoptim::DEoptim.control(NP = NP, itermax = itermax, \n#>         trace = trace, initialpop = initial)\n#>     res <- DEoptim::DEoptim(fit, lower = rep(1, n_sel), upper = rep(ctx$N + \n#>         0.999, n_sel), control = ctrl)\n#>     decode(res$optim$bestmem, ctx$N, n_sel)\n#> }\n#> <bytecode: 0xaca49d038>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalpha_max <- 0.01\nset.seed(9)\nde_idx <- suppressWarnings(\n  sel_de(ctx, n_sel, alpha_max = alpha_max, gd_ref = null$gd_ref,\n         NP = 120, itermax = 250))\n\nfmt(c(index      = mean_index(de_idx, ctx),\n      alpha_pct  = 100 * alpha_loss(de_idx, ctx, null$gd_ref),\n      budget_pct = 100 * alpha_max,\n      Ns         = status_number(de_idx, ctx),\n      Ne_parents = ne_parents(de_idx, ctx)), 3)\n#>      index  alpha_pct budget_pct         Ns Ne_parents \n#>      1.330      0.978      1.000      0.738     22.857\n```\n:::\n\n\n### The warm start is not optional\n\nWithout seeding the initial population with greedy solutions, the DE ends up\n*below* a plain greedy -- at any affordable budget.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbudget <- list(NP = 120, itermax = 250)\nset.seed(21)\ncold <- suppressWarnings(\n  sel_de(ctx, n_sel, alpha_max, null$gd_ref, NP = budget$NP,\n         itermax = budget$itermax, seeds = list(sample.int(ctx$N, n_sel))))\n# `seeds = NULL`, the default, would have built the greedy sweep for us.\n\nfeasible_greedy <- {\n  cand <- lapply(ws, function(w) sel_greedy(ctx, n_sel, w = w))\n  ok <- vapply(cand, function(s) alpha_loss(s, ctx, null$gd_ref) <= alpha_max, logical(1))\n  cand[ok][[which.max(vapply(cand[ok], mean_index, numeric(1), ctx = ctx))]]\n}\n\nres <- c(`cold DE` = mean_index(cold, ctx),\n         `best feasible greedy` = mean_index(feasible_greedy, ctx),\n         `warm DE` = mean_index(de_idx, ctx))\nbp <- barplot(res, col = c(\"grey70\", \"#2166ac\", \"#b2182b\"), ylab = \"mean index (s.d.)\",\n              ylim = c(0, max(res) * 1.2))\ntext(bp, res, sprintf(\"%.3f\", res), pos = 3, cex = 0.8)\n```\n\n::: {.cell-output-display}\n![With and without a greedy warm start, at identical evaluation budget. Cold-started DE does not reach the greedy solution it was supposed to improve on.](10-combinatorial-selection_files/figure-typst/unnamed-chunk-13-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfmt(res, 4)\n#>              cold DE best feasible greedy              warm DE \n#>               1.2289               0.1343               1.3299\n```\n:::\n\n\nThe mechanism is dimensional. At roughly 60 integer dimensions the search space\nis far too large for 30,000 evaluations to find anything a construction\nheuristic has not already found. The warm start does not help the DE converge\nfaster -- it gives the DE something worth improving on.\n\n`sel_de()` builds the warm start automatically from a greedy sweep, and\n**removing it will silently degrade every result in this book.**\n\n### Checking convergence against the bound\n\n@sec-relaxation gives a relaxation. Turning it into a *bound* takes one more\nstep, derived in @sec-bound: the relaxation at a given $\\lambda$ maximises a\npenalised objective rather than the index, so the best relaxation point inside\nthe budget is not an upper bound on the best plan inside the budget. The\nLagrangian combination is.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrelax <- ocs_relaxation(ctx, n_sel, lambdas = 10^seq(-1, 2.5, length.out = 10))\na_relax <- (null$gd_ref - relax[, \"GD\"]) / null$gd_ref\n\nbound <- ocs_bound(ctx, n_sel, alpha_max, null$gd_ref)\n\nc(DE_index = mean_index(de_idx, ctx),\n  upper_bound = as.numeric(bound),\n  gap_pct = 100 * (as.numeric(bound) - mean_index(de_idx, ctx)) / as.numeric(bound))\n#>    DE_index upper_bound     gap_pct \n#>    1.329921    1.552420   14.332431\n```\n:::\n\n\nA large gap means **the optimiser has not converged**, not that the problem is\nintrinsically hard. A small gap means further optimiser effort is wasted.\n\n::: {.callout-tip}\n## If the DE ever looks unconvincing on real data\n\n@debeukelaer2018, optimising core-collection subsets with local search rather\nthan DE, found that a basic stochastic hill-climber was already competitive,\nthat a considerably more complex genetic algorithm did *not* reliably beat it,\nand that the method which won -- parallel tempering -- won by combining many\nsimple local searches rather than by being individually more sophisticated.\n\nThe common thread with the warm-start result here: for this class of problem,\nthe return on a smarter *search strategy* around a simple move consistently\noutweighs the return on a more elaborate *single-solution* algorithm. That\ndirection is taken up in @sec-advanced, which builds the local search on the\n`O(L)` swap this package already had and measures it against the DE at equal\nwall-clock.\n:::\n\n## The full frontier\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalphas <- c(0, 0.0025, 0.005, 0.01, 0.02)\nfront <- do.call(rbind, lapply(alphas, function(a) {\n  r <- suppressWarnings(sel_de(ctx, n_sel, a, null$gd_ref, NP = 100, itermax = 180))\n  data.frame(alpha_max = a, alpha = alpha_loss(r, ctx, null$gd_ref),\n             index = mean_index(r, ctx), Ne_par = ne_parents(r, ctx))\n}))\n\nplot(front$alpha * 100, front$index, type = \"b\", pch = 19, lwd = 2, col = \"#b2182b\",\n     xlab = \"gene diversity loss, alpha (%)\", ylab = \"mean index (s.d.)\",\n     xlim = range(c(front$alpha, gf$alpha, a_relax) * 100),\n     ylim = range(c(front$index, gf$index, relax[, \"index\"])))\nlines(gf$alpha * 100, gf$index, type = \"b\", pch = 17, col = \"#2166ac\", cex = 0.7)\nlines(sort(a_relax) * 100, relax[order(a_relax), \"index\"], type = \"b\", pch = 1,\n      lty = 2, col = \"grey55\", cex = 0.7)\nabline(v = 0, lty = 3)\nlegend(\"bottomright\", c(\"constrained DE\", \"greedy sweep\", \"continuous OCS bound\"),\n       col = c(\"#b2182b\", \"#2166ac\", \"grey55\"), pch = c(19, 17, 1),\n       lty = c(1, 1, 2), lwd = c(2, 1, 1), bty = \"n\", cex = 0.8)\ngrid()\n```\n\n::: {.cell-output-display}\n![Everything together. The constrained DE, the greedy sweep, the continuous upper bound, and the fixed reference strategies.](10-combinatorial-selection_files/figure-typst/unnamed-chunk-16-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfmt(front, 4)\n```\n\n::: {.cell-output-display}\n\n| alpha_max|   alpha|  index|  Ne_par|\n|---------:|-------:|------:|-------:|\n|    0.0000| -0.0001| 0.9700| 29.8755|\n|    0.0025|  0.0022| 1.0980| 27.4809|\n|    0.0050|  0.0048| 1.2015| 25.0871|\n|    0.0100|  0.0099| 1.3024| 23.3010|\n|    0.0200|  0.0199| 1.5591| 18.9474|\n\n:::\n:::\n\n\nTwo things to read. The DE sits above the greedy sweep at every budget -- that\nis what it is for. And the realised `alpha` tracks `alpha_max` closely, which is\nthe constraint doing its job: at each budget the optimiser spends the diversity\nit was allowed and no more.\n\n## Which strategy to use\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Situation                                             |Use                                                                               |\n|:-----------------------------------------------------|:---------------------------------------------------------------------------------|\n|The constraint is inactive (ceiling below your limit) |truncation -- nothing to optimise                                                 |\n|A per-line cap already meets the constraint           |`sel_truncation_cap()` -- no matrix needed                                        |\n|One-off analysis, small pool                          |`sel_greedy()` swept over w                                                       |\n|Production scale, several simultaneous restrictions   |`sel_de_fast()` or `sel_local_search()` on the **line** encoding -- @sec-advanced |\n\n\n:::\n:::\n\n\nThe honest summary is that the optimiser earns its place only in the last row.\nIn the first three, something simpler is either exactly as good or good enough,\nand @sec-choosing's cost table is the reason to check which row you are in\nbefore writing any optimisation code.\n",
    "supporting": [
      "10-combinatorial-selection_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}