{
  "hash": "589ec284772c6793f8a34cc442037c9c",
  "result": {
    "engine": "knitr",
    "markdown": "# Choosing metrics: collapse, cost, redundancy {#sec-choosing}\n\n\n\n@sec-catalogue built a catalogue. This chapter asks which of it to keep, and\nanswers with two questions the catalogue could not: **what does each metric cost\nper evaluation**, and **how much of what it reports is already in $\\theta$**.\n\nThe recommendation is **two** metrics inside the optimiser and **three** at\nvalidation.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: The recommendation. Everything else is redundant with theta, too expensive for an inner loop, or both.\n\n|Role                  |Metric                                                                                                                     |Where it runs               |Cost per evaluation                    |\n|:---------------------|:--------------------------------------------------------------------------------------------------------------------------|:---------------------------|:--------------------------------------|\n|**Constraint**        |Group coancestry theta of the selected set, as proportional loss of gene diversity against a same-size resampling baseline |inside DE, every evaluation |**5 us** (incremental) / 106 us (full) |\n|**Second constraint** |Effective number of parent lines                                                                                           |inside DE, every evaluation |**7 us**, shares the state vector      |\n|Validation            |Marker alleles retained (allelic richness)                                                                                 |on the returned plan only   |0.9 ms                                 |\n|Validation            |Within/between heterotic-pool decomposition of theta                                                                       |on the returned plan only   |62 us                                  |\n|Validation            |Status number Ns = 1/(2 theta)                                                                                             |free, algebraic             |0                                      |\n\n\n:::\n:::\n\n\nThree findings drive this, and each is derived and verified below rather than\nasserted.\n\n## Finding 1: the hybrid coancestry matrix is never needed {#sec-collapse}\n\n### Derivation\n\nLet lines $a, b, \\dots$ be homozygous, with $\\mathbf{f}^L$ their molecular\ncoancestry matrix. The hybrid $(ab)$ carries one genome from each parent.\nMolecular coancestry is the probability that two alleles, one drawn at random\nfrom each individual, are identical in state. Drawing at random from hybrid\n$(ab)$ selects parental genome $a$ or $b$ with probability $\\tfrac12$ each, and\nlikewise for $(cd)$, so\n\n$$f_{(ab),(cd)} \\;=\\; \\tfrac14\\left(f^L_{ac} + f^L_{ad} + f^L_{bc} + f^L_{bd}\\right).$$\n\nNow let a selection of $n$ hybrids use line $a$ exactly $k_a$ times across all\nits parental slots, $\\sum_a k_a = 2n$, and write $w_a = k_a/(2n)$. Group\ncoancestry of the selected hybrids is the mean of $f$ over all ordered pairs;\nsubstituting the identity above and collecting terms by line gives\n\n$$\\theta_S \\;=\\; \\mathbf{w}^{\\top}\\, \\mathbf{f}^L \\,\\mathbf{w},$$\n\nwith the selection allele frequencies following the same collapse,\n$\\bar{\\mathbf{p}} = \\mathbf{w}^{\\top}\\mathbf{G}^L$.\n\n### Four consequences\n\n**The $N \\times N$ hybrid matrix is never required.** Memory drops from $O(N^2)$\nto $O(L^2)$. At $L = 300$ lines and $N = 22{,}500$ hybrids that matrix would\noccupy 3.77 GB; in the benchmark below it\nwas deliberately never formed, and every metric that needs it simply has no\ntiming entry at that scale.\n\n**The vector $\\mathbf{w}$ is a sufficient statistic.** Group coancestry, gene\ndiversity, status number, effective number of parents, selection allele\nfrequencies and the heterotic-pool decomposition are all functions of\n$\\mathbf{w}$ alone. One $O(L)$ tabulation per evaluation serves all of them.\n\n**Swapping one hybrid is a rank-2 update.** Exchanging hybrid $h$ for $h'$\nchanges at most four entries of $\\mathbf{w}$, so $\\theta$ updates in $O(L)$\nrather than $O(L^2)$.\n\n**The discrete hybrid problem is exactly optimal-contribution selection on\nlines**, restricted to the lattice $w_a \\in \\{0, 1/(2n), 2/(2n), \\dots\\}$. That\nconnects it directly to the OCS literature of @sec-ocs, with the caveat that the\nlattice restriction makes it combinatorial rather than the continuous quadratic\nprogramme OCS usually solves.\n\n### Verification\n\nEvery identity was checked against literal transcriptions of the reference\nimplementations across $F_{ST} \\in \\{0.05, 0.15, 0.35\\}$, two seeds and\n$n \\in \\{20, 100\\}$, thirty replicate selections each.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Agreement with reference implementations: machine precision throughout.\n\n|                      |Identity                                    |Worst deviation |\n|:---------------------|:-------------------------------------------|:---------------|\n|max_pairwise_f        |pairwise f: hybrid vs line formula          |1.1e-16         |\n|max_theta_sub_vs_line |theta: line route vs f submatrix            |2.2e-16         |\n|max_theta_sub_vs_freq |theta: line route vs allele-frequency route |1.1e-16         |\n|max_pbar              |selection allele frequencies                |0 (exact)       |\n|max_He                |Nei He                                      |0 (exact)       |\n|max_Neparents         |effective number of parents                 |2.1e-14         |\n|max_alleles_lost      |allele loss at MAF threshold                |0 (exact)       |\n|max_theta_pools       |pool decomposition                          |1.2e-15         |\n|max_swap_update       |incremental swap vs full recompute          |4.4e-16         |\n|bitset_vs_literal     |bitset allelic richness vs literal count    |0 (exact)       |\n\n\n:::\n:::\n\n\nThe same identity, live, on the book's own data:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nctx  <- fast_ctx(simulate_data(book_cfg))\nset.seed(51)\nidx  <- sample.int(ctx$N, 60)\nc(via_hybrid_matrix = theta_group(idx, ctx),\n  via_line_route    = fast_theta(idx, ctx),\n  difference        = theta_group(idx, ctx) - fast_theta(idx, ctx))\n#> via_hybrid_matrix    via_line_route        difference \n#>         0.6745897         0.6745897         0.0000000\n```\n:::\n\n\nAnd the incremental swap, which is what makes a local search affordable:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nst  <- theta_state(idx, ctx)\nout <- idx[1]; inn <- setdiff(seq_len(ctx$N), idx)[1]\nst2 <- theta_swap(st, out, inn, ctx)\nc(after_swap_incremental = st2$theta,\n  after_swap_recomputed  = theta_group(c(idx[-1], inn), ctx),\n  difference             = st2$theta - theta_group(c(idx[-1], inn), ctx))\n#> after_swap_incremental  after_swap_recomputed             difference \n#>           6.747225e-01           6.747225e-01           2.220446e-16\n```\n:::\n\n\n::: {.callout-warning}\n## Two implementation traps found while building this\n\nR's `$` performs **partial matching** on lists, so `ctx$f` silently returns\n`ctx$fL` when the hybrid matrix is absent -- a wrong answer with no error. Every\naccessor in the package uses `ctx[[\"f\"]]`. Any pipeline carrying both matrices\nin one list is exposed to this.\n\nR integers are signed 32-bit, so `bitwShiftL(1L, 31L)` is `NA` and the usual\nmultiply-based popcount overflows. The bitset in `pack_lines()` packs 31 bits\nper word, and `popcount32()` counts them with a branch-free SWAR routine.\n:::\n\n## Finding 2: what each metric costs\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Cost per fitness evaluation. Panel A: scaling in the number of candidate hybrids. Panel B: hours to complete one million evaluations at production scale.](figs/cost_scaling.png){fig-align='center'}\n:::\n:::\n\n\nAt $L = 300$ lines, $N = 22{,}500$ hybrids, $m = 10{,}000$ markers and\n$n = 1{,}000$ selected:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Median cost per evaluation at production scale. E-NE, A-NE and effective dimensionality are absent because they require the hybrid matrix, which was never formed.\n\n|metric                    | us per evaluation| hours per 1e6 evals|\n|:-------------------------|-----------------:|-------------------:|\n|theta: incremental swap   |               5.0|              0.0014|\n|Ne_parents                |               7.2|              0.0020|\n|pool decomposition        |              62.0|              0.0172|\n|theta: LINE route         |             106.1|              0.0295|\n|theta: line route precomp |             108.0|              0.0300|\n|allelic richness: bitset  |             891.9|              0.2478|\n|allelic richness: float   |            5091.0|              1.4142|\n|allele loss (MAF thr)     |            5296.9|              1.4714|\n|He / gene diversity(freq) |           50096.0|             13.9156|\n|theta: allele-freq route  |           51113.1|             14.1981|\n\n\n:::\n:::\n\n\nThree thresholds matter:\n\n- **The genotype-scan route is disqualified.** Computing $\\theta$ from selection\n  allele frequencies costs 14.2 hours per million evaluations. The line route\n  costs 106 us -- a **482x reduction** for an algebraically identical number.\n- **The incremental swap is effectively free** at 5 us, or 1.4 seconds per\n  million evaluations. $N_{e,\\text{par}}$ at 7 us shares the same state vector\n  and is free in practice once $\\theta$ has been computed.\n- **Allelic richness cannot go inside the loop, and need not.** The bitset\n  implementation is 5.7x faster than the floating-point version, but still 178x\n  the cost of the line-route $\\theta$. It belongs at validation.\n\nThe same ordering is visible at the book's scale, where every route is\naffordable and so the comparison is about ratios, not feasibility:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfmt(cost_per_eval(ctx, n_sel = 60, reps = 40), 1)\n```\n\n::: {.cell-output-display}\n\n|metric          | us_per_eval|\n|:---------------|-----------:|\n|theta_group     |          25|\n|theta_from_freq |         175|\n|ne_parents      |           0|\n|alleles_lost    |         150|\n|ENE             |          75|\n|ANE             |         475|\n|eff_dim         |         100|\n|Gst             |        1350|\n\n:::\n:::\n\n\n## Finding 3: the metric space is nearly one-dimensional\n\n621 selections were generated across four strategy families -- random,\ntruncation at varying intensity, greedy construction over a grid of diversity\nweights, and restricted line pools -- and all 17 metrics computed on each.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Metric redundancy. A: Spearman correlations. B: PCA of rank-transformed metrics. C: the discriminating case, inside a narrow coancestry band.](figs/metric_redundancy.png){fig-align='center'}\n:::\n:::\n\n\n**PC1 absorbs 88% of the rank variance; PC2 adds 7%.** Rank correlations with\n$\\theta$ are $|\\rho| \\ge 0.93$ for status number, $H_e$, effective\ndimensionality, $N_{e,\\text{par}}$ and MAF-threshold allele loss. Reporting\nthese alongside $\\theta$ adds cost and length, not information.\n\nBut the marginal correlation is the wrong test. The question is whether a metric\nvaries **at fixed $\\theta$** -- because $\\theta$ is the constraint, and any\nmetric that is a deterministic function of it cannot discriminate among plans\nthe optimiser treats as equivalent. Two analyses agree:\n\n- After regressing each metric's ranks on $\\theta$ (quadratic), **allelic\n  richness retains 52% of its rank standard deviation** and $N_{e,\\text{par}}$\n  retains 36%. Effective dimensionality retains 25% -- close to a restatement of\n  $\\theta$.\n- Inside a band $\\theta \\in [0.666, 0.670]$ containing 399 selections,\n  **alleles retained still spans 171 markers** (11,680 to 11,851 of 12,000) and\n  $N_{e,\\text{par}}$ spans **30.1 to 55.8**.\n\nPlans the constraint cannot distinguish differ materially in how much allelic\nvariation they carry forward. That is the empirical justification for the\ntwo-metric recommendation.\n\n### Reproducing the argument at book scale\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(77)\ngrid <- do.call(rbind, lapply(seq(0, 4, length.out = 30), function(w) {\n  s <- sel_greedy(ctx, 60, w = w)\n  data.frame(w = w, theta = theta_group(s, ctx), Ne_par = ne_parents(s, ctx),\n             lost = alleles_lost(s, ctx))\n}))\nrnd <- do.call(rbind, lapply(1:60, function(i) {\n  s <- sample.int(ctx$N, 60)\n  data.frame(w = NA, theta = theta_group(s, ctx), Ne_par = ne_parents(s, ctx),\n             lost = alleles_lost(s, ctx))\n}))\nall <- rbind(grid, rnd)\n\nplot(all$theta, all$Ne_par, pch = 19, col = ifelse(is.na(all$w), \"grey60\", \"#b2182b\"),\n     xlab = expression(theta), ylab = expression(N[e]~\"parents\"))\nlegend(\"topright\", c(\"greedy sweep\", \"random\"), pch = 19,\n       col = c(\"#b2182b\", \"grey60\"), bty = \"n\")\ngrid()\n```\n\n::: {.cell-output-display}\n![At fixed theta, the effective number of parents still varies by a factor of two. The constraint cannot see the difference; the second metric can.](07-choosing-metrics_files/figure-typst/unnamed-chunk-10-1.svg){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nband <- all[abs(all$theta - median(all$theta)) < 0.0015, ]\nc(n_in_band = nrow(band),\n  theta_span = diff(range(band$theta)),\n  Ne_par_min = min(band$Ne_par), Ne_par_max = max(band$Ne_par),\n  alleles_lost_span = diff(range(band$lost)))\n#>         n_in_band        theta_span        Ne_par_min        Ne_par_max \n#>      55.000000000       0.002502847      31.578947368      41.860465116 \n#> alleles_lost_span \n#>      31.000000000\n```\n:::\n\n\n::: {.callout-note}\n## A caveat on transfer\n\nThese numbers come from a two-pool simulation at $F_{ST} = 0.15$. The\nqualitative conclusion -- near one-dimensionality, with allelic richness as the\nexception -- is robust in direction, but the exact residual fractions shift with\npool divergence and marker density. Re-running the redundancy analysis on real\ngenotypes is a half-hour job and worth doing before treating the recommendation\nas final.\n:::\n\n## Finding 4: the encoding, not the constraint handler, decides whether DE works\n\nThe optimiser was run under four simultaneous restrictions: diversity loss\n$\\le 0.5\\%$, $N_{e,\\text{par}} \\ge 50$, at most 6 uses per line, and\nheterotic-pool balance within 5%. Budget fixed at 60,000 evaluations for every\nconfiguration, three seeds each.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Differential evolution under four simultaneous restrictions at equal evaluation budget.](figs/de_convergence.png){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Mean over 3 seeds. All configurations returned feasible plans.\n\n|encoding              | index| loss %| Ne parents| max uses| seconds|\n|:---------------------|-----:|------:|----------:|--------:|-------:|\n|hybrid keys / penalty | 0.351|  0.060|     76.634|    5.667|   6.550|\n|hybrid keys / repair  | 0.351|  0.060|     76.634|    5.667|   9.621|\n|line weights / repair | 1.988|  0.448|     50.084|    6.000|  12.126|\n\n\n:::\n:::\n\n\n**The encoding decides the outcome; the constraint handler does not.** One\nrandom key per hybrid gives DE a 3,600-dimensional problem and it reaches index\n0.351. One weight per *line* -- dimension 120, available only because of the\ncollapse -- reaches **1.988 at the same budget**, a 5.7x improvement. Penalty\nand repair handlers produced numerically identical solutions in the hybrid\nencoding, because at that dimension DE never approaches the constraint boundary\nwhere the handlers differ.\n\n**Only the line encoding makes the constraints bind.** It finishes with\n$N_{e,\\text{par}} = 50.08$ against a floor of 50, max uses exactly 6 against a\ncap of 6, and loss 0.448% against a 0.5% ceiling. The hybrid encoding leaves\nevery constraint slack -- not because it found a better trade-off, but because\nit never searched far enough from random to reach the boundary.\n\n> A slack constraint at the end of a run is a diagnostic of a failed search, not\n> of a conservative plan.\n\nFor calibration: unconstrained truncation reaches index 2.337 but violates\neverything (loss 1.62%, $N_{e,\\text{par}} = 33.2$, one line used 17 times). The\nline encoding recovers **85% of the truncation index while satisfying all four\nrestrictions.**\n\nA note on tuning. `DEoptim` warns that `NP` should be at least ten times the\nparameter count; at dimension 3,600 that is 36,000 population members, which is\ninfeasible. At dimension 120 the recommendation is 1,200 and entirely reachable.\nThe reparameterisation does not merely speed the search up -- it moves the\nproblem into the regime where DE's own tuning guidance can be followed.\n\n## Finding 5: the index is not the truth, and its error is not white\n\nFindings 1 to 4 are about the diversity side of the objective. This one is about\nthe other side, and it is the larger uncertainty of the two.\n\nEverywhere in this book `ctx$index` is built from *known* marker effects\n(@sec-simulating-crosses), so every result so far assumes the breeding values are\npredicted without error. Real ones are not, and the error is not white noise:\npredictions for close relatives are wrong in the same direction, because they lean\non the same training records and share the same haplotypes. The book already has a\nmatrix of exactly that structure -- the molecular coancestry $\\mathbf{f}$ -- so\nthe error can be simulated without inventing anything. (@sec-genomic-prediction\nfits an actual GBLUP model later and finds the same structure in its real\nresiduals, at a comparable accuracy, without injecting anything.)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_sel <- 60\nnull  <- null_distribution(ctx, n_sel, B = 400, B_full = 60)\ngd    <- null$gd_ref\nu     <- ctx$index\nLc    <- t(chol(ctx$f + diag(1e-8, ctx$N)))\n\n# A predicted index at accuracy r. `kind` decides whether the error is\n# correlated with relatedness or independent between hybrids.\npredicted <- function(r, seed, kind = \"correlated\") {\n  set.seed(seed)\n  z <- rnorm(ctx$N)\n  e <- if (kind == \"correlated\") as.numeric(Lc %*% z) else z\n  e <- (e - mean(e)) / stats::sd(e)\n  as.numeric(scale(r * u + sqrt(1 - r^2) * e))\n}\n```\n:::\n\n\nSelect on the prediction, then score the plan on the truth:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrun <- function(r, seed = 1, kind = \"correlated\") {\n  ch <- ctx; ch$index <- predicted(r, seed, kind)\n  sel <- list(truncation = sel_truncation(ch, n_sel),\n              greedy     = sel_greedy(ch, n_sel, w = 3e-4))\n  do.call(rbind, lapply(names(sel), function(nm) data.frame(\n    method = nm, r = r,\n    reported = mean(ch$index[sel[[nm]]]),\n    realised = mean(u[sel[[nm]]]),\n    alpha    = alpha_loss(sel[[nm]], ctx, gd))))\n}\nacc <- do.call(rbind, lapply(c(1, 0.9, 0.7, 0.5), run))\nfmt(acc, 4)\n```\n\n::: {.cell-output-display}\n\n|method     |   r| reported| realised|  alpha|\n|:----------|---:|--------:|--------:|------:|\n|truncation | 1.0|   1.9919|   1.9919| 0.0412|\n|greedy     | 1.0|   1.5893|   1.5893| 0.0133|\n|truncation | 0.9|   1.9247|   1.9003| 0.0406|\n|greedy     | 0.9|   1.4745|   1.3965| 0.0092|\n|truncation | 0.7|   1.7529|   1.5950| 0.0356|\n|greedy     | 0.7|   1.3851|   1.1464| 0.0088|\n|truncation | 0.5|   1.6223|   1.1751| 0.0301|\n|greedy     | 0.5|   1.2591|   0.7965| 0.0056|\n\n:::\n:::\n\n\nTwo things move. The gap between `reported` and `realised` opens up -- at\n$r = 0.5$ truncation reports an index of\n1.62 and delivers\n1.18. Selection on a\nnoisy value selects partly on the noise, so the plan's own scorecard is biased\nupward. Nothing in the pipeline can detect this; it is invisible without the truth.\n\nAnd $\\alpha$ *falls* as accuracy drops. That is not the constraint working better.\nNoisy selection is closer to random selection, and random selection is what\n$\\bar H_{\\text{ref}}$ is defined against -- so the plan drifts toward the baseline\nfrom which loss is measured.\n\n### The correlation structure matters more than the amount\n\nHold accuracy fixed at $r = 0.6$ and change only whether the error is correlated\nwith relatedness, over twenty draws:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncmp <- do.call(rbind, lapply(c(\"correlated\", \"independent\"), function(k)\n  do.call(rbind, lapply(1:20, function(s) {\n    ch <- ctx; ch$index <- predicted(0.6, s, k)\n    tr <- sel_truncation(ch, n_sel)\n    data.frame(kind = k, realised = mean(u[tr]),\n               alpha = alpha_loss(tr, ctx, gd), max_line = max_line_use(tr, ctx))\n  }))))\nfmt(aggregate(cbind(realised, alpha, max_line) ~ kind, cmp, mean), 4)\n```\n\n::: {.cell-output-display}\n\n|kind        | realised|  alpha| max_line|\n|:-----------|--------:|------:|--------:|\n|correlated  |   1.1508| 0.0391|    18.15|\n|independent |   1.2253| 0.0121|    12.60|\n\n:::\n:::\n\n\nSame accuracy, same method, same number selected. Correlated error costs roughly\n3.2\ntimes the diversity of independent error, and leans\n1.4\ntimes as hard on its favourite line.\n\nThe mechanism is direct. Independent error scatters the mistakes, which\naccidentally diversifies the plan. Error correlated with relatedness makes whole\nfamilies look good together, so the plan takes families -- and a family is exactly\nwhat the diversity constraint exists to stop it taking.\n\n:::: {.callout-warning}\n## The worst case is not the noisiest one\n\nTruncation on a perfect index loses\n4.12% of gene\ndiversity and earns every bit of the index it reports. Under correlated error at\n$r = 0.6$ it still loses\n3.91%\n-- nearly the same price -- while delivering\n1.15\ninstead of 1.99.\n\nYou pay the full diversity cost of aggressive selection and collect a fraction of\nthe gain. That is the case to design against, and it is the ordinary case in a\nreal programme.\n::::\n\n### What this does to the recommendation\n\nNothing, for the metric set. Findings 1 to 3 are statements about $\\mathbf{f}$ and\nhold whatever the index is. But it changes what the numbers in @sec-case-study\nmean, and it reorders the priorities: the choice between two diversity metrics is\nworth a fraction of a percent of index, and prediction accuracy is worth tens of\npercent. Report $\\alpha$ against the plan you actually planted, validate accuracy\nbefore tuning the constraint, and treat a reported index as an upper bound.\n\n## The recommendation, stated\n\n### Inside the optimiser\n\nUse two metrics, both functions of the line-usage vector $\\mathbf{w}$:\n\n1. **Proportional loss of gene diversity**,\n   $(\\bar H_{\\text{ref}} - H_S)/\\bar H_{\\text{ref}}$ with\n   $H_S = 1 - \\mathbf{w}^\\top \\mathbf{f}^L \\mathbf{w}$ and\n   $\\bar H_{\\text{ref}}$ the mean over same-size random subsets. Compute it by\n   the line route, never by scanning genotypes.\n2. **Effective number of parent lines**,\n   $N_{e,\\text{par}} = (\\sum k_a)^2 / \\sum k_a^2$. It costs 7 us, shares the\n   state vector, and blocks concentration onto a few lines -- a failure mode\n   $\\theta$ tolerates.\n\nReparameterise the search on **line weights**, and enforce the per-line usage\ncap in the decoder rather than by penalty.\n\n### At validation, on the returned plan only\n\n3. **Marker alleles retained**, via the bitset route. The one metric carrying\n   information $\\theta$ does not.\n4. **Within/between heterotic-pool decomposition**, to confirm the plan has not\n   preserved diversity by degrading pool separation.\n5. **Status number** $N_s = 1/(2\\theta)$, free from $\\theta$, as the reportable\n   descriptor. Do not report a rate-based $N_e$ under active management.\n\n### Not recommended\n\nNei's $H_e$ as a separate metric (it *is* $1 - \\theta$); effective\ndimensionality ($|\\rho| = 0.97$ with $\\theta$, and needs the hybrid matrix);\nMAF-threshold allele loss ($|\\rho| = 0.93$, and 1.47 hours per million\nevaluations); Core Hunter's E-NE and A-NE (both require the $O(N^2)$ matrix and\nare unavailable at production scale -- they are designed for core-collection\nassembly, a different problem).\n\n### Caveats\n\nThe choice of $\\mathbf{f}^L$ remains open in the literature. Post-2018 work is\nconsistent that molecular or IBD-flavoured coancestry beats a VanRaden-style\ndrift matrix for diversity management, but reports no consensus on a single\npreferred formulation, and matrix choice demonstrably changes allele-frequency\ntrajectories (@sec-plant-literature). The collapse derived here is a property of\nthe F1 structure and holds for **any** symmetric line-level $\\mathbf{f}^L$ -- so\nif the matrix choice changes, every cost and identity result in this chapter\nsurvives unchanged.\n\nManaging on molecular coancestry controls homozygosity, not drift; these\ndiverge, and a plan optimal on one is not optimal on the other\n(@sec-genomic-era). Predicted $\\Delta f$ is biased downward, with the bias\ngrowing as the candidate pool shrinks -- report realised $\\theta$ on the chosen\nplan rather than a predicted rate.\n\n## Drop-in code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nctx <- fast_ctx(ctx, GL = line_genotypes, pack = TRUE)   # no N x N matrix needed\n\ngd_ref <- mean(replicate(500, fast_gene_div(sample.int(ctx$N, n_sel), ctx)))\n\nfit <- make_fitness_fast(ctx, n_sel, gd_ref, alpha_max = 0.005,\n                         ne_par_min = 50, max_use = 6, penalty = 5,\n                         encoding = \"lines\")\n\nres <- DEoptim::DEoptim(fit,\n                        lower = rep(0, ctx$n_lines), upper = rep(1, ctx$n_lines),\n                        control = DEoptim::DEoptim.control(NP = 200, itermax = 300))\n\nidx <- decode_lines(res$optim$bestmem, ctx, n_sel, max_use = 6)\nc(theta      = fast_theta(idx, ctx),\n  loss_pct   = 100 * (gd_ref - fast_gene_div(idx, ctx)) / gd_ref,\n  Ne_parents = fast_ne_parents(idx, ctx),\n  alleles    = alleles_retained_fast(idx, ctx),\n  fast_theta_pools(idx, ctx))\n```\n:::\n\n",
    "supporting": [
      "07-choosing-metrics_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}