{
  "hash": "e7bb5536e65057ebc9a1377ff6737834",
  "result": {
    "engine": "knitr",
    "markdown": "# Diversity in a subdivided population {#sec-subdivided}\n\n\n\nA breeding programme is never one population. It is heterotic groups, or\naccessions, or landraces, or cycles -- and the diversity of the whole is not the\naverage of the diversity of the parts. @caballero2002 give the partition that\nmakes this precise, and it is the analytical backbone of everything that\nfollows: the constraint in @sec-ocs is a special case of it, and the\nwithin/between asymmetry that makes plant hybrid breeding different from animal\nbreeding is a statement about which term of it you are allowed to minimise.\n\nThe paper's central claim is uncomfortable and worth stating first: **a method\nthat ranks accessions by distance alone can invert the correct conclusion.** An\naccession can be the most distant *because* it is internally fixed, and removing\nit can *raise* the diversity of the pool. We reproduce that result numerically\nbelow.\n\n## Notation\n\n- A metapopulation of $n$ subpopulations; subpopulation $i$ has $N_i$\n  individuals, $N_T = \\sum_i N_i$.\n- A tilde, $\\tilde{x}$, is a weighted mean **within** subpopulations:\n  $\\tilde{f} = \\sum_i f_{ii} N_i / N_T$.\n- A bar, $\\bar{x}$, is a mean over **all pairs** in the metapopulation,\n  between-subpopulation pairs included:\n  $\\bar{f} = \\sum_{i,j} f_{ij} N_i N_j / N_T^2$.\n- Always $\\bar{f} \\le \\tilde{f} \\le \\tilde{s}$. The differences between those\n  three numbers *are* the partition of diversity.\n- Everything is computed per locus and then averaged over loci. Never average\n  frequencies first.\n\n::: {.callout-warning}\n## The subtle point, and the one most often got wrong\n\nEvery coancestry here includes the pairs of an individual with **itself** --\ngroup coancestry in the sense of Cockerham. That is what makes $1 - f_{ii}$\nexactly Nei's expected heterozygosity, and it is what makes the algebra close.\nDrop the diagonal and none of the identities below hold.\n:::\n\n## The three coancestry blocks\n\n### $f_{ij}$, between subpopulations\n\nThe probability that two alleles, one sampled at random in subpopulation $i$ and\none in $j$, are identical. From markers, $f_{ij} = \\sum_k \\tilde p_{k,i}\n\\tilde p_{k,j}$.\n\nRead it as **redundancy** between two materials. If you cross plants of $i$ with\nplants of $j$, the progeny has expected inbreeding $F = f_{ij}$. It answers:\nwhat do I gain by recombining these two accessions?\n\nIn maize, $f_{ij}$ between a Stiff Stalk pool and a Non-Stiff Stalk pool is\ntypically low -- and that low between-group coancestry is exactly what sustains\nthe heterotic pattern. Between two elite lines of the same family it can exceed\n0.6, and the cross generates nothing new.\n\n### $f_{ii}$, within a subpopulation\n\nThe case $i = j$. From markers $f_{ii} = \\sum_k \\tilde p_{k,i}^2$, the expected\nhomozygosity, so\n\n$$1 - f_{ii} \\;=\\; H_{e,i} \\;=\\; \\text{Nei's gene diversity of accession } i.$$\n\nA landrace accession regenerated twenty times with forty ears per cycle\naccumulates coancestry and watches $f_{ii}$ rise silently. It is the cheapest\nalarm for genetic erosion *inside* a genebank -- and it is precisely what a\ndistance tree cannot see.\n\n### $s_i$ and $F_i$, self-coancestry and molecular inbreeding\n\n$$s_i = \\sum_k \\sum_l \\frac{p_{k,l,i}^2}{N_i}, \\qquad\n  F_i = 2 s_i - 1, \\qquad 1 - s_i = H_{o,i}$$\n\nwith $p_{k,l,i}$ the dosage of allele $k$ in individual $l$.\n\n::: {.callout-important}\n## $F_i$ here is molecular, and is not $F_{IS}$\n\nIt is measured against a hypothetical base in which all alleles are distinct. It\nis **not** comparable across studies using different marker panels. For the\nquestion \"is this population mating at random?\", use $\\alpha_i$ below.\n:::\n\nIn soybean, rice and wheat, pure lines have $s_i \\to 1$, so $F_i \\to 1$ and\n$H_o \\to 0$. That is expected, not a symptom. It changes only *where* the\ndiversity resides.\n\n## Two per-subpopulation metrics\n\n$$\\alpha_i = \\frac{F_i - f_{ii}}{1 - f_{ii}}, \\qquad\n  G_i = \\frac{s_i - f_{ii}}{1 - f_{ii}} = \\frac{1 + \\alpha_i}{2}$$\n\n$\\alpha_i$ is the subpopulation's analogue of $F_{IS}$: positive means an excess\nof homozygotes (selfing, mating among relatives, a Wahlund effect from internal\nsubstructure, null alleles); negative means an excess of heterozygotes\n(dioecy, self-incompatibility, selection, or a freshly formed F1 or synthetic).\n\n$G_i$ is the proportion of the accession's diversity that sits **between**\nindividuals rather than inside them, and it is probably the most underused\nquantity in the paper. It is a mating-system meter:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: G_i as a mating-system meter.\n\n|G_i    |Situation               |Typical material                                       |\n|:------|:-----------------------|:------------------------------------------------------|\n|~ 0.5  |perfect panmixia        |maize, sunflower, open populations                     |\n|< 0.5  |excess of heterozygotes |F1 synthetics, heterozygous clones, self-incompatibles |\n|-> 1.0 |all homozygous          |inbred lines, doubled haploids, selfing species        |\n\n\n:::\n:::\n\n\nOperationally, $1 - G_i$ is the fraction of an accession's diversity stored\n*inside* each plant, and it decides the sampling design. With $G_i \\to 1$\n(selfers), one individual captures almost nothing and you need many plants per\naccession. With $G_i \\approx 0.5$ (maize), a few plants already capture half.\n\n## Distances, and what they actually are\n\nNei's minimum distance between subpopulations is\n\n$$\\mathbf{D}_{ij} = \\frac{f_{ii} + f_{jj}}{2} - f_{ij}\n                  = \\sum_k \\tfrac{1}{2}(\\tilde p_{k,i} - \\tilde p_{k,j})^2 .$$\n\nNote what that is: **half the sum of squared allele-frequency differences** -- a\nvariance component, not an evolutionary distance calibrated in time. It is the\npiece that enters $F_{ST}$, and it is legitimate. The error in a\ndistance-only method is not using $\\mathbf{D}_{ij}$; it is using *only*\n$\\mathbf{D}_{ij}$.\n\n::: {.callout-tip}\n## A free $O(N^2)$ saving\n\nThe paper's Eq. 13 computes $D_{ij}$ by a double sum over all pairs of\nindividuals, at cost $O(N_i N_j m)$. That is unnecessary: the identity\n$D_{ij} = (s_i + s_j)/2 - f_{ij}$ is **exact** and reduces the cost to $O(Nm)$.\nFor a 50k-SNP panel and 5000 accessions this is the difference between hours and\nseconds.\n:::\n\n## The equation that matters most in practice\n\n$$\\bar{f} = \\sum_{i} \\frac{N_i}{N_T}\n  \\Big[\\, \\underbrace{f_{ii}}_{\\text{internal coancestry}}\n        - \\underbrace{\\textstyle\\sum_j \\mathbf{D}_{ij} N_j / N_T}_{\\text{mean distance to the others}} \\Big]$$\n\nEach accession's contribution to global coancestry -- that is, to the *loss* of\ndiversity in the pool -- has **two terms of opposite sign**:\n\n- **Term 1 (+).** The more internally fixed an accession is, the more it\n  *raises* global coancestry: it dilutes the pool with copies of the same\n  allele.\n- **Term 2 (−).** The more distant it is from the others, the more it *reduces*\n  global coancestry.\n\nA distance-only method sees term 2 alone. That is the whole mechanism of the\ninverted conclusions.\n\n## F statistics and the partition\n\n$$F_{IS} = \\frac{\\tilde F - \\tilde f}{1 - \\tilde f}, \\qquad\n  F_{ST} = \\frac{\\tilde f - \\bar f}{1 - \\bar f} = \\frac{\\bar D}{1 - \\bar f}, \\qquad\n  F_{IT} = \\frac{\\tilde F - \\bar f}{1 - \\bar f}$$\n\nwith $(1 - F_{IT}) = (1 - F_{IS})(1 - F_{ST})$.\n\nThe partition itself is the heart of the paper:\n\n$$(1 - \\bar f) = \\underbrace{(1 - \\tilde s)}_{GD_{WI}}\n              + \\underbrace{(\\tilde s - \\tilde f)}_{GD_{BI}}\n              + \\underbrace{(\\tilde f - \\bar f)}_{GD_{BS}}$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: The partition of gene diversity (Caballero & Toro 2002, Eq. 7).\n\n|Component             |Definition                            |Biologically                                                   |\n|:---------------------|:-------------------------------------|:--------------------------------------------------------------|\n|GD_T = 1 - f_bar      |total diversity                       |He of the whole pool if everything were recombined             |\n|GD_WI = 1 - s_til     |within individuals                    |heterozygosity carried inside each plant                       |\n|GD_BI = s_til - f_til |between individuals, within accession |segregating variation available to within-population selection |\n|GD_WS = 1 - f_til     |within subpopulations                 |GD_WI + GD_BI                                                  |\n|GD_BS = f_til - f_bar |between subpopulations                |divergence; the only component a distance method sees          |\n\n\n:::\n:::\n\n\nwith the clean identities\n\n$$\\frac{GD_{WI}}{GD_T} = (1-G)(1-F_{ST}), \\quad\n  \\frac{GD_{BI}}{GD_T} = G(1-F_{ST}), \\quad\n  \\frac{GD_{WS}}{GD_T} = 1-F_{ST}, \\quad\n  \\frac{GD_{BS}}{GD_T} = F_{ST}.$$\n\n### Why the partition changes the strategy by species\n\n- **Outcrossers** (maize, sunflower, forages, forest trees): $GD_{WI}$ is large.\n  The diversity is literally *inside* the plants. Conserving means maintaining\n  heterozygosity -- regenerate with many individuals and balanced contributions.\n- **Selfers** (soybean, wheat, rice, beans) **and DH or line collections**:\n  $GD_{WI} \\approx 0$. All diversity is $GD_{BI} + GD_{BS}$. Conserving means\n  maintaining the *number of distinct lines*; heterozygosity is not a target.\n  Regenerating with few plants per line is acceptable; losing lines is not.\n- **Clonal crops** (potato, sugarcane, fruit trees): $GD_{WI}$ is high and\n  **frozen** -- it does not decay by drift while the clone exists. The $N_e$\n  algebra does not apply without adaptation.\n\nThis is the reason a hybrid maize programme cannot manage diversity with a\nsingle pool-wide number: it needs $GD_{WS}$ defended and $GD_{BS}$ held, and\nthose two pull in opposite directions under selection.\n\n## The worked example, reproduced\n\nThe paper's metapopulation: four subpopulations of $N$ = 12, 4, 8, 6, three loci\nwith 5, 3 and 3 alleles. Its published coancestry matrix:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf <- matrix(c(0.3391, 0.3021, 0.2535, 0.3229,\n              0.3021, 0.8750, 0.3073, 0.3889,\n              0.2535, 0.3073, 0.4766, 0.2483,\n              0.3229, 0.3889, 0.2483, 0.3704), 4, 4, byrow = TRUE,\n            dimnames = list(paste0(\"Sub\", 1:4), paste0(\"Sub\", 1:4)))\nN <- c(12, 4, 8, 6)\nw <- N / sum(N)\n```\n:::\n\n\nNote subpopulation 2: $f_{22} = 0.875$, so $H_e = 0.125$. It is nearly fixed\ninternally. Now the global quantities, with the paper's published values beside\nthem:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf_bar <- drop(w %*% f %*% w)\nf_til <- sum(w * diag(f))\ns_til <- 0.7056                       # published; needs individual genotypes\n\ndata.frame(\n  quantity = c(\"f_bar\", \"f_til\", \"GD_T\", \"GD_WI\", \"GD_BI\", \"GD_BS\", \"F_ST\"),\n  computed = round(c(f_bar, f_til, 1 - f_bar, 1 - s_til, s_til - f_til,\n                     f_til - f_bar, (f_til - f_bar) / (1 - f_bar)), 4),\n  published = c(0.3256, 0.4535, 0.6744, 0.2944, 0.2521, 0.1279, 0.1897)\n)\n```\n\n::: {.cell-output-display}\n\n|quantity | computed| published|\n|:--------|--------:|---------:|\n|f_bar    |   0.3256|    0.3256|\n|f_til    |   0.4535|    0.4535|\n|GD_T     |   0.6744|    0.6744|\n|GD_WI    |   0.2944|    0.2944|\n|GD_BI    |   0.2521|    0.2521|\n|GD_BS    |   0.1279|    0.1279|\n|F_ST     |   0.1897|    0.1897|\n\n:::\n:::\n\n\nEvery value reproduces exactly. Note that $GD_{BS}$ is only 19% of the total:\nthe between-subpopulation divergence -- the only thing a distance method\nmeasures -- accounts for less than a fifth of the diversity in this\nmetapopulation.\n\n### Removing an accession can *increase* diversity\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nres <- list(f = f, by_subpop = data.frame(N = N))\ncbind(ct_loss_gain(res),\n      delta_pct_equal = round(ct_loss_gain(res, \"equal\")$delta_pct, 2))\n```\n\n::: {.cell-output-display}\n\n|pop  | GD_without|  delta_pct| delta_pct_equal|\n|:----|----------:|----------:|---------------:|\n|Sub1 |  0.6296049| -6.6468853|           -6.92|\n|Sub2 |  0.6868734|  1.8444502|            6.47|\n|Sub3 |  0.6480760| -3.9081294|           -6.94|\n|Sub4 |  0.6689694| -0.8102105|           -3.56|\n\n:::\n:::\n\n\nThe number to look at is subpopulation 2. A Weitzman-style analysis calls it the\nmost valuable in the set -- losing it would cost 65.5% of the diversity, because\nit is the most divergent. The coancestry analysis says removing it **raises**\npool diversity by 1.8% (census weights) or 6.5% (equal weights).\n\nIt is distant *because* it is fixed. Alleles fixed in a sample of four\nindividuals are not a genetic resource; they are the result of drift. The same\npattern appears in the paper's reanalysis of eleven European pig breeds: the\nbreed a distance method nominates as most valuable turns out to raise diversity\nby 0.67% when removed.\n\n::: {.callout-caution}\n## What this does and does not license\n\nFor a genebank: a rare accession with few plants and high homozygosity -- the\narchetypal \"unique\" accession on a distance tree -- may be contributing\n*negatively* to the pool. That does **not** mean discard it. It means the\ncorrect priority may be to **regenerate it at larger $N$**, not to replicate it\ninto a core collection. Storing seed is cheap; extinction is irreversible.\n:::\n\n### Optimal contributions\n\nMaximising $GD_T = 1 - \\sum_{i,j} f_{ij} c_i c_j$ subject to $c_i \\ge 0$ and\n$\\sum_i c_i = 1$ is a quadratic programme:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noc <- optimal_contributions(f)\noc$c_i\n#>     Sub1     Sub2     Sub3     Sub4 \n#> 0.522398 0.000000 0.269890 0.207711\nc(GD_before = 1 - f_bar, GD_after = oc$GD_max,\n  gain_pct = 100 * (oc$GD_max - (1 - f_bar)) / (1 - f_bar))\n#> GD_before  GD_after  gain_pct \n#> 0.6744338 0.6873675 1.9177220\n```\n:::\n\n\nSubpopulation 2 receives weight **zero**, and total diversity rises from 0.6744\nto 0.6874. This reproduces the paper's published solution\n$\\mathbf{c} = (0.522,\\, 0,\\, 0.270,\\, 0.208)$ exactly.\n\nThree direct uses in plant breeding:\n\n- **Base population for recurrent selection.** $c_i$ gives the seed proportion\n  from each source that maximises long-term additive variance.\n- **Core collection.** Instead of clustering heuristics plus proportional\n  sampling, solve the quadratic programme directly with operational constraints\n  ($c_i \\le$ multiplication capacity, $c_i \\ge$ a policy minimum for accessions\n  of cultural importance).\n- **Optimal contribution selection.** Replace the objective with\n  $\\max \\mathbf{c}'\\mathbf{g} - \\lambda\\,\\mathbf{c}'\\mathbf{F}\\mathbf{c}$ and you\n  have Meuwissen's framework, now standard in genomic programmes. This chapter is\n  the case $\\lambda \\to \\infty$, pure diversity. A breeder operates in the middle\n  of the curve -- which is @sec-ocs.\n\n## Minimising coancestry is maximising $N_e$\n\nSince $N_s = 1/(2\\bar f)$, minimising group coancestry and maximising effective\nsize are the same operation. The paper's Eq. 14 makes the operational\nconsequence explicit. With **equal** contributions ($S_W^2 = S_B^2 = 0$),\n$N_e \\approx 2Nn/(1 - F_{IT})$ -- roughly **double** the $N_e$ obtained under\nrandom (Poisson) contributions.\n\n> Harvesting the same number of seeds from every plant, and the same number of\n> plants from every family, doubles the effective size. No genotyping, no\n> technology, no cost.\n\nIt is probably the best cost-benefit intervention available in germplasm\nmanagement. The opposite -- bulk harvest from a plot, which in practice samples\nthe most productive plants disproportionately -- inflates $S_W^2$ and collapses\n$N_e$.\n\n## The honest caveats\n\nThe paper makes these, and a breeder should take them seriously.\n\nCriteria based on within-population variation systematically **favour larger\npopulations**. A $\\bar f$ criterion can push a genebank toward abundant elite\nmaterial -- the opposite of the conservation objective. Beyond that:\n\n- Neutral markers do not measure adaptive value, disease resistance, stress\n  adaptation or cultural value. A fixed accession may carry the only resistance\n  allele to an emerging rust.\n- **Allelic richness** is more sensitive to bottlenecks than heterozygosity and\n  is often the more relevant criterion for pre-breeding. The argument that\n  minimising $\\bar f$ maximises allelic richness in the long run (via the\n  effective number of alleles being the inverse of mean coancestry) is valid\n  asymptotically but does **not** protect rare alleles in the short term. This\n  is why allelic richness survives the redundancy analysis in @sec-choosing as\n  the one genuinely independent axis.\n- Weighting between-group variation more heavily is arbitrary. A more defensible\n  fix is to optimise $\\mathbf{c}$ with per-accession minimum constraints.\n\n**Rule of thumb:** use $\\bar f$ to decide *proportions and regeneration effort*;\nnever use $\\bar f$ alone to decide *discard*.\n\n## Two errata, found while verifying\n\nWorth recording, since the numbers above were checked against the published\ntables.\n\n- Table 2b lists $F_2 = 0.8383$, but $F_i = 2s_i - 1 = 2(0.9167) - 1 = 0.8333$.\n  A typographical error. Every other value in Tables 2 and 3 reproduces exactly.\n- Conceptually, the Discussion states that equal contributions\n  ($S_B^2 = S_W^2 = 0$) are required \"to minimise effective size\" and \"maximise\n  mean coancestry\". That is inverted: Eq. 15 and the entire argument of the\n  paper show that equal contributions **maximise** $N_e$ and **minimise**\n  $\\bar f$.\n\n## What manages this quantity, and where\n\nThis chapter is the book's keystone, and it is easy to read it as a\nself-contained treatment of Caballero & Toro. The partition it derives is not\nbackground: it is the object every later chapter operates on. Stated once, so\nthe rest of the book can refer back rather than re-introduce it:\n\n| Term | What it is | Where it is managed |\n|---|---|---|\n| $GD_{WI}$ | diversity within individuals | exactly zero with inbred parents (@sec-catalogue); the hybrid-level $GD_{WI\\text{-}hyb}$ is what carries signal |\n| $GD_{BI}$ | between individuals, within pool | the quantity $\\alpha$ budgets (@sec-ocs), and the one recurrent selection erodes (@sec-cycles) |\n| $GD_{BS}$ | between pools | the heterosis engine, to be **preserved** not minimised -- derived as an exact identity in @sec-heterosis |\n\nThree consequences follow, and each is a chapter.\n\n**A single pool-wide statistic cannot express \"conserve within, hold between\".**\nThat is why @sec-catalogue reports the partition rather than only $GD_T$, and why\n@sec-stages makes S1 a separate monitoring stage instead of folding pool\nconservation into the hybrid-selection constraint.\n\n**The between term is not a bonus to be maximised.** @sec-heterosis-flat shows\nthat under neutral drift every unit of $GD_{BS}$ gained is paid for out of the\nshared term, so pushing the pools apart buys nothing. The partition tells you\nwhere diversity *is*, not which direction to move it.\n\n**The within term is the one with a future.** $GD_{BI}$ is the raw material of\nnext cycle's response, which @sec-response makes precise: it is the same sum over\nthe same loci as genic variance, weighted equally instead of by squared effect.\nThat is the entire reason a diversity constraint is worth writing down, and\n@sec-limits is where the equivalence is pushed until it breaks.\n",
    "supporting": [
      "02-subdivided_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}