{
  "hash": "f77f257a464572e5039562093e579a9d",
  "result": {
    "engine": "knitr",
    "markdown": "# Diversity metrics in the genomic era {#sec-genomic-era}\n\n\n\nIn classical theory, inbreeding measured as **loss of heterozygosity** and\ninbreeding measured as **drift of allele frequencies** are the same thing.\n@meuwissen2020 show that inside genomic optimal-contribution schemes they stop\nbeing the same thing, and can diverge badly, whenever diversity is controlled\nthrough **identity by state** on a marker panel. Only when control is through\n**identity by descent** is the classical equivalence restored.\n\nThe practical consequence is uncomfortable:\n\n> You hit exactly the target you wrote into the optimiser's constraint, and you\n> pay an unmonitored price in the metric you did not write.\n\nIf you constrain $\\tfrac{1}{2}\\mathbf{c}'\\mathbf{G}\\mathbf{c}$ using a VanRaden\n$\\mathbf{G}$, you are constraining **drift**. The loss of heterozygosity in your\ngermplasm may be running at a different rate, in either direction, from the one\nyou believe you are controlling.\n\nThis chapter is written for one kind of programme, stated in full in\n@sec-era-programme: an allogamous, maize-type hybrid programme running\nreciprocal recurrent selection over two heterotic pools. The first half defines\nthe metrics; the second half is the sequence of steps that puts them into a\ncycle report, with the check and the failure mode of each step.\n\n## The programme this chapter is written for {#sec-era-programme}\n\nEvery number below is computed under these assumptions. They are declared here\nbecause several of the results are false outside them.\n\n**A1. The species is allogamous and the product is an F1 hybrid.** Maize-type:\ntwo heterotic pools, A and B, crossed to produce single-cross hybrids. The\ncommercial product carries the heterozygosity; the parents do not. Nothing here\nis addressed to a self-pollinated crop whose product is a line, and nothing here\nis addressed to a programme whose commercial unit is a synthetic or a population\ncross -- both change which quantity is the product and therefore which loss\nmatters.\n\n**A2. Parent lines are fully inbred, by DH induction or by selfing to fixation.**\nThis is a property of the *programme*, not of the mating system: an allogamous\ncrop bred for hybrids still delivers inbred parents. In this simulation the\nlines are homozygous at every locus, which the coancestry kernel reports exactly:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(het_fraction_lines   = mean(L / 2 == 0.5),\n  self_coancestry_min  = min(diag(molecular_coancestry(L / 2))),\n  het_fraction_F1      = mean(ctx$X == 0.5),\n  twice_GD_WI_hyb      = 2 * gd_partition(seq_len(ctx$N), ctx)[[\"GD_WI_hyb\"]])\n#>  het_fraction_lines self_coancestry_min     het_fraction_F1     twice_GD_WI_hyb \n#>           0.0000000           1.0000000           0.3616896           0.3616896\n```\n:::\n\n\nLine heterozygosity is zero and every line's self-coancestry is 1, so\nindividual-level inbreeding coefficients are 1 by construction and carry no\nmanagement information. The F1s carry\n0.362 of their loci heterozygous, and that fraction is\nexactly twice `GD_WI_hyb` -- the identity @sec-heterosis derives. **The\nmanageable quantity is therefore an allele frequency in a pool, never a\nhomozygosity within an individual.** Everything below is computed on\nfrequencies.\n\n**A3. Germplasm is recycled within pool; only information crosses the pool\nboundary.** Lines are chosen on hybrid performance against the opposite pool\n(@comstock1949) and recycled inside their own pool. A DH taken from an\n$A \\times B$ F1 would be a blend of both pools and would destroy the heterotic\npattern, so it never happens. `run_cycles()` in @sec-cycles implements exactly\nthis loop.\n\n**A4. Cycles are discrete.** Pool sizes are constant across cycles and no\ngeneration overlap is modelled. Real programmes overlap cycles and reuse the\nsame line for years, which biases any $\\Delta F$ read off a cycle index; see\n@sec-limits.\n\n**A5. Markers are neutral, biallelic, coded $0/0.5/1$** as the frequency of the\nreference allele within the individual, and are in linkage equilibrium within\npool because each line's genotype is drawn independently per locus\n(`simulate_lines()`). Linkage equilibrium makes the audit step of\n@sec-era-step5 a best case, and that is said again where the number is reported.\n\n**A6. The frequency base $p_0$ is frozen at the founding cycle** and never\nrecomputed. This is `ctx$p0`, set once in `build_ctx()`. @sec-era-step1 is that\nstep and measures what happens without it.\n\n**A7. No dominance enters any metric in this chapter.** $\\theta$, $GD$ and\n$\\alpha$ are functions of allele frequencies alone. The dominance side of the\nsame germplasm -- what the divergence between pools is worth in heterosis -- is\n@sec-heterosis, and the two must not be mixed inside one constraint.\n\n**A8. The scale is the book's teaching scale**: 25 +\n25 lines, 2000 markers, 625 hybrids in the\nfull factorial. The production scale is 71 + 71 lines and 25000 markers. Where a\nresult is scale-dependent, it says so.\n\n## Three lenses, not three synonyms\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: The three lenses of the section title, plus the hybrid of two of them: G_ROH reads homozygosity and is interpreted as IBD, which is why it gets a row of its own and not a lens of its own. G_0.5 is the matrix this book calls f -- see @sec-coancestry.\n\n|Lens         |What the metric actually sees                      |Inbreeding metric |Relationship matrix          |\n|:------------|:--------------------------------------------------|:-----------------|:----------------------------|\n|Drift        |squared allele-frequency change relative to a base |F_drift           |G_VR2, G_VR1, G_i(p)         |\n|Homozygosity |proportion of heterozygosity remaining             |F_hom             |G_0.5 (molecular coancestry) |\n|IBD          |segments inherited by descent from a defined base  |F_IBD             |A, G_LA                      |\n|Hybrid       |haplotype homozygosity used as a proxy for IBD     |F_ROH             |G_ROH                        |\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## Every inbreeding metric is a ratio to a reference population\n\nWithout explicitly declaring your base -- cycle 0 of the recurrent programme? a\nlandrace panel? the founding heterotic pool? -- none of the numbers below mean\nanything. This is the commonest error in plant applications: using the *current*\ngeneration's frequencies as the base, which zeroes the historical memory of\nerosion. @sec-era-step1 measures the size of that mistake: it is not an\nattenuation, it is an exact zero.\n:::\n\n## The metrics, one at a time\n\n### Rate of inbreeding and effective size\n\nWhat you manage is not $F$ but its rate of accumulation. $F$ is a stock;\n$\\Delta F$ is a flow.\n\n$$\\Delta F = \\frac{F_t - F_{t-1}}{1 - F_{t-1}}, \\qquad N_e = \\frac{1}{2\\Delta F}$$\n\nwith $F_t \\in (-\\infty, 1]$ the inbreeding coefficient of cycle $t$ against the\nfrozen base (negative values are possible for $F_{hom}$, see below),\n$\\Delta F$ the per-cycle rate and $N_e$ the effective size it implies\n[@falconer1996, Ch. 3-4].\n\nSince $1 - F_t = (1 - \\Delta F)^t$, a regression of $\\log(1 - F_t)$ on $t$ has\nslope $\\log(1 - \\Delta F)$, so $\\Delta F = 1 - e^{\\text{slope}}$ and\n$-\\text{slope}$ is only its first-order approximation. **The linearity of that\nregression is itself a diagnostic:** in @meuwissen2020, $\\log(1 - F_{drift})$\nwas approximately linear under every scheme, while $\\log(1 - F_{hom})$ showed\nmarked curvature under some, notably the ROH-based one. Curvature means a\nnon-constant rate -- your $N_e$ target is not being met steadily.\n\nA tropical maize recurrent programme targeting $N_e = 50$ per cycle needs\n$\\Delta F = 0.01$. Measuring $F$ only at cycle 8 and dividing by 8 hides the\npossibility that cycles 1-3 were conservative and cycles 6-8 collapsed the base.\n@sec-era-step4 fits the regression on a case where the answer is known in\nadvance, and then on one where the diagnostic has to fire.\n\n### `F_hom`, homozygosity-based {#sec-era-fhom}\n\nWright defined an inbreeding coefficient to run from 0 to 1 as heterozygosity\nunder random mating falls from its initial state to zero. So the metric is the\nfraction of heterozygosity already lost relative to the base:\n\n$$F_{hom} = 1 - \\frac{1}{N_{SNP}}\\sum_k \\frac{2p_{t,k}(1 - p_{t,k})}{2p_{0,k}(1 - p_{0,k})}\n          = 1 - \\frac{1}{N_{SNP}}\\sum_k \\frac{H_{t,k}}{H_{0,k}}$$\n\nwith $p_{t,k} \\in [0,1]$ the frequency of the reference allele at marker $k$ in\nthe population being scored, $p_{0,k} \\in (0,1)$ the same frequency in the frozen\nbase, $H = 2p(1-p)$ the expected heterozygosity under random mating, and\n$N_{SNP}$ the number of markers [@meuwissen2020, their Eq. 1A defines it as the\ntotal marker count]. This book restricts the sum to markers polymorphic in the\nbase, because $H_{0,k} = 0$ makes the ratio undefined otherwise --\n`freq_metrics()` does that with `keep <- ctx$p0 > eps & ctx$p0 < 1 - eps` -- and\nthe restriction changes nothing against their result, since their own panels\nwere random samples of loci already segregating in the base population.\n\n**It can be negative.** If management pushes frequencies toward 0.5,\nheterozygosity rises above the base and the \"inbreeding coefficient\" goes below\nzero. That is not a numerical error: it is the expected behaviour of any scheme\nthat maximises heterozygosity on the monitored panel.\n\nIt protects against inbreeding depression and the expression of deleterious\nrecessives in homozygosis. It is the right lens when the dominant risk is\n*vigour* -- in this programme, the vigour of the segregating crossing block and\nnot of the fixed lines, which is a narrower claim than it looks and is qualified\nat the end of this section.\n\n#### What this lens is computed on, and what it is not\n\n$F_{hom}$ as `freq_metrics()` computes it takes $p_t$ from\n`colMeans(X[idx, ])`: the reference-allele frequency of the **merged** hybrid\nset. With inbred parents that merged frequency is\n$\\bar p = (\\tilde p_A + \\tilde p_B)/2$, with $\\tilde p_A$ and $\\tilde p_B$ the\ntwo pools' frequencies weighted by the line usage the selection induces. So the\n$He$ column of the same call is $\\overline{2\\bar p(1 - \\bar p)}$, which is\n$GD_T = 1 - \\bar f$ of the Caballero & Toro partition [@caballero2002, Eq. 7]\n*identically*, not approximately: $\\bar f = (\\theta_A + 2\\theta_{AB} +\n\\theta_B)/4 = \\overline{\\bar p^2 + (1 - \\bar p)^2}$ under A2.\n\n**That is gene diversity of the notional merged pool, and it is not the\nheterozygosity of the product.** The realised F1 heterozygosity is\n$2\\,GD_{WI\\text{-}hyb}$ -- exactly, by the self-coancestry identity of\nassumption A2 -- and on the full factorial it equals $GD_T + GD_{BS}$, the\nbetween-pool component counted twice (@sec-heterosis-identity). The difference\nbetween the two quantities is therefore $GD_{BS}$, which the $F_{hom}$ lens does\nnot carry, and which moves with the selection:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(31)\nsels <- list(random     = sample.int(ctx$N, 60),\n             max_div    = sel_greedy(ctx, 60, w = 0),\n             balanced   = sel_greedy(ctx, 60, w = 1),\n             truncation = sel_truncation(ctx, 60))\ntwo_levels <- t(sapply(sels, function(i) {\n  gp <- gd_partition(i, ctx)\n  fm <- freq_metrics(i, ctx)\n  c(He_merged = fm[[\"He\"]], GD_T = gp[[\"GD_T\"]], F_hom = fm[[\"F_hom\"]],\n    GD_BS = gp[[\"GD_BS\"]], F1_het = mean(ctx$X[i, ] == 0.5),\n    two_GD_WI_hyb = 2 * gp[[\"GD_WI_hyb\"]],\n    GD_T_plus_BS = gp[[\"GD_T\"]] + gp[[\"GD_BS\"]])\n}))\nstopifnot(isTRUE(all.equal(two_levels[, \"He_merged\"], two_levels[, \"GD_T\"])),\n          isTRUE(all.equal(two_levels[, \"F1_het\"], two_levels[, \"two_GD_WI_hyb\"])))\nfmt(as.data.frame(two_levels), 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|           | He_merged|   GD_T|   F_hom|  GD_BS| F1_het| two_GD_WI_hyb| GD_T_plus_BS|\n|:----------|---------:|------:|-------:|------:|------:|-------------:|------------:|\n|random     |    0.3257| 0.3257|  0.0115| 0.0355| 0.3607|        0.3607|       0.3612|\n|max_div    |    0.3302| 0.3302| -0.0113| 0.0361| 0.3707|        0.3707|       0.3664|\n|balanced   |    0.3124| 0.3124|  0.0426| 0.0524| 0.3646|        0.3646|       0.3648|\n|truncation |    0.3124| 0.3124|  0.0426| 0.0524| 0.3646|        0.3646|       0.3648|\n\n</div>\n:::\n:::\n\n\nTwo identities hold to machine precision in that table and the `stopifnot()`\nenforces both on every render: $He = GD_T$, and the realised F1 heterozygosity\nequals $2\\,GD_{WI\\text{-}hyb}$. The third comparison is *not* an identity on a\nselected subset: $GD_T + GD_{BS}$ departs from the realised heterozygosity by at\nmost 0.0043\nacross these four rows, because $GD_T$ and $GD_{BS}$ are computed from line-usage\nweights -- what a random re-pairing of the selected parents would give -- while\n$GD_{WI\\text{-}hyb}$ scores the pairs actually chosen (@sec-heterosis states the\nsame limit from the other side).\n\nNow read the ranking. Truncation has the **highest** $F_{hom}$,\n0.0426 against\n0.0115 for the random draw, which on the usual\nreading is \"most heterozygosity lost\". Yet its hybrids are *more* heterozygous\nthan the random draw's:\n0.3646 against\n0.3607. The two readings are not in conflict\nbecause they are two quantities: truncation concentrated usage inside the pools\n(@sec-era-step6 measures that) and so lost merged-pool gene diversity, while the\n$A \\times B$ pairs it kept happen to be more divergent --\n$GD_{BS}$ = 0.0524 against\n0.0355. Reported alone, $F_{hom}$ would have\ncalled that plan the worst of the four for the very quantity -- product\nheterozygosity -- on which it beats the random draw.\n\nWithin a heterotic pool under reciprocal recurrent selection, $F_{hom}$ on the\n*pool's* own frequencies is still the right lens for one thing, and that one\nthing is narrower than it is usually stated to be. It is the **segregating\ncrossing block**, which is not inbred and in which inbreeding depression is\ntherefore expressed:\n$ID = 2F\\sum_k d_k p_k q_k$ [@falconer1996, Ch. 14], with $d_k$ the dominance\ndeviation at locus $k$, $p_k$ and $q_k = 1 - p_k$ the pool's current\nfrequencies, and $F \\in [0,1]$ the block's inbreeding coefficient relative to\nrandom mating at those same *current* frequencies -- which is **not** the $F_t$\nof this chapter's two lenses, measured against the frozen base $p_0$, and the\ntwo must not be substituted for one another. @sec-heterosis-id verifies that\nquantity against `heterosis_partition()`'s shared term. It is built from the\nsame per-locus product $p_k q_k$ that $F_{hom}$ aggregates -- but weighted by\n$d_k$, which $F_{hom}$ does not carry, so $F_{hom}$ locates the erosion and\ndoes not price it.\n\nIt does **not** anticipate the per-se value of the inbred lines themselves.\nUnder A2 a line has no heterozygous locus, so its dominance contribution is\nexactly zero whatever the pool's frequencies are -- @sec-heterosis-id measures\nthat exact zero -- and a fully homozygous genotype's value is therefore the\nadditive sum $\\sum_k a_k (2x_{ik} - 1)$ alone, the genotypic-value model of\n@sec-heterosis with $x_{ik} \\in \\{0, 1\\}$ at every locus and $a_k$ the per-locus\nadditive effect. Its pool mean moves with the frequencies in whichever direction\nthey move, so there is no directional decline there for $F_{hom}$ to anticipate. It also says nothing about between-pool\ndivergence (@sec-heterosis). Computed\ninstead on the homozygosity of individual inbred parents it is 1 by construction\n-- assumption A2 -- and is **useless for management**. The mating system of the\nspecies does not rescue that: an inbred maize line is as fixed as an inbred wheat\nline. What distinguishes the hybrid programme is that the pool of lines can be\nintermated, so the pool has a frequency vector worth managing even though none of\nits members does.\n\n### `F_drift`, drift-based\n\n$$F_{drift} = \\frac{1}{N_{SNP}}\\sum_k \\frac{(p_{t,k} - p_{0,k})^2}{p_{0,k}(1 - p_{0,k})}$$\n\nwith the same symbols [@meuwissen2020].\n\n**Never negative.** It has the algebraic form of the standardised-variance\ndefinition of $F_{ST}$ -- a variance of allele frequencies divided by\n$p_0(1-p_0)$, the form @wright1951 introduced and @holsinger2009 separate from\nthe several other quantities that carry the same name -- but applied to *one\npopulation through time* rather than to a set of populations in space. That is\nan analogy of form, not an identity: nothing here is a between-subpopulation\nvariance, and the chapter's own $F_{ST}$ column (@sec-era-step6) is the Nei\n$G_{ST}$ of `gd_partition()`, a different statistic on a different partition.\n$F_{drift}$ is exactly the quantity constrained when `G_VR2` goes into the\noptimiser.\n\nIt protects against random change in phenotypic value for traits **outside** the\nselection objective, against rare deleterious recessives rising to dangerous\nfrequencies, and against irreversible loss of rare alleles.\n\n**It must not be read as a measure of *this programme's* selection intensity,\neven though @meuwissen2020 offer exactly that reading for a locus under\ndirectional selection.** They call $\\delta p^2/[p_0(1-p_0)]$ \"an approximation\nto the squared total intensity ($i^2$) applied to the marker\" (citing Liu &\nWoolliams 2010 for the underlying non-linearity), and where the only thing\nmoving frequencies is truncation selection on a trait, that reading is theirs\nto make. But $F_{drift}$ is accumulated over **every** source of displacement a\nscheme has -- selection, pure drift, and a diversity constraint that pushes\nfrequencies on its own -- and the three are not separable from the statistic\nalone. @sec-era-step4 runs a crossing block with **no selection of any kind**\nand $F_{drift}$ climbs over twelve cycles to a value the step reports, which\nunder an unconditional intensity reading would be a large intensity applied by\nnothing; @sec-era-step2's `max_div` plan moves $F_{drift}$ by minimising\ncoancestry, not by selecting on any trait. Even where selection is the only\ndriver, the displacement is not a function of frequency alone: it depends on\nthe average effect of a gene substitution at that locus, $a + d\\,(q - p)$\n[@falconer1996, Ch. 7] -- classically written $\\alpha$, which in this book is\nthe diversity-loss statistic instead (@sec-heterosis says the same) -- and on\nthe phenotypic standard deviation of the trait under selection, neither of\nwhich appears anywhere in $F_{drift}$. So an intensity read off `F_drift` alone,\nwith no independent knowledge of what moved it, cannot be trusted, and this\nchapter does not attempt one. What constraining `F_drift` does constrain is the\nsquared *displacement* of the genome from its base, whatever moved it.\n\nA programme running six cycles of genomic selection with a VanRaden\n$\\mathbf{G}$ and reporting $\\Delta F \\approx 1\\%$ has reported\n$\\Delta F_{drift}$ on the training panel. Quantitative disease-resistance loci\nnot yet prioritised may have hitch-hiked to extreme frequencies alongside yield\nQTL, and none of that appears in the reported metric.\n\n## The classical equivalence, and the covariance that destroys it\n\nUnder purely random drift, with $E[\\delta p_t \\mid p_0] = 0$ for every $p_0$,\n\n$$\\frac{\\mathrm{var}(p_{t,k})}{p_0(1-p_0)} = 1 - \\frac{H_t}{H_0}\n  \\;\\;\\Longrightarrow\\;\\; F_{drift} = F_{hom}.$$\n\nThe paper's central result quantifies the departure:\n\n$$F_{hom} - F_{drift} \\;=\\; 2\\,\\mathrm{cov}\\!\\left(\n  \\frac{\\delta p_{t,k}}{\\sqrt{p_{0,k}(1-p_{0,k})}},\\;\n  \\frac{p_{0,k} - 1/2}{\\sqrt{p_{0,k}(1-p_{0,k})}}\\right)$$\n\n[@meuwissen2020, their Eq. 3], where $\\delta p_{t,k} = p_{t,k} - p_{0,k}$ and\nthe covariance is taken over markers with divisor $N_{SNP}$ -- which is why\n`freq_metrics()` computes it as `2 * mean(x * y)` and not with `cov()`. The two\ndiffer for two independent reasons: `stats::cov()` divides by $N_{SNP} - 1$,\nand $\\overline{xy} = \\mathrm{cov}_{N}(x, y) + \\bar x\\,\\bar y$, so the product\nterm vanishes only if *one of the two means* is zero -- either will do, and\nneither is zero here.\n\nIn words: **if the direction of frequency change is correlated with the starting\nfrequency, the two measures diverge.** The non-obvious part is that this\ncovariance is induced by the *diversity management itself*, not by directional\nselection -- @meuwissen2020 demonstrate this by running the scheme with random\nGEBVs, and the divergence persists.\n\n### Verifying the identity\n\n`freq_metrics()` returns all three quantities in one marker sweep. The identity\nis asserted in `tests/testthat/test-lenses.R`; here it is on live data:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(31)\nidx <- sample.int(ctx$N, 60)\nfm <- freq_metrics(idx, ctx)\nfmt(fm[c(\"F_hom\", \"F_drift\", \"cov_diag\")], 6)\n#>    F_hom  F_drift cov_diag \n#> 0.011458 0.005192 0.006267\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstopifnot(isTRUE(all.equal(fm[[\"cov_diag\"]], fm[[\"F_hom\"]] - fm[[\"F_drift\"]])))\n# The two standardised marker vectors of Eq. 3, on the markers polymorphic in\n# the base, so `2 * mean(x * y)` can be put next to `2 * cov(x, y)`.\nkeep <- ctx$p0 > 1e-6 & ctx$p0 < 1 - 1e-6\nsdv  <- sqrt(ctx$p0[keep] * (1 - ctx$p0[keep]))\nx    <- (colMeans(ctx$X[idx, keep, drop = FALSE]) - ctx$p0[keep]) / sdv\ny    <- (ctx$p0[keep] - 0.5) / sdv\nstopifnot(isTRUE(all.equal(2 * mean(x * y), unname(fm[[\"cov_diag\"]]))))\nc(F_hom_minus_F_drift = unname(fm[[\"F_hom\"]] - fm[[\"F_drift\"]]),\n  cov_diag            = unname(fm[[\"cov_diag\"]]),\n  residual            = unname(fm[[\"cov_diag\"]] - (fm[[\"F_hom\"]] - fm[[\"F_drift\"]])),\n  mean_x              = mean(x),\n  mean_y              = mean(y),\n  two_times_R_cov     = 2 * stats::cov(x, y))\n#> F_hom_minus_F_drift            cov_diag            residual              mean_x \n#>        6.266505e-03        6.266505e-03        8.673617e-18       -7.725594e-04 \n#>              mean_y     two_times_R_cov \n#>       -1.005046e-02        6.254209e-03\n```\n:::\n\n\nExact to machine precision, and the two `stopifnot()`s mean this page cannot\nrender if it stops being. The last three entries are the point of the previous\nparagraph: neither marker-wise mean is zero, so `2 * cov(x, y)` returns\n0.006254 where the quantity Eq. 3 defines is\n0.006267. And when the selection *is* the base,\nboth lenses must read zero:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfmt(freq_metrics(seq_len(ctx$N), ctx)[c(\"F_hom\", \"F_drift\", \"cov_diag\")], 12)\n#>    F_hom  F_drift cov_diag \n#>        0        0        0\n```\n:::\n\n\n### Why each matrix generates a sign\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: The sign of the bias is a property of the matrix, not of the data. Mechanisms as set out by Meuwissen et al. (2020), their Discussion and Supplementary Information 1; the di/dp expression in the last row is theirs, after Liu and Woolliams (2010).\n\n|Matrix |Covariance           |Mechanism                                                                                                                                                                 |\n|:------|:--------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|G_VR2  |positive             |the constraint penalises delta-p^2, so moving an allele to the *far* extreme costs more than to the near one; the optimiser pushes rare alleles to 0 and common ones to 1 |\n|G_0.5  |negative             |frequencies are measured as deviations from 0.5, so the optimiser buys 'diversity' by pushing everything to intermediate frequencies                                      |\n|G_VR1  |positive, attenuated |G_VR2 reweighted by 2p0(1-p0), giving more weight to already-intermediate loci and less room at the extremes                                                              |\n|G_i(p) |negative             |uses accumulated intensity instead of delta-p^2; since di/dp = [p(1-p)]^-1/2, moves toward the extremes get more expensive                                                |\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Your MAF spectrum decides how bad this is\n\n@meuwissen2020 state this as an expectation rather than as a measured\ncomparison: \"the covariance generated is expected to be larger for WGS data\nwhere allele frequencies are extreme with typical MAF close to 0, than for SNP\n(chip) panels where allele frequencies are generally closer to 1/2\" (their\nsecond Conclusion bullet), having observed that the strength of the covariance\n\"depends on the distribution of $(p_0 - \\tfrac12)$\" (their Discussion). Their own\nsimulation used four panels, all random samples of the same whole-genome\nsequence data (an SNP-BLUP panel, a neutral panel, a QTL panel and a second\nmanagement panel) -- none a SNP chip -- so the comparison across a WGS panel\nand a chip panel is an inference from the algebra of Eq. 3 and not a result of\ntheir experiment either.\n\nThe algebra can be made a number, which is worth doing because it decides whether\n`G_VR2` is usable. Apply one deterministic management rule -- move every frequency\n5% of the way toward 0.5, the caricature of a heterozygosity-maximising\nconstraint used again in @sec-era-step4 -- to a sequence-like panel whose folded\nsite-frequency spectrum has density proportional to $1/[p(1-p)]$, and then to\nMAF-filtered subsets of the *same* draw:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(21)\n# Folded site-frequency spectrum with density proportional to 1/[p(1-p)] on\n# [1e-3, 1 - 1e-3]: the logit of p is uniform. One draw, filtered four ways.\np_seq <- plogis(runif(2e5, qlogis(1e-3), qlogis(1 - 1e-3)))\nmaf_row <- function(floor, pull = 0.05) {\n  p0 <- p_seq[pmin(p_seq, 1 - p_seq) >= floor]\n  p1 <- p0 + pull * (0.5 - p0)                 # the rule, applied exactly\n  s2 <- p0 * (1 - p0)\n  c(maf_floor = floor, markers = length(p0),\n    W = mean((p0 - 0.5)^2 / s2),               # the panel's own weight\n    F_hom = 1 - mean(p1 * (1 - p1) / s2),\n    F_drift = mean((p1 - p0)^2 / s2),\n    cov_diag = 2 * mean((p0 - 0.5) * (p1 - p0) / s2))\n}\nmafw <- as.data.frame(t(sapply(c(0.001, 0.01, 0.05, 0.20), maf_row)))\n# Under this rule all three lenses are multiples of one panel statistic, W.\nstopifnot(isTRUE(all.equal(mafw$F_drift, 0.05^2 * mafw$W)),\n          isTRUE(all.equal(mafw$cov_diag, -2 * 0.05 * mafw$W)))\nkeep0  <- ctx$p0 > 1e-6 & ctx$p0 < 1 - 1e-6        # as freq_metrics() drops them\nW_book <- mean((ctx$p0[keep0] - 0.5)^2 / (ctx$p0[keep0] * (1 - ctx$p0[keep0])))\nfmt(mafw, 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| maf_floor| markers|       W|   F_hom| F_drift| cov_diag|\n|---------:|-------:|-------:|-------:|-------:|--------:|\n|     0.001|  200000| 35.7687| -3.4874|  0.0894|  -3.5769|\n|     0.010|  132755|  4.8542| -0.4733|  0.0121|  -0.4854|\n|     0.050|   85382|  1.1056| -0.1078|  0.0028|  -0.1106|\n|     0.200|   40109|  0.1761| -0.0172|  0.0004|  -0.0176|\n\n</div>\n:::\n:::\n\n\nUnder a rule of this form $\\delta p = c\\,(0.5 - p_0)$ the algebra is exact:\n$F_{drift} = c^2 W$ and `cov_diag` $= -2cW$ with\n$W = \\overline{(p_0 - 0.5)^2 / [p_0(1-p_0)]}$, the panel statistic the\n`stopifnot()` above verifies. Everything about the panel enters through $W$, and\n$W$ is 32.4 times larger at a MAF floor of 0.001\nthan at 0.05 on the same draw: `cov_diag` moves from\n-3.577 to -0.111 for the same 5%\npull. For reference, this book's own hybrid panel has $W =$ 1.27\nover the 1934 markers polymorphic in the base, which sits at the\nchip-like end of that table -- a consequence of the $U(0.05, 0.95)$ ancestral\ndraw of `simulate_lines()`, not of anything biological.\n\n**Translated to plants, as a stated expectation and not as a measurement on real\ngermplasm:** GBS or skim-seq retaining the full spectrum puts a programme at the\nhigh-$W$ end; a 20-50k chip filtered to MAF > 0.05 puts it at the low-$W$ end. The\nrule above is a caricature, not an optimiser, so the *ratio* between panels is\nthe transferable part and the absolute values are not.\n:::\n\n## The other matrices, briefly\n\n**`F_IBD` via `G_LA`.** Instead of assuming a 50/50 transmission probability for\neach parental allele (as the pedigree matrix $\\mathbf{A}$ does), linkage\nanalysis over the markers infers which parental haplotype was actually\ntransmitted along the chromosome. It requires pedigree **and** markers. It\nmeasures IBD relative to a base explicitly defined as unrelated and\nnon-inbred, so frequency change is determined by the base population rather\nthan by linkage disequilibrium generated during selection -- and the\nproblematic covariance disappears. It was the **only scheme tested that met\nboth the $\\Delta F_{hom}$ and $\\Delta F_{drift}$ targets**, on the managed panel\nand at unmonitored neutral loci. On gain it was not the highest in absolute\nterms; what @meuwissen2020 report is that at the *same* averaged inbreeding --\ninterpolating each scheme's gain to the mean of $F_{hom}$ and $F_{drift}$ --\n`G_LA` beat $\\mathbf{A}$ in 65 of 100 replicates and `G_ROH` in 62 of 100\n(their Genetic Gain section).\n\nFor a hybrid programme this is the point of greatest friction, and also the one\nwhere the news is best. In biparental populations and backcross families\n`G_LA` is natural and cheap -- phase is known and the number of meioses since\nthe base is small. In a maize recurrent-selection population with a complete\nrecycling pedigree, which commercial programmes generally have because every DH\nline records its F1 parents, it is feasible. In a germplasm panel *without*\npedigree it is inapplicable, and the honest alternative is segment-based IBD.\n\n**`F_ROH`.** A run of homozygosity is an uninterrupted stretch of homozygous\nmarkers; the logic is that many consecutive markers are unlikely to be IBS by\nchance, so the stretch is probably IBD. The fundamental ambiguity is that\n`F_ROH` is IBD when runs are **long** (recent inbreeding) and homozygosity when\nthey are **short** (ancient inbreeding, accumulated IBS). The minimum-length\nthreshold is therefore a knob that selects the *age* of inbreeding you are\nmeasuring, and there is no well-defined reference base.\n\nEmpirically, `G_ROH` behaved more like `G_0.5` than like an IBD measure. It also\nis **not guaranteed positive semi-definite** -- its elements are computed\npairwise -- and required substantial diagonal additions for inversion, which\nmade it diagonally dominant and artificially inflated the number of parents\nselected.\n\nIn an inbred parent line the entire genome is one ROH and $F_{ROH} \\approx 1$:\nthe metric saturates for exactly the reason assumption A2 makes every\nindividual-level coefficient useless. Applied instead to the *hybrids*, or to\nthe segregating crossing block from which DH lines are induced, it is useful for\ndiagnosing erosion of an elite pool. For *management* inside an optimiser, check\npositive definiteness carefully -- @sec-era-step7 shows the check.\n\n### Side by side\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Seven matrices in the same optimiser (Meuwissen et al. 2020, their Tables 2 and 3, Figure 5 and Discussion). The Behaviour column is qualitative and no number from either panel is transcribed in this table; where a rate is invoked (the reference-results table below), it is always the *unmonitored neutral* panel N. The one exception is G_VR2's 'only on the managed panel', a paraphrase of their Discussion that reports a Panel M outcome without a Panel M number appearing anywhere in this chapter. Class is the lens the matrix is *computed* from, which is why G_ROH sits with homozygosity -- the Hybrid row of the first table is the same matrix labelled by its intended *interpretation*.\n\n|Matrix |Class                     |Behaviour in the optimiser                                                                      |\n|:------|:-------------------------|:-----------------------------------------------------------------------------------------------|\n|A      |IBD (expectation)         |high gain, but exceeded targets by ~40% by not accounting for within-family LD                  |\n|G_VR2  |drift                     |meets the drift target *only on the managed panel*; F_hom runs away                             |\n|G_VR1  |drift                     |reweighted version; smaller bias, smaller gain                                                  |\n|G_0.5  |homozygosity              |misses the drift target by the widest margin of the eight schemes; loses genetic variance early |\n|G_i(p) |drift                     |inverts the sign of the bias; constraint only indirectly tied to F                              |\n|G_LA   |IBD                       |the only one meeting both targets; highest gain at equal averaged inbreeding                    |\n|G_ROH  |homozygosity, read as IBD |high gain, uncontrolled drift, numerical problems                                               |\n\n\n:::\n:::\n\n\n## Reference results\n\nTarget $\\Delta F = 0.005$ per generation ($N_e = 100$). Values at the\n**unmonitored neutral loci** (their Panel N), generation 20, as reported by\n@meuwissen2020. Four columns are transcribed and one is derived:\n\n- `dF_hom`, `dF_drift` and `gap` are the three Panel N columns of their Table 2.\n  `gap` is the *level* $F_{hom} - F_{drift}$ reached in generation 20, not a\n  rate and not a difference of the two rate columns; it is `cov_diag` of Eq. 3\n  accumulated over the 20 generations. Their reported standard errors are\n  $< 2.5 \\times 10^{-5}$ on the rates and $< 2.2 \\times 10^{-4}$ on `gap`.\n- `gain` is their Table 3: cumulative genetic gain after 20 generations,\n  expressed in units of the **initial genetic standard deviation**, standard\n  errors $\\le 0.004$.\n- `gain_per_dF` is computed here, not transcribed, and is **not** the device\n  @meuwissen2020 use: their own interpolation (Genetic Gain section, their\n  Figure 5) compares gains at a common generation-20 *level* of averaged\n  inbreeding, $(F_{hom} + F_{drift})/2$ from their Table 3 -- a stock -- not at\n  a common mean of the two *rate* columns used here. `gain_per_dF` is offered\n  only as a same-chapter summary of the reference table above, and reading 1\n  below states explicitly which ordering it does and does not support.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Both rate targets are 0.005. Only G_LA meets both. gain_per_dF is derived in the chunk, the other columns are transcribed from their Tables 2 and 3.\n\n|Scheme      |Class        | dF_hom| dF_drift|    gap|  gain| gain_per_dF|\n|:-----------|:------------|------:|--------:|------:|-----:|-----------:|\n|G_VR2(M,M)  |drift        | 0.0103|   0.0068|  0.054| 7.124|         833|\n|G_VR2(M,D)  |drift        | 0.0101|   0.0068|  0.050| 7.107|         841|\n|G_VR1(M,M)  |drift        | 0.0080|   0.0069|  0.021| 6.680|         897|\n|G_i(p)(M,M) |drift        | 0.0065|   0.0077| -0.031| 7.111|        1002|\n|G_0.5(M,M)  |homozygosity | 0.0073|   0.0176| -0.170| 6.734|         541|\n|G_ROH(M,M)  |homozygosity | 0.0054|   0.0088| -0.070| 9.099|        1282|\n|G_LA(M,M)   |IBD          | 0.0043|   0.0049| -0.010| 7.188|        1563|\n|A(M,~)      |IBD          | 0.0070|   0.0084| -0.021| 9.890|        1284|\n\n\n:::\n:::\n\n\nFour readings:\n\n1. **No IBS scheme met both targets.** `G_LA` came closest: within about 2% of\n   the 0.005 target on `dF_drift` on both panels M and N (their own figure for\n   that lens), but 14% below target on `dF_hom` (0.0043 against 0.005) -- the\n   2% is a drift-lens precision, not a joint one. It also has\n   the largest `gain_per_dF`, 1563 against\n   1284 for $\\mathbf{A}$ and\n   1282 for `G_ROH` -- but\n   that ordering is not robust to the denominator: against `dF_hom` alone\n   `G_ROH` is marginally ahead\n   (1685\n   against\n   1672).\n   The claim that survives is the replicate-level one in reading 4, not a ratio\n   of table means.\n2. Pedigree $\\mathbf{A}$ gave the highest absolute gain but overshot by ~40% --\n   neutral loci hitch-hiking with QTL through within-family LD, which the\n   pedigree expectation of IBD cannot capture.\n3. Using a separate panel for management instead of the GEBV panel changed gain\n   by **less than 0.3%**. Not worth the complexity as a *gain* measure; it is\n   still worth it as an *audit* measure, which is a different use and is the\n   subject of @sec-era-step5 below.\n4. At equal mean inbreeding, `G_LA` beat $\\mathbf{A}$ in 65 of 100 replicates\n   and `G_ROH` in 62 of 100.\n\nThose are animal-breeding numbers under the assumptions of\n@sec-era-transposition, and none of them is reproduced here. What follows is.\n\n## The monitoring protocol {#sec-era-protocol}\n\nSeven steps, in the order a cycle report is assembled. Each one names the\nfunction to call, the quantity to check, and what a failure looks like.\n\n### Step 1 -- Freeze $p_0$ at the founding cycle {#sec-era-step1}\n\nBoth lenses are ratios to a base, so the base is the first thing a cycle report\nhas to pin down. In this book it is `ctx$p0`, the candidate-pool allele\nfrequencies, set once in `build_ctx()` and carried forward unchanged by\n`run_cycles()`.\n\nAt the hybrid level the base is not a free choice: on the full factorial it is\nthe average of the two pool bases, exactly.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstopifnot(isTRUE(all.equal(ctx$p0, as.vector((P0[\"A\", ] + P0[\"B\", ]) / 2))))\n# Unequal pool sizes, still a complete factorial: each pool-A line appears in\n# n_pool_B hybrids and each pool-B line in n_pool_A, so the internal weight\n# stays uniform within each pool and the identity is untouched.\ncfg_u <- utils::modifyList(book_cfg, list(n_pool_A = 10, n_pool_B = 40))\nctx_u <- simulate_data(cfg_u)\nPu    <- pool_freqs(simulate_lines(cfg_u) / 2,\n                    rep(c(\"A\", \"B\"), c(cfg_u$n_pool_A, cfg_u$n_pool_B)))\n# A balanced INCOMPLETE factorial -- not the full n_A*n_B hybrids, but each\n# line still used equally often within its own pool (a cyclic 1-to-3 design,\n# the shape of a real NCII): the identity does not need completeness.\nk <- 3\nidx_bal <- unlist(lapply(seq_len(book_cfg$n_pool_A), function(a) {\n  bpart <- ((a - 1 + 0:(k - 1)) %% book_cfg$n_pool_B) + 1\n  which(ctx$ped$a == a & ctx$ped$b %in% (bpart + book_cfg$n_pool_A))\n}))\np_bal <- colMeans(ctx$X[idx_bal, , drop = FALSE])\n# An UNbalanced candidate set with concentrated line usage: it is not.\np_sub <- colMeans(ctx$X[sel_truncation(ctx, 60), , drop = FALSE])\nc(complete_balanced     = max(abs(ctx$p0 - (P0[\"A\", ] + P0[\"B\", ]) / 2)),\n  complete_unequal_pools = max(abs(ctx_u$p0 - (Pu[\"A\", ] + Pu[\"B\", ]) / 2)),\n  incomplete_balanced   = max(abs(p_bal - (P0[\"A\", ] + P0[\"B\", ]) / 2)),\n  truncation_subset     = max(abs(p_sub - (P0[\"A\", ] + P0[\"B\", ]) / 2)))\n#>      complete_balanced complete_unequal_pools    incomplete_balanced \n#>           1.110223e-16           1.110223e-16           1.110223e-16 \n#>      truncation_subset \n#>           3.133333e-01\n```\n:::\n\n\nEach pool-A line appears in 25 hybrids and each pool-B line\nin 25, so a column mean over the factorial is\n$(p_A + p_B)/2$ with no weighting left over. Two consequences a breeder should\nread off this identity. First, freezing $p_0$ at the hybrid level freezes both\npool bases *jointly*, so the hybrid-level lenses cannot attribute erosion to one\npool -- that is @sec-era-step6's job. Second -- and this is the part that is\neasy to state wrongly -- what the identity requires is **uniform line usage\nwithin each pool**, not completeness of the factorial as such. With\n10 lines in one pool against 40 in the other,\nstill complete, the identity holds to\n1.1e-16. It holds\njust as exactly (1.1e-16)\non a **balanced but incomplete** factorial -- 75 of the\n625 possible hybrids, each line used\nexactly 3 times, the shape of a real NCII design -- because each pool's\nlines are still used equally often *within* that pool. What re-weights the two\npools inside the base is unequal **line usage**, which a balanced partial\nfactorial does not have and a selected subset typically does: the column means\nof the 60-hybrid truncation set depart from $(p_A + p_B)/2$ by up to\n0.313 on a single marker,\nbecause truncation concentrates hybrids on a few high-value lines in each pool.\nA base computed on a set with unequal line usage is therefore a different\nbase -- which is the failure mode below, and not a property of the design\nbeing a factorial or not.\n\nNow the failure mode. `build_ctx()` recomputes `p0 <- colMeans(X)` on every\ncall, so rebuilding the context from the *selected* hybrids each cycle -- which\nis what re-running a `G`-construction function per cycle amounts to -- re-anchors\nthe base on the population you were about to measure:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ni_md   <- sel_greedy(ctx, 60, w = 0)\nXs     <- ctx$X[i_md, , drop = FALSE]\nrebase <- build_ctx(X = Xs, f = molecular_coancestry(Xs), G = NULL,\n                    traits = ctx$traits[i_md, , drop = FALSE],\n                    ped = ctx$ped[i_md, ], n_lines = ctx$n_lines,\n                    pool = ctx$pool, fL = ctx$fL, cfg = NULL)\nfmt(rbind(frozen_base   = freq_metrics(i_md, ctx)[c(\"F_hom\", \"F_drift\", \"cov_diag\")],\n          rebased       = freq_metrics(seq_along(i_md), rebase)[c(\"F_hom\", \"F_drift\", \"cov_diag\")]), 6)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|            |     F_hom|  F_drift|  cov_diag|\n|:-----------|---------:|--------:|---------:|\n|frozen_base | -0.011338| 0.006019| -0.017357|\n|rebased     |  0.000000| 0.000000|  0.000000|\n\n</div>\n:::\n:::\n\n\nNot attenuated -- **identically zero, both lenses**. A rebased report is not a\nconservative report or a noisy one; it is a report that cannot detect erosion at\nall, and it will look clean for as many cycles as you run it.\n\nThe check has to be on the base itself, and it has to be the right check. If the\nbase is stored per cycle, comparing each cycle's vector with cycle 0's catches\nthe failure; collapsing the whole history into a `range()` does not, because\n`range()` discards the cycle dimension and returns the marker-wise spread of\n$p_0$, the same number whether the base moved or not -- here\n1, the whole unit interval, because\n66 of the 2000 markers are fixed\nin the candidate pool:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchk <- function(h) {\n  data.frame(\n    all_identical_to_cycle0 = all(vapply(h, identical, logical(1), h[[1]])),\n    max_abs_deviation       = max(vapply(h, function(p) max(abs(p - h[[1]])), 0)),\n    collapsed_range         = diff(range(unlist(h))))\n}\nfmt(rbind(frozen  = chk(list(ctx$p0, ctx$p0, ctx$p0)),\n          rebased = chk(list(ctx$p0, ctx$p0, rebase$p0))), 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|        |all_identical_to_cycle0 | max_abs_deviation| collapsed_range|\n|:-------|:-----------------------|-----------------:|---------------:|\n|frozen  |TRUE                    |            0.0000|               1|\n|rebased |FALSE                   |            0.1233|               1|\n\n</div>\n:::\n:::\n\n\nThe first two columns separate the two histories; the third is the same number\nin both rows, which is the whole point.\n\n**Call.** `build_ctx()` once at cycle 0; pass `p0` forward (`run_cycles()` does\nthis through its internal `cycle_ctx()`).\n**Check.** `identical(ctx$p0, p0_cycle0)` at every cycle -- one `TRUE`, with no\ntolerance. With a stored history,\n`max(vapply(p0_history, function(p) max(abs(p - p0_history[[1]])), 0))`, which\nmust be exactly 0. Never a `range()` over the flattened history.\n**Warning sign.** $F_{drift}$ near zero in a cycle where line usage was visibly\nconcentrated, or an $F_{drift}$ series that does not accumulate across cycles.\n**Threshold.** There is none to tune: the correct value of the base drift is\nexactly zero.\n\n### Step 2 -- Compute both lenses in one marker sweep {#sec-era-step2}\n\n`freq_metrics()` is the single sweep: it computes $He$, `alleles_lost`,\n$F_{hom}$, $F_{drift}$, `cov_diag`, `cor_dp_p0` and `rare_retained` from one\n`colMeans(X[idx, ])`. Anything else needing the selected frequencies belongs\ninside it, not in a second function with its own sweep.\n\nThe pure max-diversity greedy is the `G_0.5` scheme in miniature: it constrains\nmolecular coancestry and nothing else. Its signature has to be read against a\n**resampled** baseline rather than against one random draw, for the reason the\nnumbers below make explicit. The baseline is the package's own\n`null_distribution()`, 1000 resampled subsets of the same size, and the z-scores\ncome from `discriminatory_power()`, so the comparison is the same machinery\nevery scenario in @sec-case-study is reported through:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# `sels` is the set of four selections built in @sec-era-fhom.\ncols   <- c(\"He\", \"F_hom\", \"F_drift\", \"cov_diag\", \"rare_retained\")\nnull60 <- null_distribution(ctx, 60, B = 2000, B_full = 1000, seed = 7)\npanel  <- t(sapply(sels, freq_metrics, ctx = ctx))[, cols]\nfmt(rbind(null_mean = colMeans(null60$full[, cols]),\n          null_sd   = apply(null60$full[, cols], 2, stats::sd),\n          panel), 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|           |     He|   F_hom| F_drift| cov_diag| rare_retained|\n|:----------|------:|-------:|-------:|--------:|-------------:|\n|null_mean  | 0.3259|  0.0069|  0.0070|  -0.0001|        0.9583|\n|null_sd    | 0.0008|  0.0038|  0.0014|   0.0035|        0.0229|\n|random     | 0.3257|  0.0115|  0.0052|   0.0063|        0.9481|\n|max_div    | 0.3302| -0.0113|  0.0060|  -0.0174|        0.9481|\n|balanced   | 0.3124|  0.0426|  0.0558|  -0.0131|        0.7338|\n|truncation | 0.3124|  0.0426|  0.0558|  -0.0131|        0.7338|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nz <- discriminatory_power(evaluate(sels, ctx, null60$gd_ref), null60)[, cols]\nfmt(as.data.frame(z), 2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|           |     He| F_hom| F_drift| cov_diag| rare_retained|\n|:----------|------:|-----:|-------:|--------:|-------------:|\n|random     |  -0.25|  1.20|   -1.26|     1.80|         -0.45|\n|max_div    |   5.58| -4.79|   -0.67|    -4.92|         -0.45|\n|balanced   | -17.06|  9.41|   35.08|    -3.72|         -9.81|\n|truncation | -17.06|  9.41|   35.08|    -3.72|         -9.81|\n\n</div>\n:::\n:::\n\n\nResult. The max-diversity plan drives $F_{hom}$ negative,\n-0.0113, which is\n4.8 s.d. below a null mean of\n0.0069: the selection is more heterozygous on\nthe monitored panel than the frozen base. Its `cov_diag` is\n-0.0174, 4.9\ns.d. below a null centred on\n-0.0001. Its $F_{drift}$, however,\nis 0.006 against a null mean of\n0.007: a z of\n-0.67, and\n76%\nof the 1000 resampled subsets pay **more** drift than it does. Truncation is the\nrow with the drift bill: $F_{drift}$ = 0.0558,\nz = 35.1.\n\nThis is where one draw would have misled. The `random` row is a single subset,\nand its $F_{drift}$ sits 1.3 s.d. below the\nresampled mean -- *further* below it than `max_div` is -- so a two-row\n`random`-versus-`max_div` comparison reports max-diversity as paying more drift\nthan random, which the 1000-subset null says it does not. The failure is not the\nmetric, it is the baseline: with a null s.d. of\n0.0014 on a quantity whose value is\n0.006, no single draw can serve as a control.\n\nInterpretation, and what it does not license. At this scale, on a single\nselection from a fixed candidate set, **minimising** molecular coancestry (the\n`max_div` plan, `w = 0`, which maximises gene diversity `GD = 1 - theta`) buys a\nmeasurable divergence between the two lenses -- the negative covariance that the\n`G_0.5` row of the matrix-sign table predicts -- and **no** measurable drift\nexcess over random sampling. The drift excess @meuwissen2020 report for `G_0.5`\n($\\Delta F_{drift} = 0.0176$ against a 0.005 target) is a 20-generation\n*cumulative* result under recurrent optimal contributions, where each cycle's\nfrequency change compounds on the last; one subset drawn once from one candidate\npool is not that experiment, and the honest way to run it here is the\nmulti-cycle arm of @sec-era-step4, where the same pull toward 0.5 does produce\ndrift at more than twice the neutral rate. What survives at one cycle is the\ncovariance, and a report carrying only $F_{hom}$ would not show it.\n\nOne thing the table quietly says about the *weight* rather than the metric:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nidentical(sort(sel_greedy(ctx, 60, w = 1)), sort(sel_truncation(ctx, 60)))\n#> [1] TRUE\n```\n:::\n\n\nAt this scale `w = 1` is not a compromise between index and coancestry -- it\nreturns the truncation set exactly, because the index is standardised to unit\nvariance (`sd(ctx$index)` = 1) while the spread of\n$\\theta$ across candidate subsets of the same size is\n7.58e-04, the standard deviation of the\n`theta` column over the 2000 cheap-metric resamples of the\nsame null. That is a ratio of\n1319: three orders of\nmagnitude, not two. A linear weight has to be calibrated to that ratio, which\nis why `sel_greedy_budget()` sweeps a *logarithmic* grid of `w` instead of\ntrusting any single value.\n\n**Call.** `freq_metrics(idx, ctx)` per cycle; `metrics_cheap()` if you also need\nthe coancestry block, `metrics_full()` post-hoc for the expensive ones.\n**Check.** Both lenses present in the report, side by side, with the sign of\n$F_{hom}$ preserved (never take an absolute value or clamp at zero).\n**Warning sign.** A single \"inbreeding\" column in the cycle report. If you\ncannot tell which lens it is, it is the one your constraint used, and the other\none is unmeasured.\n**Threshold.** Not the $\\Delta F$ target. Both columns here are *stocks*\naccumulated against the frozen base, and a stock cannot be compared with a rate\n-- @sec-era-step4 opens on exactly that point. Within one cycle the reference is\nthe resampled null in the same table, i.e. the z columns above, read on **both**\nlenses separately and never on their average. The comparison with the\nprogramme's $\\Delta F$ budget requires a trajectory and happens only through the\nregression of @sec-era-step4.\n\n### Step 3 -- Report the covariance, not just the two lenses {#sec-era-step3}\n\n`cov_diag` is the gap between the two lenses, and by Eq. 3 it is not an\napproximation of the gap -- it *is* the gap, which the `stopifnot()` above\nenforces on every render. The operational point is that `cov_diag` is the only\ncolumn that tells you *why* the two lenses disagree, and its sign identifies the\nmechanism from the matrix-sign table above: negative means the management pushed\nfrequencies toward 0.5, positive means it pushed them to the extremes.\n\n**Call.** `freq_metrics(idx, ctx)[[\"cov_diag\"]]`, already computed by step 2 at\nno extra cost; `cor_dp_p0` from the same call is the scale-free version.\n**Check.** `cov_diag == F_hom - F_drift` to machine precision. If it does not,\nthe base and the frequencies were computed on different marker sets.\n**Warning sign.** $|$`cov_diag`$|$ of the same order as the stock it is meant to\nexplain. In the panel of @sec-era-step2 the max-diversity plan reports\n`cov_diag` = -0.0174 against an\n$F_{drift}$ of 0.006: the discrepancy between\nthe two lenses is 2.9\ntimes the quantity being reported.\n**Threshold.** No absolute one, and not the $\\Delta F$ budget -- `cov_diag` is a\nstock like the two lenses it separates. Compare it with $F_{drift}$ in the same\nrow, as just done, and with the resampled null: the `null_sd` row of\n@sec-era-step2's table puts the max-diversity plan\n4.9 s.d. out, which is the statement that\nthe covariance was induced by the management rather than by the sampling.\n\n### Step 4 -- Regress $\\log(1 - F)$ on cycle, and read $R^2$ {#sec-era-step4}\n\nA single cycle's $F$ is a stock and cannot be compared to a rate target. The\nrate comes from the trajectory. Before trusting the regression on a real\nprogramme, calibrate it on a case whose answer is known.\n\nLet $n_{gam}$ be the number of allele copies the pool samples per cycle. Drawing\nthem at random from the previous cycle's frequencies gives\n$\\mathbb{E}[H_t] = H_0\\,(1 - 1/n_{gam})^t$ exactly, so\n$\\Delta F = 1/n_{gam}$ and $N_e = n_{gam}/2$; with $n_{gam} = 2N$ this is the\nidealised population of [@falconer1996, Ch. 3] and $\\Delta F = 1/(2N)$. In a\ntwo-pool programme $n_{gam}$ is not a matter of taste, and the two natural\nregimes differ by a factor of two:\n\n- a **crossing block** of $n$ plants intermated at random passes $2n$ gametes,\n  so $\\Delta F = 1/(2n)$ and $N_e = n$;\n- a pool **re-derived as $n$ doubled-haploid lines** passes only $n$ distinct\n  allele copies, because each DH is homozygous and contributes one allele\n  identity per locus, so $\\Delta F = 1/n$ and $N_e = n/2$. This is literally\n  what `next_pool()` does in @sec-cycles: one Bernoulli draw per locus per new\n  line.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# One heterotic pool, n_gam allele copies sampled per cycle, n_cyc cycles,\n# `reps` independent replicates. `pull` first moves every frequency a fixed\n# fraction toward 0.5: a caricature of a heterozygosity-maximising constraint,\n# not an optimiser.\npool_traj <- function(n_gam, m, n_cyc, pull = 0, reps = 20, seed = 11) {\n  out <- vector(\"list\", reps)\n  for (r in seq_len(reps)) {\n    set.seed(seed + r)\n    p0 <- runif(m, 0.05, 0.95)\n    s2 <- p0 * (1 - p0)\n    p  <- p0\n    rows <- vector(\"list\", n_cyc + 1L)\n    for (t in 0:n_cyc) {\n      rows[[t + 1L]] <- data.frame(\n        rep = r, cycle = t,\n        F_hom    = 1 - mean(p * (1 - p) / s2),\n        F_drift  = mean((p - p0)^2 / s2),\n        cov_diag = 2 * mean((p0 - 0.5) * (p - p0) / s2))\n      p <- rbinom(m, n_gam, p + pull * (0.5 - p)) / n_gam\n    }\n    out[[r]] <- do.call(rbind, rows)\n  }\n  do.call(rbind, out)\n}\n\nper_cycle <- function(tr, n_gam) {\n  a <- aggregate(cbind(F_hom, F_drift, cov_diag) ~ cycle, tr, mean)\n  a$expected <- 1 - (1 - 1 / n_gam)^a$cycle\n  # One s.d. per lens: the two lenses are not equally noisy across replicates,\n  # so a deviation has to be compared with the s.d. of the lens it came from.\n  a$sd_hom   <- aggregate(F_hom ~ cycle, tr, sd)$F_hom\n  a$sd_drift <- aggregate(F_drift ~ cycle, tr, sd)$F_drift\n  a\n}\n\n# dF from the slope, not from its first-order approximation.\ndF_fit <- function(a, col) {\n  d <- a[a$cycle > 0, ]                 # cycle 0 is identically zero by construction\n  f <- lm(log(1 - d[[col]]) ~ cycle, d)\n  b <- coef(f)[[\"cycle\"]]\n  c(dF = 1 - exp(b), Ne = 1 / (2 * (1 - exp(b))), R2 = summary(f)$r.squared)\n}\n\nn_line <- 50\nn_cyc  <- 12\nblock  <- per_cycle(pool_traj(2 * n_line, book_cfg$m, n_cyc), 2 * n_line)\ndh     <- per_cycle(pool_traj(n_line, book_cfg$m, n_cyc), n_line)\nfmt(block, 5)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| cycle|   F_hom| F_drift| cov_diag| expected|  sd_hom| sd_drift|\n|-----:|-------:|-------:|--------:|--------:|-------:|--------:|\n|     0| 0.00000| 0.00000|  0.00000|  0.00000| 0.00000|  0.00000|\n|     1| 0.01014| 0.00992|  0.00022|  0.01000| 0.00466|  0.00046|\n|     2| 0.02032| 0.01971|  0.00061|  0.01990| 0.00554|  0.00065|\n|     3| 0.02978| 0.02963|  0.00015|  0.02970| 0.00643|  0.00099|\n|     4| 0.03787| 0.03898| -0.00111|  0.03940| 0.00772|  0.00089|\n|     5| 0.04759| 0.04874| -0.00116|  0.04901| 0.00764|  0.00112|\n|     6| 0.05676| 0.05802| -0.00126|  0.05852| 0.00852|  0.00142|\n|     7| 0.06557| 0.06784| -0.00227|  0.06793| 0.00878|  0.00179|\n|     8| 0.07405| 0.07722| -0.00317|  0.07726| 0.00918|  0.00205|\n|     9| 0.08414| 0.08667| -0.00253|  0.08648| 0.00961|  0.00293|\n|    10| 0.09459| 0.09600| -0.00141|  0.09562| 0.00995|  0.00289|\n|    11| 0.10342| 0.10503| -0.00161|  0.10466| 0.01029|  0.00284|\n|    12| 0.11166| 0.11411| -0.00246|  0.11362| 0.01160|  0.00310|\n\n</div>\n:::\n:::\n\n\nThe `expected` column is the closed form, not a fit. Both lenses agree with it\nand with each other, in both regimes:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndev <- function(a) max(abs(c(a$F_hom, a$F_drift) - rep(a$expected, 2)))\nfit_n <- rbind(block_F_hom   = dF_fit(block, \"F_hom\"),\n               block_F_drift = dF_fit(block, \"F_drift\"),\n               dh_F_hom      = dF_fit(dh, \"F_hom\"),\n               dh_F_drift    = dF_fit(dh, \"F_drift\"))\nfmt(rbind(crossing_block = c(target_dF = 1 / (2 * n_line), target_Ne = n_line,\n                             max_deviation = dev(block),\n                             sd_hom_final = block$sd_hom[nrow(block)],\n                             sd_drift_final = block$sd_drift[nrow(block)]),\n          dh_pool        = c(1 / n_line, n_line / 2, dev(dh),\n                             dh$sd_hom[nrow(dh)], dh$sd_drift[nrow(dh)])), 5)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|               | target_dF| target_Ne| max_deviation| sd_hom_final| sd_drift_final|\n|:--------------|---------:|---------:|-------------:|------------:|--------------:|\n|crossing_block |      0.01|        50|       0.00321|      0.01160|        0.00310|\n|dh_pool        |      0.02|        25|       0.00522|      0.01136|        0.00658|\n\n</div>\n:::\n\n```{.r .cell-code}\nfmt(fit_n, 5)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|              |      dF|       Ne|      R2|\n|:-------------|-------:|--------:|-------:|\n|block_F_hom   | 0.00979| 51.09840| 0.99935|\n|block_F_drift | 0.01007| 49.65000| 0.99996|\n|dh_F_hom      | 0.01941| 25.76038| 0.99992|\n|dh_F_drift    | 0.01987| 25.16253| 0.99998|\n\n</div>\n:::\n:::\n\n\nFor the crossing block the fitted rates are 0.00979\nand 0.01007 against a target of\n0.01, giving $N_e$ of\n51.1 and\n49.7 against the true 50. For the\nDH-derived pool of the same 50 lines they are\n0.01941 and 0.01987\nagainst a target of 0.02, giving\n$N_e \\approx$ 25 against the true\n25. In both regimes the largest deviation of either lens from the\nclosed form (0.0032 and 0.0052) falls on the\nhomozygosity lens, and is within *its* between-replicate standard deviation at\nthe last cycle (0.0116 and\n0.0114, 20 replicates); the drift lens is the tighter\nof the two on both counts, deviating by at most\n0.0005 and\n0.0011. $R^2 \\ge 0.999$ on all\nfour fits.\n\nTwo things to carry out of that. The regression recovers $N_e$ to within the\nsampling noise of 20 replicates of 2000 loci, which is what licenses\nthe $R^2$ threshold used below -- *at this scale only*: 20 replicates,\n2000 loci, 12 cycles, one pool, one seed family. And a pool maintained\nas doubled-haploid lines drifts at twice the rate of a crossing block of the same\ncount, so a programme that recycles 50 DH lines per pool per cycle is\nrunning at $N_e \\approx$ 25, not 50. That factor of two is\nstructural, not a simulation artefact: it is the homozygosity of the DH itself.\n\nA third thing, which is what the $F_{drift}$ section above needed and could not\ncompute at that point in the chapter. At cycle 12 the unmanaged crossing\nblock stands at $F_{drift} =$ 0.1141 and the DH\npool at 0.2142, with **no selection applied in any\ncycle of either arm**: `pool_traj(pull = 0)` is a binomial resampling of the\nprevious cycle's frequencies and nothing else. A statistic that reaches those\nvalues under pure drift is not an accumulated selection intensity, and reading\nit as one would attribute an intensity to a process that has none.\n\nNow the crossing block again with the caricature constraint switched on: every\nfrequency moved 5% of the way toward 0.5 before each drift step, which is what a\nheterozygosity-maximising objective does to the frequencies without needing an\noptimiser to do it.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmanaged <- per_cycle(pool_traj(2 * n_line, book_cfg$m, n_cyc, pull = 0.05),\n                     2 * n_line)\nfmt(managed[, c(\"cycle\", \"F_hom\", \"F_drift\", \"cov_diag\", \"sd_drift\")], 5)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| cycle|    F_hom| F_drift| cov_diag| sd_drift|\n|-----:|--------:|-------:|--------:|--------:|\n|     0|  0.00000| 0.00000|  0.00000|  0.00000|\n|     1| -0.05218| 0.01222| -0.06440|  0.00040|\n|     2| -0.09793| 0.02661| -0.12454|  0.00071|\n|     3| -0.13887| 0.04265| -0.18153|  0.00104|\n|     4| -0.17648| 0.06062| -0.23710|  0.00163|\n|     5| -0.20992| 0.07989| -0.28981|  0.00220|\n|     6| -0.24216| 0.10079| -0.34295|  0.00276|\n|     7| -0.26926| 0.12213| -0.39139|  0.00384|\n|     8| -0.29260| 0.14298| -0.43558|  0.00448|\n|     9| -0.31282| 0.16482| -0.47764|  0.00502|\n|    10| -0.33217| 0.18661| -0.51878|  0.00669|\n|    11| -0.35098| 0.20884| -0.55982|  0.00675|\n|    12| -0.36562| 0.23091| -0.59653|  0.00808|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstopifnot(isTRUE(all.equal(managed$cov_diag, managed$F_hom - managed$F_drift)))\nfit_m <- rbind(F_hom = dF_fit(managed, \"F_hom\"), F_drift = dF_fit(managed, \"F_drift\"))\nfmt(fit_m, 5)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|        |       dF|        Ne|      R2|\n|:-------|--------:|---------:|-------:|\n|F_hom   | -0.02335| -21.41636| 0.96037|\n|F_drift |  0.02276|  21.97079| 0.99243|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\narms <- list(`crossing block` = block, `DH pool` = dh, `pull toward 0.5` = managed)\nop <- par(mfrow = c(1, 3), mar = c(4, 4, 2.5, 1))\nfor (nm in names(arms)) {\n  a <- arms[[nm]]\n  plot(a$cycle, a$F_drift, type = \"b\", pch = 19, col = \"#b2182b\",\n       ylim = c(-0.42, 0.26), xlab = \"cycle\", ylab = \"F against frozen p0\",\n       main = nm)\n  lines(a$cycle, a$F_hom, type = \"b\", pch = 17, col = \"#2166ac\")\n  lines(a$cycle, a$expected, lty = 2, col = \"grey40\")\n  abline(h = 0, col = \"grey70\")\n  legend(\"bottomleft\", c(\"F_drift\", \"F_hom\", \"closed form\"), bty = \"n\",\n         cex = 0.75, pch = c(19, 17, NA), lty = c(NA, NA, 2),\n         col = c(\"#b2182b\", \"#2166ac\", \"grey40\"))\n}\npar(op)\n```\n\n::: {.cell-output-display}\n![The two lenses on one heterotic pool over 12 cycles, averaged over 20 replicates, against a base frozen at cycle 0. Left: a crossing block of 50 plants (100 gametes per cycle). Centre: the same 50 lines re-derived as doubled haploids (50 allele copies per cycle), which drifts at twice the rate. In both, the closed form 1 - (1 - 1/n_gam)^t is the dashed line and the two lenses sit on it. Right: the crossing block with every frequency moved 5% toward 0.5 before each drift step, where the homozygosity lens reports a gain of heterozygosity against the frozen base while the drift lens reports more than twice the neutral rate; the dashed line is the same neutral closed form, here a reference both lenses leave. Nothing is selected in any panel; the divergence in the right-hand panel is produced by the management rule alone.](05-genomic-era_files/figure-html/fig-era-lens-divergence-1.png){#fig-era-lens-divergence fig-align='center' width=1350}\n:::\n:::\n\n\n@fig-era-lens-divergence puts the three arms side by side. At cycle 12 the\nmanaged pool reports\n$F_{hom} =$ -0.366 and\n$F_{drift} =$ 0.231, a gap of\n-0.597 which is exactly `cov_diag`. The\nfitted drift rate is 0.0228, or\n2.26 times the\nunmanaged crossing-block rate, implying $N_e =$\n22 instead of 50. The fit on\n$\\log(1 - F_{hom})$ returns a **negative** rate,\n-0.0233, and therefore a negative $N_e$, which is the\narithmetic telling you the series it was handed is not an inbreeding trajectory\nat all. $R^2$ falls to 0.96 on that lens against\n0.99935 in the unmanaged arm.\n\nThe inference, and its limits: a rule that pushes frequencies toward 0.5\ngenerates exactly the negative covariance that the `G_0.5` row of the\nmatrix-sign table predicts, and it does so with no selection whatsoever, which\nis the point @meuwissen2020 make with random GEBVs. What this arm does **not**\nestablish is the magnitude -- `pull = 0.05` is a stipulated caricature, not a\nfitted optimiser, and the factor of\n2.26\nwould move with `pull`, with $n_{gam}$ and with the ancestral frequency\ndistribution.\nThe direction is algebra; the size is this parameterisation.\n\n**Call.** `lm(log(1 - F) ~ cycle)` on cycles $1..t$, separately for each lens;\n$\\Delta F = 1 - e^{\\text{slope}}$; @sec-cycles does this on `run_cycles()`\noutput.\n**Check.** $R^2$ on both fits, and the sign of $\\Delta F$.\n**Warning sign.** A negative fitted $\\Delta F$ (the series is not an inbreeding\nseries), or an $R^2$ that is high while the two lenses disagree in sign -- a\nsmooth curve through the wrong quantity.\n**Threshold.** Calibrated above: a neutral trajectory at this scale gives\n$R^2 \\ge 0.999$, so treat $R^2 < 0.995$ on an averaged series as a non-constant\nrate. $R^2$ says *that* the rate is not constant, not *why*: a decelerating,\nsaturating series depresses it too, and @sec-cycles shows that case -- there the\ndiagnostic fires on the **unconstrained** run.\n\n### Step 5 -- Audit on loci that did not enter the management {#sec-era-step5}\n\nThe constraint is met on the panel it is computed on. Whether it is met anywhere\nelse is a separate measurement, and it needs loci the optimiser never saw. Split\nthe marker panel in two, manage on one half, and read the report on the other:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmgmt  <- seq(1, ctx$m, by = 2)\naudit <- seq(2, ctx$m, by = 2)\nsub_ctx <- function(k) {\n  build_ctx(X = ctx$X[, k], f = molecular_coancestry(ctx$X[, k]), G = NULL,\n            traits = ctx$traits, ped = ctx$ped, n_lines = ctx$n_lines,\n            pool = ctx$pool, fL = ctx$fL, cfg = NULL)\n}\nc_mgmt <- sub_ctx(mgmt)\nc_audit <- sub_ctx(audit)\n# The base of each half is the corresponding slice of the full base, and the\n# index is untouched: only the marker set differs.\nstopifnot(isTRUE(all.equal(c_mgmt$p0, ctx$p0[mgmt])),\n          isTRUE(all.equal(c_mgmt$index, ctx$index)))\n\ni_div <- sel_greedy(c_mgmt, 60, w = 0)     # maximise diversity on the mgmt half\ni_bal <- sel_greedy(c_mgmt, 60, w = 1)\ncols <- c(\"He\", \"F_hom\", \"F_drift\", \"cov_diag\")\naud <- rbind(max_div_managed = freq_metrics(i_div, c_mgmt)[cols],\n             max_div_audit   = freq_metrics(i_div, c_audit)[cols],\n             index_managed   = freq_metrics(i_bal, c_mgmt)[cols],\n             index_audit     = freq_metrics(i_bal, c_audit)[cols])\nfmt(as.data.frame(aud), 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                |     He|   F_hom| F_drift| cov_diag|\n|:---------------|------:|-------:|-------:|--------:|\n|max_div_managed | 0.3333| -0.0300|  0.0117|  -0.0417|\n|max_div_audit   | 0.3228|  0.0221|  0.0124|   0.0097|\n|index_managed   | 0.3120|  0.0452|  0.0580|  -0.0128|\n|index_audit     | 0.3129|  0.0401|  0.0536|  -0.0135|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngaps <- rbind(max_div = aud[\"max_div_audit\", ] - aud[\"max_div_managed\", ],\n              index   = aud[\"index_audit\", ]   - aud[\"index_managed\", ])\nfmt(as.data.frame(gaps[, c(\"F_hom\", \"F_drift\")]), 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|        |   F_hom| F_drift|\n|:-------|-------:|-------:|\n|max_div |  0.0521|  0.0007|\n|index   | -0.0051| -0.0043|\n\n</div>\n:::\n:::\n\n\nResult. The plan that maximises diversity on the management half reports\n$F_{hom} =$ -0.0300 there and\n$F_{hom} =$ 0.0221 on the half it never saw:\nthe sign reverses. Its drift readings are\n0.0117 and\n0.0124 -- practically the same number on\nboth halves, a gap of 0.0007 against\n0.0521 on the homozygosity lens. The\nindex-weighted plan, which optimises nothing about heterozygosity, has an\n$F_{hom}$ gap of only -0.0051.\n\nInterpretation. The homozygosity lens does not generalise off the panel it was\nmaximised on, while the drift lens does; the gap is a property of having\nmaximised, not of the marker set, which is why it nearly vanishes in the\nindex-weighted row. Two limits on that inference. First, in this simulation loci\nare in linkage equilibrium within pool (assumption A5), so the two halves are as\nindependent as a split panel can be. With real linkage disequilibrium the audit\nhalf is correlated with the management half, the measured gap shrinks, and the\naudit becomes *less* sensitive: the gap measured here is close to an upper bound\non what a real split panel would report, not a typical value. Second, this is a\none-cycle, single-seed measurement at the teaching scale; the cycle-by-cycle\nversion of the same audit is @sec-cycles.\n\n**Call.** Two contexts over disjoint marker sets, both anchored on slices of the\nsame frozen $p_0$; `freq_metrics()` on each.\n**Check.** The $F_{hom}$ and $F_{drift}$ gaps between managed and audit halves.\n**Warning sign.** A sign reversal in $F_{hom}$, as above. Also a *large* gap in\n$F_{drift}$, which would mean the management is not even controlling drift off\nits own panel.\n**Threshold.** The gap should be within the sampling noise of the split. A cheap\nempirical reference: the `index` row of the same table, which had no\nheterozygosity objective at all.\n\n### Step 6 -- Read the two pools separately, and never $F_{ST}$ alone {#sec-era-step6}\n\nEverything so far is a single-population reading. A hybrid programme has two,\nand they must be constrained in opposite directions: within pool, limit\n$\\Delta F$; between pools, *preserve* divergence, because that is the heterosis\nengine (@sec-heterosis proves the identity, @sec-stages Trap 3 states the\nprescription). A single global\n$\\tfrac{1}{2}\\mathbf{c}'\\mathbf{G}\\mathbf{c}$ cannot express that.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npool_row <- function(i) {\n  c(GD = gene_diversity(i, ctx), index = mean(ctx$index[i]),\n    theta_pools(i, ctx)[c(\"theta_A\", \"theta_B\")],\n    gd_partition(i, ctx)[c(\"GD_T\", \"GD_BS\", \"F_ST\")],\n    ne_lines_pool(i, ctx), Ne_parents = ne_parents(i, ctx),\n    max_line = max_line_use(i, ctx))\n}\nset.seed(31)\npr <- rbind(random     = pool_row(sample.int(ctx$N, 60)),\n            truncation = pool_row(sel_truncation(ctx, 60)),\n            max_div    = pool_row(sel_greedy(ctx, 60, w = 0)),\n            capped     = pool_row(sel_greedy(ctx, 60, w = 1, max_use = 4)))\nstopifnot(isTRUE(all.equal(unname(pr[, \"GD\"]), unname(pr[, \"GD_T\"]))))\nfmt(as.data.frame(pr), 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|           |     GD|   index| theta_A| theta_B|   GD_T|  GD_BS|   F_ST| Ne_lines_A| Ne_lines_B| Ne_parents| max_line|\n|:----------|------:|-------:|-------:|-------:|------:|------:|------:|----------:|----------:|----------:|--------:|\n|random     | 0.3257| -0.3178|  0.7089|  0.7108| 0.3257| 0.0355| 0.1090|    19.1489|    20.2247|    39.3443|        5|\n|truncation | 0.3124|  1.9919|  0.7581|  0.7219| 0.3124| 0.0524| 0.1678|     4.4888|    11.8421|    13.0199|       23|\n|max_div    | 0.3302|  0.1343|  0.7053|  0.7066| 0.3302| 0.0361| 0.1095|    18.9474|    18.3673|    37.3057|        5|\n|capped     | 0.3248|  0.8204|  0.7096|  0.7153| 0.3248| 0.0372| 0.1146|    15.5172|    15.5172|    31.0345|        4|\n\n</div>\n:::\n:::\n\n\nTwo gene-diversity columns sit in that table and they are the **same** quantity\nreached by two routes, which the `stopifnot()` in the chunk enforces on every\nrender: `GD` is $1 - \\theta$ from $\\mathbf{f}$ over the selected hybrids\n(@sec-catalogue), `GD_T` is $1 - \\bar f$ from the line-usage weights of the\nCaballero & Toro partition, and both reduce to\n$\\overline{\\bar p_k^2 + (1 - \\bar p_k)^2}$ with $\\bar p$ the usage-weighted\nmerged frequency, because under A2 a hybrid's marker row is the average of its\ntwo parents'. It is the same identity as $He = GD_T$ in @sec-era-fhom, and\n`GD`, `GD_T` and Nei's $He$ are one number on this germplasm. The columns that\n*are* a different quantity are $GD_{BS}$ and $F_{ST}$: both are built from\n$\\tilde f = (\\theta_A + \\theta_B)/2$, which no hybrid-level average can\nreproduce, and both are read below.\n\nResult. Truncation on the index costs\n4.1% of gene\ndiversity against the random baseline -- which is the $\\alpha$ of\n@sec-catalogue, computed here on a single random draw rather than on the\nresampled `gd_ref` -- and 5.4%\nagainst the max-diversity ceiling. Meanwhile $\\theta_A$ rises to\n0.7581 against\n$\\theta_B =$ 0.7219, and the effective number\nof lines used falls to 4.49 in pool A\nagainst 11.84 in pool B. One line appears\nin 23 of the 60 hybrids.\n\nThe dangerous column is $F_{ST}$. It *rises* from\n0.1095 to\n0.1678 under truncation, and so does $GD_{BS}$.\nRead as divergence, that looks like a gain in heterosis potential. It is not: by\nthe Caballero & Toro definitions `gd_partition()` implements\n[@caballero2002, Eq. 7], $GD_{BS} = \\tilde f - \\bar f$ with\n$\\tilde f = (\\theta_A + \\theta_B)/2$ and\n$\\bar f = (\\theta_A + 2\\theta_{AB} + \\theta_B)/4$, so concentrating usage inside\n*one* pool raises $\\tilde f$ twice as fast as it raises $\\bar f$ and therefore\nraises the between-pool component -- even though the two pools' lines are\nunchanged and their coancestry matrix $\\mathbf{f}^L$ is fixed. All that moved is\nthe weight the selection puts on each line. $F_{ST}$ then divides by a $GD_T$\nthat fell at the same time -- the `GD_T` column of the table above, from\n0.3302 to 0.3124 -- which\namplifies the artefact: the numerator rises by\n45% while\nthe denominator falls by\n5%. A\nwithin-pool collapse and a genuine divergence are indistinguishable in $F_{ST}$,\nand only the separate $\\theta_A$, $\\theta_B$ columns tell them apart.\n\nThe limitation to state here rather than hide: `freq_metrics()` computes its two\nlenses on `ctx$X` against `ctx$p0`, and @sec-era-step1 showed that hybrid base to\nbe $(p_A + p_B)/2$. So $F_{hom}$ and $F_{drift}$ as this package computes them\nare **pooled over the two pools** and cannot, on their own, tell you which pool\neroded. The pool-level attribution comes from three other places: $\\theta_A$ and\n$\\theta_B$ (`theta_pools()`), the effective number of lines used per pool\n(`ne_lines_pool()`), and the pool-level panel `s1_monitor()` returns from the\nline matrix:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ns1 <- s1_monitor(L / 2, pool, cycle = 0)\nfmt(s1, 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| cycle| GD_within| GD_total| Fst_Wright| Gst_Nei| Ns_total|   GD_A|   GD_B| frac_opposite_fixed| mean_abs_delta_p| mean_sq_delta_p|\n|-----:|---------:|--------:|----------:|-------:|--------:|------:|------:|-------------------:|----------------:|---------------:|\n|     0|    0.2945|   0.3281|     0.1858|  0.1024|   0.7442| 0.2953| 0.2937|                   0|           0.1982|          0.0672|\n\n</div>\n:::\n:::\n\n\nThe two panels are the same quantities computed from the two ends of the\ncontract, and on the full factorial -- where line usage is uniform -- they agree\nexactly:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngp_full <- gd_partition(seq_len(ctx$N), ctx)\nstopifnot(isTRUE(all.equal(gp_full[[\"GD_T\"]], s1$GD_total)),\n          isTRUE(all.equal(gp_full[[\"F_ST\"]], s1$Gst_Nei)))\nc(gd_partition_GD_T = gp_full[[\"GD_T\"]], s1_GD_total = s1$GD_total,\n  gd_partition_F_ST = gp_full[[\"F_ST\"]], s1_Gst_Nei = s1$Gst_Nei,\n  s1_Fst_Wright = s1$Fst_Wright)\n#> gd_partition_GD_T       s1_GD_total gd_partition_F_ST        s1_Gst_Nei \n#>         0.3280928         0.3280928         0.1024003         0.1024003 \n#>     s1_Fst_Wright \n#>         0.1857770\n```\n:::\n\n\nNote which two agree. `gd_partition()`'s `F_ST` is $GD_{BS}/GD_T$, which is the\nNei $G_{ST}$ form, and it equals `s1_monitor()`'s `Gst_Nei` to machine\nprecision; `Fst_Wright` is the other definition and is\n1.81 times larger on the same germplasm. That\nis @sec-stages Trap 2, and it is the reason to name the definition in the report\nrather than the symbol.\n\n**Call.** `theta_pools()`, `gd_partition()`, `ne_lines_pool()`,\n`max_line_use()`, `ne_parents()` on the selection; `s1_monitor()` on the line\nmatrix of each cycle.\n**Check.** $\\theta_A$ and $\\theta_B$ separately; $GD_{BS}$ held in a band, not\nmaximised; the number of distinct lines used per pool.\n**Warning sign.** $F_{ST}$ rising while $GD_T$ falls -- almost always a\none-pool collapse, not divergence. An `Ne_lines` asymmetry between pools of the\nsize in the `truncation` row above\n(4.5 against\n11.8).\n**Threshold.** A per-line usage cap is the direct instrument: the `capped` row\nis `sel_greedy(ctx, 60, w = 1, max_use = 4)`, which holds\n$|\\theta_A - \\theta_B|$ at\n0.0056 and both\npools above 15.5\neffective lines, against an index of 0.82 where\ntruncation reached 1.99. That index difference\nis the price, and @sec-cycles is where it is paid back or not. `max_use`\ndefaults to `NULL` everywhere in this package, so the cap is opt-in.\n\n> **The diagnostic nobody runs.** Schemes based on IBD selected many parents in\n> @meuwissen2020; VanRaden-style schemes selected few. If your\n> optimal-contribution run is delivering high gain with a suspiciously small\n> number of parents and $\\Delta F$ on target, compute $F_{hom}$ and $F_{drift}$\n> separately on a panel **not used** in the management (@sec-era-step5). The\n> difference between them is your hidden bill. This book's\n> implementation is `ne_parents()`, which @sec-case-study reports alongside the\n> two lenses for every scenario. The `era-pools` table above is the small\n> version of the same diagnostic: between the `random` and `truncation` rows\n> gene diversity falls by\n> 4.1%\n> while the effective number of parents falls from\n> 39.3 to\n> 13.0, which is\n> 67%\n> -- the two relative drops differ by a factor of\n> 16.\n> A budget written on gene diversity alone is therefore a weak constraint on the\n> parent count, and the `capped` row -- the same greedy with `max_use = 4` -- is\n> what holding the parent count directly costs:\n> 31.0 effective parents at an index\n> of 0.82 where truncation reached\n> 1.99. Measured on one candidate set at the\n> teaching scale, with a single random draw as the `random` row.\n\n### Step 7 -- Check the matrix you are about to invert {#sec-era-step7}\n\n::: {.callout-note}\n## An implementation note that is routinely ignored\n\n`G_VR1`, `G_VR2`, `G_0.5` and `G_i(p)` are all only **semi**-definite positive,\nso every one of them needs $\\alpha$ added to the diagonal ($\\alpha = 0.01$ in\n@meuwissen2020, their Methods) before it can be inverted and before\nthe optimal-contribution algorithm will run. $\\mathbf{A}$ and `G_LA` are\npositive definite by construction.\n\n**The mechanism is not the same for all four, and the difference matters here.**\nFor the centred VanRaden forms it is the centring: $\\mathbf{Z}$ is centred on the\n*population's own* allele frequencies, so its columns sum to zero over\nindividuals, the constant vector lies in the null space and one degree of\nfreedom is gone by construction. For `G_0.5`, which is the molecular coancestry\nthis book calls $\\mathbf{f}$, it is **not** the centring -- $\\mathbf{f}$ is not\ncentred on anything and stays in $[0, 1]$ by design (@sec-coancestry). Its\ndeficiency has a different cause, derived below. Both statements are checkable:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nZh  <- ctx$X - 0.5\nrkf <- qr(ctx[[\"f\"]])$rank\nrkG <- qr(ctx[[\"G\"]])$rank\nc(f_equals_half_plus_gram = max(abs(ctx[[\"f\"]] -\n                                      (2 * tcrossprod(Zh) / ctx$m + 0.5))),\n  f_rowsum_min            = min(rowSums(ctx[[\"f\"]])),\n  f_rowsum_max            = max(rowSums(ctx[[\"f\"]])),\n  G_sum                   = sum(ctx[[\"G\"]]),\n  G_rowsum_max_abs        = max(abs(rowSums(ctx[[\"G\"]]))),\n  rank_f = rkf, rank_G = rkG, n_lines = ctx$n_lines, N = ctx$N)\n#> f_equals_half_plus_gram            f_rowsum_min            f_rowsum_max \n#>            1.110223e-16            4.159937e+02            4.246250e+02 \n#>                   G_sum        G_rowsum_max_abs                  rank_f \n#>           -4.178879e-11            1.163340e-13            4.900000e+01 \n#>                  rank_G                 n_lines                       N \n#>            4.800000e+01            5.000000e+01            6.250000e+02\n```\n:::\n\n\n$\\mathbf{f} = 0.5 + \\tfrac{2}{m}\\mathbf{Z}_h\\mathbf{Z}_h'$ with\n$\\mathbf{Z}_h = \\mathbf{X} - 0.5$, to machine precision -- a Gram matrix plus the\npositive rank-one term $0.5\\,\\mathbf{1}\\mathbf{1}'$, hence positive\nsemi-definite, and with row sums nowhere near zero (`f_rowsum_min` above), so\nneither $\\mathbf{1}$ nor any other constant vector is in its null space.\nVanRaden's\n$\\mathbf{G}$ on the same hybrids has `sum(G)` and every row sum at numerical\nzero, which *is* the centring, and its rank comes out exactly one below\n$\\mathrm{rank}(\\mathbf{f})$ on this data set: one dimension is what centring\ncosts, and it is the only part of either deficiency that centring explains. The\nother 576 missing dimensions have a different cause entirely, and the\nrest of this step is that cause.\n:::\n\nIn a hybrid programme the deficiency is far worse than one zero eigenvalue, and\nit is structural rather than numerical. A hybrid's marker row is the average of\nits two parents' rows, so $\\mathbf{X} = \\tfrac12 \\mathbf{B}\\mathbf{M}_L$ with\n$\\mathbf{B}$ the $N \\times L$ parent-usage incidence matrix (a 1 in the two\ncolumns of its parents) and $\\mathbf{M}_L$ the $L \\times m$ line matrix (the\n`L / 2` object of `simulate_lines()`; the subscript keeps it apart from the\n$\\mathbf{G}_\\bullet$ relationship matrices of this chapter). The hybrid\ncoancestry matrix is a Gram matrix of that,\n$\\mathbf{f} = [\\mathbf{X}, 1 - \\mathbf{X}][\\mathbf{X}, 1 - \\mathbf{X}]'/m$. Its\ncolumn space lies in the span of the columns of $\\mathbf{X}$ plus the constant\nvector, so its rank is bounded by\n$\\min(\\mathrm{rank}(\\mathbf{B}),\\, m) + 1$ however many hybrids you have.\nMeasured:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nincidence <- function(idx, ctx) {\n  B <- matrix(0, length(idx), ctx$n_lines)\n  B[cbind(seq_along(idx), ctx$ped$a[idx])] <- 1\n  B[cbind(seq_along(idx), ctx$ped$b[idx])] <- 1\n  B\n}\nset.seed(31)\n# A separate set from the `sels` of @sec-era-fhom: these vary n_sel, which is\n# the axis the rank depends on. Named apart so neither chunk shadows the other.\nrk_sels <- list(full_factorial = seq_len(ctx$N),\n                random_60      = sample.int(ctx$N, 60),\n                truncation_60  = sel_truncation(ctx, 60),\n                max_div_60     = sel_greedy(ctx, 60, w = 0),\n                random_20      = sample.int(ctx$N, 20))\nrk <- do.call(rbind, lapply(names(rk_sels), function(n) {\n  i <- rk_sels[[n]]\n  data.frame(selection = n, n_sel = length(i),\n             lines_used = length(unique(c(ctx$ped$a[i], ctx$ped$b[i]))),\n             rank_f = qr(ctx[[\"f\"]][i, i])$rank,\n             rank_incidence = qr(incidence(i, ctx))$rank)\n}))\nrk$deficiency <- rk$n_sel - rk$rank_f\nfmt(rk)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|selection      | n_sel| lines_used| rank_f| rank_incidence| deficiency|\n|:--------------|-----:|----------:|------:|--------------:|----------:|\n|full_factorial |   625|         50|     49|             49|        576|\n|random_60      |    60|         47|     46|             46|         14|\n|truncation_60  |    60|         33|     32|             32|         28|\n|max_div_60     |    60|         43|     41|             41|         19|\n|random_20      |    20|         31|     20|             20|          0|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstopifnot(all(rk$rank_f == rk$rank_incidence))\nev_min <- min(eigen(ctx[[\"f\"]], symmetric = TRUE, only.values = TRUE)$values)\nc(rank_full_factorial = rk$rank_f[1], n_lines = ctx$n_lines)\n#> rank_full_factorial             n_lines \n#>                  49                  50\nc(min_eigenvalue_f = signif(ev_min, 3))\n#> min_eigenvalue_f \n#>        -4.28e-13\n```\n:::\n\n\nResult. In all five selections the rank of $\\mathbf{f}$ equals the rank of the\nparent-usage incidence matrix exactly. On the full factorial that is\n49 $= L - 1$ for 50 lines, against 625 hybrids:\na deficiency of 576, with a smallest eigenvalue at\n-4.3\\times 10^{-13}. A subset of 20 hybrids drawn from 50 lines is full rank.\n\nInterpretation. The deficiency is not a rounding artefact and does not shrink\nwith more markers; it is the factorial structure. $N$ hybrids built from $L$\nlines live in an at most $L$-dimensional space, so any hybrid-level optimiser\nthat needs $\\mathbf{f}^{-1}$ must regularise, and the amount of regularisation\nrequired is predictable *before* any eigendecomposition: compute\n$\\mathrm{rank}(\\mathbf{B})$, which costs one `qr()` on an $N \\times L$ 0/1\nmatrix. The equality `rank_f == rank_incidence` is a measurement over five\nselections at one scale, not a theorem -- the algebra above bounds\n$\\mathrm{rank}(\\mathbf{f})$ by $\\mathrm{rank}(\\mathbf{B}) + 1$, and the extra\ndimension the bound allows is not attained in any of the five. It is also the\nreason this book's selection machinery never inverts $\\mathbf{f}$:\n`metrics_cheap()` and the DE fitness only ever evaluate the quadratic form\n$\\mathbf{c}'\\mathbf{f}\\mathbf{c}$, which needs no inverse. The\nquadratic-programming routes do need a definite matrix, and both\n`optimal_contributions()` and `ocs_quadprog()` add `diag(1e-8, n)` for exactly\nthis reason -- four orders of magnitude above the numerical zero reported above,\nand small enough not to move the optimum. See @sec-ocs and @sec-g-singular.\n\n**Call.** `qr()` on the usage incidence matrix, or on $\\mathbf{f}$ restricted to\nthe candidate set; `eigen(..., only.values = TRUE)` for the spectrum if you want\nthe size of the numerical zero.\n**Check.** `rank(f) < n_sel`, and how far below.\n**Warning sign.** A quadratic-programming solver that returns without error but\nwith contributions concentrated on a handful of hybrids: a singular matrix makes\nthe objective flat along $N - \\mathrm{rank}$ directions, and the solver will pick\na vertex.\n**Threshold.** The added diagonal $\\alpha$ must exceed the largest magnitude of\nthe numerically-zero eigenvalues, here about 4\\times 10^{-13}, by\nseveral orders of magnitude; $\\alpha = 0.01$ on a matrix whose diagonal averages\n0.82 is a perturbation of about\n1.2% and must be documented as such,\nbecause it changes the optimum.\n\n## What not to do\n\nFour recommendations that do not need their own step. Each one is labelled with\nwhat backs it, because they are not backed equally: one is measured in this\nchapter, three are positions taken by @meuwissen2020 and carried forward here as\n*their* argument, and none of the three has been tested on plant germplasm\nanywhere in this book.\n\n**Do not maximise marker heterozygosity as an objective.** *Measured here:*\nraising heterozygosity on the monitored panel does not raise it at unmonitored\nloci -- @sec-era-step5 measures the sign reversal, under linkage equilibrium,\nwhich makes it a best case. *Their argument, not measured here:* doing so also\nraises IBD-based inbreeding, because \"changes in allele frequency result from\nmultiple copies of a subset of base generation alleles, so increasing frequency\nis promoting IBD based inbreeding\" [@meuwissen2020, Discussion, Management of\nDiversity]. This book has no IBD route at all -- every matrix in it is\nidentity-by-state -- so that half is a reason to distrust the objective, not a\nresult reproduced here.\n\n**Region-specific diversity targets rarely earn their complexity.** *Their\nargument.* @meuwissen2020 give two grounds in the same paragraph: that causative\nalleles of quantitative traits are quite evenly distributed across the genome\n(their Discussion, citing Wood et al. 2014 on human stature -- an observation\nabout one species and one trait, not about maize), and that \"what happens in a\nsample of loci does not necessarily predict what happens at loci outside that\nsubset\", which is the claim @sec-era-step5 does test, at the marker level. They\nname the major histocompatibility complex as the case that *does* earn a\nconstraint of its own; the plant analogue offered here is R-gene-type resistance\nloci, where allelic diversity has direct and known value. That analogy is\noffered as such, and nothing in this book measures it.\n\n**Deleterious recessives are a load problem, not a diversity problem.** *Their\njudgement:* for regions carrying known recessive defects, \"direct inclusion of\nthe known defects in the breeding goal seems more effective in controlling their\nfrequencies\" than prioritising the region for diversity management\n[@meuwissen2020, Discussion]. Neither they nor this book compare the two\nroutes quantitatively, so read it as the expectation of the authors of the\nscheme, not as a measured efficiency. In a hybrid programme there is a second\nand independent reason, which follows from A1 and A2 rather than from anyone's\njudgement: a recessive carried at low frequency in pool A is masked in every\n$A \\times B$ hybrid unless pool B carries it too, so the load is expressed in\nthe crossing block and in the DH induction, not in the product.\n\n**In a pure conservation scheme the problem is expected to be *worse*, not\nbetter.** *Their expectation, stated as one:* \"the potential covariance between\nthe change in allele frequency and the initial frequency is expected to\nincrease, since the inbreeding management term is more important in pure\nconservation schemes\" [@meuwissen2020, Discussion], which is why they argue the\nIBD recommendation is stronger there. Their simulations all carry selection, so\nno conservation scheme was run to test it; the sign of the mechanism is\nnevertheless the same algebra as everything above -- a constraint that is the\nonly thing moving frequencies is a constraint that generates the whole\ncovariance.\n\n## Limits of the animal-to-plant transposition {#sec-era-transposition}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Assumption in the paper                                           |Situation in a hybrid crop programme                                                                                                                                                                                           |\n|:-----------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|discrete generations, two sexes, one contribution per individual  |same line reused for years, cloning of parents through DH maintenance, overlapping cycles, one line used in dozens of crosses                                                                                                  |\n|reliable, deep pedigree                                           |recycling pedigree usually complete inside the programme, absent for introduced germplasm and genebank accessions                                                                                                              |\n|base = simulated founder population at mutation-drift equilibrium |base is an administrative choice (cycle 0) with pre-existing heterotic structure already in it                                                                                                                                 |\n|target Ne = 100 over 20 generations                               |shorter cycles with GS; this book measures no commercial elite Ne, but @sec-era-step6's own teaching-scale example shows Ne_parents falling well below the pool size under plain truncation (39.3 to 13.0)                     |\n|one population, one target                                        |two heterotic pools with opposite-signed constraints, several target environments                                                                                                                                              |\n|heterozygosity is always desirable                                |desirable in the product, undesirable in the parents, irrelevant at the individual level once lines are fixed -- and in none of the three cases is it what F_hom measures, which is merged-pool gene diversity (@sec-era-fhom) |\n\n\n:::\n:::\n\n\nNone of this invalidates the central conclusion. It is an **algebraic** property\nof the optimiser, not a biological property of the species. What it changes is\n*which matrix is practicable*, and -- for a two-pool programme -- that one global\nconstraint is never enough.\n\n## Operational checklist\n\nThe protocol above, in one column, with the step that implements each item.\n\n| Check | Step |\n|---|---|\n| Is the base $p_0$ frozen at the founding cycle, and documented? | @sec-era-step1 |\n| Is the hybrid-level base the balanced average of the two pool bases? | @sec-era-step1 |\n| Are `F_hom` and `F_drift` computed **separately** and reported together? | @sec-era-step2 |\n| Is it recorded that `F_hom` is merged-pool gene diversity and **not** F1 heterozygosity, with $GD_{BS}$ reported next to it? | @sec-era-fhom |\n| Is every single-cycle value compared with a **resampled** null rather than with one random draw? | @sec-era-step2 |\n| Is the sign of `F_hom` preserved rather than clamped? | @sec-era-step2 |\n| Is `cov_diag` reported as a diagnostic, with its sign? | @sec-era-step3 |\n| Is $\\log(1 - F)$ regressed on cycle, with $R^2$ shown, for both lenses? | @sec-era-step4 |\n| Is $\\Delta F$ read as $1 - e^{\\text{slope}}$ rather than $-\\text{slope}$? | @sec-era-step4 |\n| Is there a panel of loci **not used in management**, for audit? | @sec-era-step5 |\n| Are $\\theta_A$ and $\\theta_B$ reported separately, never only $F_{ST}$? | @sec-era-step6 |\n| Is the number of parent lines used per pool biologically plausible? | @sec-era-step6 |\n| Is $GD_{BS}$ held in a band rather than maximised? | @sec-era-step6 |\n| Is the matrix's rank checked before any inversion, and the added $\\alpha$ documented? | @sec-era-step7 |\n| Is true genetic variance (or the best estimate of it) being tracked? | @sec-response |\n| Where possible, is an IBD alternative compared in parallel? | @sec-era-transposition |\n",
    "supporting": [
      "05-genomic-era_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}