{
  "hash": "ccd1d51661faf01633e3ab53ca09ea57",
  "result": {
    "engine": "knitr",
    "markdown": "# Advanced selection: structure, bounds and scale {#sec-advanced}\n\n\n\n@sec-combinatorial stops at a warm-started differential evolution. That is a\nreasonable place to stop if the problem is a black box. It is not one. This\nchapter names the structure, and then spends it: on cheaper moves, on genuine\napproximation guarantees, on a bound that is actually a bound, and on an oracle\nthat says how far from optimal the heuristics really are.\n\nThe target throughout is the scale the method has to survive: **200 hybrids\nchosen from 10,000**, a full factorial of 100 by 100 lines. That is an ordinary\nsize for a hybrid maize programme at the end of a cycle: two heterotic pools of\na hundred inbred or doubled-haploid lines each, every cross between them a\nlegitimate candidate, and a few hundred of them going into the next round of\nmulti-location testing.\n\nThat is a different -- and deliberately larger -- \"production scale\" from the\none @sec-combinatorial quotes. There, production means the real dataset this\npackage was written for, 71 + 71 lines and $N = 5041$ candidates, which is the\nsize the encoding argument is made at. Here it is the 100 + 100 factorial the\nscaling study and the head-to-head benchmark are run at, because a cost curve\nneeds a span of $N$ wider than one point provides. Neither is wrong and they\nare not interchangeable: every per-evaluation cost and every memory figure in\nthis chapter is at $N = 10{,}000$, and the dimension counts in\n@sec-combinatorial are at $N = 5041$.\n\n**What has to be in hand**, beyond @sec-combinatorial's three objects, is the\nline-level route: `fast_ctx()` adds `ctx$parents`, the $N \\times 2$ matrix of\nparent indices, to a context that already carries `ctx$fL`, the $L \\times L$\ncoancestry *between lines*. Everything in this chapter that scales is a\nfunction of those two and of nothing else.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(candidates_N = ctx$N,\n  lines_L      = ctx$n_lines,\n  hybrids_kept = n_sel,\n  budget_pct   = 100 * am,\n  gd_ref       = gd,\n  f_MiB        = as.numeric(object.size(ctx[[\"f\"]])) / 2^20,\n  fL_MiB       = as.numeric(object.size(ctx$fL)) / 2^20)\n#> candidates_N      lines_L hybrids_kept   budget_pct       gd_ref        f_MiB \n#> 625.00000000  50.00000000  60.00000000   1.00000000   0.32583857   2.98043823 \n#>       fL_MiB \n#>   0.01927948\n```\n:::\n\n\nThe assumptions are @sec-combinatorial's, unchanged and worth restating because\ntwo of them are load-bearing here: parent lines are homozygous, which is what\nmakes $f_{ij}$ a function of the four parental coancestries and hence collapses\nthe problem to $L$ dimensions (@sec-collapse); and `f` is molecular coancestry\nin $[0, 1]$, not a centred relationship matrix, which is what makes it a Gram\nmatrix with the properties the next section needs.\n\n## Three facts about this problem\n\nEverything below follows from three properties of `f`, each of which takes\nthree lines to check and none of which has been stated in this book so far.\n\n### `f` is a Gram matrix\n\nMolecular coancestry is\n$f_{ij} = \\frac{1}{m}\\sum_k [x_{ik}x_{jk} + (1-x_{ik})(1-x_{jk})]$, which is an\ninner product of the stacked vectors $[\\mathbf{x}_i;\\, \\mathbf{1}-\\mathbf{x}_i]$.\nSo `f` is not merely symmetric, it is a **Gram matrix**, exactly:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nV  <- cbind(ctx[[\"X\"]], 1 - ctx[[\"X\"]])\nev <- eigen(ctx[[\"f\"]], symmetric = TRUE, only.values = TRUE)$values\nc(max_abs_difference = max(abs(ctx[[\"f\"]] - tcrossprod(V) / ctx$m)),\n  min_eigenvalue     = min(ev),\n  min_over_max_eig   = min(ev) / max(ev))\n#> max_abs_difference     min_eigenvalue   min_over_max_eig \n#>       0.000000e+00      -4.275667e-13      -1.018142e-15\n```\n:::\n\n\nThe check is the whole argument: the difference is exactly zero, and the\nsmallest eigenvalue is zero to the eigensolver's own rounding -- its sign is\narbitrary 15 orders of magnitude below\nthe largest eigenvalue. A negative eigenvalue large enough to see on that scale\nwould mean `f` had been centred, rescaled, or built on the wrong marker\ncoding -- and every method in this chapter would silently lose its\njustification.\n\nTwo consequences carry the rest of the chapter. First, $\\mathbf{c}'\\mathbf{f}\\mathbf{c}$\nis a **convex** quadratic, so the diversity budget is a convex constraint --\nwhich is what makes the exact method of @sec-oa possible at all. Second,\n$d_{ij} = f_{ii} + f_{jj} - 2f_{ij}$ is a squared Euclidean distance, hence a\ndistance of **negative type**, which is the precise hypothesis the strongest\napproximation results require.\n\n### Maximising diversity is minimising the submatrix sum\n\n$\\theta_S = \\frac{1}{n^2}\\sum_{i,j \\in S} f_{ij}$, and at fixed $n$ the\nnormaliser is a constant:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ns <- sel_greedy(ctx, n_sel, w = 1)\nc(theta_times_n2 = theta_group(s, ctx) * n_sel^2,\n  submatrix_sum  = sum(ctx[[\"f\"]][s, s]),\n  difference     = theta_group(s, ctx) * n_sel^2 - sum(ctx[[\"f\"]][s, s]))\n#> theta_times_n2  submatrix_sum     difference \n#>   2.475329e+03   2.475328e+03   1.818989e-12\n```\n:::\n\n\nSo the objective is $\\lambda \\sum_{i \\in S} u_i - \\sum_{i,j \\in S} f_{ij}$: a\n**modular** term plus a **submodular** one, since the marginal cost of adding a\nhybrid grows with the set. Writing the same thing through $d_{ij}$,\n$\\sum_{i<j} d_{ij} = n\\,\\mathrm{tr}(f_S) - n^2\\theta_S$, identifies it as the\n**max-sum diversification** problem of @borodin2017. I have not found it named\nthat way in the plant-breeding literature, and this book makes no claim about\nwhat a systematic screen would find -- no such screen was run. The structural\nidentity is the load-bearing part, and it holds whether or not anyone has\nwritten it down before.\n\nThe practical content of \"fixed $n$\" is worth spelling out: it is *only* at a\nfixed set size that maximising gene diversity and minimising the submatrix sum\nare the same instruction. Comparing $\\theta$ across selections of different\nsizes compares two different things, which is the same reason `gd_ref` has to\nbe resampled at the size actually being used (@sec-baseline).\n\n### The per-line cap is a partition matroid\n\n\"No line may parent more than `max_use` of the selected hybrids\" is one\npartition matroid per heterotic pool. Together with the cardinality constraint\nthat is an intersection of matroids -- not an arbitrary combinatorial\nrestriction, but the single best-understood constraint class in discrete\noptimisation.\n\nThe structure comes from the mating design, not from the mathematics. Every\ncandidate is a cross between one pool-A line and one pool-B line, so each\nselected hybrid contributes exactly one use to a pool-A line and one to a\npool-B line, and the counts within each pool sum to $n$ by construction:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncnt <- line_counts(s, ctx)\nc(uses_pool_A     = sum(cnt[ctx$pool == \"A\"]),\n  uses_pool_B     = sum(cnt[ctx$pool == \"B\"]),\n  n_sel           = n_sel,\n  distinct_A_used = sum(cnt[ctx$pool == \"A\"] > 0),\n  distinct_B_used = sum(cnt[ctx$pool == \"B\"] > 0))\n#>     uses_pool_A     uses_pool_B           n_sel distinct_A_used distinct_B_used \n#>              60              60              60              10              23\n```\n:::\n\n\nThat is exactly the ground-set partition a partition matroid needs. It also\ngives the feasibility condition for any cap $c$ directly: a plan of $n$ crosses\nexists under the cap only if $n \\le L_A c$ and $n \\le L_B c$. In a programme the\ncap is rarely chosen for theoretical reasons -- it is set by how many\nseed-production fields a female line can support -- and the point of naming the\nstructure is that a constraint arriving from the field turns out to be the one\nclass of constraint discrete optimisation handles best.\n\n::: {.callout-note}\n## Why naming the structure is worth a section\n\nThree named properties buy three concrete things, and it is worth being blunt\nabout which is which.\n\n| Property | What it buys | Worth in practice |\n|---|---|---|\n| `f` positive semi-definite | a convex constraint, hence valid gradient cuts and a valid Lagrangian bound | **large** -- @sec-bound is a correction, not an ornament |\n| submodular plus modular objective | $1 - 1/e$ under cardinality [@nemhauser1978], $1/(p+1)$ under $p$ matroids [@fisher1978]; a PTAS for negative-type distances under a matroid [@cevallos2016] | **small** -- worst-case bounds, and the measured gap is around 1% |\n| line collapse $\\theta = \\mathbf{w}'\\mathbf{f}^L\\mathbf{w}$ | memory $O(N^2) \\to O(L^2)$, an $O(L)$ swap, and an $L$-dimensional contributions programme in place of an $N$-dimensional one | **large** -- 0.745 GiB against 0.3 MiB, and the swap is what makes local search affordable |\n:::\n\n## What lazy greedy would not buy\n\nThe obvious first move on a submodular objective is the accelerated, or \"lazy\",\ngreedy of @minoux1978: keep stale marginal gains in a priority queue and\nre-evaluate only the top one, which is valid precisely because submodularity\nmakes a stale gain an upper bound on the current one. Two distinct results are\neasy to conflate here, so name them apart: the acceleration is Minoux's, while\nthe worst-case guarantee for the plain greedy it accelerates is @nemhauser1978's\nand is quoted separately below. It is the standard accelerator for this\nobjective class, and here it is **worthless**.\n\n`sel_greedy()` already carries the running vector `s` of coancestry sums\nagainst the chosen set, so every candidate's marginal gain is $O(1)$ and the\nwhole step is one vectorised pass. Lazy evaluation optimises precisely the cost\nthat is already free. Reaching for it would add a heap, add bugs, and save\nnothing.\n\nThe guarantee is worth stating even so, because it settles a question rather\nthan improving a number: greedy under our constraints cannot do worse than\n$1/(p+1)$ of optimal, with $p$ the number of matroids intersected -- here the\ncardinality constraint plus one partition matroid per pool.\n\nState it with its hypotheses, though, because they are not all met. The\n$1 - 1/e$ and $1/(p+1)$ results of @nemhauser1978 and @fisher1978 are proved\nfor **monotone, non-negative** submodular functions. Our objective is neither\nin general: the index is standardised to mean zero over the candidate pool, so\n$\\bar u_S$ can be negative, and adding a hybrid increases the coancestry term,\nso the objective is monotone only where the merit term dominates. The guarantee\ntherefore belongs in this chapter as a statement about the *constraint class* --\nthe cap is not an arbitrary restriction -- and not as a certificate for any\nparticular run. The certificate this chapter actually uses is the Lagrangian\nbound of @sec-bound, and @sec-oa measures what greedy does in fact achieve.\n\n## The move that was already paid for {#sec-localsearch}\n\n@sec-collapse established $\\theta_S = \\mathbf{w}'\\mathbf{f}^L\\mathbf{w}$, and\n`theta_state()`/`theta_swap()` have been in the package ever since, maintaining\ngroup coancestry in $O(L)$ per swap. Nothing consumed them. @sec-combinatorial\neven ends with a callout recommending local search, citing @debeukelaer2018 --\nand then does not run one.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_swap\n#> function (st, out_h, in_h, ctx) \n#> {\n#>     cnt <- st$cnt\n#>     v <- st$v\n#>     po <- ctx$parents[out_h, ]\n#>     pi_ <- ctx$parents[in_h, ]\n#>     for (a in po) {\n#>         cnt[a] <- cnt[a] - 1L\n#>         v <- v - ctx$fL[, a]\n#>     }\n#>     for (a in pi_) {\n#>         cnt[a] <- cnt[a] + 1L\n#>         v <- v + ctx$fL[, a]\n#>     }\n#>     s <- st$s\n#>     list(cnt = cnt, v = v, s = s, theta = sum(cnt * v)/(s * s))\n#> }\n#> <bytecode: 0xbcf6feee8>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\nFour rank-one column updates. No `N x N` matrix is touched, and the cost\ndepends on neither $N$ nor $m$. The state it maintains is three objects: the\nline-count vector `cnt`, the product `v = fL %*% cnt`, and their inner product\ndivided by $s^2$, which is $\\theta$. Removing a hybrid subtracts the two\ncolumns of `fL` belonging to its parents; adding one adds the two columns of\nthe entrant's parents. Because a swap keeps the set size fixed, the normaliser\n$s = 2n$ never changes.\n\nIt is an exact update, not an approximation, and that is checkable in three\nlines:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nst    <- theta_state(s, ctx)\nout_h <- s[1]\nin_h  <- setdiff(seq_len(ctx$N), s)[1]\nst2   <- theta_swap(st, out_h, in_h, ctx)\nafter <- c(setdiff(s, out_h), in_h)\nstopifnot(isTRUE(all.equal(st2$theta, theta_group(after, ctx))))\nc(incremental = st2$theta, recomputed = theta_group(after, ctx))\n#> incremental  recomputed \n#>   0.6863819   0.6863819\n```\n:::\n\n\nIf that identity ever fails, the state and the selection have drifted apart --\nthe usual cause being a move that was accepted in the selection vector but not\napplied to the state, or the reverse.\n\nThat last property is the one that matters, and it is worth being precise about\nwhere the saving actually comes from, because the obvious answer is wrong. The\nline *encoding* does not make an evaluation cheaper. Taking two rows of\n@sec-scaling's table:\n\n| route | at $N = 3600$ | at $N = 10{,}000$ |\n|---|---|---|\n| hybrid encoding, `mean(f[idx, idx])` | 40 us | 132 us |\n| line encoding, full fitness | 83 us | 169 us |\n| of which `decode_lines()`, which sorts all $N$ candidates | 77 us | 159 us |\n| incremental swap, no decode at all | **3.3 us** | **4.2 us** |\n\nThe line encoding is *slower* per evaluation, because decoding a weight vector\ninto a selection has to rank every candidate. What it buys is a smaller search\nspace, not a cheaper objective. The order-of-magnitude saving belongs to the\nswap -- and the swap is available only to a method that moves in the space of\nselections rather than decoding one from scratch each time.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nargs(sel_local_search)\n#> function (ctx, n_sel, alpha_max, gd_ref, start = NULL, max_use = NULL, \n#>     mode = c(\"hill\", \"anneal\", \"tempering\"), iters = 20000, n_chains = 8, \n#>     penalty = 5, t0 = NULL, swap_every = 50L, seed = NULL, trace = FALSE) \n#> NULL\n```\n:::\n\n\nThree modes, one driver, differing only in the temperature schedule. The driver\ndoes the following, and each step is a decision a breeder can inspect:\n\n1. **Start from a plan, never from noise.** `start = NULL` builds a warm start:\n   capped truncation, plus the greedy sweep whenever an $N \\times N$ `f` is\n   present. The test is literally `nrow(ctx[[\"f\"]]) == ctx$N`, and it is worth\n   being accurate about which branch produced the numbers in this chapter: the\n   production benchmark of @sec-scaling deliberately forms the 0.745 GiB matrix\n   so that the routes needing it can be timed at all, so **its rows took the\n   greedy branch**. Among the candidates it takes the highest-index one that\n   *meets the budget*, and if none does, the one with the smallest loss. As in\n   `sel_de()`, `NULL` never means \"start cold\".\n\n   The greedy branch is guarded, but the ranking that follows it is not: the\n   warm start scores every candidate with `alpha_loss()`, which reads `ctx$f`.\n   So `start = NULL` needs the $N \\times N$ matrix whichever branch it takes,\n   and on a context built without one it fails -- `subscript out of bounds`,\n   measured in @sec-ffree. Supplying an explicit `start =` skips the whole\n   function, and from there the search is `fL`-only; that is the call to make\n   if `f` does not fit in memory, and @sec-ffree is where the two are run side\n   by side.\n2. **Build the state.** `theta_state()` on the starting selection, plus the\n   running index sum and a logical membership vector, so that every later\n   question is $O(1)$ or $O(L)$.\n3. **Calibrate the temperature.** With `t0 = NULL` and a stochastic mode, the\n   driver proposes up to 200 random swaps, records the median absolute change\n   in the objective, and uses that as the starting temperature. Nothing about\n   the scale of the index is assumed, so the same call transfers between\n   datasets. `mode = \"hill\"` skips this entirely, since it never accepts a\n   worsening move.\n4. **Propose a feasible move.** Pick one of the $n$ selected crosses at random\n   to leave; draw entrants at random until one is found whose parents stay\n   under `max_use` once the leaving cross is removed, giving up after 20\n   attempts. The cap is tested, never punished.\n5. **Score it in $O(L)$.** `theta_swap()` for the new $\\theta$, one addition\n   and one subtraction for the new index sum, and the objective is\n   $\\bar u_S$ minus `penalty` times the budget violation *expressed in units of\n   the budget itself* -- the violation is divided by `alpha_max`, so a 5\n   becomes an effective slope of 500 index standard deviations per unit of\n   relative loss at a 1% budget, and 5000 at 0.1%. The tighter the budget, the\n   harder a violation is punished, which is the behaviour you want and is not\n   what `make_fitness()`'s fixed multiplier of 1000 on the *absolute* violation\n   does.\n6. **Accept or reject.** Improving moves are always accepted; worsening ones\n   with probability $\\exp(\\Delta / t_k)$ at the current temperature. The\n   best-ever selection is tracked separately from the current one and is what\n   is returned -- so a chain that wanders away at high temperature loses\n   nothing.\n\nTwo design points are worth stopping on.\n\n**The cap is tested, not punished.** Whether a swap keeps every line under\n`max_use` is an $O(1)$ question given the count vector, so infeasible moves are\nnever proposed. Penalising them instead spends the evaluation budget on being\nrejected -- with a tight cap that was the difference between the search\nimproving on its warm start and not moving at all.\n\n**The temperature calibrates itself.** A constant would not transfer between\ndatasets, so `t0 = NULL` samples the median absolute objective change over a\nshort burn-in and uses that.\n\nOne run of each is not a comparison. Three seeds -- 1, 2 and 3, the same three\nthe cached benchmark two subsections below uses, so the two panels are read\nagainst the same draws:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodes <- c(\"hill\", \"anneal\", \"tempering\")\nls_raw <- do.call(rbind, lapply(1:3, function(sd_) {\n  do.call(rbind, lapply(modes, function(m) {\n    # sel_local_search() sets the seed itself, immediately before its own draws.\n    s <- sel_local_search(ctx, n_sel, am, gd, mode = m, iters = 20000, seed = sd_)\n    data.frame(seed = sd_, mode = m, index = mean_index(s, ctx),\n               alpha_pct = 100 * alpha_loss(s, ctx, gd),\n               Ne_par = ne_parents(s, ctx), max_line = max_line_use(s, ctx))\n  }))\n}))\nls_res <- do.call(rbind, lapply(modes, function(m) {\n  d <- ls_raw[ls_raw[[\"mode\"]] == m, ]\n  data.frame(mode = m, index = mean(d[[\"index\"]]), index_sd = sd(d[[\"index\"]]),\n             alpha_pct = mean(d[[\"alpha_pct\"]]), Ne_par = mean(d[[\"Ne_par\"]]),\n             max_line = max(d[[\"max_line\"]]))\n}))\n# The same three modes and the same three seeds in the cached benchmark below,\n# which runs 30,000 moves instead of 20,000.\nbmode <- vapply(modes, function(m)\n  mean(bench$index[bench$scale == \"book\" & bench$method == m]), numeric(1))\nfmt(ls_res, 3)\n```\n\n::: {.cell-output-display}\n\n|mode      | index| index_sd| alpha_pct| Ne_par| max_line|\n|:---------|-----:|--------:|---------:|------:|--------:|\n|hill      | 1.526|    0.002|     0.999| 20.553|       13|\n|anneal    | 1.520|    0.002|     0.996| 20.514|       14|\n|tempering | 1.493|    0.004|     0.993| 20.854|       13|\n\n:::\n\n```{.r .cell-code}\nfmt(rbind(here_20000 = setNames(ls_res[[\"index\"]], modes),\n          benchmark_30000 = bmode), 4)\n```\n\n::: {.cell-output-display}\n\n|                |   hill| anneal| tempering|\n|:---------------|------:|------:|---------:|\n|here_20000      | 1.5264| 1.5202|    1.4933|\n|benchmark_30000 | 1.5274| 1.5276|    1.5132|\n\n:::\n:::\n\n\nNote that `iters` is the total number of proposed moves *summed over chains*,\nso the three modes cost about the same wall-clock at equal `iters` and the\ncomparison above is a fair one. In tempering mode those 20,000 moves are split\nacross `n_chains` replicas on a geometric temperature ladder spanning three\ndecades, exchanging adjacent rungs every `swap_every` moves.\n\nThe realised `alpha` sits against the 1% budget in every mode: the constraint\nis doing its job, and the search is spending the diversity it was allowed.\n\nThree checks before a plan from this function is used, in this order: realised\n$\\alpha$ against the budget (a plan far inside it means the search never\nreached the boundary, or the penalty was too steep); `max_line` against the cap\nyou set; and $N_{e,\\text{par}}$, which is free and catches the case where\n$\\theta$ is satisfied by a handful of lines used many times each.\n\nResult. Over the three seeds the three schedules span\n2.2% of\nindex, against a within-mode seed-to-seed standard deviation of at most\n0.24% -- so\nthe ordering at this iteration count, `\"hill\"` and `\"anneal\"` within\n0.4%\nof each other and `\"tempering\"` behind both, is not a seed artefact.\n\nInterpretation, and what limits it. Splitting a fixed move budget across\ntempering's replicas costs more than the exchanges return at this size -- a\nstatement about `iters = 20000` on 625 candidates, not about parallel\ntempering. The hill-versus-anneal ordering in particular does **not** survive a\nchange in budget, which is why the second panel prints both: at 20,000 moves\n`\"hill\"` leads `\"anneal\"` by\n6.2 thousandths of\nan index unit -- more than the\n3.7-thousandth within-mode standard\ndeviation, so not noise at that budget -- while at the benchmark's 30,000 moves\nthe sign flips to\n0.2 thousandths in\n`\"anneal\"`'s favour. That ordering is therefore a property of the move budget\nand not of the schedule. Read this panel as evidence that the\ntemperature schedule is a second-order choice at fixed move budget -- not as a\nranking of the three, and not as a claim that the move rather than the schedule\nis what buys the index. That claim is a comparison against the other methods\nand it belongs to the benchmark below, which has the dispersion to support it.\n\n### Against the differential evolution, at equal wall-clock\n\nEqual *evaluations* is the wrong comparison when one evaluation costs\nseventeen times what another does. The honest axis is seconds.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Best index reached against wall-clock seconds, at book scale under a 1% diversity budget. The dashed line is the Lagrangian bound of @sec-bound. Local search is at 1.52 within a tenth of a second; the differential evolution reaches only 1.45 after two seconds.](figs/search_anytime.png){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Book scale, mean of 3 seeds, 1% diversity budget. The gap is against the certified Lagrangian bound.\n\n|method        | index| loss %| Ne parents| max uses| seconds| gap to bound %|\n|:-------------|-----:|------:|----------:|--------:|-------:|--------------:|\n|anneal        | 1.528|  0.999|     20.594|       13|   0.232|          1.718|\n|hill          | 1.527|  0.998|     20.552|       13|   0.225|          1.733|\n|tempering     | 1.513|  0.998|     20.750|       13|   0.222|          2.645|\n|ocs_round     | 1.487|  0.895|     20.749|       14|   0.009|          4.339|\n|greedy        | 1.378|  0.550|     21.818|       13|   0.008|         11.331|\n|de_hybrid     | 1.360|  0.960|     22.314|       14|   0.846|         12.517|\n|greedy_cap    | 1.112|  0.968|     25.000|        5|   0.008|         28.445|\n|de_hybrid_cap | 1.110|  0.976|     25.263|        5|   0.961|         28.604|\n|tempering_cap | 1.110|  0.976|     25.263|        5|   0.286|         28.604|\n|de_lines_cap  | 1.106|  0.881|     25.714|        5|   1.563|         28.870|\n|ocs_round_cap | 1.106|  0.881|     25.714|        5|   0.010|         28.870|\n|de_lines      | 1.059|  0.996|     16.314|       11|   0.800|         31.843|\n\n\n:::\n:::\n\n\nRead that table by columns rather than by rank. `index` orders the methods;\n`loss %` says which of them actually spent the budget; `max uses` says which\nwere capped, since the capped variants are solving a strictly harder problem\nand must not be compared with the uncapped ones on index alone; `seconds` is\nthe axis the ranking is conditional on; and `gap to bound %` is the only column\nthat says whether the leader is near optimal or merely ahead of the others. The\ngreedy row is the one to keep in view: swept finely over $w$ it reaches index\n1.378 in 8 ms, which\nis 9.8% below the\nleading method at about\n29x less wall-clock. Whether\nthat shortfall is worth 0.23 seconds is a question\nabout the programme, not about the algorithm -- at production scale the same\nratio is what decides whether a frontier of ten budgets is an afternoon or a\nminute.\n\nThis table is also where the move-versus-schedule question can actually be\nsettled, because it has replication on both sides of it and both scales:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmv <- do.call(rbind, lapply(c(\"book\", \"production\"), function(sc) {\n  d   <- bench[bench$scale == sc, ]\n  m   <- aggregate(index ~ method, d, mean)\n  ls_ <- m[[\"index\"]][m[[\"method\"]] %in% modes]\n  de_ <- m[[\"index\"]][m[[\"method\"]] %in% c(\"de_hybrid\", \"de_lines\")]\n  sds <- aggregate(index ~ method, d[d$method %in% modes, ], sd)\n  data.frame(scale = sc, schedule_spread = diff(range(ls_)),\n             best_swap_minus_best_de = max(ls_) - max(de_),\n             ratio = (max(ls_) - max(de_)) / diff(range(ls_)),\n             max_seed_sd = max(sds[[\"index\"]]),\n             hill_minus_anneal =\n               mean(d[[\"index\"]][d[[\"method\"]] == \"hill\"]) -\n               mean(d[[\"index\"]][d[[\"method\"]] == \"anneal\"]))\n}))\nfmt(mv, 4)\n```\n\n::: {.cell-output-display}\n\n|scale      | schedule_spread| best_swap_minus_best_de|   ratio| max_seed_sd| hill_minus_anneal|\n|:----------|---------------:|-----------------------:|-------:|-----------:|-----------------:|\n|book       |          0.0144|                  0.1679| 11.6579|      0.0040|           -0.0002|\n|production |          0.1267|                  0.3701|  2.9217|      0.0059|            0.0024|\n\n:::\n:::\n\n\nResult. The three temperature schedules share one move and span\n0.014 index units at book scale and\n0.127 at production, with a within-mode\nseed-to-seed standard deviation of at most\n0.0059. The best of them sits\n0.168 units above the better of the\ntwo differential evolutions at book scale and\n0.37 at production --\n11.7x and 2.9x the spread\namong the schedules respectively, and in a fraction of the wall-clock in both\ncases -- the `seconds` column above at book scale, and the production panel of\n@sec-scaling at the other.\n\nInterpretation. What moves the index at both scales measured is the\nneighbourhood the search moves in -- the $O(L)$ swap, available only to a\nmethod that does not decode a selection from scratch -- rather than the\nschedule wrapped around it. Two things limit that: the ratio is\n4 times smaller at production\nthan at book scale, so it narrows with $N$ rather than holding constant; and\nit rests on three seeds per cell, where the DE arms carry the larger\ndispersion. It is a comparison of two families at two sizes, not a law.\n\n::: {.callout-tip}\n## What the literature says about picking a metaheuristic\n\n@debeukelaer2018, on core-collection subsets, found a plain stochastic\nhill-climber already competitive with a considerably more complex genetic\nalgorithm, and parallel tempering winning by combining many simple local\nsearches rather than by being individually cleverer.\n\n@yadav2025 compared GA, DE, PSO and SA head to head on parent selection in\nwheat and ranked them by convergence AUC at 0.879, 0.860, 0.820 and 0.769, with\nDE running two to three times slower than GA for a marginally worse result. The\ncurrent tools agree: TrainSel [@akdemir2021], which drives MateR\n[@fernandezgonzalez2026], is a genetic algorithm hybridised with simulated\nannealing.\n\nSo the differential evolution of @sec-combinatorial is not the obvious choice,\nand never was. What it had going for it was the warm start. What it lacked was\na cheap move.\n:::\n\n### The encoding, wired up at last\n\n@sec-combinatorial measures the line encoding against a fully $N$-dimensional\none -- one random key per hybrid -- and finds a 5.7x margin in the line\nencoding's favour at equal budget. That is a verdict on $N$-dimensional\nencodings, not a verdict on `sel_de()`, whose search space is $n_{sel}$\ncoordinates wide; the head-to-head between the two encodings the package\nactually ships is in this chapter's own benchmark below, and it goes the other\nway. What is true regardless is that `decode_lines()` and `make_fitness_fast()`\nhave been exported since the line route was written with nothing driving them.\n`sel_de_fast()` closes that:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsel_de_fast\n#> function (ctx, n_sel, gd_ref, alpha_max, ne_par_min = NULL, max_use = NULL, \n#>     pool_tol = NULL, NP = 300, itermax = 2000, seeds = NULL, \n#>     trace = FALSE) \n#> {\n#>     if (is.null(ctx$parents)) \n#>         ctx <- fast_ctx(ctx)\n#>     L <- ctx$n_lines\n#>     fit <- make_fitness_fast(ctx, n_sel, gd_ref, alpha_max, ne_par_min = ne_par_min, \n#>         max_use = max_use, pool_tol = pool_tol)\n#>     if (is.null(seeds)) {\n#>         v <- -rowMeans(ctx$fL)\n#>         v <- (v - min(v))/max(max(v) - min(v), 1e-12)\n#>         seeds <- lapply(seq(0, 1, length.out = 8), function(s) s * \n#>             v)\n#>     }\n#>     initial <- matrix(stats::runif(NP * L), NP, L)\n#>     for (i in seq_len(min(length(seeds), NP))) initial[i, ] <- seeds[[i]]\n#>     ctrl <- DEoptim::DEoptim.control(NP = NP, itermax = itermax, \n#>         trace = trace, initialpop = initial)\n#>     res <- DEoptim::DEoptim(fit, lower = rep(0, L), upper = rep(1, \n#>         L), control = ctrl)\n#>     decode_lines(as.numeric(res$optim$bestmem), ctx, n_sel, max_use)\n#> }\n#> <bytecode: 0xbcda307b0>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\nWhat the call does, in order:\n\n1. Builds the fast fitness: decode the line weights into a selection, tabulate\n   the parent counts, evaluate $\\theta = \\mathbf{w}'\\mathbf{f}^L\\mathbf{w}$ on\n   the used lines only, and add one proportional penalty per active\n   restriction -- diversity budget, minimum $N_{e,\\text{par}}$, per-line cap,\n   pool balance. No $N \\times N$ matrix is formed or indexed anywhere.\n2. Builds the seeds. They sweep a **line-diversity direction**, not a merit\n   weight: `p` proportional to the negated mean coancestry of each line, at\n   eight increasing strengths from zero to one.\n3. Searches the box $[0, 1]^L$ with `DEoptim`, and decodes the best member.\n\nThe zero-strength seed is worth isolating, because it is the natural origin of\nthe encoding: with every line weight at zero the decoder ranks on index alone\nand takes crosses greedily under the cap, which is capped truncation exactly.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncap <- ceiling(2 * n_sel / ctx$n_lines) + 1\nzero_w <- decode_lines(rep(0, ctx$n_lines), ctx, n_sel, max_use = cap)\nstopifnot(identical(as.integer(zero_w),\n                    as.integer(sel_truncation_cap(ctx, n_sel, cap = cap))))\nc(cap = cap, index = mean_index(zero_w, ctx),\n  alpha_pct = 100 * alpha_loss(zero_w, ctx, gd),\n  max_line = max_line_use(zero_w, ctx))\n#>       cap     index alpha_pct  max_line \n#> 4.0000000 0.8203555 0.3257287 4.0000000\n```\n:::\n\n\nThe seeds sweep a line-diversity direction rather than a merit weight, but the\nprinciple is @sec-combinatorial's unchanged: `seeds = NULL` builds the sweep and\nnever means \"start cold\". The practical consequence of the identity above is\nthat the population always contains at least one plan that respects the cap by\nconstruction, whatever the diversity penalty later does.\n\n#### What it is actually for {#sec-defast-restrictions}\n\n`sel_de_fast()` is the only route in this package that accepts more than a\nbudget and a cap, so the case for it has to be made where those extra\nrestrictions are active. Here they are, all four at once, run rather than\ndescribed:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncap4  <- ceiling(4 * n_sel / ctx$n_lines)     # the benchmark's cap, not the default\npool_share <- function(s) mean(ctx$pool[as.vector(ctx$parents[s, ])] == \"A\")\n\nde_fast <- do.call(rbind, lapply(c(20, 25, 30), function(nemin) {\n  set.seed(7)\n  s <- suppressWarnings(\n    sel_de_fast(ctx, n_sel, gd, am, ne_par_min = nemin, max_use = cap4,\n                pool_tol = 0.05, NP = 100, itermax = 300))\n  data.frame(Ne_floor = nemin, index = mean_index(s, ctx),\n             alpha_pct = 100 * alpha_loss(s, ctx, gd),\n             Ne_par = ne_parents(s, ctx), max_line = max_line_use(s, ctx),\n             pool_A = pool_share(s))\n}))\nfmt(de_fast, 4)\n```\n\n::: {.cell-output-display}\n\n| Ne_floor|  index| alpha_pct|  Ne_par| max_line| pool_A|\n|--------:|------:|---------:|-------:|--------:|------:|\n|       20| 1.1056|    0.8859| 25.7143|        5|    0.5|\n|       25| 1.1056|    0.8859| 25.7143|        5|    0.5|\n|       30| 1.1056|    0.8859| 25.7143|        5|    0.5|\n\n:::\n\n```{.r .cell-code}\nc(distinct_plans_over_the_three_floors =\n    length(unique(round(de_fast[[\"index\"]], 12))))\n#> distinct_plans_over_the_three_floors \n#>                                    1\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(7)\nls_capped <- sel_local_search(ctx, n_sel, am, gd, mode = \"anneal\",\n                              iters = 20000, max_use = cap4, seed = 7)\nfmt(c(de_fast_index          = de_fast[[\"index\"]][de_fast[[\"Ne_floor\"]] == 25],\n      local_search_index     = mean_index(ls_capped, ctx),\n      local_search_alpha_pct = 100 * alpha_loss(ls_capped, ctx, gd),\n      local_search_Ne        = ne_parents(ls_capped, ctx),\n      local_search_max_line  = max_line_use(ls_capped, ctx)), 4)\n#>          de_fast_index     local_search_index local_search_alpha_pct \n#>                 1.1056                 1.1102                 0.9614 \n#>        local_search_Ne  local_search_max_line \n#>                25.0871                 5.0000\n```\n:::\n\n\nThree readings, in the order they narrow the recommendation.\n\n**The cap is satisfied by construction and the pool balance is free.**\n`max_line` equals the cap in every row, because the decoder never proposes a\nplan that breaks it. `pool_A` is exactly 0.5 in every row, and not because the\nsearch found it: in a complete factorial every cross spends one pool-A slot and\none pool-B slot, so the `matroid-check` panel above already forced it. Of the\nfour restrictions `make_fitness_fast()` accepts, one is structural and cannot\nbind in this mating design.\n\n**The $N_{e,\\text{par}}$ floor does not shape the plan either.** All three\nfloors return the *same* selection, at $N_{e,\\text{par}} =$\n25.71: met with room to spare at 20 and 25, missed\nat 30 with a penalty that does not recover it. The restriction that is actually\ndeciding the plan is the cap -- 120 parent slots over\n50 lines is a mean usage of\n2.4, against a cap of 5. That is the\ndiagnosis of @sec-scaling arriving early: compare $2n/L$ with the cap before\ncrediting any other restriction with the shape of a plan.\n\n**And it still does not lead on index.** Under the same budget and the same\ncap, a plain annealed local search reaches\n1.11 against `sel_de_fast()`'s\n1.106. The honest recommendation is\ntherefore narrow: reach for `sel_de_fast()` when a restriction exists that the\nswap neighbourhood cannot test -- an $N_{e,\\text{par}}$ floor that actually\nbinds, or an incomplete factorial where pool balance is a real degree of\nfreedom -- and not because it optimises better, because on every number in this\nchapter it does not.\n\n## The bound was not a bound {#sec-bound}\n\n@sec-relaxation introduces the continuous relaxation as an upper bound, and the\nconvergence check of @sec-combinatorial was originally written to take the best\nrelaxation point whose own `alpha` falls inside the budget. That construction\nis **not valid**, and it is worth showing rather than asserting.\n\nThe relaxation at a given $\\lambda$ maximises $\\mathbf{c}'\\mathbf{u} - \\lambda\\,\n\\mathbf{c}'\\mathbf{f}\\mathbf{c}$ -- a penalised objective, not the index. Its\noptimum happens to land at some diversity, but nothing makes it the best index\nachievable *at* that diversity. A discrete plan can beat it, and does:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlam   <- 10^seq(-1, 3, length.out = 12)\nrel   <- ocs_relaxation(ctx, n_sel, lam, iters = 2000)\na_rel <- (gd - rel[, \"GD\"]) / gd\nV     <- rel[, \"index\"] - lam * rel[, \"theta\"]     # the relaxation's dual value\n\ncmp <- do.call(rbind, lapply(c(0.0025, 0.005, 0.01, 0.02), function(a) {\n  ok  <- a_rel <= a\n  old <- if (any(ok)) max(rel[ok, \"index\"]) else NA_real_\n  new <- min(V + lam * (1 - gd * (1 - a)))  # the Lagrangian form, under-converged\n  best <- max(vapply(\n    Filter(function(s) alpha_loss(s, ctx, gd) <= a + 1e-12,\n           c(list(sel_local_search(ctx, n_sel, a, gd, mode = \"anneal\",\n                                   iters = 8000, seed = 1)),\n             lapply(c(0, .5, 1, 2, 4, 8, 16), function(w) sel_greedy(ctx, n_sel, w = w)))),\n    mean_index, numeric(1), ctx = ctx))\n  data.frame(alpha_max = a, feasible_plan = best, old_bound = old,\n             lagrangian_2000 = new, old_valid = old >= best - 1e-9,\n             lagrangian_valid = new >= best - 1e-9)\n}))\nfmt(cmp, 4)\n```\n\n::: {.cell-output-display}\n\n| alpha_max| feasible_plan| old_bound| lagrangian_2000|old_valid |lagrangian_valid |\n|---------:|-------------:|---------:|---------------:|:---------|:----------------|\n|    0.0025|        1.2824|    0.8459|          1.3373|FALSE     |TRUE             |\n|    0.0050|        1.3566|    0.8459|          1.4034|FALSE     |TRUE             |\n|    0.0100|        1.5202|    1.4879|          1.5355|FALSE     |TRUE             |\n|    0.0200|        1.7365|    1.4879|          1.7998|FALSE     |TRUE             |\n\n:::\n:::\n\n\nThe experiment is a falsification, not an illustration. `feasible_plan` is the\nbest plan any method in this book could find *inside* the stated budget;\n`old_bound` is what the discarded construction would have reported; a valid\nupper bound must be at least `feasible_plan` in every row. The `old_valid`\ncolumn is FALSE at all four budgets tested -- the \"bound\" is below a plan that\nexists, which is a contradiction and not a tight bound.\n\n`lagrangian_2000` is the correct *form* evaluated at a deliberately cheap\nsetting -- 12 multipliers, 2,000 projected-gradient iterations -- and it is\nhere only to show that the form survives where the construction does not.\n**It is not a certified bound and nothing downstream of this chunk quotes it.**\nThe certified value comes from `ocs_bound()` below.\n\nThe correct statement is a Lagrangian one, and it takes a line. Any selection\n$S$ of size $n$ has an equal-weight contribution vector feasible for the\nrelaxation, so with $V(\\lambda)$ the relaxation's optimal value,\n\n$$V(\\lambda) \\;\\ge\\; \\bar u_S - \\lambda\\,\\theta_S \\;\\ge\\; \\bar u_S - \\lambda\\,\\theta_{\\max}$$\n\nfor every $S$ meeting the budget, and therefore\n$\\bar u_S \\le V(\\lambda) + \\lambda\\,\\theta_{\\max}$ for **every** non-negative\n$\\lambda$. The tightest such statement is the minimum over $\\lambda$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nocs_bound\n#> function (ctx, n_sel, alpha_max, gd_ref, lambdas = 10^seq(-1, \n#>     3, length.out = 25), iters = 4000, lines = NULL, tol = 0.001, \n#>     max_doublings = 6L) \n#> {\n#>     theta_max <- 1 - gd_ref * (1 - alpha_max)\n#>     at <- function(it) {\n#>         rel <- ocs_relaxation(ctx, n_sel, lambdas, iters = it, \n#>             lines = lines)\n#>         b <- rel[, \"index\"] - lambdas * rel[, \"theta\"] + lambdas * \n#>             theta_max\n#>         j <- which.min(b)\n#>         list(v = b[j], lam = lambdas[j], rel = rel, iters = it)\n#>     }\n#>     cur <- at(iters)\n#>     converged <- FALSE\n#>     for (k in seq_len(max_doublings)) {\n#>         nxt <- at(2L * cur$iters)\n#>         done <- abs(nxt$v - cur$v) <= tol * max(abs(cur$v), 1e-12)\n#>         cur <- nxt\n#>         if (done) {\n#>             converged <- TRUE\n#>             break\n#>         }\n#>     }\n#>     if (!converged) \n#>         warning(\"ocs_bound() did not converge in \", max_doublings, \n#>             \" doublings (last \", cur$iters, \" iterations). An under-converged \", \n#>             \"relaxation understates V(lambda), so this may not be a valid \", \n#>             \"bound. Raise `iters`, `max_doublings`, or pass `lines = TRUE`.\")\n#>     structure(cur$v, lambda = cur$lam, relaxation = cur$rel, \n#>         iters = cur$iters, converged = converged, names = NULL)\n#> }\n#> <bytecode: 0xbce5edb60>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\nTo use it: translate the budget into\n$\\theta_{\\max} = 1 - \\text{gd\\_ref}(1 - \\alpha_{\\max})$; solve the relaxation\nat each $\\lambda$ to get $V(\\lambda)$; take the minimum of\n$V(\\lambda) + \\lambda\\,\\theta_{\\max}$; and **read the `converged` attribute\nbefore quoting anything**. The function doubles its iteration count until the\nvalue stops moving because the value rises monotonically with iterations, so an\nunder-converged run reports the bound too small -- the one failure mode that\nturns a bound into a wrong number rather than a loose one.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbound <- ocs_bound(ctx, n_sel, am, gd)\nfmt(c(hand_12_lambdas_2000_iters = min(V + lam * (1 - gd * (1 - am))),\n      ocs_bound                  = as.numeric(bound),\n      lambda_star                = attr(bound, \"lambda\"),\n      iterations                 = attr(bound, \"iters\"),\n      theta_max                  = 1 - gd * (1 - am)), 4)\n#> hand_12_lambdas_2000_iters                  ocs_bound \n#>                     1.5355                     1.5532 \n#>                lambda_star                 iterations \n#>                    68.1292                  8000.0000 \n#>                  theta_max \n#>                     0.6774\nattr(bound, \"converged\")\n#> [1] TRUE\n```\n:::\n\n\nThe two numbers in the first two rows are the same formula at two iteration\ncounts, and the gap between them is the failure mode named in the paragraph\nabove, measured. The cheap sweep reports\n1.5355; the converged run reports\n1.5532, higher by\n1.16%.\nUnder-convergence pushes a Lagrangian bound *down*, which is the one direction\nthat turns it into a wrong number rather than a loose one. Everything this\nchapter quotes as a bound from here on is `bound`, the certified object.\n\nTwo practical consequences. Every $\\lambda$ gives a valid bound, so a coarse\ngrid costs tightness and never validity -- unlike the old construction, where a\ncoarse grid could silently produce a \"bound\" below the achievable. And the bound\nis now usable as a stopping rule: when the gap is small, further optimiser\neffort is provably wasted.\n\n::: {.callout-warning}\n## This changes a number in @sec-combinatorial\n\nThe convergence check in @sec-combinatorial once used the invalid\nconstruction, and the gap it reported was not a gap. That chapter now calls\n`ocs_bound()`, and the number there is the Lagrangian one; its qualitative\nconclusion survived the correction -- the warm-started DE does sit below the\nfrontier, and the size of the shortfall is what @sec-localsearch closes. The\nlesson is the one that generalises: a quantity is only a bound if a feasible\nsolution can never exceed it, and that is a property to test, not to assume.\n\n**@sec-relaxation has not been rewritten to match, and the contradiction is\nnamed here rather than left to be discovered.** That section still describes\neach row of its $\\lambda$ sweep as \"an upper bound on what any discrete plan of\nthe same diversity can achieve\", and its figure caption still says discrete\nstrategies must sit below and to the left of the curve. Both statements are the\nconstruction falsified above. Until that text is corrected, read\n@sec-relaxation's curve as a relaxation -- a penalised optimum at each\n$\\lambda$, nothing more -- and take every bound in this book from\n`ocs_bound()`.\n:::\n\n## Rounding the relaxation into a plan\n\nWith a bound in hand, the relaxation stops being only a diagnostic. Solve the\noptimal-contribution programme in **line** space, where `quadprog` returns\ninstantly because the dimension is $L$, round the contributions to integer line\nusage, and assign concrete crosses under both pools' caps. That two-stage shape\n-- contributions first, mate allocation second -- is exactly @waldmann2025's,\nwhose mate-allocation stage solves in under 0.01 seconds.\n\nThe five steps inside `ocs_round()`, in the order they run:\n\n1. **Line merit.** Each line is scored by the mean index of the hybrids it\n   parents in the candidate set. That quantity is a general combining ability:\n   a property of the line *against the opposite pool as represented in this\n   factorial*, never a property of the line alone (@sec-heterosis-gca-sca).\n   Change the tester pool and the score changes.\n2. **Contributions.** `ocs_quadprog()` on `ctx$fL` with those merits, at a\n   given $\\lambda$, with each line's contribution capped at\n   $\\texttt{max\\_use} / 2n$ -- the cap expressed as a share of the $2n$ parent\n   slots.\n3. **Rounding.** Contributions times $2n$, floored, and the shortfall handed to\n   the largest remainders; then clipped at `max_use` again.\n4. **Mate allocation.** Walk the candidates in decreasing index and take each\n   cross whose two parents still have quota and are under the cap -- a greedy\n   b-matching. If quota runs out before $n$ crosses are found, top up on the\n   cap alone, because the quota is a rounding artefact and the cap is the real\n   restriction.\n5. **Choose $\\lambda$ by budget, not by preference.** The whole sweep is\n   evaluated and the plan returned is the best-index one whose realised\n   $\\alpha$ respects `alpha_max`. The exchange rate stays an internal detail;\n   the budget remains the interface.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr <- ocs_round(ctx, n_sel, am, gd, bound = as.numeric(bound))\nfmt(c(index = r[[\"index\"]], alpha_pct = 100 * r[[\"alpha\"]],\n      lambda = r[[\"lambda\"]], bound = r[[\"bound\"]],\n      gap_pct = 100 * r[[\"gap\"]]), 4)\n#>     index alpha_pct    lambda     bound   gap_pct \n#>    1.4869    0.8998   52.7500    1.5532    4.2729\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#>        here_index   benchmark_index       here_gd_ref        here_bound \n#>           1.48688           1.48688           0.32584           1.55324 \n#>   benchmark_bound      here_gap_pct benchmark_gap_pct \n#>           1.55432           4.27288           4.33929\n```\n:::\n\n\nThat second panel exists because the benchmark table of @sec-localsearch\nreports this same method and does not report exactly this gap. The plan is\nidentical -- both reach index 1.486876 -- and the whole\ndifference is in `gd_ref`: this chapter resamples the random reference at\n$B = 400$ and the cached benchmark at $B = 500$, so\n$\\theta_{\\max} = 1 - \\text{gd\\_ref}(1 - \\alpha_{\\max})$ differs in the fourth\ndecimal and the bound with it. Two draws of the same reference, not two\nresults. What would be a real discrepancy, and was one until this section was\ncorrected, is a gap computed against an *uncertified* bound: the cheap sweep\nabove would have reported\n3.17%\nhere, more than a point tighter than the truth, because the quantity it divides\nby is too small.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfmt(r[[\"frontier\"]], 4)\n```\n\n::: {.cell-output-display}\n\n|   lambda|  index|   alpha|\n|--------:|------:|-------:|\n|   0.1000| 1.9919|  0.0412|\n|   0.2448| 1.9919|  0.0412|\n|   0.5995| 1.9919|  0.0412|\n|   1.4678| 1.9919|  0.0412|\n|   3.5938| 1.9919|  0.0412|\n|   8.7992| 1.9919|  0.0412|\n|  21.5443| 1.9741|  0.0365|\n|  52.7500| 1.4869|  0.0090|\n| 129.1550| 0.7365| -0.0093|\n| 316.2278| 0.4064| -0.0125|\n\n:::\n:::\n\n\nThe frontier table is the step-5 diagnostic: at small $\\lambda$ the programme\nputs everything on the best lines and the realised loss exceeds the budget; at\nlarge $\\lambda$ it spreads contributions and the loss goes negative -- more\ndiverse than a random subset. The plan returned is the highest-index row that\nrespects the budget, which because index falls monotonically with $\\lambda$ is\nthe smallest feasible $\\lambda$ on the grid. If *no* row is feasible the\nfunction falls back to the least-loss one, which is a result to notice rather\nthan to use -- the returned `alpha` is then above `alpha_max` and nothing in\nthe call will say so.\n\nThe rounding is visible in the plan itself. Line usage should track combining\nability, and it does:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmerit <- tapply(rep(ctx$index, 2),\n                factor(c(ctx$parents[, 1], ctx$parents[, 2]),\n                       levels = seq_len(ctx$n_lines)), mean)\nused  <- line_counts(r[[\"idx\"]], ctx)\nisA   <- ctx$pool == \"A\"\nc(cor_merit_usage_A = cor(merit[isA], used[isA]),\n  cor_merit_usage_B = cor(merit[!isA], used[!isA]),\n  lines_used_A      = sum(used[isA] > 0),\n  lines_used_B      = sum(used[!isA] > 0),\n  max_line          = max(used))\n#> cor_merit_usage_A cor_merit_usage_B      lines_used_A      lines_used_B \n#>         0.9392334         0.8125721        11.0000000        21.0000000 \n#>          max_line \n#>        14.0000000\n```\n:::\n\n\nResult: usage correlates with line merit at 0.94\nin pool A and 0.81 in pool B, over\n32 lines of 50 actually used.\nInterpretation: the quadratic programme is doing what an\noptimal-contribution scheme is supposed to do -- allocate more crosses to\nbetter general combiners and stop where relatedness makes the next cross\nexpensive. Note that this call passes no `max_use`, so the plan's\n`max_line` is whatever the coancestry term alone permits; with a cap set, the\nbound stays valid but goes loose, because the relaxation it comes from carries\nno cap and therefore bounds an easier problem.\n\nIt is not the best method here, and it is not meant to be. What it gives is a\nplan and a certificate in one call, at a cost that does not grow with $N$ in\nthe part that matters -- and a sanity check on everything else.\n\n## Exact, and how far the heuristics really are {#sec-oa}\n\nEverything so far is a heuristic with a bound. The remaining question is what\nthe true optimum is, and the honest answer requires solving the problem exactly\nat a scale where that is possible.\n\nThe obvious route is closed. Maximising a linear index subject to a **quadratic**\ndiversity constraint over binary variables is a mixed-integer quadratically\nconstrained programme, and HiGHS -- like most open solvers -- does not accept a\nquadratic term together with integer variables at all.\n\nConvexity opens a different one. Because `f` is positive semi-definite,\n$\\mathbf{x}'\\mathbf{f}\\mathbf{x}$ is convex, so its tangent at any point is a\nvalid linear *under*-estimate, and\n\n$$\\bar{\\mathbf{x}}'\\mathbf{f}\\bar{\\mathbf{x}} + 2(\\mathbf{f}\\bar{\\mathbf{x}})'(\\mathbf{x} - \\bar{\\mathbf{x}}) \\;\\le\\; b$$\n\nis a linear relaxation of $\\mathbf{x}'\\mathbf{f}\\mathbf{x} \\le b$. Solve the\nresulting mixed-integer **linear** programme, add a cut wherever the solution\nviolates the true constraint, re-solve. This is outer approximation\n[@duran1986], it needs only a MILP solver, and it terminates: each cut strictly\nremoves the infeasible point that generated it.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nargs(sel_exact)\n#> function (ctx, n_sel, alpha_max, gd_ref, max_use = NULL, start = NULL, \n#>     max_cuts = 200L, time_limit = 60) \n#> NULL\n```\n:::\n\n\nThe loop, step by step:\n\n1. **Translate the budget.** The diversity constraint becomes\n   $\\mathbf{x}'\\mathbf{f}\\mathbf{x} \\le n^2\\,\\theta_{\\max}$ with\n   $\\theta_{\\max} = 1 - \\text{gd\\_ref}(1 - \\alpha_{\\max})$ -- the same quantity\n   as in the Lagrangian bound, expressed in submatrix-sum units because that is\n   what the solver sees.\n2. **Write the structural rows.** One cardinality row summing to $n$, and one\n   row per line for the partition matroid when `max_use` is set. Those are\n   linear and exact; only the quadratic needs approximating.\n3. **Carry an incumbent from the start.** The warm start is the same\n   `sel_local_search()` warm start; if it satisfies the budget it becomes the\n   incumbent and is handed to the solver as a starting point, so that a run\n   stopped by the clock still reports a real interval.\n4. **Solve, cut, repeat.** If the MILP solution satisfies the true quadratic\n   constraint, it is optimal for the current relaxation and the loop can stop;\n   otherwise a gradient cut at that point is added and the MILP re-solved.\n5. **Read the dual bound from the right field.** `objective_value` is an upper\n   bound only for a MILP solved to optimality; the moment the solver hits its\n   own time limit the bound must come from `mip_dual_bound`. Cuts only tighten\n   the relaxation, so the running minimum over iterations stays valid.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(theta_max       = 1 - gd * (1 - am),\n  budget_xfx      = n_sel^2 * (1 - gd * (1 - am)),\n  binary_vars     = ctx$N,\n  structural_rows = 1 + ctx$n_lines)\n#>       theta_max      budget_xfx     binary_vars structural_rows \n#>       0.6774198    2438.7113298     625.0000000      51.0000000\n```\n:::\n\n\nIt also returns more than a black-box call would. The MILP objective is a valid\nupper bound at every iteration and the warm start supplies a feasible\nincumbent, so a run stopped by the clock still hands back a **certified\ninterval** containing the true optimum.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: The oracle, seeded with the local-search solution so that a timed-out run still reports a real interval. `status` is \"optimal\" only where the loop proved it.\n\n|scale |   N|  n| budget %| local search| incumbent| dual bound|status     | cuts| seconds|   gap %|\n|:-----|---:|--:|--------:|------------:|---------:|----------:|:----------|----:|-------:|-------:|\n|tiny  |  36|  8|      0.5|       1.1215|    1.1215|     1.1215|optimal    |   40|   7.135|  0.0000|\n|tiny  |  36|  8|      1.0|       1.1277|    1.1277|     1.1277|optimal    |   73|  14.667|  0.0000|\n|tiny  |  36|  8|      2.0|       1.2500|    1.2500|     1.2500|optimal    |   20|   1.846|  0.0000|\n|book  | 625| 60|      0.5|       1.3804|    1.3804|     1.6424|time limit |    4| 300.487| 15.9535|\n|book  | 625| 60|      1.0|       1.5280|    1.5280|     1.6995|time limit |    4| 300.509| 10.0943|\n\n\n:::\n:::\n\n\nRead the two halves separately, because they say opposite things.\n\nAt tiny scale the loop **proves** optimality, and the local search matches the\nproven optimum to machine precision at every budget -- the gap is not small,\nit is zero. That is the result worth having: on instances where the truth is\nknowable, the heuristic is not leaving anything on the table at all.\n\nAt book scale the loop does not converge, and would not at production scale\neither. Gradient cuts on a dense quadratic are weak, each MILP re-solve is\nexpensive, and the number of cuts needed grows fast. @ahadi2024, solving an\ninteger programme for mate selection with a commercial solver, reach the same\nconclusion and say plainly that large datasets will need decomposition and\n\"sub-optimal (but good quality) feasible solutions\".\n\nThe scale caveat cuts both ways and belongs here rather than in a footnote:\n\"the heuristic is exactly optimal\" is measured at $N = 36$, on instances small\nenough to prove. It is evidence that the move and the objective are right, not\nevidence that the same holds at 625 or at 10,000, where the true optimum is\nunknown and only the interval between the best plan and the certified bound is\nreportable.\n\n::: {.callout-note}\n## What the oracle is for\n\nNot production. `sel_exact()` forms the `N x N` matrix and scales like the\nmixed-integer programme it is. It belongs with the `ref_*` functions of\n@sec-verification: deliberately slow, deliberately literal, and the only way to\nknow whether the fast route is right. Run it once, small, when the data\nchanges; do not put it in a pipeline.\n:::\n\n## Scaling to 200 of 10,000 {#sec-scaling}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Cost of one objective evaluation, by route. n_sel is 2 percent of N by construction in this sweep, so the hybrid route's column mixes growth in N with growth in the size of the selection; the line route's is dominated by the decode, which sorts all N candidates; the swap never decodes. The matrix-size column is GiB (bytes / 2^30) throughout, despite being named f_GB in the cached CSV.\n\n|     N|   L| n_sel| f size (GiB)| hybrid (us)| line (us)| of which decode (us)| swap (us)|\n|-----:|---:|-----:|------------:|-----------:|---------:|--------------------:|---------:|\n|   400|  40|    20|        0.001|         6.6|      17.9|                 13.3|       2.7|\n|  1600|  80|    32|        0.019|         7.7|      36.3|                 30.5|       3.0|\n|  3600| 120|    72|        0.097|        39.9|      83.0|                 76.6|       3.3|\n|  6400| 160|   128|        0.305|        78.2|     147.8|                140.9|       3.9|\n| 10000| 200|   200|        0.745|       132.2|     168.7|                159.1|       4.2|\n| 22500| 300|   450|        3.772|          NA|        NA|                   NA|        NA|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#>        N_from          N_to    n_sel_from      n_sel_to growth_hybrid \n#>        400.00      10000.00         20.00        200.00         20.11 \n#>  growth_lines growth_decode   growth_swap \n#>          9.42         11.99          1.54\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Cost per objective evaluation against the number of candidate hybrids. Only the incremental swap is flat. Both encodings grow: the line route by 9.4x, dominated by decode_lines()'s O(N log N) sort over all candidates, and the hybrid route by 20x -- but that arm is confounded, because the sweep sets n_sel to 2 percent of N (20 crosses at N = 400, 200 at N = 10,000) and mean(f[idx, idx]) is quadratic in the selection, not in N.](figs/search_scaling.png){fig-align='center'}\n:::\n:::\n\n\nThree things scale badly, and they are worth separating because only one of the\nthree is fixed by the line encoding.\n\n**Memory.** `f` is $8N^2$ bytes: 0.745 GiB at $N = 10{,}000$ and 3.8 GiB at\n$N = 22{,}500$, which is why @sec-choosing's benchmark refuses to form it there.\n$\\mathbf{f}^L$ is $200 \\times 200$, or 0.3 MiB. **Fixed by the line route.**\n\n**Search dimension.** Not what the line encoding fixes -- not for the two\ndifferential evolutions, at any rate. `sel_de()` searches $n_{sel}$ continuous\ncoordinates and `sel_de_fast()` searches $L$; at this chapter's target both are\n**200**, which is also the figure @sec-notreach quotes. The 10,000-dimensional\nalternative is one key per hybrid, the encoding @sec-combinatorial rejects and\nno route in this package uses. What the collapse genuinely moves to $L$ is the\n*contributions* space: `ocs_quadprog()` inside `ocs_round()` solves a\n200-variable quadratic programme where `ocs_relaxation()` works on a\n10,000-variable contribution vector, which is why `ocs_round()` (uncapped, no\n`max_use`) sweeps its ten $\\lambda$ values and returns a *plan* in\n157\nms at production scale. That number is the rounding and nothing else: the\nbenchmark passes `bound =` a value computed once, outside the timed block, and\nat $N = 10{,}000$ that value comes back **uncertified**, so the plan is what is\nfast here and there is no certificate at this scale to be fast about. The\nparagraph after the table below is where that is measured.\n**Fixed for the quadratic programme; already true for the DE.**\n\n**Cost per evaluation.** `mean(f[idx, idx])` is $O(n^2)$ in the *selection*, so\nit degrades exactly as the problem gets interesting -- but `decode_lines()` is\n$O(N \\log N)$, so the line encoding does not fix this and at these sizes is\nslightly worse. **Fixed only by not decoding**, which is what the swap\nneighbourhood does.\n\nScaling up is therefore not a matter of buying time. It is a matter of not\nforming `f` at all: build `ctx$fL` and `ctx$parents`, and use the routes that\nread only those. That last clause is a real restriction and not a formality,\nbecause most of this package still reaches for the $N \\times N$ matrix, and\n`fast_ctx()` does not change that -- it *adds* `parents` to whatever context it\nis handed and neither builds `f` nor drops it. The constructor with the switch\nis `ctx_from_pools(sim, with_f = FALSE)`, and the next section is what actually\nhappens on the context it returns.\n\n### Which routes actually run without `f` {#sec-ffree}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsim <- simulate_pools(n_A = 10, n_B = 10, m = 400, seed = 1)\ncxF <- ctx_from_pools(sim, with_f = FALSE)   # fL + parents, no N x N matrix\ncxT <- ctx_from_pools(sim, with_f = TRUE)    # the same data, f as well\nk   <- 12\ngdk <- null_distribution(cxT, k, B = 50, B_full = 10)$gd_ref\nst  <- sel_truncation_cap(cxF, k, cap = 3)   # a valid starting selection\nset.seed(1); wts <- runif(cxF$n_lines)\n# Line merit as ocs_round() defines it: mean index of the hybrids a line parents.\nmerit <- vapply(seq_len(cxF$n_lines), function(l)\n  mean(cxF$index[cxF$parents[, 1] == l | cxF$parents[, 2] == l]), numeric(1))\n\nruns <- function(e) tryCatch({ force(e); \"runs\" },\n                             error = function(err) paste0(\"ERROR: \", conditionMessage(err)))\nknitr::kable(data.frame(\n  Route = c(\"`theta_state()` / `theta_swap()`\", \"`fast_theta()`\",\n            \"`sel_truncation_cap()`\", \"`decode_lines()`\", \"`sel_de_fast()`\",\n            \"`ocs_quadprog()`\", \"`ocs_bound()`\",\n            \"`sel_local_search(start = st)`\", \"`sel_local_search(start = NULL)`\",\n            \"`theta_group()` / `alpha_loss()`\", \"`null_distribution()`\",\n            \"`sel_greedy()`\", \"`ocs_round()`\"),\n  `On a ctx with no f` = c(\n    runs(theta_swap(theta_state(st, cxF), st[1], setdiff(seq_len(cxF$N), st)[1], cxF)),\n    runs(fast_theta(st, cxF)),\n    runs(sel_truncation_cap(cxF, k, cap = 3)),\n    runs(decode_lines(wts, cxF, k)),\n    runs(suppressWarnings(sel_de_fast(cxF, k, gdk, am, NP = 20, itermax = 10))),\n    runs(ocs_quadprog(cxF$fL, merit, lambda = 1, upper = 1)),\n    runs(suppressWarnings(ocs_bound(cxF, k, am, gdk, iters = 200, max_doublings = 1L))),\n    runs(sel_local_search(cxF, k, am, gdk, start = st, iters = 500, seed = 1)),\n    runs(sel_local_search(cxF, k, am, gdk, iters = 500, seed = 1)),\n    runs(theta_group(st, cxF)),\n    runs(null_distribution(cxF, k, B = 20, B_full = 5)),\n    runs(sel_greedy(cxF, k, w = 1)),\n    runs(ocs_round(cxF, k, am, gdk, bound = NA_real_))),\n  check.names = FALSE), row.names = FALSE,\n  caption = \"Every route in this chapter, run on a context carrying fL and parents but no N x N f.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Every route in this chapter, run on a context carrying fL and parents but no N x N f.\n\n|Route                            |On a ctx with no f                |\n|:--------------------------------|:---------------------------------|\n|`theta_state()` / `theta_swap()` |runs                              |\n|`fast_theta()`                   |runs                              |\n|`sel_truncation_cap()`           |runs                              |\n|`decode_lines()`                 |runs                              |\n|`sel_de_fast()`                  |runs                              |\n|`ocs_quadprog()`                 |runs                              |\n|`ocs_bound()`                    |runs                              |\n|`sel_local_search(start = st)`   |runs                              |\n|`sel_local_search(start = NULL)` |ERROR: subscript out of bounds    |\n|`theta_group()` / `alpha_loss()` |ERROR: subscript out of bounds    |\n|`null_distribution()`            |ERROR: subscript out of bounds    |\n|`sel_greedy()`                   |ERROR: argument is of length zero |\n|`ocs_round()`                    |ERROR: subscript out of bounds    |\n\n\n:::\n\n```{.r .cell-code}\n\n# The f-free replacement for null_distribution(): the same resampling, scored\n# with fast_theta() instead of theta_group(). Same seed, same draws, same gd_ref.\nset.seed(7)\ngd_free <- mean(replicate(50, 1 - fast_theta(sample.int(cxF$N, k), cxF)))\nstopifnot(all.equal(gd_free, gdk))\n\n# What the matrix was buying the local search: only the starting point.\nobjs <- c(\n  with_f_start_NULL = attr(sel_local_search(cxT, k, am, gdk, iters = 500, seed = 1),\n                           \"objective\"),\n  no_f_start_given  = attr(sel_local_search(cxF, k, am, gdk, start = st, iters = 500,\n                                            seed = 1), \"objective\"))\n```\n:::\n\n\nRead the second column before designing a pipeline around the paragraph above\nit. The incremental swap, the line decoder, the line-space quadratic programme\nand the Lagrangian bound are genuinely `f`-free, and so is `sel_local_search()`\n**once it is given an explicit `start =`**: on this instance it reaches\n1.5804 against\n1.5804 for the default warm start with `f`\npresent, so at this size the matrix was buying the starting point and nothing\nelse. That is one instance, not a guarantee -- the greedy warm start is there\nbecause at book and production scale it is worth having.\n\n`sel_greedy()` is the honest failure: it opens with `f <- ctx[[\"f\"]]` and dies\non a `NULL`. The rest are the trap `ctx$f` is. `theta_group()` is\n`mean(ctx$f[idx, idx])`, and with no `f` in the list that `$` *partial-matches*\n`ctx$fL` -- an $L \\times L$ matrix, then indexed with hybrid subscripts, so\nwhat surfaces is `subscript out of bounds` and not a missing object. Through\n`gene_diversity()` and `alpha_loss()` that reaches `null_distribution()`,\n`ocs_round()`'s per-$\\lambda$ frontier, and `sel_local_search()` at its\ndocumented default of `start = NULL`: `ls_warm_start()` does guard the greedy\nbranch with `nrow(ctx[[\"f\"]]) == ctx$N`, but the ranking that follows it scores\nevery candidate with `alpha_loss()`, and that call is unguarded. Had the\nselection been small enough to index a $20 \\times 20$ matrix legally, the same\nline would have returned a diversity computed from the wrong matrix, silently.\n\nSo the honest scaling recipe has two branches. If `f` fits, form it: the\nbenchmark below does, on purpose, and the whole chapter's numbers come from\nthat branch. If it does not fit, the `f`-free subset is the *whole* pipeline\nyou get -- `sel_truncation_cap()` for a starting plan, `fast_theta()` over\nrandom subsets for `gd_ref` in place of `null_distribution()` (same seed, same\ndraws, the same `gd_ref` to machine precision, which the chunk above asserts),\n`sel_local_search(start = ...)` and `sel_de_fast()` for the search,\n`ocs_quadprog()` and `ocs_bound()` for the contributions and the bound -- and\nthe greedy sweep, the resampled null and the rounding route are simply not\navailable.\n\n### The head-to-head at production scale\n\nNothing broke at 10,000 and nothing here claims it did: the\nbenchmark below forms the 0.745 GiB matrix on purpose, and the hybrid route\nstill evaluates in\n132 us. The wall is further out, and\nit is documented rather than predicted -- at $N = 22{,}500$ the matrix is\n3.8 GiB and @sec-choosing's cost benchmark\ndeclines to form it at all, so every metric that needs it has no timing entry\nat that scale. The line route has one.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Production scale: N = 10,000 from 100 + 100 lines, n_sel = 200, 1% budget, mean of 3 seeds.\n\n|method        | index| loss %| Ne parents| max uses| seconds|\n|:-------------|-----:|------:|----------:|--------:|-------:|\n|hill          | 1.816|  0.999|     46.796|   20.333|   0.341|\n|anneal        | 1.814|  0.998|     47.014|   19.000|   0.343|\n|ocs_round     | 1.789|  0.832|     45.121|   20.000|   0.157|\n|tempering     | 1.689|  0.999|     56.383|   15.333|   0.352|\n|greedy        | 1.500|  0.227|     54.348|   18.000|   0.221|\n|de_hybrid     | 1.446|  0.986|     57.948|   18.667|   8.858|\n|de_lines      | 1.336|  0.988|     28.925|   29.667|   6.314|\n|greedy_cap    | 1.123|  0.317|    100.756|    4.000|   0.329|\n|de_hybrid_cap | 1.122|  0.310|    101.266|    4.000|   9.022|\n|de_lines_cap  | 1.122|  0.310|    101.266|    4.000|  15.041|\n|ocs_round_cap | 1.122|  0.310|    101.266|    4.000|   0.214|\n|tempering_cap | 1.122|  0.310|    101.266|    4.000|   0.466|\n\n\n:::\n:::\n\n\nTwo things in that table are worth more than the ranking.\n\n**The cap binds, the budget does not.** Every capped method lands on essentially\nthe same plan, at a diversity loss far inside the 1% allowed. With\n$n = 200$ over $L = 200$ lines the mean usage is already 2, so a cap of 4 leaves\nvery little to choose; the restriction that is actually deciding the plan is the\none nobody wrote a budget for. Check `max_line` and realised `alpha` together\nbefore concluding that a diversity constraint is doing any work.\n\nRead down the capped rows only, as the rule above the book-scale table\nrequires, and the ordering inverts. `greedy` ranks\n5 of\n7 among the uncapped rows and\n1 of\n5 among the capped ones: it tops them\nat 1.12252 in\n0.329 s, ahead of `tempering_cap` at\n1.12233 in\n0.466 s and of both capped\ndifferential evolutions and of `ocs_round_cap`, all three of which land on the\nidentical plan to the tempering here. The same\nholds at book scale, ranks\n5 uncapped and\n1 capped, where `greedy_cap` reaches\n1.11220 in\n0.008 s against `tempering_cap`'s\n1.10972 in\n0.286 s. A cap this tight leaves the\noptimiser nothing to find that a capped greedy sweep does not already reach.\n\nThe diagnosis is arithmetic and takes a minute: compare $2n/L$, the mean number\nof uses per line, against the cap. If the cap is a small multiple of the mean,\nit is the binding restriction and the diversity budget is decoration. Raising\nthe cap, or enlarging the candidate pool, changes the plan; tightening the\nbudget does not.\n\n**The certificate does not scale, and the bound is reported as uncertified.**\n`ocs_bound()` doubles its iteration count until the value stops moving. At book\nscale it converges; at $N = 10{,}000$ it does not, within any budget worth\nspending. The reason is in the step size, $1/(2\\lambda \\max_i \\sum_j f_{ij})$,\nwhose denominator grows with $N$ -- so the same iteration count that converges\non 625 candidates is nowhere near enough on 10,000. An under-converged\nrelaxation reports $V(\\lambda)$ *too small*, which makes the \"bound\" too small,\nand it stops bounding anything.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Where the certificate holds.\n\n|scale      |     N|  bound|certified |\n|:----------|-----:|------:|:---------|\n|book       |   625| 1.5543|TRUE      |\n|production | 10000| 1.8378|FALSE     |\n\n\n:::\n:::\n\n\nThat is a finding, not a defect, and it is why the function warns instead of\nreturning a number. At production scale you have heuristics that agree with each\nother and no proof that any of them is close -- which is the honest position, and\na better one than a gap column computed from a quantity that is not a bound.\n\n## Multi-objective, and why not NSGA-II\n\n`stage2_select()` traces the frontier by sweeping `alpha_max` and running a\nfull optimisation at each point. That is already the epsilon-constraint method,\nand it is the right one: each point is a plan a committee can approve, expressed\nin a budget rather than in an exchange rate (@sec-ocs).\n\nThe available saving is not a Pareto algorithm. It is that consecutive budgets\nhave nearly identical solutions, so the plan found at $\\alpha_k$ is the obvious\nwarm start for $\\alpha_{k+1}$ -- which the sweep currently throws away. That is\na `start =` argument, not a new optimiser.\n\nNSGA-II would return the whole front in one run, at worse quality per point and\nwith a crowding heuristic that has nothing to say about a constraint the\nbreeder has already chosen. For a one-dimensional trade-off already\nparameterised by an interpretable budget, it is machinery in search of a\nproblem.\n\n## What not to reach for {#sec-notreach}\n\n**Reinforcement learning.** BreedGym and its successors [@younis2024] cast the\n*breeding programme* as a Markov decision process: how to allocate resources\nacross cycles, when to recycle, how many crosses to make each generation. Those\nare sequential decisions with delayed reward. Choosing 200 hybrids from a fixed\ncandidate pool, once, with a closed-form objective, is not. The tool is aimed at\na different question.\n\n**Bayesian optimisation.** For expensive black-box objectives with a handful of\ncontinuous inputs. Ours costs 5 microseconds and has 200 integer dimensions.\n\n**Sampling from a determinantal point process.** DPPs are the natural\nprobabilistic model of a diverse subset, and $\\log\\det(\\mathbf{I} + \\beta\n\\mathbf{f}_S)$ is genuinely submodular and monotone, so its greedy carries a\n$1 - 1/e$ guarantee [@chen2018]. But *sampling* from a DPP gives diversity in\ndistribution when what is wanted is a single best plan, and the log-determinant\nlens is not $\\theta$ -- adopting it would quietly change the quantity the\nprogramme is constraining. @sec-catalogue's rule applies: one diversity lens,\nchosen deliberately, reported against a null.\n\n## Which method to use\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Situation                                                   |Use                                                                                                                                                                                                                                                                                                                                                                            |\n|:-----------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|Any scale, first thing to run                               |`sel_greedy()` swept over w, then `sel_truncation_cap()` -- @sec-combinatorial                                                                                                                                                                                                                                                                                                 |\n|Production scale, a budget and a per-line cap               |`sel_greedy(max_use = cap)` swept over w -- highest index of any *capped* route at both scales (1.112 in 0.008 s at book scale, 1.123 in 0.329 s at production); `sel_local_search(max_use = cap, mode = \"tempering\")` comes close without matching it -- 2.5 thousandths of an index unit short at book scale, 0.2 at production -- and is the only mode measured under a cap |\n|A restriction the swap cannot test (Ne floor, pool balance) |`sel_de_fast()` -- the only route that accepts them; it trails the capped greedy on index (@sec-defast-restrictions)                                                                                                                                                                                                                                                           |\n|You need to know whether to keep optimising                 |`ocs_bound()` -- a valid bound, but check `converged`; a small gap means stop                                                                                                                                                                                                                                                                                                  |\n|You need to know the true optimum                           |`sel_exact()` on a subsample -- an oracle, not a pipeline                                                                                                                                                                                                                                                                                                                      |\n|Contributions are genuinely continuous                      |`ocs_quadprog()` -- @sec-ocs                                                                                                                                                                                                                                                                                                                                                   |\n\n\n:::\n:::\n\n\nAs a protocol at production scale:\n\n1. Build `ctx` through `fast_ctx()`, and decide up front whether the\n   $N \\times N$ matrix is going to exist, because that decision selects the\n   rest of the protocol (@sec-ffree). `ctx$fL` and `ctx$parents` are required\n   by every fast route; `f` is required by `null_distribution()`,\n   `sel_greedy()`, `ocs_round()` and `sel_local_search()`'s automatic warm\n   start. At $8N^2$ bytes it fits at $N = 10{,}000$ and the benchmark above\n   forms it. If it does not fit, steps 2-4 change as noted, and the `f`-free\n   subset is what you have.\n2. Get `gd_ref` from a resampling at the target `n_sel`, and set\n   $\\alpha_{\\max}$ below the attainable ceiling (@sec-ocs). With no `f`,\n   `null_distribution()` is unavailable and the resampling has to be\n   `mean(replicate(B, 1 - fast_theta(sample.int(ctx$N, n_sel), ctx)))`, which\n   is `fL`-only and returns the same `gd_ref` at the same seed (@sec-ffree).\n3. Run the sweeps that cost milliseconds -- `sel_truncation_cap()` and, when\n   `f` exists, `sel_greedy()` over a $w$ grid spanning your data's crossover,\n   passing `max_use` if a cap applies -- and record what they achieve. They are\n   the baseline every later number is judged against, and under a cap they are\n   also, at both scales measured here, the winner (the table above).\n4. Run `sel_local_search()` for as many seconds as you are willing to spend,\n   with the cap passed as `max_use` rather than enforced afterwards. With `f`\n   present, leave `start = NULL` and let it build the warm start; with no `f`,\n   pass `start = sel_truncation_cap(...)` explicitly, which is the only\n   configuration of this route that runs without the matrix. The mode is the\n   least consequential choice in this list: on the benchmark above `\"hill\"` and\n   `\"anneal\"` are\n   0.2 thousandths of an index\n   unit apart at book scale and\n   2.4 at production, with the\n   sign of the difference changing between them, while `\"tempering\"` trails at\n   both. Take the simplest one unless your own data says otherwise -- but note\n   that those three are the *uncapped* rows, and the only mode benchmarked\n   under a cap is `\"tempering\"`.\n5. Compute `ocs_bound()` and check its `converged` attribute. Certified and the\n   gap small: stop. Certified and the gap large: keep going. Uncertified:\n   report no gap at all, and judge the plan by agreement between independent\n   methods instead.\n6. Validate the returned plan on the lens the constraint does not pin --\n   `F_drift` and allelic richness -- and on the pool decomposition, before it\n   is used (@sec-case-study).\n\nThe honest summary is that one change matters more than the rest put together,\nand it is not an algorithm and not an encoding either. The problem was always\n$L$-dimensional in its *state* -- $\\theta$ is a function of the line-usage\nvector and of nothing else -- and that is what buys the $O(L)$ swap, the 0.3\nMiB matrix and the 200-variable contributions programme. What it does not buy\nis a better parameter vector for a population method: `sel_de()` at\n$n_{sel} = 200$ and `sel_de_fast()` at $L = 200$ search boxes of the same\nwidth, and the measured difference between them is small and runs the other\nway. Everything else in this chapter -- the guarantees, the corrected bound,\nthe oracle -- is there to tell you when you are done, which turns out to be\nmuch earlier than the size of the candidate set suggests.\n\n> Name the structure before choosing the algorithm. The difficulty in this\n> problem was in the state, not in the optimiser -- and a claim about an\n> encoding is only as good as the two things it was actually measured between.\n",
    "supporting": [
      "10b-advanced-selection_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}