{
  "hash": "e098337dc5311650478783ea375d2d23",
  "result": {
    "engine": "knitr",
    "markdown": "# Heterosis, dominance, and what divergence buys {#sec-heterosis}\n\n\n\nSince @sec-subdivided this book has repeated a claim without proving it: that the\ndivergence between the heterotic pools is the engine of heterosis, and is therefore\nto be maintained rather than minimised. @sec-catalogue will decompose diversity on\nthat basis and @sec-stages will build a monitoring panel around it. The claim has\ncarried a lot of weight for an assertion.\n\nThis chapter derives it, and then corrects it. The derivation is short and the\nidentity is exact. The correction is that the usual reading of the identity --\n*push the pools apart and you will get more heterosis* -- is false: under neutral\ndivergence expected heterosis does not move at all, and the simulation shows it.\n\nThe chapter then goes one step past the mean. Expected heterosis is what a pool\npair is worth on average; what a breeder selects on is how heterosis is\n*distributed* across the crosses of the factorial. Those are different questions\nwith different answers, and the second one is where general and specific combining\nability come from.\n\nThe derivations come first and @sec-heterosis-protocol turns them into the eight\nsteps that compute them on a real programme's data, with the check and the\nfailure mode of each one. Read that section first if the question is what to run\nrather than why it holds.\n\nThree premises carry everything below. They are stated here once, because every\nresult in the chapter uses all three and two of them are restrictive.\n\n**Parents are fully inbred.** Every parent line is homozygous at every locus, so\nan F1's marker row is the average of its two parents' rows and a locus is\nheterozygous in the F1 exactly when the parents differ. This is what makes the\nadditive effects cancel from the mid-parent difference and what makes `GD_WI`\nzero. Note that this is a property of the *programme*, not of the mating system:\nthe crop here is allogamous -- maize-type, two heterotic pools under reciprocal\nrecurrent selection -- and it is DH induction or selfing to fixation that\ndelivers homozygous parents from it. Nothing here transfers to a programme\ncrossing non-inbred parents (an inter-population cross, a synthetic, S1 parents)\nwithout re-derivation, and @sec-heterosis-step1 measures how large the error is\nif the formulae below are applied anyway: a factor of five, not a few per cent.\n\n**The genotypic model is dominance within loci and additivity between them.**\nThere is no epistatic term anywhere below: the genotypic value is a sum over\nloci, $H_i$ is a sum of per-locus indicators, and the combining-ability expansion\nof @sec-heterosis-gca-sca is bilinear only because no term couples two loci.\n@labroo2021 review epistasis alongside dominance as a proposed mechanism for\nheterosis; this model excludes it, and no result below should be read as evidence\nabout it. What $d_k$ does absorb is every *within-locus* story, as the next\nsection sets out.\n\n**The marker panel is the set of dominance loci.** $d_k$ is indexed by the same\n$k$ as the markers, so every locus carrying dominance is genotyped and the\nfrequency statistics are computed on exactly the loci that generate heterosis.\nThis is the strongest assumption of the three, and it is the one that carries the\ndistance results of @sec-heterosis-distance. A real panel tags causal loci\nthrough linkage disequilibrium rather than containing them, which weakens every\nstatement below about markers predicting heterosis but does not change the\nalgebra, since the algebra is written over whatever set $k$ indexes.\n\n## The dominance model, minimally\n\n### The one-locus scale\n\nThe classical parameterisation puts the origin at the midpoint of the two\nhomozygotes: one homozygote is worth $+a$, the other $-a$, and the heterozygote\n$d$. Under random mating at frequency $p$, with $q = 1 - p$, the population mean\nis [@falconer1996, Eq. 7.2]\n\n$$M = a\\,(p - q) + 2pq\\,d$$\n\nThe first term is the additive contribution, and the mid-parent of any cross\nalready carries it. The second is the dominance contribution. It is the only part\nof $M$ that depends on how many heterozygotes there are, and therefore the only\npart a cross can add over its own mid-parent.\n\n::: {.callout-note}\n## $a$ is a scale, not a quantity this chapter computes\n\nThe symbols in that display are the textbook ones. This book's additive marker\neffects are $\\beta_k$ (@sec-genomic-prediction), and its $\\alpha$ is the\ndiversity-loss statistic of @sec-catalogue, not the classical average effect of a\nsubstitution. The per-locus $a_k$ reappears three times below and never as a\nresult: in the genotypic-value model used to show that it cancels, in the\ndefinition of overdominance as $|d| > |a|$, and in the average effect of a\nsubstitution $a + d(q - p)$. No quantity this chapter reports depends on it.\n:::\n\n### What $d_k$ is, and what it is not\n\n$d_k$ is *functional* dominance: the departure of the heterozygote from the\nhomozygote midpoint at locus $k$. It is a property of the locus. It does not move\nwhen allele frequencies move.\n\nFisher's *statistical* dominance deviation is a different object: the residual\nleft after projecting genotypic values onto the best additive model **in a\nparticular population**. It is a property of the population as much as of the\nlocus, and it changes when frequencies change.\n\nBoth appear in this chapter, and keeping them apart is the whole trick.\n$d_k$ is the input. The specific combining ability of @sec-heterosis-gca-sca is\nthe statistical dominance deviation that a given $d_k$ *induces* over a given pair\nof pools. One is a constant; the other is an answer that depends on where the\npools happen to sit.\n\nThe distinction also buys the model what generality it has, and marks where that\ngenerality stops. Dominance, overdominance (a heterozygote outside both\nhomozygotes, $|d| > |a|$) and pseudo-overdominance (two dominant favourable\nalleles in repulsion phase, too close for any marker to separate) are three\ndifferent biological stories, and @labroo2021 review the evidence for each. At\nmarker resolution they are the same arithmetic: a locus at which the F1 gains\nsomething the mid-parent does not. A single $d_k$ absorbs all three, and nothing\nbelow can distinguish them -- nor needs to. Epistasis is the fourth story on\n@labroo2021's list and $d_k$ does not absorb it, because a single per-locus\nnumber cannot represent a term that depends on two loci at once. That is the\nsecond premise above, and it is an exclusion rather than an approximation.\n\n### The mid-parent difference\n\nCode a genotype by $x_k \\in \\{0, 0.5, 1\\}$, the frequency of the reference allele\nwithin the individual, and take the genotypic value to be the additive part plus\nthe dominance deviation at every heterozygous locus:\n\n$$G(\\mathbf{x}) = \\sum_k a_k\\,(2x_k - 1) + \\sum_k d_k\\,\\mathbb{1}\\{x_k = 0.5\\}$$\n\nThe parents are fully inbred, so each is homozygous at every locus and the F1's\nrow is the average of its two parents' rows. The additive part is linear in\n$\\mathbf{x}$, so the two parents' additive values average exactly to the F1's own\nand cancel from the mid-parent difference. What survives is the dominance\ndeviation at the loci where the F1 is heterozygous:\n\n$$H_i = \\sum_k d_k \\, \\mathbb{1}\\{x_{ik} = 0.5\\}$$\n\nThe additive effects never appear. That is the result, not an omission, and it is\nwhy `heterosis_value()` takes no additive-effect argument:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheterosis_value\n#> function (X, d) \n#> {\n#>     stopifnot(length(d) == ncol(X))\n#>     drop((X == 0.5) %*% d)\n#> }\n#> <bytecode: 0xc86a0cd60>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\nAgainst the literal oracle of @sec-verification, which loops over loci and\ncompares the two parents' genotypes one at a time:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmax(abs(heterosis_value(ctx$X[1:25, ], d) -\n        ref_heterosis(L, head(ctx$ped, 25), d)))\n#> [1] 0\n```\n:::\n\n\nThe cancellation is worth seeing directly. Draw additive effects at random, score\na real F1 and its two parents under $G(\\mathbf{x})$, and subtract:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(9)                       # the cancellation is exact for any a; seed it anyway\na   <- rnorm(ctx$m, 0, 0.2)\nval <- function(x) sum(a * (2 * x - 1)) + sum(d * (x == 0.5))\ni   <- 7\nmid <- (val(L[ctx$ped$a[i], ] / 2) + val(L[ctx$ped$b[i], ] / 2)) / 2\nc(mid_parent_difference = val(ctx$X[i, ]) - mid,\n  heterosis_value       = heterosis_value(ctx$X[i, , drop = FALSE], d))\n#> mid_parent_difference       heterosis_value \n#>              362.3386              362.3386\n```\n:::\n\n\nThe additive effects entered the first number and cancelled out of it; they never\nentered the second.\n\n## Expected heterosis over a pool pair\n\nWrite $p_{Ak}$ and $p_{Bk}$ for the reference-allele frequencies at locus $k$ in\nthe two pools, each computed over that pool's lines. A locus is heterozygous in\nthe F1 when the two gametes carry different alleles, which for a cross drawn at\nrandom between the pools happens with probability $p_A(1 - p_B) + (1 - p_A)p_B$.\nThe expected heterosis over all $A \\times B$ crosses therefore follows from the\npool frequencies alone:\n\n$$\\mathbb{E}[H] = \\sum_k d_k \\left[\\, p_{A k} + p_{B k} - 2 p_{A k} p_{B k} \\right]$$\n\nThe candidate pool here *is* the full factorial, every $A \\times B$ pairing\nexactly once, and the frequencies are the means of those same lines. The closed\nform is then the mean of the realised values as an identity rather than an\napproximation, and the residual is at machine precision:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nabs(heterosis_expected(pA, pB, d) - mean(heterosis_value(ctx$X, d)))\n#> [1] 1.136868e-13\n```\n:::\n\n\nThat is a mean over $N =$ 625 crosses, and a mean is not a ranking. Hold on\nto the question of how the individual crosses are spread around it;\n@sec-heterosis-gca-sca answers it exactly.\n\n## The identity {#sec-heterosis-identity}\n\nNow split the bracket. Writing $\\bar p = (p_A + p_B)/2$ and $y = p_A - p_B$, the\nper-locus F1 heterozygosity separates exactly:\n\n$$p_A + p_B - 2 p_A p_B \\;=\\; \\underbrace{2 \\bar p (1 - \\bar p)}_{\\text{shared}}\n                            \\;+\\; \\underbrace{y^2 / 2}_{\\text{divergence}}$$\n\nThe first term is the heterozygosity a single merged pool at frequency $\\bar p$\nwould produce under random mating. The second is what keeping the pools apart\nadds on top of it. Average both over loci with $d_k \\equiv 1$, so that the\nweighting does not obscure the algebra, and they are exactly the $GD_T$ and\n$GD_{BS}$ of the Caballero & Toro partition that @sec-subdivided derived and\n`gd_partition()` computes:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhp <- heterosis_partition(pA, pB, rep(1, ctx$m)) / ctx$m\ngp <- gd_partition(seq_len(ctx$N), ctx)\nfmt(data.frame(term       = c(\"shared\", \"divergence\"),\n               heterosis  = c(hp[[\"shared\"]], hp[[\"divergence\"]]),\n               partition  = c(gp[[\"GD_T\"]],   gp[[\"GD_BS\"]]),\n               residual   = c(abs(hp[[\"shared\"]]     - gp[[\"GD_T\"]]),\n                              abs(hp[[\"divergence\"]] - gp[[\"GD_BS\"]]))), 12)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term       | heterosis| partition| residual|\n|:----------|---------:|---------:|--------:|\n|shared     | 0.3280928| 0.3280928|        0|\n|divergence | 0.0335968| 0.0335968|        0|\n\n</div>\n:::\n:::\n\n\n> $GD_{BS}$ weighted by dominance deviations **is** the divergence half of expected\n> heterosis. \"Between-pool divergence is the heterosis engine\" is an identity, not\n> a slogan.\n\nOne thing to be clear about before reading on. $GD_T$ is the gene diversity of\nthe *merged* population, and by @sec-subdivided it already contains $GD_{BS}$:\nwith inbred lines, $GD_T = GD_{BI} + GD_{BS}$. Expected F1 heterozygosity is\ntherefore $GD_{BI} + 2\\,GD_{BS}$, the between-pool component counted twice --\nonce inside the shared term, once as the divergence term. That factor of two is\nwhere the classical result sits. Falconer & Mackay's heterosis of a cross\nbetween two *random-mating* populations is $\\sum_k d_k y_k^2$\n[@falconer1996, Ch. 14], exactly twice the divergence term here. The two do not\nconflict; they use different mid-parents. Theirs is two random-mating\npopulations, each carrying its own within-pool heterozygosity, so their $H$ is\nthe total above $\\sum_k d_k (p_{Ak}q_{Ak} + p_{Bk}q_{Bk})$. Ours is two inbred\nlines carrying none, so the whole F1 heterozygosity is heterosis, and the shared\nterm is the mean of the two pools' random-mating heterozygosities plus the half\nof $\\sum_k d_k y_k^2$ that $GD_T$ already holds.\n\nThat paragraph is an algebraic claim and it can be checked rather than asserted.\nSubtract the random-mating mid-parent from the F1's total dominance value and\nwhat is left is $\\sum_k d_k y_k^2$, exactly twice this chapter's divergence term:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhpd  <- heterosis_partition(pA, pB, d)\nmid_random_mating <- sum(d * (pA * (1 - pA) + pB * (1 - pB)))\nstopifnot(isTRUE(all.equal(hpd[[\"total\"]] - mid_random_mating,\n                           2 * hpd[[\"divergence\"]])),\n          isTRUE(all.equal(2 * hpd[[\"divergence\"]], sum(d * (pA - pB)^2))))\nc(F1_total          = hpd[[\"total\"]],\n  mid_random_mating = mid_random_mating,\n  difference        = hpd[[\"total\"]] - mid_random_mating,\n  twice_divergence  = 2 * hpd[[\"divergence\"]],\n  sum_d_y2          = sum(d * (pA - pB)^2))\n#>          F1_total mid_random_mating        difference  twice_divergence \n#>         355.66859         289.77816          65.89042          65.89042 \n#>          sum_d_y2 \n#>          65.89042\n```\n:::\n\n\nThe first number is what an F1 between two inbred lines gains over *its* mid-parent\nof zero; the third is what the same F1 gains over a mid-parent of two random-mating\npools. They differ by 289.8 units of dominance value that\nthe random-mating parents already carry themselves. Which mid-parent is the right\none is not a matter of convention: it is whichever one the programme actually\nplants. @sec-heterosis-step1 measures the consequence of getting it wrong.\n\n### A third form: one minus the between-pool coancestry\n\nThe sum of the two components has a name of its own. $\\theta_{AB} = \\mathbf{w}_A'\n\\mathbf{f}^L \\mathbf{w}_B$ is the between-pool coancestry of @sec-catalogue: on\nthe full factorial, where the line weights are uniform, it is the probability\nthat an allele drawn from a pool-A line and an allele drawn from a pool-B line\nare identical in state. Its complement is the whole bracket:\n\n$$GD_T + GD_{BS} \\;=\\; 1 - \\theta_{AB}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntp <- theta_pools(seq_len(ctx$N), ctx)\nc(shared_plus_divergence = gp[[\"GD_T\"]] + gp[[\"GD_BS\"]],\n  one_minus_theta_AB     = 1 - tp[[\"theta_AB\"]])\n#> shared_plus_divergence     one_minus_theta_AB \n#>              0.3616896              0.3616896\n```\n:::\n\n\nThis one is algebra rather than simulation. `gd_partition()` defines\n$GD_T = 1 - \\bar f$ and $GD_{BS} = \\tilde f - \\bar f$ with\n$\\bar f = (\\theta_A + 2\\theta_{AB} + \\theta_B)/4$ and\n$\\tilde f = (\\theta_A + \\theta_B)/2$, and the sum collapses to $1 - \\theta_{AB}$.\nWhich is the shortest statement the chapter has to make: **expected F1\nheterozygosity is one minus between-pool coancestry.** Everything else here is a\nweighting of that quantity, or a way of splitting it.\n\n## A second identity, at the hybrid level\n\n@sec-catalogue reports `GD_WI_hyb`, the within-individual gene diversity actually\ncarried by the F1s, separately from the line-level partition, because with inbred\nparents `GD_WI` is zero by construction and carries no signal. A hybrid's\nself-coancestry is $1 - h_i/2$, with $h_i$ its heterozygous fraction, so\n`GD_WI_hyb` is half the mean F1 heterozygosity and the two levels are linked:\n\n$$2 \\cdot GD_{WI\\text{-}hyb} = GD_T + GD_{BS}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(lhs = 2 * gp[[\"GD_WI_hyb\"]], rhs = gp[[\"GD_T\"]] + gp[[\"GD_BS\"]],\n  GD_WI = gp[[\"GD_WI\"]])\n#>           lhs           rhs         GD_WI \n#>  3.616896e-01  3.616896e-01 -4.440892e-16\n```\n:::\n\n\nExact on the full factorial, because every $A \\times B$ pairing is present exactly\nonce. On a *selected* subset it holds only approximately. There $GD_T$ and\n$GD_{BS}$ are computed from the line-usage weights, which is what a random\nre-pairing of the selected parents would give, while `GD_WI_hyb` scores the pairs\nactually chosen. The gap is the pairing structure of the subset.\n`tests/testthat/test-dominance.R` asserts the identity to `1e-12` on the full\nfactorial and, on a *random* 40-hybrid subset at one scale (12 lines per pool,\n800 markers), bounds the gap with `expect_equal(tolerance = 5e-3)`. That\ntolerance is **relative**, not absolute: on a gene-diversity value of order 0.4\nthe absolute bound it enforces is of order `2e-3`, and the gap the test actually\nsees is smaller again. A subset chosen by an optimiser, which concentrates line\nusage deliberately, is not covered by that bound; @sec-era-fhom is where it is\nmeasured, on four such subsets at this book's scale, and reports the largest\ndeparture of the four.\n\n## Inbreeding depression, and why it does not price $\\alpha$ {#sec-heterosis-id}\n\nThe same model run backwards gives inbreeding depression. A locus at frequency\n$p$ in a population with inbreeding coefficient $F$ is heterozygous with\nprobability $2pq(1-F)$, so the mean declines linearly in $F$\n[@falconer1996, Ch. 14]:\n\n$$ID \\;=\\; 2F\\sum_k d_k \\, p_k q_k$$\n\nAt $F = 1$ that is exactly the *shared* term of `heterosis_partition()` evaluated\nat $p_A = p_B = p$. So the depression of a pool driven to complete homozygosity\nand the expected heterosis of a cross made *within* that same pool are one\nquantity seen from two sides. @mackay2020 treat heterosis and inbreeding\ndepression together on that basis, alongside transgressive segregation, which\nthis chapter does not take up. The identity needs no new machinery:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(inbreeding_depression = inbreeding_depression(pA, d),\n  shared_term           = heterosis_partition(pA, pA, d)[[\"shared\"]],\n  deviation             = abs(inbreeding_depression(pA, d) -\n                                heterosis_partition(pA, pA, d)[[\"shared\"]]))\n#> inbreeding_depression           shared_term             deviation \n#>              288.2869              288.2869                0.0000\n```\n:::\n\n\nThe closed form is checked against simulated genotypes rather than against its\nown algebra, which is what `ref_inbreeding_depression()` exists for: it draws\neach genotype as identical by descent with probability $F$ and as two independent\nalleles otherwise, so the agreement is to Monte Carlo error:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nk <- 1:300\nc(closed_form = inbreeding_depression(pA[k], d[k], 0.6),\n  simulated   = ref_inbreeding_depression(pA[k], d[k], 0.6, n = 20000, seed = 2))\n#> closed_form   simulated \n#>    27.58563    27.57923\n```\n:::\n\n\nNow the part that matters, because the obvious next step is wrong.\n\nIt is tempting to argue: $\\alpha$ budgets a loss of within-pool gene diversity;\ngene diversity is $\\sum_k p_kq_k$; inbreeding depression is $\\sum_k d_k\\,p_kq_k$;\ntherefore spending $\\alpha$ costs yield in the current cycle, and *that* is the\nprice of the budget. The algebra does not support it.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(max_dominance_contribution_of_an_inbred_line = max(abs(heterosis_value(U, d))))\n#> max_dominance_contribution_of_an_inbred_line \n#>                                            0\n```\n:::\n\n\nZero, exactly. A fully inbred line has no heterozygous loci, so its dominance\ncontribution is zero **whatever the pool's allele frequencies are**. In a\nprogramme whose parents are inbred lines the depression was paid in full when the\nlines were made; it is a constant, and it does not move when the pool\nsubsequently loses diversity. The formula above describes the gap between a\nhypothetical random-mating pool and its inbred derivatives, and that gap\n*shrinks* as $p_kq_k$ shrinks -- but nothing in the programme stands at the\nrandom-mating end of it.\n\n::: {.callout-important}\n## Inbreeding depression is not the current-cycle price of the diversity budget\n\nThis is the same fact that makes $GD_{WI}$ exactly zero in @sec-catalogue's\npartition, and it has the same cause: with inbred parents there is no\nwithin-individual variation left to lose. Two consequences.\n\nThe cost of $\\alpha$ in this system remains what @sec-cycles measures -- an\noption value, realised cycles later through the variance available to select on\n(@sec-response), not a yield loss booked this season.\n\nAnd inbreeding depression **is** the live quantity wherever the population is\nonly partially inbred: F2, F3 and F4 in @sec-sizing, where $F$ is still climbing\nand the depression is still accumulating. That is the chapter it belongs to, not\nthis one.\n:::\n\nNote also what this does *not* say. Expected heterosis in the product is a\nseparate question. @sec-heterosis-flat answers it for the neutral case: under\ndrift the shared term lost and the divergence term gained cancel exactly, so\nhybrid heterosis is invariant. Under selection the frequencies move\ndirectionally, and what happens to expected heterosis is then the alignment\nquestion of @sec-heterosis-alignment, which can go either way. In neither case is\nthe diversity loss itself an immediate dominance cost. The bill arrives later,\nand it arrives in the additive variance.\n\n## When genetic distance predicts heterosis exactly {#sec-heterosis-distance}\n\nBefore the corrections start, one special case is worth having, because it is the\nonly case in which marker distance and heterosis are the same number.\n\nSet $d_k \\equiv d$, constant across loci. Then $H$ stops being a weighted count and\nbecomes a plain one: $d$ times the number of loci at which the two parents differ.\nFor inbred lines that count is exactly what the coancestry kernel of\n@sec-coancestry measures, so for a cross between lines $a$ and $b$\n\n$$H_{ab} \\;=\\; d\\,m\\,(1 - f^L_{ab}) \\;=\\; d\\,m\\,\\mathrm{MRD}_{ab}^2$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nh1 <- heterosis_value(ctx$X, rep(1, ctx$m))\nfL <- molecular_coancestry(L / 2)\nab <- cbind(ctx$ped$a, ctx$ped$b)\nc(vs_coancestry = max(abs(h1 - ctx$m * (1 - fL[ab]))),\n  vs_mrd        = max(abs(h1 - ctx$m * mrd_matrix(L / 2)[ab]^2)))\n#> vs_coancestry        vs_mrd \n#>  1.136868e-13  2.273737e-13\n```\n:::\n\n\nBoth residuals are at machine precision. Under flat dominance, heterosis and\nmolecular coancestry are one statistic seen twice -- Trap 1 of @sec-stages read\nfrom the other side -- and the diversity kernel this whole book runs on turns out\nto be the right object for the heterosis question as well.\n\nFlat $d$ is also precisely the condition under which $H$ is a function of marker\ndistance alone. It is a strong condition, and it fails as soon as $d$ varies: two\ncrosses at the same distance then differ by *which* loci they differ at. With the\ngamma-distributed deviations used everywhere else in this chapter the relationship\nsurvives but stops being an identity:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(cor_uniform_d = cor(h1, 1 - fL[ab]),\n  cor_real_d    = cor(heterosis_value(ctx$X, d), 1 - fL[ab]))\n#> cor_uniform_d    cor_real_d \n#>     1.0000000     0.7809147\n```\n:::\n\n\nA correlation of 0.78 is a\nuseful predictor and a poor identity. Two things move it, and both are properties\nof the germplasm rather than of the statistic: how $d$ is spread over the loci at\nwhich the parents differ, which is what @sec-heterosis-alignment is about, and --\nonce the third premise is relaxed -- how well the panel tags the causal loci.\nUnder flat $d$ on a panel that *is* the causal set the correlation is 1 by the\nidentity above. Departing from either condition generally lowers it -- not\nalways, since a $d$ that varies only across loci at which no pair of parents\ndiffers changes no $H_i$ at all -- and by how much is something this chapter does\nnot attempt to predict.\n\n## Divergence is not a bonus {#sec-heterosis-flat}\n\nRead `divergence` as free money and you will reach for $F_{ST}$. Do not.\n\nDraw the pools further apart and watch all three terms. Nothing here is selected.\nEach point re-draws both pools from the *same* ancestral frequencies -- the\nancestral vector is fixed by `seed = 5` and shared across the sweep, while the two\npool-frequency vectors are fresh Balding-Nichols draws at each `fst`\n(@sec-notation) -- so what varies along the sweep is how far the draw scatters\nand nothing else:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsweep_het <- function(fst) {\n  cf <- modifyList(book_cfg, list(fst = fst, seed = 5))\n  Lf <- simulate_lines(cf)\n  pl <- rep(c(\"A\", \"B\"), c(cf$n_pool_A, cf$n_pool_B))\n  Pf <- pool_freqs(Lf / 2, pl)\n  hp <- heterosis_partition(Pf[\"A\", ], Pf[\"B\", ], rep(1, cf$m)) / cf$m\n  cm <- pool_complementarity(Lf / 2, pl)\n  data.frame(fst = fst, shared = hp[[\"shared\"]], divergence = hp[[\"divergence\"]],\n             total = hp[[\"total\"]],\n             frac_opposite_fixed = cm[[\"frac_opposite_fixed\"]],\n             mean_abs_delta_p = cm[[\"mean_abs_delta_p\"]],\n             mean_sq_delta_p = cm[[\"mean_sq_delta_p\"]])\n}\nsw <- do.call(rbind, lapply(c(0.02, 0.05, 0.10, 0.20, 0.30, 0.45), sweep_het))\n# Read again in @sec-heterosis-step5: no marker is fixed for opposite alleles\n# anywhere below fst = 0.20, while the divergence term has already more than\n# doubled over that span.\nstopifnot(all(sw$frac_opposite_fixed[sw$fst <= 0.10] == 0))\nfmt(sw, 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  fst| shared| divergence|  total| frac_opposite_fixed| mean_abs_delta_p| mean_sq_delta_p|\n|----:|------:|----------:|------:|-------------------:|----------------:|---------------:|\n| 0.02| 0.3549|     0.0107| 0.3656|               0.000|           0.1138|          0.0214|\n| 0.05| 0.3489|     0.0171| 0.3659|               0.000|           0.1414|          0.0341|\n| 0.10| 0.3374|     0.0246| 0.3620|               0.000|           0.1715|          0.0493|\n| 0.20| 0.3231|     0.0433| 0.3664|               0.002|           0.2252|          0.0867|\n| 0.30| 0.3042|     0.0595| 0.3638|               0.012|           0.2589|          0.1191|\n| 0.45| 0.2792|     0.0846| 0.3639|               0.041|           0.3012|          0.1693|\n\n</div>\n:::\n:::\n\n\nAcross the sweep the divergence term rises by a factor of\n7.9. The comparison that matters\nis in absolute units, not in ratios: divergence gains\n0.0739 per locus and the shared\nterm loses 0.0756. The total does not\nmove.\n\n### The two terms, term by term\n\nThe algebra is one line. Pool A and pool B are drawn *independently* around a\ncommon ancestral frequency $p$, so $\\mathbb{E}[p_A] = \\mathbb{E}[p_B] = p$ and\n$\\mathbb{E}[p_A p_B] = p^2$. Therefore\n\n$$\\mathbb{E}\\!\\left[p_A + p_B - 2 p_A p_B\\right] = 2p(1-p),$$\n\nwhich contains no $F_{ST}$ at all. With ancestral frequencies drawn uniformly on\n$[0.05, 0.95]$ the predicted level is $\\mathbb{E}[2p(1-p)] =$ 0.365,\nagainst a simulated mean of 0.3646 across the whole sweep.\n\nThat the *sum* is flat is the headline, but the Balding-Nichols model predicts\neach half separately, which is the sharper statement. Under it\n$\\mathrm{Var}(p_A) = \\mathrm{Var}(p_B) = F_{ST}\\,p(1-p)$, so\n$\\mathrm{Var}(\\bar p) = F_{ST}\\,p(1-p)/2$ and $\\mathrm{Var}(y) = 2F_{ST}\\,p(1-p)$.\nSubstituting:\n\n$$\\mathbb{E}\\!\\left[2\\bar p(1 - \\bar p)\\right] = 2p(1-p)\\left(1 - \\tfrac{F_{ST}}{2}\\right),\n\\qquad\n\\mathbb{E}\\!\\left[y^2/2\\right] = F_{ST}\\,p(1-p)$$\n\nThe shared term loses $F_{ST}\\,p(1-p)$ and the divergence term gains\n$F_{ST}\\,p(1-p)$: the same expression with opposite signs, not approximately and\nnot on average over some range. Both predictions are parameter-free once the\nancestral distribution is fixed, so they can be laid straight on top of the sweep:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nEp <- 2 * (0.5 - (0.9^2 / 12 + 0.25))      # E[2p(1-p)] for p ~ U(0.05, 0.95)\nsw$pred_shared     <- Ep * (1 - sw$fst / 2)\nsw$pred_divergence <- Ep * sw$fst / 2\nfmt(sw[, c(\"fst\", \"shared\", \"pred_shared\", \"divergence\", \"pred_divergence\")], 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  fst| shared| pred_shared| divergence| pred_divergence|\n|----:|------:|-----------:|----------:|---------------:|\n| 0.02| 0.3549|      0.3614|     0.0107|          0.0036|\n| 0.05| 0.3489|      0.3559|     0.0171|          0.0091|\n| 0.10| 0.3374|      0.3468|     0.0246|          0.0182|\n| 0.20| 0.3231|      0.3285|     0.0433|          0.0365|\n| 0.30| 0.3042|      0.3102|     0.0595|          0.0548|\n| 0.45| 0.2792|      0.2829|     0.0846|          0.0821|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(sw$fst, sw$total, type = \"b\", pch = 19, col = \"#1b7837\", ylim = c(0, 0.40),\n     xlab = \"target fst between pools\", ylab = \"expected heterosis per locus (d = 1)\")\nlines(sw$fst, sw$shared, type = \"b\", pch = 17, col = \"#2166ac\")\nlines(sw$fst, sw$divergence, type = \"b\", pch = 15, col = \"#b2182b\")\nlines(sw$fst, sw$pred_shared, lty = 2, col = \"#2166ac\")\nlines(sw$fst, sw$pred_divergence, lty = 2, col = \"#b2182b\")\nabline(h = mean(sw$total), lty = 2, col = \"grey45\")\nlegend(\"right\", c(\"total\", \"shared\", \"divergence\", \"predicted\"), bty = \"n\",\n       cex = 0.8, pch = c(19, 17, 15, NA), lty = c(NA, NA, NA, 2),\n       col = c(\"#1b7837\", \"#2166ac\", \"#b2182b\", \"grey45\"))\ngrid()\n```\n\n::: {.cell-output-display}\n![Expected heterosis and its two components as the pools are driven apart by drift alone. Dashed lines are the Balding-Nichols predictions for each component separately, with no fitted parameter. Each measured component is offset from its prediction -- divergence above, shared below -- by sampling error in the pool frequencies; that offset narrows along the axis, and the text quantifies both it and the measured gap. The divergence term grows several-fold; the shared term pays for all of it, unit for unit; the total is flat. Nothing is selected here -- this is what neutral divergence does.](05b-heterosis-dominance_files/figure-html/fig-heterosis-sweep-1.png){#fig-heterosis-sweep fig-align='center' width=1050}\n:::\n:::\n\n\nThe measured divergence sits above its prediction at every `fst`, and the measured\nshared term about the same distance below it. That is not drift, it is\nestimation. The\npool frequencies are estimated from 25 and\n25 sampled lines, and a frequency estimated from $n$ lines\ncarries sampling variance $V = pq/n$. Conditional on the true pool frequencies,\n$\\mathbb{E}[\\hat y^2/2] = y^2/2 + (V_A + V_B)/2$ and\n$\\mathbb{E}[2\\hat{\\bar p}(1 - \\hat{\\bar p})] = 2\\bar p(1 - \\bar p) - (V_A + V_B)/2$:\nequal and opposite, so the total estimated from sample frequencies is unbiased\nwhile each half is not.\n\nThe offset is not constant along the sweep. It is proportional to\n$\\mathbb{E}[p_Aq_A + p_Bq_B]$, which the pools themselves erode as they diverge,\nso it shrinks with $(1 - F_{ST})$: about\n0.0072\nper locus at `fst =` 0.02, down to\n0.004\nat `fst =` 0.45, against measured gaps of\n0.007 and\n0.0025.\n\nThose two pairs do not agree equally well. At `fst =` 0.02 prediction\nand measurement are within\n2%\nof each other; at `fst =` 0.45 the measured gap is\n38%\n*below* the predicted offset. The formula gives an expectation; each row of the\nsweep is one draw of 2000 loci at one seed, and the scatter of that\ndraw is not constant either. $\\mathrm{Var}(y)$ is $2F_{ST}\\,p(1-p)$, so the\nper-locus divergence $y^2/2$ has a variance that grows with $F_{ST}$ while the\nnumber of loci averaging it stays fixed -- the high-`fst` rows are the noisy\nones, and the agreement at the bottom of the sweep is the more informative of the\ntwo. The offset is the right order and the right sign at both ends; it is not a\nper-point prediction, and nothing below rests on it being one.\n\nWhat changes by an order of magnitude along the sweep is not the offset but the\nsignal it sits on: at `fst = 0.02` the offset exceeds the predicted divergence of\n0.0036, and by `fst = 0.45` it is a small fraction of\nit. A pool pair's *apparent* divergence overstates its true divergence, most\nseverely when the true divergence is small and the pools are few.\n\n:::: {.callout-important}\n## Every unit of divergence is paid for out of the shared term\n\nUnder neutral divergence the trade is exactly one for one. Drifting the pools\napart does not create heterosis; it relocates it from the shared term to the\ndivergence term. A programme that maximises $F_{ST}$ has bought nothing and spent\nits within-pool diversity to do it.\n\nThis is the mechanism behind @sec-stages Trap 3. That section states the symptom\n-- \"$F_{ST}$ keeps rising as pools drift apart at loci that are *already*\ndivergent, which buys no additional heterosis\" -- and points here for the reason.\nThe sweep table and @fig-heterosis-sweep are that reason.\n::::\n\n## What actually buys heterosis {#sec-heterosis-alignment}\n\nIf divergence per se is worth nothing, why do heterotic groups work?\n\nBecause real pools are not diverged at random with respect to $d$. The divergence\nterm is $\\sum_k d_k y_k^2 / 2$, a *weighted* sum. It grows when the loci that\ndiverge are the loci that carry dominance; under drift the two are independent,\nwhich is exactly why the total was flat.\n\n### Alignment is a covariance\n\nThat sentence can be a number rather than a word. A sum of products is $m$ times\na mean times a mean, plus $m$ times a covariance -- the population covariance\nwith divisor $m$, which is why the chunk rescales `cov()`:\n\n$$\\sum_k d_k\\,y_k^2 / 2 \\;=\\; \\frac{m}{2}\\Big[\\, \\bar d \\; \\overline{y^2}\n  \\;+\\; \\mathrm{cov}(d,\\, y^2) \\,\\Big]$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ny2 <- (pA - pB)^2\nc(divergence = sum(d * y2 / 2),\n  from_parts = ctx$m / 2 * (mean(d) * mean(y2) + cov(d, y2) * (ctx$m - 1) / ctx$m))\n#> divergence from_parts \n#>   32.94521   32.94521\n```\n:::\n\n\nThe first bracketed term is what $F_{ST}$ can see: average divergence times\naverage dominance. The second is what it cannot. **Alignment is\n$\\mathrm{cov}(d, y^2)$**, and no statistic computed from allele frequencies alone\ncan contain it, because $d$ does not appear in one.\n\n### The scenarios\n\nHold the pools fixed, hold $F_{ST}$ fixed, hold the multiset of dominance\ndeviations fixed, and change only which locus gets which $d_k$. `aligned` gives\nthe largest $d_k$ to the largest $y_k^2$, `anti-aligned` does the reverse, and\n`independent` is the draw as made:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmk <- function(dec) { v <- numeric(ctx$m); v[order(y2)] <- sort(d, decreasing = dec); v }\nscen <- list(`anti-aligned` = mk(TRUE), `independent` = d, `aligned` = mk(FALSE))\nal <- do.call(rbind, lapply(names(scen), function(n) {\n  h <- heterosis_partition(pA, pB, scen[[n]])\n  data.frame(scenario = n, cor_d_y2 = cor(scen[[n]], y2),\n             shared = h[[\"shared\"]], divergence = h[[\"divergence\"]], total = h[[\"total\"]])\n}))\nal$relative <- al$total / al$total[al$scenario == \"independent\"]\nfmt(al, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|scenario     | cor_d_y2|  shared| divergence|   total| relative|\n|:------------|--------:|-------:|----------:|-------:|--------:|\n|anti-aligned |   -0.608| 270.538|     11.283| 281.821|    0.792|\n|independent  |    0.006| 322.723|     32.945| 355.669|    1.000|\n|aligned      |    0.953| 370.139|     66.313| 436.452|    1.227|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbp <- barplot(rbind(al$shared, al$divergence), beside = FALSE,\n              names.arg = al$scenario, col = c(\"#2166ac\", \"#b2182b\"),\n              ylab = \"expected heterosis\", border = NA)\nlegend(\"topleft\", c(\"shared\", \"divergence\"), fill = c(\"#2166ac\", \"#b2182b\"),\n       bty = \"n\", cex = 0.8, border = NA)\ntext(bp, al$total, sprintf(\"%.2fx\", al$relative), pos = 3, cex = 0.8, xpd = NA)\ngrid(nx = NA, ny = NULL)\n```\n\n::: {.cell-output-display}\n![The same two pools, the same F_ST, and the same set of dominance deviations in all three bars -- only their placement across loci differs. Expected heterosis moves by half again between the extremes. F_ST cannot see any of this, because d does not enter it.](05b-heterosis-dominance_files/figure-html/fig-heterosis-alignment-1.png){#fig-heterosis-alignment fig-align='center' width=1050}\n:::\n:::\n\n\n$F_{ST}$ is identical in all three columns of the table and in all three bars of\n@fig-heterosis-alignment -- it is a function of the frequencies only, and $d$\nnever enters it. Expected heterosis ranges over a factor of\n1.55.\n\n### Isolating the divergence channel\n\nOne honest qualification. Sorting $d$ against $y^2$ moves the *shared* term as\nwell, because $y^2$ is not independent of $2\\bar p(1 - \\bar p)$: a locus with a\nlarge frequency difference tends to sit at an intermediate mean frequency. Part\nof the effect above therefore arrives through the shared half, not the divergence\nhalf.\n\nThe channel can be separated. Permute $d$ only *within* groups of loci that share\na value of the shared weight $2\\bar p(1 - \\bar p)$. The shared term is then\ninvariant by construction -- exactly, not approximately -- and whatever moves is\nthe divergence channel alone:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhz  <- 2 * ((pA + pB) / 2) * (1 - (pA + pB) / 2)\ngrp <- split(seq_len(ctx$m), round(hz, 9))\nstrat <- function(dec) {\n  v <- numeric(ctx$m)\n  for (i in grp) v[i[order(y2[i])]] <- sort(d[i], decreasing = dec)\n  v\n}\nst <- do.call(rbind, lapply(c(aligned = FALSE, `anti-aligned` = TRUE), function(dec)\n  as.data.frame(as.list(heterosis_partition(pA, pB, strat(dec))))))\nfmt(st, 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|             |   shared| divergence|    total|\n|:------------|--------:|----------:|--------:|\n|aligned      | 322.7234|    57.7211| 380.4445|\n|anti-aligned | 322.7234|    14.4716| 337.1949|\n\n</div>\n:::\n:::\n\n\nThe shared column is identical to the digit; the divergence term still moves by\na factor of 4 and the total by\n13%. The alignment result survives\nits own control.\n\n## Reading the S1 panel again\n\n@sec-stages logs `frac_opposite_fixed` and `mean_abs_delta_p` every cycle as\nstand-ins for heterosis potential. The sweep above says how good they are.\n\n`mean_sq_delta_p` is not a proxy at all. It is $\\overline{y^2}$, so half of it is\nthe unweighted divergence term $GD_{BS}$, exactly:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(half_mean_sq = mean(sw$mean_sq_delta_p) / 2,\n  divergence   = mean(sw$divergence))\n#> half_mean_sq   divergence \n#>     0.039983     0.039983\n```\n:::\n\n\nWhat it cannot carry is the weighting by $d$, which is the previous section's\npoint; the frequency half of the divergence term it reports without loss.\n\n`frac_opposite_fixed` is a different matter:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfmt(sw[, c(\"fst\", \"divergence\", \"frac_opposite_fixed\", \"mean_abs_delta_p\",\n           \"mean_sq_delta_p\")], 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  fst| divergence| frac_opposite_fixed| mean_abs_delta_p| mean_sq_delta_p|\n|----:|----------:|-------------------:|----------------:|---------------:|\n| 0.02|     0.0107|               0.000|           0.1138|          0.0214|\n| 0.05|     0.0171|               0.000|           0.1414|          0.0341|\n| 0.10|     0.0246|               0.000|           0.1715|          0.0493|\n| 0.20|     0.0433|               0.002|           0.2252|          0.0867|\n| 0.30|     0.0595|               0.012|           0.2589|          0.1191|\n| 0.45|     0.0846|               0.041|           0.3012|          0.1693|\n\n</div>\n:::\n:::\n\n\nUp to `fst = 0.10` it is exactly zero -- not one marker in 2000\nqualifies -- and it first exceeds 1% of markers at `fst = 0.30`, near the top of\nthe sweep. It counts *near-fixed* opposite loci, and the divergence lives at\nintermediate frequency differences, which the threshold discards.\n\n**Log `mean_sq_delta_p`.** It is exact, it is monotone across the whole sweep,\nand it costs one squaring more than the statistic already being logged.\n`pool_complementarity()` and `s1_monitor()` return it.\n\n## General and specific combining ability {#sec-heterosis-gca-sca}\n\nEverything so far has been about $\\mathbb{E}[H]$. Now the spread.\n\nThe same expansion that produced the shared/divergence split produces the\ncombining-ability decomposition, with no new machinery and no model fitting. Let\n$u_{ik} \\in \\{0, 1\\}$ be the genotype of pool-A line $i$ at locus $k$ and\n$v_{jk}$ that of pool-B line $j$, and write each as its pool frequency plus a\ndeviation, $u = p_A + \\delta u$ and $v = p_B + \\delta v$. The per-locus\nheterozygosity of the cross, $u + v - 2uv$, expands to\n\n$$u + v - 2uv \\;=\\; \\underbrace{p_A + p_B - 2p_Ap_B}_{\\text{mean}}\n  \\;+\\; \\underbrace{(1 - 2p_B)\\,\\delta u}_{\\text{parent A}}\n  \\;+\\; \\underbrace{(1 - 2p_A)\\,\\delta v}_{\\text{parent B}}\n  \\;-\\; \\underbrace{2\\,\\delta u\\, \\delta v}_{\\text{both}}$$\n\nFour terms: one constant, one linear in each parent, one bilinear. Weight by $d_k$,\nsum over loci, and the classical decomposition falls out,\n\n$$H_{ij} = \\mu + g^A_i + g^B_j + s_{ij}$$\n\nwith\n\n$$g^A_i = \\sum_k d_k (1 - 2p_{Bk})\\,\\delta u_{ik}, \\qquad\n  s_{ij} = -2 \\sum_k d_k\\, \\delta u_{ik}\\, \\delta v_{jk}$$\n\nand $g^B_j$ symmetrically. What is linear in one parent is general combining\nability: it is carried into every cross that parent enters. What is bilinear\ndepends on *which two* lines met, and is specific combining ability. Because the\ndeviations are taken from each pool's own line frequencies they sum to zero over\nthat pool's lines, which is what makes the three components mean zero and\nmutually orthogonal. `heterosis_gca_sca()` is that expansion and nothing more:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheterosis_gca_sca\n#> function (U, V, d) \n#> {\n#>     stopifnot(ncol(U) == ncol(V), length(d) == ncol(U))\n#>     pA <- colMeans(U)\n#>     pB <- colMeans(V)\n#>     cU <- sweep(U, 2, pA)\n#>     cV <- sweep(V, 2, pB)\n#>     list(mu = heterosis_expected(pA, pB, d), gca_A = drop(cU %*% \n#>         (d * (1 - 2 * pB))), gca_B = drop(cV %*% (d * (1 - 2 * \n#>         pA))), sca = -2 * (cU * rep(d, each = nrow(U))) %*% t(cV))\n#> }\n#> <bytecode: 0xc857bc660>\n#> <environment: namespace:hybdiv>\n```\n:::\n\n\nIt reconstructs every hybrid in the factorial exactly, and all three components\nare mean zero:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncs <- heterosis_gca_sca(U, V, d)\nH  <- heterosis_value(ctx$X, d)\nia <- ctx$ped$a\nib <- ctx$ped$b - nA\nc(max_residual = max(abs(H - (cs$mu + cs$gca_A[ia] + cs$gca_B[ib] +\n                              cs$sca[cbind(ia, ib)]))),\n  mu_vs_mean   = abs(cs$mu - mean(H)),\n  mean_gca_A   = mean(cs$gca_A), mean_sca = mean(cs$sca))\n#>  max_residual    mu_vs_mean    mean_gca_A      mean_sca \n#>  7.958079e-13  1.136868e-13 -4.796163e-16 -1.264766e-15\n```\n:::\n\n\nThis is not a decomposition that resembles the two-way analysis of variance. It\n*is* the two-way analysis of variance: $\\mu$, $g^A$ and $g^B$ are the grand mean\nand the row and column effects of the $H_{ij}$ table, and $s_{ij}$ is the\ninteraction residual of the additive fit, to machine precision:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmax(abs(resid(lm(H ~ factor(ia) + factor(ib))) - cs$sca[cbind(ia, ib)]))\n#> [1] 6.966872e-12\n```\n:::\n\n\n@comstock1949 designed reciprocal recurrent selection around the distinction\nbetween these two components. The algebra above says what each one is made of --\nand the next section says which of the two their scheme actually selects on.\n\n### GCA is an average effect in the other pool's background\n\nLook at the weight on $\\delta u$: it is $d_k(1 - 2p_{Bk})$, and $1 - 2p_B$ is\n$q_B - p_B$. That is the frequency factor of the classical average effect of a\ngene substitution, $a + d\\,(q - p)$ [@falconer1996, Ch. 7], with two differences:\nthe additive part $a$ is absent, because it belongs to the parental mean and not\nto $H$, and the frequencies are **pool B's**, not pool A's.\n\nThis is the whole reason combining ability is not a property of a line. A pool-A\nline's alleles are always substituted into a pool-B background, so its general\ncombining ability for heterosis is a dominance effect *evaluated at the tester\npool's frequencies*. Change the tester pool and every number changes. Two limits\nfollow immediately:\n\n- A locus at which the tester pool sits at $p_B = 0.5$ contributes **exactly\n  zero** to $g^A$, whatever $\\delta u_{ik}$ is. It still contributes to $g^B$,\n  through $(1 - 2p_A)\\,\\delta v_{jk}$, and to $s_{ij}$; what it cannot do is\n  discriminate between pool-A parents.\n- A locus at which the tester pool is fixed, $p_B \\in \\{0, 1\\}$, has\n  $\\delta v \\equiv 0$, so it contributes $\\pm d_k\\,\\delta u_{ik}$ to $g^A$ and\n  nothing to either $g^B$ or $s_{ij}$. The cross is then predictable from the\n  pool-A parent by itself.\n\nBetween those two limits sits every real programme, and @sec-heterosis-relocation\nis about which limit divergence pushes it towards.\n\nThis is also the exact sense in which @comstock1949's scheme is built on the\ndecomposition. Reciprocal recurrent selection evaluates each pool-A candidate on\nits cross performance against a *sample of the opposite pool*, and symmetrically\nfor pool B. Averaging over testers removes $s_{ij}$, so of the heterosis in the\ndecomposition above only $g^A_i$ survives as a contrast between pool-A\ncandidates. Note what that does *not* say: cross performance is a genotypic\nvalue, not a mid-parent difference, so it also carries the candidate's own\nadditive contribution -- the part that cancelled out of $H$ in the mid-parent\nderivation above and is not in this decomposition at all.\nSelection on testcross means therefore acts on the additive part and $g^A_i$\ntogether. What the algebra here delimits is the dominance share of that response,\nand it says the share is general combining ability against the tester pool.\n\n### SCA is minus twice a weighted parental inner product\n\nThe bilinear term is $s_{ij} = -2\\sum_k d_k\\,\\delta u_{ik}\\,\\delta v_{jk}$: minus\ntwice the $d$-weighted inner product of the two parents' *centred* genotypes, a\ncovariance up to the factor $1/m$. For $d_k > 0$, two parents that deviate from\ntheir pools in the same direction have a positive inner product and therefore a\n**negative** SCA.\n\nRead in words: two parents that resemble each other -- after removing what is\ntypical of each pool -- cross badly, and the resemblance that counts is weighted\nby $d$, not by marker count. Similarity enters negatively throughout this chapter\n-- $1 - \\theta_{AB}$, $d\\,m\\,(1 - f^L_{ab})$ -- but everywhere else it is\nsimilarity measured against a fixed base. Here it is measured against each pool's\nown mean, which is what makes the term specific to a *pair* rather than a\nproperty either parent carries into all its crosses.\n\nIt is also @sec-heterosis-distance again. Since $\\mu$, $g^A$ and $g^B$ are the\ngrand, row and column means of the $H_{ij}$ table, $s_{ij}$ is the double-centred\n$H$ matrix. Under flat $d$, $H_{ij} = d\\,m\\,(1 - f^L_{ij})$, and double-centring\nannihilates the constant and flips the sign of what remains:\n\n$$s_{ij} \\;=\\; -\\,d\\,m \\cdot \\mathrm{DC}\\big(f^L\\big)_{ij},$$\n\nwith $\\mathrm{DC}(M)_{ij} = M_{ij} - \\bar M_{i\\cdot} - \\bar M_{\\cdot j} + \\bar\nM_{\\cdot\\cdot}$ over the $A \\times B$ block. The factor $-dm$ is not cosmetic:\n$s_{ij}$ is on the trait scale and $f^L$ is a probability, and the minus is the\nsame minus as in $-2\\sum_k d_k \\delta u\\, \\delta v$ -- more coancestry than the\ntwo margins predict means *less* SCA. So the coancestry kernel determines SCA\nunder exactly the condition it determines heterosis, up to that constant, and\nstops doing so under exactly the same condition: a $d$ that varies across loci.\n\n### The variance components\n\nBecause the three components are orthogonal, the variance of heterosis over the\nfactorial splits with them. Under the sampling model of the simulation -- each\nline's genotype an independent Bernoulli($p_{Ak}$) draw at every locus, so\nunrelated lines and linkage equilibrium within each pool -- each piece has a\nclosed form in the pool frequencies:\n\n$$\\sigma^2_{GCA_A} = \\sum_k d_k^2\\,(1 - 2p_{Bk})^2\\,p_{Ak}q_{Ak},\n\\qquad\n\\sigma^2_{SCA} = 4 \\sum_k d_k^2\\,p_{Ak}q_{Ak}\\,p_{Bk}q_{Bk}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqa <- pA * (1 - pA)\nqb <- pB * (1 - pB)\nfmt(data.frame(\n  component = c(\"GCA_A\", \"GCA_B\", \"SCA\"),\n  observed  = c(var(cs$gca_A), var(cs$gca_B), var(as.vector(cs$sca))),\n  closed_form = c(sum(d^2 * (1 - 2 * pB)^2 * qa),\n                  sum(d^2 * (1 - 2 * pA)^2 * qb),\n                  4 * sum(d^2 * qa * qb))), 2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|component | observed| closed_form|\n|:---------|--------:|-----------:|\n|GCA_A     |    32.00|       35.03|\n|GCA_B     |    35.63|       38.07|\n|SCA       |    70.38|       71.48|\n\n</div>\n:::\n:::\n\n\nThe closed forms take the sample frequencies as the pool frequencies; the observed\ncolumn is one realisation of them. The GCA rows are variances over\n25 lines, whose relative sampling error is about\n$\\sqrt{2/n} \\approx$ 28%, and the\nagreement is within that. That error rate belongs to the independent-Bernoulli\nsampling model declared immediately above, not to the statistic: it is the\nsampling error of a variance over $n$ *independent* observations, and a recycled\npool has no such $n$. @sec-heterosis-step7 measures how far the agreement moves\nonce the lines are related.\n\nNote what each one requires. $\\sigma^2_{SCA}$ carries $p_Aq_A\\,p_Bq_B$: it needs\n**both** pools to be polymorphic. Fix either pool at a locus and that locus\ncontributes no specific combining ability at all, whatever its $d_k$. Within-pool\ndiversity is not merely something the diversity constraint defends; it is the\nraw material of SCA.\n\n## Divergence destroys SCA faster than it builds GCA {#sec-heterosis-relocation}\n\nPut the two closed forms next to the drift argument of @sec-heterosis-flat and\nthe variance tells a different story from the mean. The mean was flat; the\nvariance is not, and it does not merely change shape.\n\nUnder Balding-Nichols, $\\mathbb{E}[p_Aq_A] = p(1-p)(1 - F_{ST})$ and\n$\\mathbb{E}[(1 - 2p_B)^2] = (1-2p)^2 + 4F_{ST}\\,p(1-p)$, and $p_A$ and $p_B$ are\nindependent given the ancestral $p$. Per locus, in expectation over the draw,\n\n$$\\mathbb{E}\\big[\\sigma^2_{SCA,k}\\big] = 4d_k^2\\,p^2(1-p)^2\\,(1 - F_{ST})^2,\n\\qquad\n\\mathbb{E}\\big[\\sigma^2_{GCA_A,k}\\big] = d_k^2\\,p(1-p)\\,(1 - F_{ST})\n  \\left[(1-2p)^2 + 4F_{ST}\\,p(1-p)\\right]$$\n\nRead the two expressions before reading the sweep, because they already say what\nit will show.\n\nBoth carry the erosion factor $(1 - F_{ST})$, and both are **zero at\n$F_{ST} = 1$**: a pool fixed at every locus has no two lines that differ, so it\nhas no combining-ability variance of either kind. Divergence therefore cannot\ntransfer variance from one component to the other indefinitely; it destroys both\nin the limit. SCA carries the factor twice, because it needs both pools\npolymorphic at the same locus. GCA carries it once, multiplied by the tester\nfactor $(1 - 2p_B)^2$, whose expectation *grows* with $F_{ST}$.\n\nThe two expressions therefore behave differently in $F_{ST}$. The SCA expression\nis convex and decreasing on $[0, 1]$: it is a positive constant times\n$(1 - F_{ST})^2$, so it only ever falls. The GCA expression is a *concave*\nparabola, its $F_{ST}^2$ coefficient being $-4d_k^2p_k^2(1-p_k)^2$, and\ndifferentiating it gives the only turnover in this section. GCA variance rises\nfrom $F_{ST} = 0$ at a locus if and only if $8p(1-p) > 1$, that is\n$\\tfrac12(1 - 1/\\sqrt2) < p < \\tfrac12(1 + 1/\\sqrt2)$, and turns over at\n\n$$F^\\star_k = \\frac{8p_k(1-p_k) - 1}{8p_k(1-p_k)},$$\n\nwhich is negative outside that interval -- at such loci GCA variance falls from\nthe start. A sum of concave parabolas is a concave parabola, and its maximum\nworks out to the $d_k^2\\,(p_kq_k)^2$-weighted mean of the $F^\\star_k$. Whether\nthat mean lands inside $[0, 1]$ is a property of the ancestral frequency\ndistribution, not a theorem: pools founded mostly at extreme frequencies would\nput it below zero and GCA variance would decline monotonically. Under the\n$U(0.05, 0.95)$ ancestral draw used here enough loci sit in the interval to place\nit inside the range, which is why the sweep below straddles a peak. The sweep's\ngrid can show that the peak is interior; it cannot locate it.\n\nWhat is monotone is the ratio,\n\n$$\\frac{\\mathbb{E}[\\sigma^2_{SCA,k}]}{\\mathbb{E}[\\sigma^2_{GCA_A,k}]}\n  = \\frac{4p(1-p)\\,(1 - F_{ST})}{(1-2p)^2 + 4F_{ST}\\,p(1-p)},$$\n\nwhich falls in $F_{ST}$ at every locus. So the defensible statement is about the\n*share*, not about a transfer. Expected heterosis, we already know, does not move\nat all. Sweeping the pools apart -- same ancestral frequencies, fresh\nBalding-Nichols draws at each `fst`, as in @sec-heterosis-flat -- and evaluating\nthe closed forms on the realised frequencies:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nreloc <- function(fst) {\n  cf <- modifyList(book_cfg, list(fst = fst, seed = 5))\n  Pf <- pool_freqs(simulate_lines(cf) / 2,\n                   rep(c(\"A\", \"B\"), c(cf$n_pool_A, cf$n_pool_B)))\n  a <- Pf[\"A\", ]; b <- Pf[\"B\", ]\n  va <- sum(d^2 * (1 - 2 * b)^2 * a * (1 - a))\n  vb <- sum(d^2 * (1 - 2 * a)^2 * b * (1 - b))\n  vs <- 4 * sum(d^2 * a * (1 - a) * b * (1 - b))\n  data.frame(fst = fst, var_GCA = va + vb, var_SCA = vs,\n             frac_SCA = vs / (va + vb + vs))\n}\nrl <- do.call(rbind, lapply(c(0.02, 0.05, 0.10, 0.15, 0.20, 0.30, 0.45), reloc))\nfmt(rl, 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  fst| var_GCA| var_SCA| frac_SCA|\n|----:|-------:|-------:|--------:|\n| 0.02|  60.047|  91.807|    0.605|\n| 0.05|  62.025|  87.941|    0.586|\n| 0.10|  68.630|  75.503|    0.524|\n| 0.15|  71.230|  67.599|    0.487|\n| 0.20|  77.956|  63.166|    0.448|\n| 0.30|  80.630|  45.875|    0.363|\n| 0.45|  77.894|  27.767|    0.263|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(rl$fst, rl$var_GCA, type = \"b\", pch = 19, col = \"#1b7837\",\n     ylim = range(0, rl$var_GCA, rl$var_SCA),\n     xlab = \"target fst between pools\",\n     ylab = \"variance of heterosis over the factorial\")\nlines(rl$fst, rl$var_SCA, type = \"b\", pch = 15, col = \"#b2182b\")\nlegend(\"right\", c(\"GCA (both pools)\", \"SCA\"), bty = \"n\", cex = 0.8,\n       pch = c(19, 15), col = c(\"#1b7837\", \"#b2182b\"))\ngrid()\n```\n\n::: {.cell-output-display}\n![The same neutral divergence sweep, read through the combining-ability decomposition rather than through the mean. Expected heterosis is flat across this entire range (@fig-heterosis-sweep); its decomposition is not. Specific combining ability falls steeply throughout. General combining ability rises, by much less than SCA loses, and itself turns over inside the range -- both components vanish at F_ST = 1. The two curves do not sum to a constant: most of the SCA variance lost is destroyed rather than relocated, and the exact percentages are in the text.](05b-heterosis-dominance_files/figure-html/fig-heterosis-relocation-1.png){#fig-heterosis-relocation fig-align='center' width=1050}\n:::\n:::\n\n\nTake the three columns in order, because the headline is in the arithmetic\nbetween them.\n\nSCA variance falls by\n70% across the sweep, a\ndrop of 64 units. GCA variance\nends 30% above where it\nstarted, a gain of 17.8 units, and\npeaks at an `fst` of 0.3 -- interior, as the\nancestral distribution used here leads one to expect, though a grid whose\nneighbouring points are 0.2 and\n0.45 locates the peak only to that interval and\ncannot resolve it further. So the GCA gain recovers about\n28%\nof what SCA lost. The rest is gone: total variance in heterosis over the\nfactorial falls from 151.9 to\n105.7, a\n30%\ndecline, while the mean stays fixed throughout.\n\nRead those four percentages as one realisation, not as constants. They come from\na single pair of seeds -- `seed = 5` for the pool frequencies, `set.seed(4)` for\n$d$ -- with no replication and no dispersion reported, and they will move if\neither changes. What does not depend on the seed is the direction, which is\nalready in the two closed forms above: $\\sigma^2_{SCA}$ is a positive multiple of\n$(1 - F_{ST})^2$ and can only fall, and both components vanish at $F_{ST} = 1$,\nso no amount of neutral divergence can hold the total up. The ordering of the\ncolumns is algebra; their magnitudes are this draw.\n\nThe share of that variance which is specific falls from\n0.605 to 0.263. That\nstatement -- about the share -- is the one the sweep supports; \"the dominance\nexpressed as SCA reappears as GCA\" is not, and the two columns above are why.\n\nThe share result itself is not new in direction. @reif2007 prove that the ratio\nof dominance to additive variance in a hybrid population falls as its two parent\npopulations diverge, and conclude that superior hybrids then become predictable\nfrom general combining ability effects. The direction of this section's share\nresult is theirs; the quantity is not the same one. Their ratio is\n$\\sigma^2_D / \\sigma^2_A$ over the hybrid population, whose denominator contains\nthe additive variance contributed by the parents -- the part that cancelled out\nof $H$ in the mid-parent derivation and is absent from everything computed here.\nThe ratio in the table above is $\\sigma^2_{SCA}$ over\n$\\sigma^2_{GCA} + \\sigma^2_{SCA}$ *within heterosis only*. The two move the same\nway and are not interchangeable. What the sweep adds is the denominator, which a\nratio hides: a ratio can fall because its\nnumerator falls, because its denominator rises, or both, and the columns above\nsay which. Here the numerator collapses and the denominator recovers only part of\nit, so the share falls and the total falls with it.\n\n> *Neutral* divergence -- drift, the only kind on this sweep -- does not buy\n> expected heterosis, and it does not move heterosis from one combining-ability\n> component into the other. It **shrinks the part of hybrid variation that only a\n> cross can reveal**, destroying SCA variance faster than it builds GCA variance.\n> An additive model looks better against diverged pools mainly because there is\n> less left for it to miss. Divergence that is *aligned* with dominance is a\n> different matter and @sec-heterosis-alignment is where it is measured; the\n> sweep here holds alignment at zero by construction.\n\nThis sharpens a question @sec-genomic-prediction had to leave open. That chapter\nfits one additive effect per marker and notes that such a model cannot represent\nSCA at all. The sweep says how large the unrepresentable share is, and how it\nmoves: against poorly separated pools most of the variance in heterosis is\nspecific; against well separated ones a minority is. These are shares of the\nvariance in *heterosis*, not of total hybrid value, whose parental-mean part is\nadditive at every $F_{ST}$. @technow2014 report high accuracy for additive hybrid\nprediction in established, clearly separated dent and flint pools, which is the\nregime where this model puts the specific share at its lowest -- consistent with\nthe mechanism, though a single observational study in one crop cannot test it.\n\n:::: {.callout-warning}\n## A smaller SCA share is not a better programme, and this is not a licence to maximise $F_{ST}$\n\nThree things stay true at every point on that sweep. Expected heterosis does not\nchange. The within-pool diversity spent to buy the divergence is spent for good.\nAnd $\\sigma^2_{SCA} \\to 0$ is the limit in which no cross is better than its\nparents predict -- there is nothing left to *find* by testing combinations, which\nis the activity the whole factorial exists to support. Past the peak of the GCA\ncurve in @fig-heterosis-relocation even the predictable half shrinks: at\n$F_{ST} = 1$ there is no\ncombining-ability variance of either kind, because no two lines in a pool differ.\n\nThe falling SCA share is therefore a fact about what a predictor can express, not\na gain. A programme reading it as one would be congratulating itself on having\nless to predict.\n\nSo this is a second, independent reason for @sec-stages Trap 3's prescription to\nhold $F_{ST}$ in a band rather than at a maximum. @sec-heterosis-flat gave the\ndiversity-side reason. This is the prediction-side one, and it points the same\nway.\n::::\n\n### What this says about ranking crosses\n\nThe F1 of two fixed lines is genetically uniform, so the progeny-variance term\nthat drives the usefulness criterion at @sec-stages S2 is zero for the hybrid\nitself, and cross ranking reduces to ranking means. That is true, and it is why\nthis book ranks hybrids on an index rather than on $\\mu + i h \\sigma$.\n\nIt does not follow that the ranking is easy. The *mean* of an F1 contains an SCA\nterm that an additive $\\mathbf{G}$ omits entirely, and @sec-heterosis-relocation\nsized its share of the variance in heterosis: a majority of it against weakly\nseparated pools, a minority against well separated ones, and zero only at the\ndegenerate limit where one pool is fixed at every locus. The\nprogeny variance collapses; the dominance deviation does not.\n\n## Running this on a real programme {#sec-heterosis-protocol}\n\nEight steps, in the order they have to be executed on a maize-type programme's\nown data. Each one names the function to call, the quantity to check and what\nfailure looks like. Steps 1-5 need only genotypes and pool labels.\n\nSteps 6-8 need more, and the requirement is worth naming because it is the\nreason these steps are rarely run. $H_{ij}$ is a **mid-parent difference**, so\nfitting the decomposition on real data needs the hybrid trial *and* per-se\nphenotypes of the parent lines, measured on the same scale as the hybrid trial:\na separate inbred-level trial, in the same environments, with a common check set\nor an overlapping design to put the two on one scale. Very few programmes run\none, because inbred per-se performance has no commercial value. Without it what\nthe two-way layout of step 6 fits is hybrid *performance*, not heterosis, and\nits row effects are then general combining ability **plus** the parent's own\nadditive contribution -- the term @sec-heterosis-gca-sca shows is not in $H$ at\nall. Both decompositions are legitimate; they are not the same decomposition,\nand the difference is exactly the parental additive part.\n\n### Step 1 -- Verify the parents are inbred, and price it if they are not {#sec-heterosis-step1}\n\nEvery formula in this chapter rests on the first premise. It is checkable in one\nline: an inbred line's self-coancestry is exactly 1, and its heterozygous\nfraction exactly 0.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(min_self_coancestry = min(diag(molecular_coancestry(L / 2))),\n  max_het_fraction    = max(rowMeans(L / 2 == 0.5)),\n  dominance_value_of_the_most_heterozygous_line =\n    max(abs(heterosis_value(rbind(U, V), d))))\n#>                           min_self_coancestry \n#>                                             1 \n#>                              max_het_fraction \n#>                                             0 \n#> dominance_value_of_the_most_heterozygous_line \n#>                                             0\n```\n:::\n\n\nIf those numbers are not 1, 0 and 0, the parents are not fixed and the mid-parent\nalready carries dominance of its own. The size of the resulting error is not\nsmall. Build parents that are *intra-pool* F1s instead of inbred lines -- one\nrandom cross within each pool, so each parent sits at its pool's random-mating\nheterozygosity -- then cross them across pools by drawing one gamete per parent\nper locus:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nintra_pool_f1 <- function(W, n, seed) {\n  set.seed(seed)\n  (W[sample.int(nrow(W), n, TRUE), ] + W[sample.int(nrow(W), n, TRUE), ]) / 2\n}\nZA  <- intra_pool_f1(U, nrow(U), 101)\nZB  <- intra_pool_f1(V, nrow(V), 102)\npd2 <- expand.grid(a = seq_len(nrow(ZA)), b = seq_len(nrow(ZB)))\n\n# One gamete per parent per locus, five independent draws of the whole factorial.\ndraw <- t(vapply(1:5, function(r) {\n  set.seed(200 + r)\n  gA <- matrix(rbinom(length(ZA), 1, ZA), nrow(ZA))[pd2$a, ]\n  gB <- matrix(rbinom(length(ZB), 1, ZB), nrow(ZB))[pd2$b, ]\n  H  <- heterosis_value((gA + gB) / 2, d)\n  mp <- (heterosis_value(ZA, d)[pd2$a] + heterosis_value(ZB, d)[pd2$b]) / 2\n  c(hybrid_value = mean(H), mid_parent_gain = mean(H - mp))\n}, numeric(2)))\n\nclosed_form <- heterosis_expected(colMeans(ZA), colMeans(ZB), d)\nc(parent_het_fraction   = mean(c(ZA, ZB) == 0.5),\n  closed_form           = closed_form,\n  simulated_hybrid      = mean(draw[, \"hybrid_value\"]),\n  simulated_gain        = mean(draw[, \"mid_parent_gain\"]),\n  # The parental term is fixed across draws, so both columns carry the same s.d.\n  sd_across_draws       = sd(draw[, \"hybrid_value\"]),\n  exact_sum_d_y2        = sum(d * (pA - pB)^2),\n  overstatement         = closed_form / mean(draw[, \"mid_parent_gain\"]))\n#> parent_het_fraction         closed_form    simulated_hybrid      simulated_gain \n#>            0.294260          355.428354          355.106663           67.222488 \n#>     sd_across_draws      exact_sum_d_y2       overstatement \n#>            1.708396           65.890423            5.287343\n```\n:::\n\n\nResult. The parents carry\n0.294 of their loci heterozygous.\n`heterosis_expected()` is still correct about the *hybrid*: it predicts\n355.4 against a simulated\n355.1 (s.d. 1.71\nover five gamete draws), because that formula uses gamete frequencies only and\ndoes not care what the parents' own genotypes are. What it is not correct about\nis the *gain*: the mid-parent difference is\n67.2, the same\n1.71 standard deviation shifted down by the\nparents' own dominance value, so reading the closed form as heterosis overstates\nthe gain by a factor of\n5.29. The simulated gain\nagrees with the exact $\\sum_k d_k y_k^2$ of\n@sec-heterosis-identity, 65.9, to within one\nstandard deviation of the gamete draw.\n\nInterpretation, with its limit. The correction is not a fudge factor: it is the\nparents' own dominance contribution,\n287.9 here,\nwhich `heterosis_value()` computes on the parent matrix directly and which is\nexactly zero under the inbred premise. Subtracting it recovers the mid-parent\ngain, and that gain matches the $\\sum_k d_k y_k^2$ of @sec-heterosis-identity\n**in expectation only**: the realised intra-pool F1 parents are one draw, not\ntheir own expectation, so each replicate's mid-parent carries a sampling\ndeviation of its own -- which is why the agreement reported above is to within\none standard deviation of the gamete draw and not exact. The factor of\n5.29 itself is specific to\nthis configuration -- `fst` = 0.15, gamma-distributed $d$, parents at\nfull random-mating heterozygosity -- and it shrinks toward 1 as the parents\napproach fixation. Five gamete draws at one seed family give the dispersion\nreported and no more.\n\n**Call.** `diag(molecular_coancestry(GL))`; `heterosis_value()` on the parent\nmatrix, not only on the hybrids.\n**Check.** Self-coancestry 1 and heterozygous fraction 0 for every parent.\n**Warning sign.** Any parent with a heterozygous fraction above the marker error\nrate. Partially inbred parents (S1, S2, clonal maintenance of a heterozygous\nplant) invalidate the mid-parent cancellation, not the hybrid prediction.\n**Threshold.** `heterosis_value()` on the parent set must return zero to machine\nprecision. If it does not, subtract it: the mid-parent gain is the hybrid value\nminus the parents' mean, always.\n\n### Step 2 -- Compute pool frequencies, and keep them distinct from $p_0$ {#sec-heterosis-step2}\n\n`pool_freqs(GL, pool)` returns one row per pool. These are the *current* cycle's\nfrequencies and they are supposed to move; they are not the frozen base $p_0$\nthat @sec-genomic-era's two inbreeding lenses are measured against. Both objects\nare frequency vectors over the same markers and confusing them produces a\nheterosis prediction anchored to a population that no longer exists.\n\n**Call.** `pool_freqs(GL / 2, pool)` on the current cycle's line matrix.\n**Check.** `nrow() == 2` and the pool labels are the heterotic groups, not\nfamilies or locations.\n**Warning sign.** A pool frequency vector computed over *hybrids* rather than\nlines. On the full factorial that gives $(p_A + p_B)/2$ for both pools --\n@sec-era-step1 proves the identity -- which sets $y \\equiv 0$ and reports the\ndivergence term as zero.\n**Threshold.** None; this is a bookkeeping step, and the only failure is silent.\n\n### Step 3 -- Decide what stands in for $d_k$, and say so {#sec-heterosis-step3}\n\nNothing below step 4 can be computed without a weight per locus. Three defensible\nchoices, in decreasing order of what they require:\n\n1. **Estimated $d_k$** from a dominance model fitted on hybrid data. This is what\n   the third premise assumes exists, and it is the only option that lets\n   $\\mathrm{cov}(d, y^2)$ be computed.\n2. **Flat $d_k \\equiv 1$**, which makes $H$ proportional to marker distance and\n   the whole calculation a function of the coancestry kernel\n   (@sec-heterosis-distance). Everything in this chapter's frequency algebra\n   still holds; what is lost is alignment, which is exactly the term flat $d$\n   sets to zero.\n3. **No $d$ at all**, reporting only $GD_{BS}$ and `mean_sq_delta_p`, which is\n   the frequency half of the divergence term and is exact\n   (@sec-heterosis-alignment says what is missing).\n\nThe cost of choice 2 is measurable, and it is the correlation already computed\nin @sec-heterosis-distance: under flat $d$ heterosis and marker distance are the\nsame statistic, and under the gamma-distributed $d$ used here the correlation\nbetween them is 0.78.\n\n**Call.** `heterosis_value(X, d)` with whichever vector you have chosen, and\nrecord the choice next to the number.\n**Check.** `length(d) == ncol(X)` and $d$ indexed in the same marker order.\n**Warning sign.** A report that gives expected heterosis without saying which of\nthe three choices produced it. At the correlation just quoted the choices are not\ninterchangeable for ranking crosses, and their absolute values are on different\nscales altogether.\n**Threshold.** If choice 2 is used, state that alignment is assumed zero, because\nthat is what flat $d$ asserts.\n\n### Step 4 -- Partition, and cross-check against the diversity partition {#sec-heterosis-step4}\n\n`heterosis_partition(pA, pB, d)` returns `shared`, `divergence` and `total`.\nWith $d \\equiv 1$ and divided by $m$ the first two are the $GD_T$ and $GD_{BS}$\nof `gd_partition()`, and the chunk in @sec-heterosis-identity checks that to\ntwelve digits. Running both is a consistency test worth the two lines it costs --\nbut only if the two calls are given the **same line weights**, and by default\nthey are not.\n\nThe algebra says why. For any weights $w$ over the lines of a pool, with inbred\nlines, $\\theta_A = \\overline{p_{A,w}^2 + q_{A,w}^2}$ where $p_{A,w} = \\sum_i w_i\nu_{ik}$ is the *weighted* pool frequency, and the same for $B$ and for\n$\\theta_{AB}$. Substituting into `gd_partition()`'s definitions,\n$GD_T = 1 - \\bar f = \\overline{2\\bar p(1 - \\bar p)}$ and\n$GD_{BS} = \\tilde f - \\bar f = \\overline{(p_{A,w} - p_{B,w})^2}/2$, which are\nexactly `heterosis_partition()`'s two terms evaluated at $p_{A,w}$ and\n$p_{B,w}$. So the identity holds for *any* weighting -- as long as both sides use\nthe same one. `gd_partition(idx, ctx)` weights each line by how often the\nselection uses it (`line_weights()`), while `pool_freqs()` is unweighted. On the\nfull factorial usage is uniform and the two coincide; on a selected subset they\ndo not, and the discrepancy is not small:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ni_trunc <- sel_truncation(ctx, 60)     # index truncation: deliberately unbalanced\ngp_sel  <- gd_partition(i_trunc, ctx)\nGLh <- L / 2\nwt  <- line_weights(i_trunc, ctx)\nhp2 <- function(a, b) {\n  heterosis_partition(a, b, rep(1, ctx$m))[c(\"shared\", \"divergence\")] / ctx$m\n}\ncmp <- rbind(\n  `all lines, unweighted`  = hp2(pA, pB),\n  `lines used, unweighted` = hp2(colMeans(GLh[unique(ctx$ped$a[i_trunc]), ]),\n                                 colMeans(GLh[unique(ctx$ped$b[i_trunc]), ])),\n  `usage-weighted`         = hp2(as.vector(wt[[\"A\"]] %*% GLh),\n                                 as.vector(wt[[\"B\"]] %*% GLh)),\n  `gd_partition(idx, ctx)` = c(gp_sel[[\"GD_T\"]], gp_sel[[\"GD_BS\"]]))\nstopifnot(isTRUE(all.equal(unname(cmp[\"usage-weighted\", ]),\n                           c(gp_sel[[\"GD_T\"]], gp_sel[[\"GD_BS\"]]))))\nfmt(data.frame(cmp,\n               shared_err_pct     = 100 * (cmp[, \"shared\"] / gp_sel[[\"GD_T\"]] - 1),\n               divergence_err_pct = 100 * (cmp[, \"divergence\"] / gp_sel[[\"GD_BS\"]] - 1)), 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                       | shared| divergence| shared_err_pct| divergence_err_pct|\n|:----------------------|------:|----------:|--------------:|------------------:|\n|all lines, unweighted  |  0.328|      0.034|          5.020|            -35.899|\n|lines used, unweighted |  0.326|      0.039|          4.351|            -26.403|\n|usage-weighted         |  0.312|      0.052|          0.000|              0.000|\n|gd_partition(idx, ctx) |  0.312|      0.052|          0.000|              0.000|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(lines_used_A = length(unique(ctx$ped$a[i_trunc])),\n  lines_used_B = length(unique(ctx$ped$b[i_trunc])),\n  max_line_use = max_line_use(i_trunc, ctx), n_sel = length(i_trunc))\n#> lines_used_A lines_used_B max_line_use        n_sel \n#>           10           23           23           60\n```\n:::\n\n\nResult. With usage weights on both sides the identity is exact to machine\nprecision -- the `stopifnot()` enforces it -- while the unweighted pool\nfrequencies of `pool_freqs()` overstate `shared` by\n+5.0%\nand understate `divergence` by\n35.9%\non this 60-hybrid truncation set, which uses only\n10 pool-A lines with one of them in\n23 of the 60 crosses. Restricting the unweighted mean to\nthe lines actually used recovers part of the gap and not the rest, because the\nusage *within* the used set is itself far from uniform.\n\nInterpretation. The two functions are not inconsistent; they answer the same\nquestion on two different populations -- a notional pool in which every line is\nequally represented, and the pool as the selection actually weights it. Which one\na report wants depends on the question, and the only error is comparing one with\nthe other and calling the difference a bug. The order of magnitude quoted here is\none selection at one scale; a plan with a usage cap (`max_use`) sits between the\ntwo rows.\n\n**Call.** `heterosis_partition()` on the pool frequencies and\n`gd_partition(idx, ctx)` on the hybrid set -- with the pool frequencies weighted\nby `line_weights(idx, ctx)` if the two are to be compared at all.\n**Check.** `shared / m == GD_T` and `divergence / m == GD_BS` under flat $d$,\n**both computed from usage-weighted pool frequencies**. On the full factorial,\nor under any uniform usage, the unweighted `pool_freqs()` satisfies this too.\n**Warning sign.** A disagreement on a selected subset is almost always the\nweighting above, not a coding error: check `line_weights()` first, and only then\nwhether the lines are coded 0/1 or the pool labels differ between the calls.\nA $GD_{WI}$ that is not zero is the separate failure -- with inbred parents it\nmust be, and a non-zero value means the line matrix contains heterozygotes, back\nto step 1.\n**Threshold.** Machine precision when both sides carry the same weights. With\nunweighted pool frequencies against a selected subset, expect tens of per cent on\nthe divergence term, of the size measured above, and do not treat it as a\ntolerance to tighten.\n\n### Step 5 -- Log `mean_sq_delta_p` every cycle {#sec-heterosis-step5}\n\n`s1_monitor(GL / 2, pool, cycle)` is the per-cycle panel. Of its three\ndivergence columns only `mean_sq_delta_p` is exact -- it is $\\overline{y^2}$, so\nhalf of it is $GD_{BS}$ -- and `frac_opposite_fixed` is zero across most of the\nuseful range, as the sweep in @sec-heterosis-flat shows.\n\n**Call.** `s1_monitor()` once per cycle, appended to a single data frame.\n**Check.** `mean_sq_delta_p / 2` against `gd_partition()`'s `GD_BS`.\n**Warning sign.** `frac_opposite_fixed` used as the divergence statistic. In the\nsweep of @sec-heterosis-flat it is exactly zero at every `fst` up to 0.10 -- not\none marker in 2000 -- while over the same span the divergence term has\nalready risen by a factor of\n2.3\n(0.0107 to\n0.0246 per locus at $d = 1$). The first\nnon-zero entry is at `fst` =\n0.2, by which point divergence has\nrisen 4.1-fold.\n**Threshold.** A *band* on $F_{ST}$, not a maximum. @sec-heterosis-flat gives\nthe diversity-side reason and @sec-heterosis-relocation the prediction-side one.\n\n### Step 6 -- Check that the crossing layout identifies what you intend to fit {#sec-heterosis-step6}\n\nThis is the step most often skipped, and it is arithmetic, not opinion. The\ndecomposition $H_{ij} = \\mu + g^A_i + g^B_j + s_{ij}$ is the two-way layout with\nidentified rows and columns. Count the degrees of freedom the layout actually\nprovides:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlayout_df <- function(n_testers) {\n  k <- which(ib <= n_testers)\n  a <- factor(ia[k]); b <- factor(ib[k])\n  X_add <- if (n_testers > 1) model.matrix(~ a + b) else model.matrix(~ a)\n  X_sat <- if (n_testers > 1) model.matrix(~ a * b) else X_add\n  data.frame(testers = n_testers, crosses = length(k),\n             rank_mu_gca = qr(X_add)$rank, rank_with_sca = qr(X_sat)$rank,\n             sca_df = qr(X_sat)$rank - qr(X_add)$rank,\n             residual_df = length(k) - qr(X_sat)$rank)\n}\nfmt(do.call(rbind, lapply(c(1, 2, 5, book_cfg$n_pool_B), layout_df)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| testers| crosses| rank_mu_gca| rank_with_sca| sca_df| residual_df|\n|-------:|-------:|-----------:|-------------:|------:|-----------:|\n|       1|      25|          25|            25|      0|           0|\n|       2|      50|          26|            50|     24|           0|\n|       5|     125|          29|           125|     96|           0|\n|      25|     625|          49|           625|    576|           0|\n\n</div>\n:::\n:::\n\n\nResult. With a single tester the $\\mu + g^A$ model already has rank equal to the\nnumber of crosses, so `sca_df` is 0: specific combining ability is not\nestimable, not merely imprecise. From two testers onward `sca_df` is positive.\n`residual_df` is 0 in every row, because there is one observation per cross --\nSCA becomes *identifiable* from the layout at two testers and *testable* only\nwhen the trial adds replication.\n\nHow much a small tester set costs for general combining ability is a separate\nquestion with a closed-form answer. Averaging a pool-A line over $k$ testers\nleaves it with $g^A_i$ plus the mean of $k$ specific deviations, so the\ncorrelation between the testcross mean and the true $g^A$ is\n\n$$r_k = \\left[1 + \\frac{\\sigma^2_{SCA}}{\\sigma^2_{GCA_A}}\n        \\cdot \\frac{n_B - k}{k\\,(n_B - 1)}\\right]^{-1/2}$$\n\nwhere the second factor is the finite-population correction for drawing $k$ of\nthe $n_B$ available testers without replacement; at $k = n_B$ it vanishes and\n$r_k = 1$ exactly, because the row mean of the complete factorial *is*\n$\\mu + g^A_i$. Twenty random tester sets per $k$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nHtab  <- matrix(H, nA, book_cfg$n_pool_B)   # rows = pool A, columns = pool B\nstopifnot(isTRUE(all.equal(Htab, cs$mu + outer(cs$gca_A, cs$gca_B, \"+\") + cs$sca)))\nv_gca <- var(cs$gca_A)\nv_sca <- var(as.vector(cs$sca))\nnBt   <- book_cfg$n_pool_B\ntester_scan <- function(k, reps = 20) {\n  r <- vapply(seq_len(reps), function(i) {\n    set.seed(55 + 1000 * k + i)\n    cor(rowMeans(Htab[, sample.int(nBt, k), drop = FALSE]), cs$gca_A)\n  }, numeric(1))\n  data.frame(testers = k, cor_mean = mean(r), cor_sd = sd(r),\n             predicted = 1 / sqrt(1 + (v_sca / v_gca) * (nBt - k) / (k * (nBt - 1))))\n}\nts <- do.call(rbind, lapply(c(1, 2, 3, 5, 10, nBt), tester_scan))\nstopifnot(isTRUE(all.equal(ts$cor_mean[ts$testers == nBt], 1)))\n# The residual is only interpretable where the tester sets differ at all; at\n# k = n_B there is one possible set, so cor_sd is a rounding residue and the\n# ratio would be 0/0 dressed up as a number.\nts$resid_sd <- ifelse(ts$cor_sd > 1e-12,\n                      (ts$cor_mean - ts$predicted) / ts$cor_sd, NA)\nfmt(ts, 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| testers| cor_mean| cor_sd| predicted| resid_sd|\n|-------:|--------:|------:|---------:|--------:|\n|       1|   0.4931| 0.1250|    0.5591|  -0.5283|\n|       2|   0.6972| 0.1021|    0.6978|  -0.0063|\n|       3|   0.7996| 0.0448|    0.7734|   0.5843|\n|       5|   0.8518| 0.0407|    0.8555|  -0.0887|\n|      10|   0.9403| 0.0171|    0.9376|   0.1552|\n|      25|   1.0000| 0.0000|    1.0000|       NA|\n\n</div>\n:::\n:::\n\n\nResult. A single tester ranks pool-A lines for general combining ability with a\ncorrelation of 0.49 (s.d. 0.12 over 20\ntester choices); five testers give 0.85 and\nten give 0.94. No $k$ deviates from the\nclosed form by as much as one standard deviation of the tester-set spread: the\ntwo largest residuals are $k = 1$ at\n-0.5 s.d. and $k = 3$ at\n0.6 s.d., in opposite directions, and\n$k = 3$ is the larger of the two. Singling out $k = 1$ would be reading the\n*absolute* gap (0.066, the largest\nin the table) while ignoring that $k = 1$ also has by far the largest dispersion\nby construction -- one tester, one draw of $s_{ij}$, nothing averaged. Measured\nagainst the standard error of a 20-replicate mean rather than against the\nsingle-draw spread, both residuals are larger than the noise\n(-2.4 and\n2.6 standard errors), so the\nclosed form is not exact at small $k$ and this section does not claim it is.\nTwo reasons are identifiable and neither is modelled here: $r_k$ is a function\nof an *expected* sampling variance, whereas the table averages 20\ncorrelations, and $x \\mapsto (1 + x)^{-1/2}$ is convex, so the two are not the\nsame quantity; and $\\mathrm{cov}_i(g^A_i, \\overline{s}_{i\\cdot})$ vanishes only\nwhen the mean runs over all $n_B$ testers, not over a subset. The scan is\nreported as a measurement with its dispersion, not as a validated formula.\n\nInterpretation. The whole scan is driven by one ratio,\n$\\sigma^2_{SCA}/\\sigma^2_{GCA_A} =$ 2.2 here. That ratio\nis what @sec-heterosis-relocation shows falling as the pools diverge, so the\nnumber of testers a programme needs is not a constant of the crop: well\nseparated pools need fewer. Two limits. This is heterosis only -- the parental\nadditive contribution to testcross performance is not in $H$ and is not tested\nhere -- and it is one realisation of $d$ and one pool pair, so the ratio, and\nwith it every entry in the table, moves with the seed.\n\n**Call.** `qr(model.matrix(...))$rank` on the layout you actually have, before\nfitting anything; `heterosis_gca_sca()` only once the layout supports it.\n**Check.** `sca_df > 0` if SCA is to be estimated; `residual_df > 0` if it is to\nbe tested.\n**Warning sign.** A testcross file against one inbred tester per pool, analysed\nas though it estimated SCA. It estimates\n$\\mu + g^A_i + (\\text{that tester's contribution})$ and nothing else.\n**Threshold.** Two testers to identify SCA; from the scan above, five to ten to\nrank GCA at $r > 0.85$ at this $\\sigma^2_{SCA}/\\sigma^2_{GCA}$ ratio -- and\nrecompute the requirement when the ratio changes.\n\n### Step 7 -- Fit the decomposition and check it reconstructs {#sec-heterosis-step7}\n\n`heterosis_gca_sca(U, V, d)` is the expansion, not a model fit: it needs no\nsolver and returns $\\mu$, `gca_A`, `gca_B` and the `sca` matrix. On simulated $d$\nit must reconstruct every hybrid exactly, and the chunk in\n@sec-heterosis-gca-sca asserts that together with the `lm()` interaction\nequivalence. On real data $d$ is unknown, so the route reverses: fit\n`lm(H ~ factor(a) + factor(b))`, take the row and column effects as $g^A$ and\n$g^B$ and the residual as $s_{ij}$. The two routes coincide only on a complete,\nbalanced factorial.\n\n**Call.** `heterosis_gca_sca()` when $d$ is known (simulation); `lm()` with both\nparent factors when it is not.\n**Check.** The reconstruction residual, and that all three components are mean\nzero.\n**Warning sign.** A non-zero mean for `gca_A` or `sca`. The deviations are taken\nfrom each pool's own line frequencies, so they sum to zero over that pool by\nconstruction; a non-zero mean means the frequencies used were not the pool's.\n**Threshold.** Machine precision for the reconstruction. **For the variance\ncomponents there is no threshold that transfers to a real pool**, and the\n$\\sqrt{2/n}$ figure quoted in @sec-heterosis-gca-sca is not one. That tolerance\nis the relative sampling error of a variance over $n$ **independent**\nobservations, and it is valid there only because the closed forms are derived\nunder the simulation's sampling model -- each line's genotype an independent\nBernoulli($p_k$) draw at every locus, hence unrelated lines and linkage\nequilibrium within pool. A recycled heterotic pool satisfies neither: assumption\nA3 of @sec-era-programme makes within-pool recycling the normal state of this\nsystem, so its lines share ancestors.\n\nThe size of the failure can be measured, at least for the relatedness half of\nit. Re-derive each pool as 25 doubled haploids drawn from\ncrosses among six of its own members -- one Bernoulli draw per locus, so the\nlines are **related but carry no linkage disequilibrium** -- and compare the\nclosed forms with the observed variances on five such pairs of pools:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrel_dev <- function(A, B) {                     # % deviation, observed vs closed form\n  p1 <- colMeans(A); p2 <- colMeans(B)\n  cc <- heterosis_gca_sca(A, B, d)\n  obs <- c(var(cc$gca_A), var(cc$gca_B), var(as.vector(cc$sca)))\n  cf  <- c(sum(d^2 * (1 - 2 * p2)^2 * p1 * (1 - p1)),\n           sum(d^2 * (1 - 2 * p1)^2 * p2 * (1 - p2)),\n           4 * sum(d^2 * p1 * (1 - p1) * p2 * (1 - p2)))\n  100 * (obs / cf - 1)\n}\nrecycle <- function(W, n_found) {               # DH lines from crosses among founders\n  fo <- W[sample.int(nrow(W), n_found), , drop = FALSE]\n  t(vapply(seq_len(nrow(W)), function(i) {\n    pr <- sample.int(n_found, 2)\n    rbinom(ncol(W), 1, (fo[pr[1], ] + fo[pr[2], ]) / 2)\n  }, numeric(ncol(W))))\n}\ndev <- t(vapply(1:5, function(r) {\n  set.seed(500 + r)                             # seeded per draw, not once\n  rel_dev(recycle(U, 6), recycle(V, 6))\n}, numeric(3)))\ndimnames(dev) <- list(paste0(\"draw\", 1:5), c(\"GCA_A\", \"GCA_B\", \"SCA\"))\nfmt(rbind(dev, `independent lines` = rel_dev(U, V)), 1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                  | GCA_A| GCA_B|   SCA|\n|:-----------------|-----:|-----:|-----:|\n|draw1             |   0.3|  46.1|   5.5|\n|draw2             | -55.7|  14.9|   6.1|\n|draw3             | -31.9|  -1.4|  -2.4|\n|draw4             | -16.4| -29.9|   8.8|\n|draw5             | -37.0|  22.8| -10.3|\n|independent lines |  -8.6|  -6.4|  -1.5|\n\n</div>\n:::\n:::\n\n\nResult. On the independently drawn lines the three closed forms are within\n8.6% of the observed variances, inside\nthe $\\sqrt{2/n} =$ 28% band. On the\nfive recycled pairs 5 of the\n15 components fall outside that band and the largest deviation is\n56%. The two GCA columns carry almost all of it;\nthe SCA column stays within\n10.3%.\n\nInterpretation, and its limits. A variance of a sum over loci picks up the\nbetween-line covariance that relatedness induces, which the closed forms --\nbeing sums of per-locus terms -- do not contain; the GCA components are sums over\nloci weighted by the tester pool's frequencies and are the ones exposed. This\nsays the tolerance must be recalibrated empirically on the programme's own\npedigree, not that the closed forms are wrong: they remain exact statements about\nthe sampling model they are derived under. The construction here is a caricature\n(six founders, one DH per F1, five draws, one seed family) and it isolates\n*relatedness only* -- there is no linkage disequilibrium in it, because each\nlocus is drawn independently. A real recycled pool violates the sampling model on\nboth counts at once, and the size of the linkage contribution is not measured\nanywhere in this book.\n\n### Step 8 -- Decide the $F_{ST}$ band on alignment, not on $F_{ST}$ {#sec-heterosis-step8}\n\nThe output of steps 4-7 answers one management question: should the pools be\npushed further apart? The chapter's answer is that $F_{ST}$ cannot inform it\n(@sec-heterosis-flat: the total does not move) and that the quantity that can is\n$\\mathrm{cov}(d, y^2)$ (@sec-heterosis-alignment: a factor of\n1.55 at constant $F_{ST}$).\n\n**Call.** $\\mathrm{cov}(d, y^2)$ with the population divisor, alongside\n$\\bar d\\,\\overline{y^2}$; the two-term identity of @sec-heterosis-alignment is\nthe check.\n**Check.** The sign and magnitude of the covariance relative to\n$\\bar d\\,\\overline{y^2}$.\n**Warning sign.** A proposal to raise $F_{ST}$ justified by the divergence term\nalone. Under neutral divergence the shared term pays for all of it, unit for\nunit, and $\\sigma^2_{SCA}$ falls at the same time.\n**Threshold.** No universal one exists, and this chapter does not supply it: the\nmissing weight $\\lambda$ between within- and between-pool diversity needs the\ntwo covariances listed in @sec-heterosis-lambda, and this book estimates\nneither.\n\n## What this does not change\n\n:::: {.callout-warning}\n## The diversity constraint stays additive\n\nNothing in this chapter reopens the optimisation. $\\theta$, $GD$ and $\\alpha$ are\ncomputed on molecular coancestry and are functions of the frequencies alone; no\ndominance term enters them, and @sec-ocs, @sec-combinatorial and @sec-advanced are\nuntouched. The combining-ability split of @sec-heterosis-gca-sca sits outside the\nconstraint for the same reason: it is a statement about the objective, not about\nthe feasible set.\n\nA dominance model changes the **mean-performance ranking**, not the diversity\nterm. @sec-case-study states the same separation from the other side. Do not\nconflate them, and do not read this chapter as licence to put a heterosis term\ninside the constraint.\n::::\n\nWhat it does change is the interpretation of the constraint's output. Two plans\nwith the same $\\alpha$ and the same $GD_{BS}$ can differ in expected heterosis by\nhalf again, if one of them concentrated its divergence on the dominance loci --\nthat is the scenario table of @sec-heterosis-alignment, whose three columns share\nevery frequency-based statistic. The partition cannot distinguish them. Only an\nestimate of $d$ can.\n\n### What it would take to use $d$ {#sec-heterosis-lambda}\n\n@sec-catalogue leaves a weight $\\lambda$ undetermined between within- and\nbetween-pool diversity and observes that the ratio of the two heterosis terms is\nwhat $\\lambda$ is trying to express. This chapter can now say what would have to\nbe estimated to set it, and it is not much:\n\n- **$\\lambda$ needs two covariances, not $d$ itself.** Each heterosis term is $m$\n  times a mean times a mean plus a covariance, so their ratio needs\n  $\\mathrm{cov}(d, y^2)$ and $\\mathrm{cov}(d, 2\\bar p(1 - \\bar p))$, each relative\n  to $\\bar d$, on top of what the frequencies already give. A programme does not\n  need per-locus dominance deviations to weight the two diversity terms against\n  each other; it needs to know whether its divergence is landing on its dominance\n  loci.\n- **Ranking crosses needs more.** $s_{ij}$ is a $d$-weighted inner product between\n  two specific parents, so it needs the deviations locus by locus. This is the\n  extension @sec-case-study names and the book does not attempt.\n- **Fitting it needs a factorial, and a testcross file is not one.** The\n  decomposition above is the two-way layout with *identified* rows and columns:\n  each pool-A line crossed to several named pool-B lines and each pool-B line to\n  several named pool-A lines, which is what makes $g^A$, $g^B$ and $s_{ij}$\n  separately estimable and what the `lm()` above fits. Testcrosses against a\n  single common tester give only a column of $\\mu + g^A_i + \\text{(one tester's\n  contribution)}$ -- no SCA is identifiable, because there is no second tester to\n  contrast against. Programmes that already cross two pools in a partial\n  factorial for hybrid evaluation have the layout; programmes that testcross\n  against one inbred tester per pool do not.\n\n## Where this connects\n\n@sec-subdivided supplied the partition and @sec-catalogue will use it; this chapter\nsupplies the reason the $GD_{BS}$ component is singled out for protection, and the\nreason protecting it is not the same as maximising it. @sec-stages Trap 3 already\nrecommended holding $F_{ST}$ in a band: @sec-heterosis-flat is why a band, and\n@sec-heterosis-alignment is what to watch instead of the band.\n@sec-heterosis-distance closes the loop with the coancestry kernel of\n@sec-coancestry: under flat dominance, the diversity matrix and the heterosis\nprediction are the same object.\n\n@sec-genomic-prediction is the chapter this one supplies a missing term to. It\npredicts breeding values with an additive model on a trait that is additive by\nconstruction, and lists specific combining ability first among what it does not\nmodel. @sec-heterosis-gca-sca is where that term comes from and\n@sec-heterosis-relocation is what share of the variance in heterosis it holds;\nboth are derived here rather than fitted, because on a simulated $d$ they can be.\n\nIt also gives a reason why a heterotic *pattern* -- which pool crosses well onto\nwhich -- is not recoverable from how far apart the pools have drifted:\n@sec-heterosis-alignment's three scenarios share every frequency-based statistic\nand differ by half again in expected heterosis. @white2020 describe heterotic\npatterns and diversity separately in North American proprietary dent germplasm;\nthis chapter says why the two need describing separately.\n\nForward, the alignment result is the argument for @sec-cycles. Drift moves\nfrequencies independently of $d$, and selection on a line's own performance\ncannot respond to $d$ either, because an inbred line's dominance contribution is\nexactly zero (@sec-heterosis-id) -- which leaves selection on *cross* performance\nas the only process in this model that can move frequencies in a way that depends\non where the dominance is. The alignment between divergence and dominance is\ntherefore something each cycle either builds or erodes, not a standing asset. A\none-cycle constraint cannot see that, and neither can $F_{ST}$. @sec-alphasimr\nruns that loop on a dominance trait and is the pipeline this chapter's algebra\ndescribes.\n",
    "supporting": [
      "05b-heterosis-dominance_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}