{
  "hash": "c13798c6e737375c6ef268199d1c488e",
  "result": {
    "engine": "knitr",
    "markdown": "# The limit, and what the metrics cannot see {#sec-limits}\n\n\n\n@sec-cycles ran the programme forward and found the crossover: a constrained\nprogramme trails an unconstrained one for about eight cycles and leads\nthereafter. That is a measurement. This chapter asks the two questions a\nmeasurement leaves open -- could it have been *predicted*, and is the quantity\nbeing managed the quantity that actually matters.\n\nThe answers are yes-with-a-condition, and no-not-entirely.\n\n## Robertson's limit\n\n@sec-response wrote down the response to one cycle of selection. Robertson\n[-@robertson1960] wrote down the sum of all of them. Selection fixes alleles; a\nfinite population fixes some of the favourable ones in the wrong direction; and\nthe total advance before everything is fixed is approximately\n\n$$R_{\\text{total}} \\;\\approx\\; 2 N_e R_1$$\n\nwith a half-life of about $1.4 N_e$ generations. The result is the theoretical\nancestor of every optimal-contribution scheme in this book: it is *why* $N_e$ is\nthe thing to manage, and it says exactly what a unit of $N_e$ is worth in units\nof cumulative gain.\n\nBoth inputs are already in @sec-cycles' trajectory. $R_1$ is the first cycle's\nresponse, and $N_e$ comes from the rate of inbreeding, exactly as @sec-cycles\ncomputed it:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrob <- do.call(rbind, lapply(unique(traj$budget), function(b) {\n  d  <- aggregate(cbind(index, F_drift) ~ cycle, traj[traj$budget == b, ], mean)\n  f  <- lm(log(1 - F_drift) ~ cycle, d[-1, ])\n  Ne <- 1 / (-2 * coef(f)[[\"cycle\"]])\n  R1 <- d$index[2] - d$index[1]\n  data.frame(budget = b, R2 = summary(f)$r.squared, Ne = Ne, R1 = R1,\n             limit = 2 * Ne * R1, half_life = 1.4 * Ne,\n             observed_15 = d$index[16] - d$index[1],\n             predicted_15 = 2 * Ne * R1 * (1 - (1 - 1 / (2 * Ne))^15))\n}))\nfmt(rob, 3)\n```\n\n::: {.cell-output-display}\n\n|budget        |    R2|     Ne|    R1|  limit| half_life| observed_15| predicted_15|\n|:-------------|-----:|------:|-----:|------:|---------:|-----------:|------------:|\n|unconstrained | 0.853| 17.115| 1.277| 43.697|    23.960|       7.812|       15.688|\n|0.020         | 0.993| 13.984| 1.222| 34.167|    19.578|      10.431|       14.378|\n|0.005         | 0.998| 18.890| 0.802| 30.281|    26.446|       9.980|       10.032|\n\n:::\n:::\n\n\nRead the last two columns against each other, and then read both against the\nfirst.\n\n## The $R^2$ column decides whether the theory applies\n\nFor the tightest budget the prediction is\n10.03 and the observation is\n9.98. Robertson's theory, published\nin 1960 and derived for a single locus under idealised drift, predicts fifteen\ncycles of a genomic hybrid programme to better than one percent.\n\nFor the unconstrained programme it predicts\n15.69 against an observed\n7.81 -- too high by about\nhalf.\n\nThe theory did not fail arbitrarily, and @sec-cycles already said why. Robertson\nassumes a *constant* rate of inbreeding, and the regression of $\\log(1-F)$ on\ncycle is where that assumption is testable. Its $R^2$ is\n0.998 for the tightest budget and\n0.853 for the unconstrained run,\nwhose drift decelerates because there is progressively less left to lose. That\nlow $R^2$ is not a nuisance. It is the theory declining to apply, in advance,\nand in a column you can read before you trust the number.\n\n::: {.callout-important}\n## Do not quote a Robertson limit without its $R^2$\n\n$N_e$ here is a *fitted* quantity, and @sec-cycles showed the fit is meaningless\nfor a saturating series -- its fitted $\\Delta F$ comes out lowest for the run\nthat is actually losing diversity fastest, which is backwards. Feeding that\n$N_e$ into $2 N_e R_1$ propagates the error into a number that looks like a\nlong-term plan.\n\nReport the $R^2$ next to every limit, and treat a limit computed from a fit\nbelow about 0.99 as an illustration rather than a projection.\n:::\n\nThat yields an argument for the constraint that this book did not previously\nhave. @sec-cycles justified $\\alpha$ by where the trajectories cross. The table\nabove adds: the constrained programme is the one whose future can be *computed*.\nAn unconstrained programme is not merely worse after cycle 8, it is\nunforecastable, because the theory that would forecast it needs a constant\n$\\Delta F$ that it does not have.\n\n## What the metrics cannot see\n\nNow the second question. Every diversity metric in this book -- $\\theta$, $GD$,\n$N_s$, allelic richness, `F_hom`, `F_drift` -- is a function of allele\nfrequencies **one locus at a time**. @sec-response showed that additive variance\nis not:\n\n$$\\operatorname{Var}(\\mathbf{X}\\boldsymbol\\beta) \\;=\\; V_{\\text{genic}}\n\\;+\\; 2\\sum_{k<l}\\beta_k\\beta_l\\operatorname{Cov}(x_k, x_l)$$\n\nDirectional selection drives that covariance term negative (Bulmer\n[-@bulmer1971]): it couples loci with like effects in repulsion, hiding genic\nvariance from the next generation without moving a single allele frequency. No\nmetric in the catalogue can detect it.\n\n@sec-cycles assumed the effect away, in assumption **C1**: *loci are unlinked, so\nno linkage disequilibrium builds up and there is no Bulmer effect on the genic\nside.* That is worth testing rather than assuming, because Bulmer's 1971\ntreatment covers unlinked loci explicitly -- free recombination halves the\ndisequilibrium each generation, but selection regenerates it every generation,\nand the equilibrium is not zero.\n\n### The experiment\n\nThe gap $\\operatorname{Var}(\\mathbf{X}\\boldsymbol\\beta) - V_{\\text{genic}}$ is\n**not** on its own a measure of the Bulmer effect. A finite founder base leaves\ndisequilibrium in the very first cycle, and two divergent pools add more. So the\ncomparison is against a control: an arm identical in every respect -- same\nfounders, same seeds, same recycling, same population sizes -- in which the\nhybrids are chosen at random instead of on the index.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngapc <- aggregate(gap ~ regime + cycle, vr, mean)\nw <- reshape(gapc, idvar = \"cycle\", timevar = \"regime\", direction = \"wide\")\nnames(w) <- sub(\"gap.\", \"\", names(w))\nw$selection_effect <- w$unconstrained - w$random\nfmt(head(w[, c(\"cycle\", \"random\", \"unconstrained\", \"constrained\",\n               \"selection_effect\")], 7), 4)\n```\n\n::: {.cell-output-display}\n\n|   | cycle|  random| unconstrained| constrained| selection_effect|\n|:--|-----:|-------:|-------------:|-----------:|----------------:|\n|1  |     0| -0.0261|       -0.0261|     -0.0261|           0.0000|\n|4  |     1| -0.0716|       -0.2686|     -0.1984|          -0.1970|\n|7  |     2| -0.0328|       -0.2167|     -0.1930|          -0.1839|\n|10 |     3| -0.0320|       -0.2616|     -0.0264|          -0.2296|\n|13 |     4|  0.0935|       -0.0931|     -0.0976|          -0.1866|\n|16 |     5| -0.0453|       -0.1069|     -0.1171|          -0.0615|\n|19 |     6|  0.0512|       -0.0711|     -0.1130|          -0.1223|\n\n:::\n:::\n\n\nCycle 0 is identical across all three arms, to the digit. Nothing has been\nselected yet, so the control is doing its job.\n\nFrom cycle 1 the arms separate. Paired within seed and cycle:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np  <- reshape(aggregate(gap ~ regime + seed + cycle, vr, mean),\n              idvar = c(\"seed\", \"cycle\"), timevar = \"regime\", direction = \"wide\")\np  <- p[p$cycle > 0, ]\ndd <- p$gap.unconstrained - p$gap.random\nc(mean_effect = mean(dd), se = sd(dd) / sqrt(length(dd)),\n  t = mean(dd) / (sd(dd) / sqrt(length(dd))), n_pairs = length(dd))\n#> mean_effect          se           t     n_pairs \n#> -0.08568088  0.02108980 -4.06266819 96.00000000\n```\n:::\n\n\n::: {.callout-warning}\n## Assumption C1 of @sec-cycles is too strong, and is restated here\n\nSelection builds negative disequilibrium among **unlinked** loci, at\n$t = -4.06$ over\n96 paired observations. Unlinked loci do not prevent the Bulmer\neffect; they make it decay fast.\n\nWhat C1 should say is that with free recombination the disequilibrium is halved\nevery generation, so it reaches a low equilibrium and does not accumulate across\ncycles the way frequency change does. That is what makes @sec-cycles' *frequency*\ntrajectories trustworthy, and it is the correct reason -- not the absence of the\neffect.\n:::\n\nThe effect is largest in the early cycles and decays toward zero late, which is\nthe expected shape: it is proportional to the genic variance still available to\nbe hidden, and by cycle 12 there is much less of it.\n\n### With real linkage\n\nThe same question with real meiosis behind it. @sec-alphasimr's reciprocal\nrecurrent selection runs on a coalescent founder history with a genetic map, and\nAlphaSimR reports `varA` (which carries the disequilibrium) and `genicVarA`\n(which does not), so this arm needs no variance code of its own.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlk$rel <- ((lk$varA_A - lk$genicVarA_A) + (lk$varA_B - lk$genicVarA_B)) /\n          (lk$genicVarA_A + lk$genicVarA_B)\npl  <- reshape(lk[, c(\"regime\", \"seed\", \"cycle\", \"rel\")],\n               idvar = c(\"seed\", \"cycle\"), timevar = \"regime\", direction = \"wide\")\npl  <- pl[pl$cycle > 0, ]\nddl <- pl$rel.selected - pl$rel.random\nc(mean_effect = mean(ddl), se = sd(ddl) / sqrt(length(ddl)),\n  t = mean(ddl) / (sd(ddl) / sqrt(length(ddl))), n_pairs = length(ddl))\n#> mean_effect          se           t     n_pairs \n#> -0.16493928  0.04672916 -3.52968674 32.00000000\n```\n:::\n\n\nSame sign, larger in magnitude, and measured with fewer replicates so the\nevidence is weaker. Linkage does what linkage should: it slows the decay, so the\ndisequilibrium selection creates persists longer than it does under free\nrecombination.\n\n::: {.callout-note}\n## A reproducibility trap in the linked arm\n\n`alphasimr_founder_pools()` is **not** reproducible from `cfg$seed`.\n`AlphaSimR::runMacs2()` hands the coalescent to MaCS, which seeds itself outside\nR's RNG, so two calls with the same configuration return different founder\nhaplotypes. Everything downstream of the founders is seeded normally.\n\nThe consequence for an experiment like this one is severe: founding the pools\nseparately for each arm would have compared two different base populations and\ncharged the difference to selection. `book/scripts/regenerate.R` founds once per\nreplicate and branches both arms off that single result, which is why cycle 0 of\nthe table above matches exactly.\n:::\n\n## The two costs of selection\n\nThe chapter's result stated once.\n\nSelection pays for gain twice. It builds negative covariance between loci, which\nis a real loss of usable variance, and **recombination repays it** -- halved\nevery generation under free recombination, more slowly under linkage. And it\nchanges allele frequencies, moving them toward fixation, and **nothing repays\nthat** short of mutation or migration.\n\nThe first cost is invisible to every metric in this book and is largely\nself-correcting. The second is what every metric in this book measures, and is\npermanent.\n\nThat is the justification for constraining the second and ignoring the first,\nand it is a stronger statement than \"the constraint is what we can compute\". It\nis worth being explicit that this ordering is a *consequence* of the two decay\nrates, not an assumption: if the disequilibrium did not decay -- tight linkage,\nfew chromosomes, short cycle times -- the ranking would change, and a constraint\nwritten on allele frequencies would be managing the smaller of the two bills.\n\n## Where this connects\n\n@sec-response supplies the variance decomposition and the breeder's equation\nthis chapter runs forward. @sec-cycles supplies the trajectories, and has one\nassumption restated as a result of the test above. @sec-alphasimr supplies the\nlinked arm, which is the only place in the book where a genetic map, rather than\nan assumption about one, decides how fast disequilibrium decays.\n\n@sec-case-study's checklist gains one line from this chapter: report the $R^2$ of\nthe $\\log(1-F)$ regression next to any projection built on $N_e$, and treat a\nprojection from a poor fit as an illustration.\n",
    "supporting": [
      "11c-limits_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}