{
  "hash": "ee59f4b8624134a5948cd070c45378e9",
  "result": {
    "engine": "knitr",
    "markdown": "# Simulating a hybrid breeding programme: AlphaSimR from the ground up {#sec-alphasimr}\n\n\n\n@sec-simulating-crosses built the `{X, f, hybrids, fL}` contract with a\ndeliberately fast simulator: Balding-Nichols allele frequencies, independent\nmarkers, no recombination, no dominance. That is enough to exercise the\ndiversity and selection machinery, but it is not how a hybrid breeding\nprogramme is actually run, and it is not how anyone would build one from\nscratch.\n\nThis chapter builds one. The crop in mind is maize, the canonical allogamous\nhybrid crop: two heterotic pools, inbred (doubled-haploid) lines drawn from\neach, lines judged by their testcrosses onto the other pool rather than by\nthemselves, pools improved by reciprocal recurrent selection (RRS;\n@comstock1949), and a commercial product that is a single cross between one\nline from each pool. Steps 1 to 7 are a **step-by-step construction** with\nAlphaSimR (@gaynor2021), written out in the primitive calls -- `runMacs()`,\n`SimParam`, `addTraitAD()`, `makeCross()`, `hybridCross()`, `makeDH()`,\n`setPheno()`, `selectInd()` -- with a plant breeder's reading of each argument\nand a measurement at each step. Step 8 assembles those primitives into RRS,\nreplicates it against a paired no-selection control, and shows that the same\nstage-1 contract comes out the other end, so `stage2_select()` runs on it\nexactly as it does on the book's own simulated data.\n\n**Why this machinery, and why it has no counterpart in a self-pollinated\nprogramme.** In an autogamous (self-pollinated) crop -- wheat, rice, soybean,\ncommon bean -- recombination happens once, in the F1, and the programme then\nnarrows a segregating population toward homozygosity by selfing or\nsingle-seed descent, selecting throughout on a line's own (per se) phenotype,\nbecause a self-pollinated genotype breeds true and its own performance *is*\nwhat a farmer will grow: the released variety is very often the same\nhomozygous line the breeder selected. @sec-programme builds exactly that\nprogramme with the same AlphaSimR primitives -- `makeDH()`, `setPheno()`,\n`selectInd()` -- and is the chapter to read this one against, step by step.\nNone of Steps 2, 4 and\n6 below would have a job there: there is no dominance for per se selection to\nbe blind to (an inbred line's value is its additive merit alone -- Step 3\nmakes this an identity, `varD = 0` exactly on a homozygous panel), no tester\nto cross a candidate onto, no general or specific combining ability to\nestimate (@sprague1942), and no second, deliberately divergent population to\nkeep apart, because there is only one gene pool, not two heterotic ones held\napart on purpose. What follows instead is specific to an allogamous,\nhybrid-product crop: the inbred line is not the product, the F1 is (Step 5);\na line's breeding value depends on which pool it will be crossed to, not on\nitself alone (Step 6's tester dependence); and the trait improvement a\nprogramme has made is realised only in a cross remade every season, never in\neither parental line by itself.\n\nThe pedagogical source is the AlphaSimR course of Gorjanc and colleagues\n[@gorjanc2022]: its vignettes on simulating DNA, simulating traits, the DNA\nlottery, single- and multi-trait selection, and a plant breeding programme.\nThe course has no hybrid programme of its own; the wheat programme it does build is the\nsubject of @sec-programme. This chapter takes the course's primitives and\nassembles them into the hybrid case.\n\nThe order matters. Everything in Step 8 is a wrapper in\n`R/13_alphasimr_bridge.R` -- `rrs_config`, `alphasimr_founder_pools()`,\n`alphasimr_rrs_cycle()`, `alphasimr_make_hybrids()`, `alphasimr_to_stage1()`,\n`alphasimr_pipeline()` -- and a wrapper is only readable once you know what it\nis wrapping. AlphaSimR is a `Suggests` dependency, guarded exactly like\n`quadprog` and `highs` elsewhere in the package; this chapter and\n@sec-programme are the only ones that need it.\n\n## Step 1 -- Founder genomes: what a founder is, and which engine to use\n\nEvery AlphaSimR simulation starts with founder haplotypes. Before choosing an\nengine, it is worth seeing what one produces, at a size small enough to read.\n`inbred = TRUE` makes every founder fully homozygous, which is what a panel of\ninbred lines is.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(1)\ntiny <- quickHaplo(nInd = 3, nChr = 2, segSites = 4, inbred = TRUE)\nSPt  <- SimParam$new(tiny)\ntiny_pop <- newPop(tiny, simParam = SPt)\npullSegSiteHaplo(tiny_pop, simParam = SPt)\n#>     1_1 1_2 1_3 1_4 2_1 2_2 2_3 2_4\n#> 1_1   0   0   0   1   0   1   1   0\n#> 1_2   0   0   0   1   0   1   1   0\n#> 2_1   0   1   1   0   1   0   1   1\n#> 2_2   0   1   1   0   1   0   1   1\n#> 3_1   1   0   0   0   0   1   0   1\n#> 3_2   1   0   0   0   0   1   0   1\n```\n:::\n\n\nOne row per haplotype, two per diploid individual (`1_1` and `1_2` are the two\nchromosome copies of individual 1), one column per segregating site across both\nchromosomes (`1_3` is chromosome 1, site 3). Alleles are coded 0 and 1 --\nancestral and derived under a coalescent engine, arbitrary labels under\n`quickHaplo()`. Because the founders are inbred, the two rows of each\nindividual are identical. `pullSegSiteGeno()` sums the two\nrows into an allele dosage in `{0, 1, 2}`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntiny_geno <- pullSegSiteGeno(tiny_pop, simParam = SPt)\ntiny_geno\n#>   1_1 1_2 1_3 1_4 2_1 2_2 2_3 2_4\n#> 1   0   0   0   2   0   2   2   0\n#> 2   0   2   2   0   2   0   2   2\n#> 3   2   0   0   0   0   2   0   2\nstopifnot(all(tiny_geno %in% c(0, 2)))\nstopifnot(isTRUE(all.equal(diag(molecular_coancestry(tiny_geno / 2)),\n                           rep(1, 3))))\n```\n:::\n\n\nThe two assertions fix the coding for the rest of the book. AlphaSimR's dosage\nis 0/1/2; the contract of @sec-simulating-crosses codes the same information as\n0/0.5/1, the within-individual frequency of the reference allele (AlphaSimR's\nderived allele plays that role), and every bridge function divides by two on\nthe way across (`stage1_build()` also detects\nand rescales 0/1/2 on its own). On an inbred individual the molecular\nself-coancestry of @sec-coancestry is exactly 1, which is the second assertion.\n\nThere are two engines, and the choice is not cosmetic. `runMacs()` runs a\nbackward-in-time coalescent (@chen2009) under a species-specific demography --\n`species = \"MAIZE\"`, `\"WHEAT\"`, `\"CATTLE\"` -- so the founders carry a realistic\nallele-frequency spectrum and realistic linkage disequilibrium. `quickHaplo()`\nsamples 0s and 1s directly: instant, and with no history behind it.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntm <- function(expr) as.numeric(system.time(expr)[\"elapsed\"])\n\n# reproducibility: two calls from the same seed, and R's own stream after each\nset.seed(7); qa <- quickHaplo(nInd = 20, nChr = 10, segSites = 50, inbred = TRUE)\nrs_qa <- .Random.seed\nset.seed(7); qb <- quickHaplo(nInd = 20, nChr = 10, segSites = 50, inbred = TRUE)\nrs_qb <- .Random.seed\nset.seed(7); ma <- runMacs(nInd = 20, nChr = 10, segSites = 50, inbred = TRUE,\n                           species = \"MAIZE\")\nrs_ma <- .Random.seed\nset.seed(7); mb <- runMacs(nInd = 20, nChr = 10, segSites = 50, inbred = TRUE,\n                           species = \"MAIZE\")\nrs_mb <- .Random.seed\nstopifnot(identical(rs_qa, rs_qb), identical(rs_ma, rs_mb))\n\n# timing: one runMacs() call; quickHaplo() over n_rep_q calls, because a\n# single call is below the clock's resolution\nn_rep_q <- 100\nt_m <- tm(runMacs(nInd = 20, nChr = 10, segSites = 50, inbred = TRUE,\n                  species = \"MAIZE\"))\nt_q <- tm(for (k in seq_len(n_rep_q))\n            quickHaplo(nInd = 20, nChr = 10, segSites = 50, inbred = TRUE)) / n_rep_q\n\nfmt(data.frame(engine              = c(\"quickHaplo\", \"runMacs\"),\n               seconds_per_call    = c(t_q, t_m),\n               same_twice          = c(identical(qa@geno, qb@geno),\n                                       identical(ma@geno, mb@geno)),\n               R_stream_same_after = c(identical(rs_qa, rs_qb),\n                                       identical(rs_ma, rs_mb))), 4)\n```\n\n::: {.cell-output-display}\n\n|engine     | seconds_per_call|same_twice |R_stream_same_after |\n|:----------|----------------:|:----------|:-------------------|\n|quickHaplo |           0.0003|TRUE       |TRUE                |\n|runMacs    |           2.7970|FALSE      |TRUE                |\n\n:::\n:::\n\n\nRead the last two columns together. **`runMacs()` is not reproducible from\n`set.seed()`, and R's own random stream is untouched by that.** `runMacs()`\ndraws a seed for MaCS from R's stream (one `sample.int()` per chromosome) and\nhands it to the binary. The fourth column, asserted in the chunk, says that\nafter two calls from the same seed R's `.Random.seed` is identical: the\namount of R's stream the call consumes is fixed, and every draw R makes\nafterwards is the same in both runs. Yet the third column says the haplotypes\ndiffer. What was measured, then, is that MaCS's output is not a deterministic\nfunction of the seed it is handed. The only thing that moves between two runs\nis the founder haplotypes themselves -- and everything computed *from* those\nfounders. `quickHaplo()` is pure R sampling and is exactly reproducible.\n\n(The `seconds_per_call` column is wall clock and will differ on your machine\nand between renders. `runMacs()` takes seconds; `quickHaplo()`, timed over\n100 calls because one call is below the clock's resolution, takes\nabout 0.26 ms per call.)\n\n::: {.callout-warning}\n## The founders are not seeded, and everything downstream is\n\nThis is the single most expensive trap in AlphaSimR, because it fails silently:\nthe code looks reproducible, runs without complaint, and returns different\nnumbers. The non-reproducibility is documented in `alphasimr_founder_pools()`'s\nhelp page for `runMacs2()`; the table above shows it is not `runMacs2`-specific\nbut true of MaCS generally.\n\nTwo consequences, both because the founders move and not because of anything\nR's stream does:\n\n1. **Found once, then branch.** Any experiment comparing two schemes must draw\n   the founders a single time and start both arms from that one object. Draw\n   them twice and the two arms start from different founders, and the\n   comparison measures the founders as much as the schemes. @sec-limits'\n   linked arm is built this way, and so is Step 8's paired control below.\n2. **Save what you cannot reseed.** `saveRDS(founderGenomes, ...)` is the only\n   way to get the same coalescent history back in a later session.\n\nEverything after the founders -- the crosses, the doubled haploids, the\nphenotyping error, the recombination -- *is* controlled by `set.seed()`, given\nthe founders. Reseeding downstream does not recover the founders and is not\nneeded for anything else.\n:::\n\nSo what does `quickHaplo()` give up? Linkage disequilibrium among the founders.\nThe honest way to measure that is against the sampling floor: with `n`\nindividuals, two completely independent loci still show `r^2` of about\n`1 / (n - 1)` by chance alone.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nldstat <- function(fg) {\n  SPx <- SimParam$new(fg)\n  g <- pullSegSiteGeno(newPop(fg, simParam = SPx), simParam = SPx)\n  g <- g[, apply(g, 2, stats::sd) > 0, drop = FALSE]\n  chr <- sub(\"_.*$\", \"\", colnames(g))           # \"chr_site\" column names\n  r <- stats::cor(g)\n  adj <- diag(r[-nrow(r), -1])                  # consecutive columns ...\n  adj <- adj[chr[-length(chr)] == chr[-1]]      # ... on the same chromosome\n  c(adjacent = mean(adj^2),                     # neighbouring sites, same chromosome\n    overall  = mean(r[upper.tri(r)]^2),         # all pairs, mostly distant\n    noise    = 1 / (nrow(g) - 1))               # what pure chance gives\n}\nset.seed(3); lq <- ldstat(quickHaplo(nInd = 100, nChr = 5, segSites = 200,\n                                     inbred = TRUE))\nset.seed(3); lm_ <- ldstat(runMacs(nInd = 100, nChr = 5, segSites = 200,\n                                   inbred = TRUE, species = \"MAIZE\"))\nfmt(rbind(quickHaplo = lq, runMacs = lm_))\n```\n\n::: {.cell-output-display}\n\n|           | adjacent| overall|  noise|\n|:----------|--------:|-------:|------:|\n|quickHaplo |   0.0103|  0.0101| 0.0101|\n|runMacs    |   0.1293|  0.0120| 0.0101|\n\n:::\n:::\n\n\n`adjacent` is the mean `r^2` between neighbouring sites on the same\nchromosome (pairs that straddle a chromosome boundary are excluded);\n`overall` is over all pairs, most of them on different chromosomes.\n`quickHaplo()`'s adjacent-site `r^2` sits on the noise floor: there is no\nfounder LD at all, as designed. `runMacs()`'s is\n13 times the floor in this render,\nand its *overall* `r^2` is barely above it -- so the LD it creates is local,\ndecaying with map distance, which is what real LD does.\n\nThe `runMacs` row of that table is itself not reproducible, for the reason the\nrow above it establishes; the `quickHaplo` row is, to the last digit.\n\nWhat that does and does not imply for the rest of the chapter. R's stream is\nunaffected by MaCS, so any step that draws its own `quickHaplo()` founders\nfrom a fresh `set.seed()` is exactly reproducible, and so would be a step that\ndid not reseed: the `runMacs()` calls above leave the stream exactly where a\nfixed number of `sample.int()` calls leaves it. What is not reproducible is\nanything computed *from* MaCS founders -- the `runMacs` rows of both tables\nhere, and all of Step 8. The chapter still calls `set.seed()` immediately\nbefore each step's own founder draw rather than once at the top, so that each\nstep is reproducible on its own and not only as part of this chapter's\nexecution order. With that in place, two independent executions agree on every\nnumber in Steps 1 to 7 except the wall-clock seconds and the `runMacs` rows.\n\nThat measurement decides the policy this chapter follows:\n\n- **`quickHaplo(inbred = TRUE)` for Steps 2--7 and all of @sec-programme.** They\n  teach the arithmetic of dominance, heterosis and response, where founder LD\n  is not the point, and in exchange every number printed is reproducible from\n  a clean clone. AlphaSimR still applies a real genetic map and real meiosis to\n  every descendant, so linkage and the Bulmer effect of @sec-limits still\n  operate -- only the founders' *history* is stylised.\n- **`runMacs2(split = )` in Step 8.** There the divergence between two heterotic\n  pools *is* the object of study, and no amount of speed compensates for not\n  having it. Every Step 8 result is therefore replicated over founder draws.\n\nFounder LD does matter where marker-QTL association is the mechanism, which is\ngenomic prediction -- see @sec-genomic-prediction, and note that the accuracies\nthere are computed on a different simulator for this reason.\n\n## Step 2 -- `SimParam`, and defining a trait with dominance\n\n`SimParam` holds everything global: the genetic map, which sites are QTL, the\ntrait effects, the error variances. It is an R6 object, so its methods are\ncalled with `$`, and a variable named `SP` is picked up automatically by every\nAlphaSimR function that needs it.\n\nA hybrid programme exists because of dominance: without it a line's cross\nperformance is its own breeding value and there is nothing a testcross can see\nthat the line per se could not (@sec-heterosis). So the trait defined here, and\nused through Step 6, carries a dominance term from the start. This is exactly\nthe reason an autogamous programme has no equivalent of this step: there,\ndominance is invisible by construction (a released, self-pollinated variety is\nhomozygous, so no heterozygote is ever evaluated or sold) and `SP$addTraitA()`\n-- additive effects only -- is the whole model, the case @sec-programme runs\nthroughout.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Seeded here, not once at the top of the chapter: Step 1 draws from R's random\n# stream (each runMacs() call consumes a fixed amount of it), so everything\n# downstream would move with any edit or re-execution of Step 1 unless the seed\n# is reset immediately before the draw that matters.\nset.seed(101)\nfounders <- quickHaplo(nInd = 60, nChr = 10, segSites = 100, inbred = TRUE)\nSP <- SimParam$new(founders)\nSP$addTraitAD(nQtlPerChr = 100, mean = 10, var = 1,\n              meanDD = rrs_cfg[[\"mean_dd\"]], varDD = rrs_cfg[[\"var_dd\"]])\nSP$setVarE(h2 = 0.4)\n```\n:::\n\n\nThere are four trait constructors, and choosing between them is choosing a model\nof gene action:\n\n| Method | Adds | When a plant programme needs it |\n|---|---|---|\n| `SP$addTraitA()` | additive only | line per se performance; the course's teaching case [@gorjanc2022], and Step 7 here |\n| `SP$addTraitAD()` | + dominance | testcross and hybrid value. This is what Steps 2--6 and Step 8 use |\n| `SP$addTraitAG()` | + genotype-by-environment | multi-location yield trials, where the same genotype is scored in several places. @sec-programme uses it |\n| `SP$addTraitADE()` | + epistasis | available; used nowhere in this book |\n\n### The dominance model, as AlphaSimR writes it\n\nFor a diploid with QTL $k = 1, \\dots, m$, let $x_{ik} \\in \\{0, 1, 2\\}$ be the\ndosage of the derived allele of individual $i$ at QTL $k$ (the column of\n`pullQtlGeno()`). AlphaSimR's `TraitAD` genetic value is\n\n$$G_i \\;=\\; \\mu_0 + \\sum_{k=1}^{m} a_k\\,(x_{ik} - 1) + \\sum_{k=1}^{m} d_k\\,\\mathbb{1}[x_{ik} = 1]$$\n\nwith $\\mu_0$ an intercept, $a_k \\in \\mathbb{R}$ the additive effect (half the\ndifference between the two homozygotes, on the classical scale of\n@falconer1996, Ch. 7, which puts the origin at the midpoint of the two\nhomozygotes and assigns them $+a$ and $-a$ and the heterozygote $d$; no\nequation number is attributed here, the scale is stated in full) and $d_k \\in\n\\mathbb{R}$ the dominance deviation, the departure of the heterozygote from that\nmidpoint. It is the model of @sec-heterosis with AlphaSimR's coding, and the\nchunk checks it rather than trusts it:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntr <- SP$traits[[1]]\na  <- tr@addEff\nd  <- tr@domEff\npop0 <- newPop(founders, simParam = SP)\nx0   <- pullQtlGeno(pop0, simParam = SP)\ngv_by_hand <- as.numeric(tr@intercept + (x0 - 1) %*% a + (x0 == 1) %*% d)\nstopifnot(isTRUE(all.equal(gv_by_hand, as.numeric(gv(pop0)))))\n```\n:::\n\n\n`meanDD` and `varDD` parameterise the **dominance degree**\n$\\delta_k = d_k / |a_k|$: AlphaSimR draws $\\delta_k \\sim N(\\texttt{meanDD},\n\\texttt{varDD})$ and sets $d_k = \\delta_k\\,|a_k|$, so $\\delta_k = 0$ is\nadditivity, $\\delta_k = 1$ complete dominance, $\\delta_k > 1$ overdominance,\nand a *positive mean* is directional dominance: on average the heterozygote\nsits above the homozygote midpoint, whichever allele is favourable. Directional\ndominance is what makes heterosis positive and inbreeding depression a loss on\nthe trait scale, and it is the standing hypothesis for yield in maize.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(n_qtl = length(a), meanDD_requested = rrs_cfg[[\"mean_dd\"]],\n  meanDD_realised = mean(d / abs(a)), varDD_requested = rrs_cfg[[\"var_dd\"]],\n  varDD_realised = stats::var(d / abs(a))) |> fmt(3)\n#>            n_qtl meanDD_requested  meanDD_realised  varDD_requested \n#>         1000.000            0.400            0.378            0.100 \n#>   varDD_realised \n#>            0.104\n```\n:::\n\n\n`nQtlPerChr` sets how polygenic the trait is. Setting it equal to `segSites`\nmakes *every* segregating site a QTL, which is what this chapter does\nthroughout -- convenient, because then the marker matrix and the causal loci\nare the same set and there is no marker-versus-QTL gap to reason about. Real\nprogrammes have that gap; @sec-genomic-era is where the book takes it\nseriously.\n\n`mean` fixes the mean genetic value of the *founders*. `var` fixes their\n**additive** variance (`useVarA = TRUE`, the default), not their total genetic\nvariance -- with inbred founders the two coincide, for a reason Step 3 shows.\n`corA` (Step 7) sets the genetic correlation between traits.\n\nThe environmental variance has two routes, and plant breeders use the second:\n\n- `SP$setVarE(h2 = 0.4)` fixes an error variance once, from the founders'\n  genetic variance (here 1.5), and every later `setPheno()`\n  reuses it.\n- `setPheno(varE = , reps = )` sets it per call. **`reps` is the plant idiom for\n  locations**: `varE` is the plot-level error, and a genotype scored in `reps`\n  plots has its error variance divided by `reps`, so the phenotype is an\n  entry mean. That is how a staged programme raises selection accuracy from\n  one stage to the next without ever changing the trait's heritability -- the\n  mechanism @sec-programme is built on, and the one Step 6 uses for testers.\n\n## Step 3 -- The base population, and where the variance components live\n\n`newPop()` turns founder haplotypes into individuals and, because a trait is\nnow defined, computes their genetic values immediately.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npop <- setPheno(newPop(founders, simParam = SP), simParam = SP)\nc(n = pop@nInd, meanG = as.numeric(meanG(pop)), varG = as.numeric(varG(pop)),\n  varP = as.numeric(varP(pop)),\n  h2_realised = as.numeric(varG(pop) / varP(pop))) |> fmt(3)\n#>           n       meanG        varG        varP h2_realised \n#>      60.000      10.000       1.000       2.614       0.383\n```\n:::\n\n\nThe realised heritability is near but not equal to the requested 0.4:\n`setVarE()` fixes a variance, and the ratio it produces in any finite sample is\nitself a random variable. This is a general and useful habit -- **check what the\nsimulation realised, do not assume what you requested.**\n\n`genParam()` returns the full decomposition. Four of its fields are the ones a\nhybrid programme cares about, and they read differently on a panel of inbred\nlines and on a random-mating population made from them:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmixed <- pop\nfor (k in 1:3) mixed <- randCross(mixed, nCrosses = 1000, simParam = SP)\n\nvrow <- function(p, lab) {\n  g <- genParam(p, simParam = SP)\n  data.frame(population = lab,\n             meanG     = as.numeric(g[[\"mu\"]]),\n             varA      = as.numeric(g[[\"varA\"]]),\n             genicVarA = as.numeric(g[[\"genicVarA\"]]),\n             ratio     = as.numeric(g[[\"varA\"]] / g[[\"genicVarA\"]]),\n             varD      = as.numeric(g[[\"varD\"]]),\n             genicVarD = as.numeric(g[[\"genicVarD\"]]))\n}\nvtab <- rbind(vrow(pop,   \"founders (fully inbred)\"),\n              vrow(mixed, \"after 3 random matings\"))\nfmt(vtab)\n```\n\n::: {.cell-output-display}\n\n|population              |   meanG|   varA| genicVarA|  ratio|   varD| genicVarD|\n|:-----------------------|-------:|------:|---------:|------:|------:|---------:|\n|founders (fully inbred) | 10.0000| 1.0000|    0.4274| 2.3397| 0.0000|    0.0496|\n|after 3 random matings  | 14.3495| 0.4503|    0.4264| 1.0560| 0.0793|    0.0494|\n\n:::\n\n```{.r .cell-code}\nstopifnot(vtab[[\"varD\"]][1] < 1e-10)\n\n# Among fully homozygous lines the locus value is a (x - 1), so at linkage\n# equilibrium varA = sum 4 p q a^2, while genicVarA = sum 2 p q alpha^2 with\n# alpha = a + d (q - p): under dominance the LE ratio is close to, not\n# exactly, 2. What varA carries above varA_LE is disequilibrium.\np_f      <- colMeans(x0) / 2                        # founder allele frequencies\nvarA_f   <- vtab[[\"varA\"]][1]\ngenic_f  <- vtab[[\"genicVarA\"]][1]\nvarA_LE  <- sum(4 * p_f * (1 - p_f) * a^2)\nratio_LE <- varA_LE / genic_f\nvarA_LD  <- varA_f - varA_LE\nratio_LD <- varA_LD / genic_f\nstopifnot(isTRUE(all.equal(as.numeric(bv(pop, simParam = SP)[, 1]),\n                           as.numeric(sweep(x0, 2, 2 * p_f) %*% a))))\nc(varA = varA_f, varA_LE = varA_LE, ratio_LE = ratio_LE,\n  varA_LD = varA_LD, ratio_LD = ratio_LD) |> fmt(4)\n#>     varA  varA_LE ratio_LE  varA_LD ratio_LD \n#>   1.0000   0.8495   1.9875   0.1505   0.3522\n```\n:::\n\n\n`varA` is the realised additive variance; `genicVarA` is what it would be if the\nloci were independent and in Hardy-Weinberg proportions. Their ratio is the\nwhole subject of @sec-limits, and the package's `genic_var()` computes the same\nquantity from a marker matrix directly.\n\nThe founders' ratio of 2.34 has two parts, and the\nchunk separates them. Among fully homozygous lines the value at QTL $k$ is\n$a_k (x_{ik} - 1)$ with $x_{ik} \\in \\{0, 2\\}$, and AlphaSimR's `bv()` on these\nfounders is exactly $\\sum_k a_k (x_{ik} - 2 p_k)$ (asserted in the chunk). At\nlinkage equilibrium its variance is `varA_LE`\n$= \\sum_k 4 p_k q_k a_k^2 =$ 0.8495, against a genic value of\n0.4274: a ratio of 1.99, exact given the effects\nand the frequencies. That part is **inbreeding** -- a homozygous population\nhas per-locus variance `4pq` where a Hardy-Weinberg one has `2pq`. It is close\nto 2 and not exactly 2 because `genicVarA` is written with the Hardy-Weinberg\naverage effect $\\alpha_k = a_k + d_k (q_k - p_k)$ defined below, whereas the\nhomozygous lines carry $a_k$; twice the genic value equals `varA_LE` only\nwhere $d_k (q_k - p_k) = 0$ at every locus. The remainder,\n`varA_LD = varA - varA_LE` $=$ 0.1505, or 0.35\nin ratio units, is sampling (gametic-phase) disequilibrium among only 60\nfounders' worth of gametes. Three rounds of random mating restore\nHardy-Weinberg and pull the ratio to 1.06; what\nremains is that same disequilibrium. A ratio away from 1 in an *outbred*\npopulation is the gametic-phase disequilibrium @sec-response defines and\n@sec-limits measures; a ratio away from 1 in an inbred one is mostly the\nhomozygosity.\n\nThe dominance columns carry the hybrid lesson. **`varD` among the inbred\nfounders is exactly zero** (the assertion above): a homozygous line has no\nheterozygous locus, so its dominance contribution is zero whatever $d$ is,\nand no amount of per se evaluation of inbred lines can see dominance. This\nsingle identity is the operational reason an autogamous programme stops at\nper se selection and never needs a testcross: its released lines are exactly\nthis \"founders\" row, `varD = 0` for the whole life of the programme, so per\nse phenotype already is breeding value up to the additive/genic gap discussed\nbelow. After random mating `varD` appears. Two identities make that quantitative. With\n$p_k$ the founders' frequency of the derived allele at QTL $k$ and\n$q_k = 1 - p_k$, the population mean under Hardy-Weinberg proportions is\n[@falconer1996, Ch. 7, Eq. 7.2]\n\n$$M_{HW} \\;=\\; \\mu_0 + \\sum_k \\big[a_k\\,(p_k - q_k) + 2\\,p_k q_k\\,d_k\\big]$$\n\nwhile the inbred panel at the same frequencies has only the first term. The\ndifference, $2\\sum_k d_k p_k q_k$, is the inbreeding depression of\n@sec-heterosis at $F = 1$, which the package computes as\n`inbreeding_depression(p, d, F_coef = 1)`. And the genic additive variance is\n$\\sum_k 2 p_k q_k \\alpha_k^2$ with $\\alpha_k = a_k + d_k\\,(q_k - p_k)$ the\naverage effect of a gene substitution. @falconer1996 define $\\alpha$ in\nCh. 7 and the single-locus additive variance $2pq\\alpha^2$ in Ch. 8; the\nequation numbers are not attributed here, so both identities are stated in\nthis chapter's notation: $\\alpha_k = a_k + d_k\\,(q_k - p_k)$ and, summed over\nindependent loci, $\\sum_k 2 p_k q_k \\alpha_k^2$, which is the genic variance:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngp  <- genParam(pop, simParam = SP)\nalpha_f <- a + d * (1 - 2 * p_f)\nstopifnot(isTRUE(all.equal(as.numeric(gp[[\"mu_HW\"]] - gp[[\"mu\"]]),\n                           inbreeding_depression(p_f, d, F_coef = 1))))\nstopifnot(isTRUE(all.equal(as.numeric(gp[[\"genicVarA\"]]),\n                           sum(2 * p_f * (1 - p_f) * alpha_f^2))))\nc(mean_inbred = as.numeric(gp[[\"mu\"]]), mean_HW = as.numeric(gp[[\"mu_HW\"]]),\n  inbreeding_depression = inbreeding_depression(p_f, d, F_coef = 1)) |> fmt(3)\n#>           mean_inbred               mean_HW inbreeding_depression \n#>                10.000                14.355                 4.355\n```\n:::\n\n\nBoth hold to machine precision against AlphaSimR's own `genParam()`. The gap\nbetween the two means is the amount a random-mating population built from these\nlines would sit *above* the lines themselves -- and, read in the other\ndirection, the amount an open-pollinated population loses on being driven to\nhomozygosity. It is the same $d$ that Step 4 turns into heterosis.\n\n## Step 4 -- The DNA lottery, heterosis, and why an F1 is not a family\n\nThe course [@gorjanc2022] demonstrates Mendelian sampling by crossing outbred\nfounders and showing that full sibs vary. With **inbred** parents the result is different,\nand it is the fact hybrid breeding is organised around.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncrosses <- list(c(1, 2), c(1, 3), c(2, 3))\nlottery <- do.call(rbind, lapply(crosses, function(ij) {\n  plan <- matrix(ij, ncol = 2)\n  f1 <- makeCross(pop, plan, nProgeny = 200, simParam = SP)\n  dh <- makeDH(makeCross(pop, plan, nProgeny = 1, simParam = SP),\n               nDH = 200, simParam = SP)\n  better <- max(gv(pop)[ij])\n  data.frame(cross         = paste(ij, collapse = \" x \"),\n             parent_mean   = mean(gv(pop)[ij]),\n             better_parent = better,\n             f1_mean       = as.numeric(meanG(f1)),\n             f1_sd         = as.numeric(sqrt(varG(f1))),\n             dh_sd         = as.numeric(sqrt(varG(dh))),\n             dh_best       = max(gv(dh)),\n             transgressive = mean(gv(dh) > better),\n             # how far the better parent sits above the DH mean, in DH s.d.\n             gap_in_dh_sd  = (better - mean(gv(pop)[ij])) / as.numeric(sqrt(varG(dh))))\n}))\nfmt(lottery, 3)\n```\n\n::: {.cell-output-display}\n\n|cross | parent_mean| better_parent| f1_mean| f1_sd| dh_sd| dh_best| transgressive| gap_in_dh_sd|\n|:-----|-----------:|-------------:|-------:|-----:|-----:|-------:|-------------:|------------:|\n|1 x 2 |      10.655|        12.193|  14.997|     0| 0.788|  12.749|         0.025|        1.952|\n|1 x 3 |      10.912|        12.193|  15.350|     0| 0.584|  12.249|         0.010|        2.193|\n|2 x 3 |       9.374|         9.632|  14.029|     0| 0.568|  11.276|         0.320|        0.453|\n\n:::\n\n```{.r .cell-code}\nstopifnot(all(lottery[[\"f1_sd\"]] < 1e-8))\nstopifnot(which.max(lottery[[\"transgressive\"]]) == which.min(lottery[[\"gap_in_dh_sd\"]]))\n```\n:::\n\n\n`f1_sd` is **zero**, asserted to machine precision. Two fully inbred parents\nare homozygous everywhere, so every gamete each one makes is identical, and\nevery F1 is the same heterozygote. Two hundred F1 plants from a cross of two inbred lines are\ntwo hundred copies of one genotype. There is no lottery yet -- and this\nuniformity is the first reason a single-cross hybrid is a saleable variety.\n\n`f1_mean` sits well above `better_parent`. That is heterosis, and under the\nmodel of Step 2 it has an exact value: for inbred parents $i$ and $j$ with\nallele indicators $u_{ik}, u_{jk} \\in \\{0, 1\\}$ (their dosage halved), the F1\nis heterozygous exactly where they differ, so\n\n$$H_{ij} \\;=\\; G_{ij} - \\tfrac{1}{2}(G_i + G_j) \\;=\\; \\sum_k d_k\\,\\mathbb{1}[u_{ik} \\neq u_{jk}]$$\n\nThe additive terms cancel from the mid-parent difference because an inbred\nparent's additive contribution is exactly half the F1's. `heterosis_value(X, d)`\nis this sum, with `X` the F1's 0/0.5/1 genotype:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nH <- vapply(seq_along(crosses), function(s) {\n  ij <- crosses[[s]]\n  f1 <- makeCross(pop, matrix(ij, ncol = 2), nProgeny = 1, simParam = SP)\n  hv <- as.numeric(heterosis_value(pullQtlGeno(f1, simParam = SP) / 2, d))\n  stopifnot(isTRUE(all.equal(as.numeric(gv(f1)) - mean(gv(pop)[ij]), hv)))\n  hv\n}, numeric(1))\nnames(H) <- lottery[[\"cross\"]]\nfmt(H, 3)\n#> 1 x 2 1 x 3 2 x 3 \n#> 4.342 4.438 4.655\n```\n:::\n\n\nOver a *set* of crosses the same identity has a closed form in the allele\nfrequencies. Take the 60 founders as two arbitrary halves, \"pool A\" (lines\n1--30) and \"pool B\" (lines 31--60) -- arbitrary because `quickHaplo()` gave\nthem a common history and no divergence, which Step 8 will add -- and cross\nevery A line to every B line. `hybridCross(crossPlan = \"testcross\")` is the\nfull factorial. With $p_{Ak}$ and $p_{Bk}$ the derived-allele frequencies of\nthe two pools at QTL $k$, the mean of $H_{ij}$ over the factorial is\n`heterosis_expected(pA, pB, d)`, the identity of @sec-heterosis:\n\n$$\\bar H \\;=\\; \\sum_k d_k\\,\\big(p_{Ak} + p_{Bk} - 2\\,p_{Ak}\\,p_{Bk}\\big)$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nA <- pop[1:30]\nB <- pop[31:60]\nfact <- hybridCross(A, B, crossPlan = \"testcross\", simParam = SP)\nU  <- pullQtlGeno(A, simParam = SP) / 2\nV  <- pullQtlGeno(B, simParam = SP) / 2\npA <- colMeans(U)\npB <- colMeans(V)\nH_bar_obs <- as.numeric(meanG(fact)) - (as.numeric(meanG(A)) + as.numeric(meanG(B))) / 2\nH_bar_exp <- heterosis_expected(pA, pB, d)\nstopifnot(isTRUE(all.equal(H_bar_obs, H_bar_exp)))\nc(n_hybrids = fact@nInd, mean_A = as.numeric(meanG(A)), mean_B = as.numeric(meanG(B)),\n  mean_hybrids = as.numeric(meanG(fact)), heterosis_observed = H_bar_obs,\n  heterosis_expected = H_bar_exp,\n  pct_of_midparent = 100 * H_bar_obs / ((as.numeric(meanG(A)) + as.numeric(meanG(B))) / 2)) |>\n  fmt(3)\n#>          n_hybrids             mean_A             mean_B       mean_hybrids \n#>            900.000             10.216              9.784             14.427 \n#> heterosis_observed heterosis_expected   pct_of_midparent \n#>              4.427              4.427             44.275\n```\n:::\n\n\nExact, on the full factorial, because every A x B pairing is present once.\nThe size -- 44.3\npercent of the mid-parent -- follows from `meanDD` and from `quickHaplo()`'s\nfrequencies near one half, where $p_A + p_B - 2 p_A p_B$ is near its\nmaximum; it is not calibrated to a crop. @falconer1996, Ch. 14, derive the\nheterosis of the F1 between two *random-mating* populations as\n$H_{F1} = \\sum_k d_k y_k^2$ with $y_k = p_{Ak} - p_{Bk}$ (stated here in this\nchapter's notation rather than by their equation number; it is twice the\n`divergence` term of `heterosis_partition()`). The two do not conflict; they\nuse different mid-parents. Theirs carries each population's own\nrandom-mating heterozygosity; an inbred line carries none, so the whole F1\nheterozygosity is heterosis and the expression above keeps the `shared` term\nas well -- @sec-heterosis works the reconciliation through.\n\nThe lottery starts one meiosis later. `dh_sd` is the standard deviation among\ndoubled haploids drawn from that F1, and it is substantial -- this is the\nsegregation that F2, DH and RIL populations exist to sample. It is also why\n@sec-sizing is a chapter: the number of DH lines you pull from a cross is the\nnumber of tickets you buy, and no downstream selection stage can recover a\ncombination that was never sampled.\n\n`transgressive` is the fraction of DH lines exceeding the *better* parent per\nse: 0.025,\n0.01 and\n0.32 for the three crosses. It depends\nstrongly on the cross, and `gap_in_dh_sd` says why: the DH lines are centred\non the mid-parent, so what matters is how far the better parent sits above it\nin units of the DH standard deviation -- 1.95,\n2.19 and\n0.45. The cross with the smallest gap is\nthe one with the most transgressive lines (asserted), about a third of them;\nthe other two, whose better parent is two DH standard deviations above the\nmid-parent, give a few percent. Crossing two parents whose favourable alleles\nsit at different loci produces progeny beyond either of them -- transgressive\nsegregation, which @mackay2020 argue is the same phenomenon as heterosis and\ninbreeding depression viewed from a third angle -- and how often depends on\nthe gap between the parents relative to the segregation variance, not on a\nconstant.\n\n## Step 5 -- Selfing, doubled haploids, and why hybrid seed is remade every year\n\nA plant breeder has to get from a heterozygous F1 to a homozygous line. There\nare two routes, and AlphaSimR implements both. Following the same cross through\nselfing generations also answers a question every hybrid grower has asked:\nwhat happens if the F1 seed is saved and sown again.\n\nThis is the one step where the allogamous, hybrid case and the autogamous\ncase use literally the same primitive -- `makeDH()` is exactly what\n@sec-programme calls to take its wheat F1s straight to a homozygous line, one\ngeneration instead of the six or seven selfing generations traced below --\nand where they diverge again in what the resulting inbred line is *for*. In\nan autogamous programme that homozygous line is commonly the release: it\nbreeds true, so what leaves the DH pipeline is what a farmer eventually\ngrows. In this chapter's programme the homozygous DH line is a parent, held\ninside a heterotic pool, testcrossed and recycled (Step 6, Step 8), and never\nsold on its own; the object a grower plants is the F1 these lines make\ntogether, which is the reason it cannot be saved.\n\nUnder selfing without selection, the fraction of the F1's heterozygous loci\nstill heterozygous in generation $F_t$ is $(1/2)^{t-1}$ in expectation, so the\nexpected mean of the selfed generation is\n\n$$\\mathbb{E}[M_{F_t}] \\;=\\; \\tfrac{1}{2}(G_i + G_j) + H_{ij}\\,(1/2)^{t-1}$$\n\nwith $H_{ij}$ the F1 heterosis of Step 4. At $t = 2$ this is the classical\nresult that the F2 retains half the F1 heterosis, $H_{F2} = \\tfrac{1}{2} H_{F1}$,\nwhich @falconer1996 derive in Ch. 14 for the F2 of a cross between two\npopulations (stated here in this chapter's notation rather than by their\nequation number); the form above extends it to later selfed generations by\nthe same argument, since the expected heterozygosity at every locus is halved\neach generation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhomozygosity <- function(p)\n  mean(pullSegSiteGeno(p, simParam = SP) %in% c(0, 2))\n\n# Seeded here so that the |z| < 4 check below does not inherit the RNG state\n# of Step 4: this z-statistic is not exactly Gaussian at this sample size, so\n# an unrelated upstream edit that reseeded Step 4 could otherwise flip the\n# check and break the render even though it passes for the seed used here.\nset.seed(55)\nij <- c(1, 2)\nmidparent <- mean(gv(pop)[ij])\nf1  <- makeCross(pop, matrix(ij, ncol = 2), nProgeny = 400, simParam = SP)\ngen <- f1\ntraj <- data.frame(generation = \"F1\", homozygosity = homozygosity(f1),\n                   meanG = as.numeric(meanG(f1)), sdG = as.numeric(sqrt(varG(f1))),\n                   expected = midparent + H[[\"1 x 2\"]])\nfor (t in 2:7) {\n  gen  <- self(gen, nProgeny = 1, simParam = SP)\n  traj <- rbind(traj, data.frame(generation = paste0(\"F\", t),\n                                 homozygosity = homozygosity(gen),\n                                 meanG = as.numeric(meanG(gen)),\n                                 sdG = as.numeric(sqrt(varG(gen))),\n                                 expected = midparent + H[[\"1 x 2\"]] * (1 / 2)^(t - 1)))\n}\ndh1 <- makeDH(f1, nDH = 1, simParam = SP)\ntraj <- rbind(traj, data.frame(generation = \"DH\", homozygosity = homozygosity(dh1),\n                               meanG = as.numeric(meanG(dh1)),\n                               sdG = as.numeric(sqrt(varG(dh1))),\n                               expected = midparent))\ntraj[[\"z\"]] <- (traj[[\"meanG\"]] - traj[[\"expected\"]]) / (traj[[\"sdG\"]] / sqrt(400))\ntraj[[\"z\"]][1] <- 0   # F1: no variance, and the identity of Step 4 is exact\nfmt(traj, 3)\n```\n\n::: {.cell-output-display}\n\n|generation | homozygosity|  meanG|   sdG| expected|      z|\n|:----------|------------:|------:|-----:|--------:|------:|\n|F1         |        0.501| 14.997| 0.000|   14.997|  0.000|\n|F2         |        0.753| 12.798| 0.667|   12.826| -0.818|\n|F3         |        0.876| 11.742| 0.759|   11.740|  0.045|\n|F4         |        0.938| 11.206| 0.792|   11.197|  0.226|\n|F5         |        0.970| 10.951| 0.792|   10.926|  0.616|\n|F6         |        0.985| 10.823| 0.797|   10.790|  0.825|\n|F7         |        0.993| 10.744| 0.790|   10.723|  0.533|\n|DH         |        1.000| 10.604| 0.809|   10.655| -1.244|\n\n:::\n\n```{.r .cell-code}\nstopifnot(all(abs(traj[[\"z\"]]) < 4))\n```\n:::\n\n\nThree columns, three lessons.\n\n`homozygosity`: `self()` halves the remaining heterozygosity every generation\n-- the familiar `1 - (1/2)^(t-1)` approach to fixation, which never quite\narrives. `makeDH()` gets there in one step, at 1.0 exactly, by doubling a\nhaploid gamete.\n\n`meanG` against `expected`: the F2 mean falls by half the heterosis, the F3 by\nthree quarters, and the DH lines land on the mid-parent. Each row is 400\nplants, one per F1 plant: `self(nProgeny = 1)` carries 400 parallel,\nindependent selfing lineages forward, so within a row the 400 values are\nindependent and `sdG / sqrt(400)` is the standard error of the row's mean.\nThe check is statistical: `z` is the observed minus expected mean in units of\nthat standard error, and the chunk asserts every `|z| < 4`. Across rows the\nsame 400 lineages are followed -- each $F_t$ plant is the selfed progeny of\none $F_{t-1}$ plant -- so successive rows are correlated, and the table is\n400 lineages checked at seven generations, not seven independent samples.\nNothing about the parents changed; the loss is the heterozygosity\nbeing halved, times $d$. This is why hybrid seed is remade from the two inbred\nparents every season and why a maize F2 crop yields visibly less than the F1\nit was saved from.\n\n`sdG`: the F1 has none and the F2 has plenty. The F2 is not a variety; it is a\nsegregating population, and a uniform, high-yielding one cannot be recovered\nfrom it by anything but selection and re-fixation -- which is the line\ndevelopment a breeding programme does, not something a grower can do.\n\nThe saving DH buys is seasons, and seasons are the currency of a breeding\nprogramme: six or seven selfing generations against one DH cycle. Step 8's\nscheme uses `makeDH()` for precisely this reason, and the cost that never\nshows up in the simulation is that DH production is a laboratory operation\nwith its own failure rate and its own genotype-dependent response.\n\nThe other operations a scheme needs are all one call each: `randCross()` for\nrandom mating within a pool, `makeCross()` for a specified crossing plan,\n`hybridCross()` for a full factorial or a testcross between two groups, and\n`mergePops()` or `c()` to combine populations.\n\n## Step 6 -- Phenotyping and selection: per se, then on the testcross\n\nSelection needs a criterion. `setPheno()` supplies the noisy one; `selectInd()`\nacts on it. This step does it twice: first on a line's own phenotype, as the\ncourse does [@gorjanc2022], to check the breeder's equation; then on the testcross, which is\nhow a hybrid programme actually ranks lines.\n\n### Per se selection and the breeder's equation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbe_draw <- function(q, r) {\n  set.seed(500 + r)\n  mx    <- setPheno(mixed, simParam = SP)\n  sel   <- selectInd(mx, nInd = round(q * mx@nInd), use = \"pheno\", simParam = SP)\n  prog  <- randCross(sel, nCrosses = 1000, simParam = SP)\n  S     <- as.numeric(meanP(sel) - meanP(mx))\n  vA    <- as.numeric(varA(mx, simParam = SP))\n  i_emp <- S / sqrt(as.numeric(varP(mx)))\n  r_emp <- stats::cor(bv(mx, simParam = SP)[, 1], pheno(mx)[, 1])\n  c(i_empirical = i_emp,\n    R_S_h2      = S * vA / as.numeric(varP(mx)),\n    R_i_r_sdA   = i_emp * r_emp * sqrt(vA),\n    R_observed  = as.numeric(meanG(prog) - meanG(mixed)))\n}\nn_be <- 20\nsweep_q <- do.call(rbind, lapply(c(0.05, 0.10, 0.20), function(q) {\n  draws <- t(sapply(seq_len(n_be), function(r) be_draw(q, r)))\n  gap   <- draws[, \"R_observed\"] - draws[, \"R_S_h2\"]\n  data.frame(q = q, i_normal = sel_intensity(q),\n             t(colMeans(draws)),\n             R_observed_sd = stats::sd(draws[, \"R_observed\"]),\n             gap_mean = mean(gap), gap_sd = stats::sd(gap))\n}))\nfmt(sweep_q, 3)\n```\n\n::: {.cell-output-display}\n\n|    q| i_normal| i_empirical| R_S_h2| R_i_r_sdA| R_observed| R_observed_sd| gap_mean| gap_sd|\n|----:|--------:|-----------:|------:|---------:|----------:|-------------:|--------:|------:|\n| 0.05|    2.063|       2.068|  0.657|     0.653|      0.654|         0.074|   -0.003|  0.081|\n| 0.10|    1.755|       1.755|  0.558|     0.554|      0.563|         0.048|    0.006|  0.048|\n| 0.20|    1.400|       1.399|  0.445|     0.442|      0.456|         0.045|    0.011|  0.045|\n\n:::\n:::\n\n\nBoth forms of the breeder's equation are here, each averaged over 20\nindependent draws of the phenotypes, the selection and the progeny (the\npopulation selected from is the same `mixed` every time, so `varA` is fixed\nand only `S`, the accuracy and the Mendelian sampling vary). `R = S * h2` uses\nthe selection differential directly, with `h2` the *narrow-sense* heritability\n`varA / varP` of the population selected from; `R = i * r * sigma_A`\ndecomposes it into intensity, accuracy and available variation -- the form\n@sec-response builds the book's objective side on. Because the trait has\ndominance, the accuracy `r` is the correlation of the phenotype with the\n**breeding value** (`bv()`), not with the total genetic value: only the\nadditive part is transmitted. `R_observed` is the realised change in\n*genetic* mean between the selected parents' random-mated progeny and the\nstarting population, which is what the prediction is a prediction of.\n\n`gap_mean` is the paired difference between the observed response and\n`R_S_h2`, with `gap_sd` its standard deviation over the draws. The mean gap is\n-0.5 percent of\nthe prediction at `q = 0.05` and\n2.5 percent at\n`q = 0.20`; its standard error over the 20 draws is\n`gap_sd / sqrt(20)`, and the largest gap in units of that standard\nerror is 1.1.\nA single draw is another matter: `R_observed_sd` says that\none realisation of the response scatters by around\n11 percent\nof the prediction at `q = 0.05`, which is why the course's one-off comparison\n[@gorjanc2022] \"did not match perfectly\" and why this one is replicated. The equation\npredicts the additive response to first order in the allele-frequency change;\nwhat it leaves out is second order in that change and the dominance\ncontribution of the progeny's departure from Hardy-Weinberg proportions, both\nsmall with 1000 progeny from 50 or more parents.\nThe empirical intensity agrees with the normal-theory value to within\n0.2\npercent: with 1000 candidates and a criterion that is a sum over\n1000 loci plus normal error, the two assumptions of `sel_intensity()`\n-- an infinite population and a normal criterion -- are nearly met.\n\nThe book exports its own selection intensity, and AlphaSimR exports one too.\nThey are independent implementations of `phi(z) / q`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nq <- 0.05\nc(hybdiv = sel_intensity(q), AlphaSimR = selInt(q),\n  difference = abs(sel_intensity(q) - selInt(q))) |> fmt(10)\n#>     hybdiv  AlphaSimR difference \n#>   2.062713   2.062713   0.000000\n```\n:::\n\n\n`selectInd()` takes `use = \"pheno\"`, `\"gv\"` or `\"ebv\"`. Selecting on `\"gv\"` is\nselecting with perfect accuracy -- impossible in a real programme, and the\ncorrect way to compute the ceiling a scheme is being measured against.\n`use = \"ebv\"` selects on whatever has been written into the population's `ebv`\nslot, which is how genomic selection enters a simulation (@sec-programme).\n`selectTop = FALSE` selects downwards, for traits where less is better.\n\n`selectWithinFam()` is the plant-specific one. A programme that truncates\nglobally on a set of families will take every entry from the two best crosses\nand nothing from the rest; capping the number retained per family holds the\nprogramme's genetic base open at some cost in immediate gain. It is the same\ntrade-off as the `max_use` parental cap of @sec-combinatorial, applied one stage\nearlier.\n\n### Selection on the testcross: general combining ability\n\nA maize breeder does not rank inbred lines on their own yield. A line is\ncrossed to a **tester** from the opposite pool, the testcross hybrids are grown\nin yield trials, and the line is ranked on the mean of its testcrosses. This\nsubsection is the one with no autogamous counterpart at all: a self-pollinated\nvariety is judged, released and grown as itself, so selection there stops at\nthe per se phenotype of Step 6's first half. A hybrid parent is judged by a\ncross it will never be sold as, which is the entire reason general and\nspecific combining ability exist as concepts. The\nquantity being estimated is the line's **general combining ability** (GCA), the\naverage performance of its crosses expressed as a deviation from the mean of\nall crosses (@sprague1942); what a particular cross does beyond the sum of its\ntwo parents' GCAs is the specific combining ability (SCA). Comstock, Robinson\nand Harvey's reciprocal recurrent selection (@comstock1949) is built on using\nthe opposite pool as the tester so that selection captures both.\n\nOn the full factorial of Step 4 the GCA of every A line against pool B can be\ncomputed exactly, and under the model of Step 2 it has a closed form. With\n$u_{ik}$ the line's allele indicator and $\\bar G$ the factorial mean,\n\n$$\\mathrm{GCA}_i \\;=\\; \\frac{1}{n_B}\\sum_{j} G_{ij} - \\bar G \\;=\\; \\sum_k \\alpha^{(B)}_k\\,(u_{ik} - p_{Ak}),\n\\qquad \\alpha^{(B)}_k = a_k + d_k\\,(1 - 2\\,p_{Bk})$$\n\n$\\alpha^{(B)}_k$ is the average effect of substituting the line's allele into a\n*pool-B* background -- the same $\\alpha = a + d(q - p)$ of Step 3, with the\nfrequency of the tester pool, not the line's own pool. That is the algebraic\ncontent of the sentence \"combining ability is a property of a line against a\ntester\": change the tester pool and the weights change. Its dominance part,\n$\\sum_k d_k (1 - 2 p_{Bk})(u_{ik} - p_{Ak})$, is the `gca_A` of\n`heterosis_gca_sca()` (@sec-heterosis-gca-sca), and the interaction residual\nof the factorial is that function's `sca`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngca_true <- tapply(gv(fact)[, 1], fact@mother, mean)[A@id] - as.numeric(meanG(fact))\ngca_formula <- drop(sweep(U, 2, pA) %*% (a + d * (1 - 2 * pB)))\nstopifnot(isTRUE(all.equal(as.numeric(gca_true), as.numeric(gca_formula))))\n\nhg <- heterosis_gca_sca(U, V, d)\nstopifnot(isTRUE(all.equal(as.numeric(gca_true) - as.numeric(sweep(U, 2, pA) %*% a),\n                           as.numeric(hg[[\"gca_A\"]]))))\n\nG_ij <- tapply(gv(fact)[, 1], list(fact@mother, fact@father), mean)[A@id, B@id]\nsca  <- sweep(sweep(G_ij, 1, rowMeans(G_ij)), 2, colMeans(G_ij)) + mean(G_ij)\nstopifnot(isTRUE(all.equal(unname(sca), unname(hg[[\"sca\"]]))))\n\nvar_gca <- mean(gca_true^2)\nvar_sca <- mean(sca^2)\nc(var_GCA_A = var_gca, var_SCA = var_sca,\n  cor_perse_gv_vs_GCA = stats::cor(gv(A)[, 1], gca_true)) |> fmt(4)\n#>           var_GCA_A             var_SCA cor_perse_gv_vs_GCA \n#>              0.2678              0.0486              0.9973\n```\n:::\n\n\nThe last number is the one to hold on to. With pools that have no divergence,\n$p_{Bk}$ sits near one half at most loci, $(1 - 2 p_{Bk})$ is near zero, and\nthe dominance contribution to GCA nearly vanishes: a line's own genetic value\nranks it for combining ability almost perfectly. Step 8 measures the same\ncorrelation on pools with a real split, and it is lower there. Divergence is\nwhat makes the testcross informative beyond the line itself, and it is the\nreason heterotic pools are kept apart.\n\n### How many testers, how many locations\n\nA programme cannot cross every candidate to every line of the other pool. It\nuses $t$ testers and $r$ locations, and the estimate of $\\mathrm{GCA}_i$ is the\nmean phenotype of the line's $t$ testcrosses, each an entry mean over $r$\nplots. Writing the testcross phenotype as $\\bar G + \\mathrm{GCA}_i +\n\\mathrm{GCA}_j + \\mathrm{SCA}_{ij} + e_{ij}$ with $e_{ij}$ the entry-mean error\nof variance $\\sigma^2_e / r$, and averaging over the $t$ testers (whose own\nGCAs are common to every candidate and drop out of the ranking), the estimate\nis $\\widehat{\\mathrm{GCA}}_i = \\mathrm{GCA}_i + \\bar s_i + \\bar e_i$, with\n$\\bar s_i$ the mean of the line's SCA with its $t$ testers and $\\bar e_i$ the\nmean error. The statistic the chunk computes is a *sample* correlation\nbetween $\\widehat{\\mathrm{GCA}}_i$ and $\\mathrm{GCA}_i$ over the\n$n_A =$ 30 fixed candidate lines, with the $t$ testers drawn without\nreplacement from the $n_B =$ 30 lines of pool B. To first order its\nexpectation is\n\n$$\\rho(t, r) \\;=\\; \\sqrt{\\frac{v_g}{v_g + v_s + v_e}}, \\qquad\nv_g = \\frac{1}{n_A - 1}\\sum_{i=1}^{n_A} \\mathrm{GCA}_i^2, \\quad\nv_s = \\frac{\\sigma^2_{SCA}}{t}\\cdot\\frac{n_A}{n_A - 1}\\cdot\\frac{n_B - t}{n_B - 1}, \\quad\nv_e = \\frac{\\sigma^2_e}{t\\,r}$$\n\nwhere $v_g$ is the sample variance ($n_A - 1$ divisor) of the candidates'\ntrue GCA, because the correlation is taken over exactly those $n_A$ points;\n$\\sigma^2_{SCA} = \\frac{1}{n_A n_B}\\sum_{ij} \\mathrm{SCA}_{ij}^2$ is the SCA\nvariance on the factorial (computed above), $(n_B - t)/(n_B - 1)$ is the\nfinite-population correction for $t$ testers drawn without replacement from\n$n_B$, $n_A/(n_A - 1)$ turns the mean of the per-candidate variances of\n$\\bar s_i$ into the expected sample variance, and $\\sigma^2_e$ is `SP$varE`,\nthe plot error of Step 2. The textbook form of this prediction replaces $v_g$\nby the population variance of GCA and $v_s$ by $\\sigma^2_{SCA}/t$: it assumes\nan infinite tester pool and population variances. It is kept in the table as\n`predicted_infinite`, so the two can be compared. Neither corrects the\nsecond-order term of a sample correlation (the Jensen term); it is measured\ndirectly, not assumed away, in the Monte Carlo chunk below the accuracy grid,\nand left uncorrected because it is small at this $n_A$. The simulation\nmeasures the thing itself: repeated draws of the tester set and of the field\nerror, at every combination.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngrid  <- expand.grid(testers = c(1, 2, 4, 8), reps = c(1, 4))\nn_acc <- 20\nacc   <- sapply(seq_len(n_acc), function(rep) {\n  set.seed(300 + rep)\n  testers <- B[sample(B@nInd, max(grid[[\"testers\"]]))]\n  tc <- hybridCross(A, testers, crossPlan = \"testcross\", simParam = SP)\n  apply(grid, 1, function(g) {\n    ph  <- setPheno(tc, reps = g[[\"reps\"]], simParam = SP)@pheno[, 1]\n    use <- tc@father %in% testers@id[seq_len(g[[\"testers\"]])]\n    est <- tapply(ph[use], tc@mother[use], mean)[A@id]\n    stats::cor(est, gca_true)\n  })\n})\n# The prediction, for the statistic actually computed above: a sample\n# correlation over the n_A FIXED candidates, with t testers drawn WITHOUT\n# replacement from the n_B lines of pool B.\n#   est_i = GCA_i + sbar_i + ebar_i\n#   v_g : the candidates' sample variance of GCA (n_A - 1 divisor), because\n#         the correlation is taken over exactly these n_A points;\n#   v_s : sbar_i is the mean of t values from row i of sca, whose n_B entries\n#         average zero, so Var(sbar_i) = (s2_i / t) (n_B - t) / (n_B - 1) with\n#         s2_i = mean_j sca_ij^2; the column means of sca are zero too, so the\n#         sample mean of sbar over candidates is exactly zero and the expected\n#         sample variance is mean_i Var(sbar_i) n_A / (n_A - 1)\n#         = var_sca n_A / (n_A - 1) (n_B - t) / (n_B - 1) / t;\n#   v_e : varE / (t r), independent of everything else.\n# To first order E[cor] = sqrt(v_g / (v_g + v_s + v_e)). The second-order\n# (Jensen) term of the sample correlation is not corrected here; it is\n# measured by Gaussian Monte Carlo in the chunk below the accuracy grid and\n# reported there (`jensen_max`) rather than asserted in advance.\n# `predicted_infinite` is the textbook form -- population variances, infinite\n# tester pool -- kept so the two can be compared at this replication.\nn_A <- A@nInd; n_B <- B@nInd\nvar_gca_n1 <- stats::var(gca_true)\nfpc <- (n_B - grid[[\"testers\"]]) / (n_B - 1)\nv_s <- var_sca * (n_A / (n_A - 1)) * fpc / grid[[\"testers\"]]\nv_e <- SP$varE / (grid[[\"testers\"]] * grid[[\"reps\"]])\ngrid[[\"predicted\"]] <- sqrt(var_gca_n1 / (var_gca_n1 + v_s + v_e))\ngrid[[\"predicted_infinite\"]] <- sqrt(var_gca / (var_gca + var_sca / grid[[\"testers\"]] + v_e))\ngrid[[\"observed_mean\"]] <- rowMeans(acc)\ngrid[[\"observed_sd\"]]   <- apply(acc, 1, stats::sd)\ngrid[[\"z\"]] <- (grid[[\"observed_mean\"]] - grid[[\"predicted\"]]) /\n  (grid[[\"observed_sd\"]] / sqrt(n_acc))\nfmt(grid, 3)\n```\n\n::: {.cell-output-display}\n\n| testers| reps| predicted| predicted_infinite| observed_mean| observed_sd|      z|\n|-------:|----:|---------:|------------------:|-------------:|-----------:|------:|\n|       1|    1|     0.389|              0.384|         0.371|       0.132| -0.612|\n|       2|    1|     0.513|              0.507|         0.521|       0.163|  0.203|\n|       4|    1|     0.646|              0.639|         0.620|       0.085| -1.388|\n|       8|    1|     0.768|              0.762|         0.752|       0.044| -1.625|\n|       1|    4|     0.628|              0.622|         0.622|       0.107| -0.258|\n|       2|    4|     0.753|              0.747|         0.733|       0.084| -1.028|\n|       4|    4|     0.852|              0.847|         0.843|       0.039| -0.922|\n|       8|    4|     0.918|              0.914|         0.922|       0.019|  0.905|\n\n:::\n\n```{.r .cell-code}\nacc_max_z <- max(abs(grid[[\"z\"]]))\nacc_max_z_infinite <- max(abs(grid[[\"observed_mean\"]] - grid[[\"predicted_infinite\"]]) /\n                            (grid[[\"observed_sd\"]] / sqrt(n_acc)))\nacc_max_gap <- max(abs(grid[[\"predicted\"]] - grid[[\"predicted_infinite\"]]))\nc(max_abs_z = acc_max_z, max_abs_z_infinite = acc_max_z_infinite,\n  max_gap_between_predictions = acc_max_gap) |> fmt(3)\n#>                   max_abs_z          max_abs_z_infinite \n#>                       1.625                       1.913 \n#> max_gap_between_predictions \n#>                       0.007\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# The second-order term the first-order prediction leaves out: the bias of a\n# sample correlation over n_A points, by Gaussian Monte Carlo per cell,\n# y = x + N(0, v_s + v_e), E[cor(x, y)] minus the first-order value. In the\n# table above the candidates are the SAME 30 lines in every draw, so `jensen`\n# holds x fixed at gca_true and draws only the noise -- the design actually\n# measured. `jensen_random_x` redraws x ~ N(0, v_g) as well, the textbook\n# small-sample bias of a correlation between two random variables, which is\n# a different (larger) quantity and not the one the table is exposed to.\nset.seed(600)\nn_mc <- 4000\ncor_cols <- function(x, y) {\n  xc <- sweep(x, 2, colMeans(x)); yc <- sweep(y, 2, colMeans(y))\n  colSums(xc * yc) / sqrt(colSums(xc^2) * colSums(yc^2))\n}\njensen_mc <- function(x_of) vapply(seq_len(nrow(grid)), function(i) {\n  x <- x_of()\n  y <- x + matrix(stats::rnorm(n_A * n_mc, 0, sqrt(v_s[i] + v_e[i])), n_A)\n  mean(cor_cols(x, y)) - grid[[\"predicted\"]][i]\n}, numeric(1))\njensen <- jensen_mc(function() matrix(gca_true, n_A, n_mc))\njensen_random_x <- jensen_mc(function()\n  matrix(stats::rnorm(n_A * n_mc, 0, sqrt(var_gca_n1)), n_A))\nnames(jensen) <- names(jensen_random_x) <- paste0(\"t\", grid[[\"testers\"]], \"_r\", grid[[\"reps\"]])\njensen_max <- max(abs(jensen))\nfmt(rbind(fixed_candidates = c(jensen, max_abs = jensen_max),\n          random_x = c(jensen_random_x, max_abs = max(abs(jensen_random_x)))), 4)\n```\n\n::: {.cell-output-display}\n\n|                 |   t1_r1|   t2_r1|   t4_r1|   t8_r1|   t1_r4|   t2_r4|   t4_r4|   t8_r4| max_abs|\n|:----------------|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|\n|fixed_candidates | -0.0032|  0.0013| -0.0013|  0.0019| -0.0023|  0.0024|  0.0009|  0.0023|  0.0032|\n|random_x         | -0.0074| -0.0049| -0.0075| -0.0085| -0.0041| -0.0054| -0.0037| -0.0033|  0.0085|\n\n:::\n:::\n\n\nThe Jensen term for the design actually run (`fixed_candidates`, `gca_true`\nheld fixed at the 30 candidates) is at most 0.003 in\nabsolute value across the eight cells, small next to the accuracies themselves\n(0.39 to 0.92),\nwhich is what \"left uncorrected\" means quantitatively; `random_x` is the\nlarger, textbook small-sample bias of a correlation between two random\nvariables, shown only for contrast and not the quantity this chapter's\nstatistic carries.\n\nAccuracy rises with both, and the two arguments buy different things. More\nlocations shrink only the error term; more testers shrink the error term *and*\nthe SCA term, because a line's specific interactions with its testers average\nout. The table is 20 draws of the tester set and of the field error\nper cell; the corrected and the textbook predictions differ by at most\n0.007 here. `z` is the observed mean minus the corrected\nprediction in units of the standard error of that mean over the 20\ndraws; the largest `|z|` over the eight cells is 1.63 (it\nwould be 1.91 against the textbook form), so at\nthis replication the observed accuracies agree with the prediction. Each\n`observed_sd` is across tester sets and error draws, on a fixed set of\ncandidates: what a single testcross trial's ranking is worth depends on which\ntesters were drawn, not only on how many; with one tester at one location the\nspread across tester sets is\n0.35 of the\naccuracy itself.\n\nIn the scheme of Step 8 the testers are 2 individuals\nof the opposite pool and the trials have one location, which puts it in the\nlow-accuracy corner of this table. A real maize programme would use elite\ninbred testers and several locations; @hallauer2010 is the reference on the\nchoice of tester.\n\n## Step 7 -- Two traits, and what equal weighting assumes\n\n`corA` makes the traits genetically correlated, which is where selection stops\nbeing one-dimensional. This step uses an additive trait pair on its own founder\ndraw: index theory is written on breeding values, and the point being made\ndoes not need dominance.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(202)\nf2 <- quickHaplo(nInd = 80, nChr = 10, segSites = 100, inbred = TRUE)\nSP2 <- SimParam$new(f2)\nSP2$addTraitA(nQtlPerChr = 100, mean = c(10, 10), var = c(1, 4),\n              corA = matrix(c(1, -0.4, -0.4, 1), 2, 2))\nSP2$setVarE(h2 = c(0.6, 0.1))\n\nmt <- newPop(f2, simParam = SP2)\nfor (k in 1:3) mt <- randCross(mt, nCrosses = 1000, simParam = SP2)\nmt <- setPheno(mt, simParam = SP2)\n\nG <- varG(mt); P <- varP(mt); a2 <- c(1, 1)\nc(cor_genetic = stats::cov2cor(G)[2, 1],\n  cor_pheno   = stats::cov2cor(P)[2, 1],\n  h2_trait1   = as.numeric(diag(G)[1] / diag(P)[1]),\n  h2_trait2   = as.numeric(diag(G)[2] / diag(P)[2])) |> fmt(3)\n#> cor_genetic   cor_pheno   h2_trait1   h2_trait2 \n#>      -0.416      -0.084       0.470       0.072\n```\n:::\n\n\nThe genetic correlation lands near the requested `-0.4`; the phenotypic one is\nmuch weaker, because the environmental components were left uncorrelated\n(`SP$setCorE()` is where that would change). The two traits differ in variance\nand, sharply, in heritability -- the ordinary situation.\n\nThe book's pipeline defaults to `weights = NULL`, meaning equal weight on every\ntrait. Step 7 is where that default gets examined, using the index functions\n@sec-response introduced:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor_with_H <- function(w)\n  drop(crossprod(w, G %*% a2)) /\n    sqrt(drop(crossprod(w, P %*% w)) * drop(crossprod(a2, G %*% a2)))\n\nBw <- rbind(equal       = a2,\n            smith_hazel = index_smith_hazel(P, G, a2),\n            restricted  = index_restricted(P, G, a2, R = cbind(c(0, 1))))\n# expected response per unit selection intensity on the index I = b'x:\n# the vector of phenotypic differentials is S = i P b / sqrt(b'Pb), and the\n# multi-trait breeder's equation R = G P^-1 S gives R = i G b / sqrt(b'Pb)\ndG <- t(apply(Bw, 1, function(w) drop(G %*% w) / sqrt(drop(crossprod(w, P %*% w)))))\ncolnames(dG) <- c(\"gain_trait1\", \"gain_trait2\")\nidx_tab <- cbind(Bw, dG, aggregate = rowSums(dG),\n                 cor_with_H = apply(Bw, 1, cor_with_H))\nfmt(idx_tab)\n```\n\n::: {.cell-output-display}\n\n|            | Trait1| Trait2| gain_trait1| gain_trait2| aggregate| cor_with_H|\n|:-----------|------:|------:|-----------:|-----------:|---------:|----------:|\n|equal       | 1.0000| 1.0000|      0.0108|      0.3612|    0.3720|     0.2434|\n|smith_hazel | 0.0789| 0.0589|      0.0437|      0.3289|    0.3727|     0.2438|\n|restricted  | 0.1986| 0.0386|      0.3179|      0.0000|    0.3179|     0.2080|\n\n:::\n\n```{.r .cell-code}\nstopifnot(isTRUE(all.equal(idx_tab[, \"aggregate\"],\n                           idx_tab[, \"cor_with_H\"] * sqrt(drop(crossprod(a2, G %*% a2))),\n                           check.attributes = FALSE)))\n```\n:::\n\n\n`gain_trait1` and `gain_trait2` are the expected genetic change in each trait\nper unit of selection intensity on the index, `G b / sqrt(b' P b)`, and\n`aggregate` is their `a`-weighted sum -- which equals `cor_with_H` times the\nstandard deviation of the aggregate genotype, asserted. Three readings, in the\norder they matter:\n\n1. **Equal weights are not the Smith-Hazel solution.** Smith-Hazel puts\n   0.75 units of\n   weight on trait 2 for every unit on trait 1, not 1.00. The index is\n   `b = P^-1 G a` (@smith1936; @hazel1943), with no further structure, and\n   `b` is proportional to `a` if and only if `a` is an eigenvector of\n   `P^-1 G`. A sufficient condition is `G = c P` -- every trait with the same\n   heritability `c` and the genetic correlations equal to the phenotypic ones\n   -- which says nothing about the traits being equally variable or\n   uncorrelated: `index_smith_hazel()`'s help page gives a correlated-trait\n   pair (`G = I`, `P = [[2, 0.5], [0.5, 2]]`) for which equal weights are\n   exact. Here the heritabilities are\n   0.47 and 0.07\n   and the genetic and phenotypic correlations\n   -0.42 and -0.08,\n   so `G` is nowhere near a multiple of `P`, and the table shows that `(1, 1)`\n   is not an eigenvector of `P^-1 G`.\n2. **The cost on the objective is modest here; the composition of the gain is\n   not.** Equal weighting loses\n   0.2\n   percent of the attainable correlation with the aggregate genotype. But it\n   moves trait 1 by 0.011 per unit\n   intensity where Smith-Hazel moves it by\n   0.044,\n   4.1\n   times as much; both indices put most of the aggregate into trait 2, whose\n   variance is four times larger, and the weights decide how much trait 1\n   moves at all. An index that is nearly as good on the objective can still\n   land the gain somewhere else.\n3. **The restricted index holds trait 2 at exactly zero**, at a cost of\n   15\n   percent of the aggregate. That is Kempthorne and Nordskog's construction\n   (@kempthorne1959) and, as @sec-response argues, the classical ancestor of\n   this book's `alpha` constraint -- restrict a direction rather than price it.\n\nSmith-Hazel is defined as the weight vector maximising that correlation, so the\nclaim is checkable against a numerical optimum rather than taken on faith:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nopt <- stats::optim(c(1, 1), function(w) -cor_with_H(w), method = \"BFGS\")\nc(numerical = -opt$value, smith_hazel = cor_with_H(Bw[\"smith_hazel\", ]),\n  difference = abs(-opt$value - cor_with_H(Bw[\"smith_hazel\", ]))) |> fmt(10)\n#>   numerical smith_hazel  difference \n#>   0.2438417   0.2438417   0.0000000\n```\n:::\n\n\nMulti-trait genomic selection in wheat, balancing yield against protein content\nand quality, is the standing plant example -- @michel2019. In the hybrid scheme\nbelow only trait 1 enters the ranking; the second trait rides along in the\ncontract so that `stage2_select()` has an index to build.\n\n## Step 8 -- The parts assembled: reciprocal recurrent selection\n\nEverything above was one operation at a time. A breeding scheme is those\noperations in a loop, and the loop for two heterotic pools is reciprocal\nrecurrent selection: each pool is improved using the *other* pool as tester.\nDoubled-haploid lines are drawn from pool A, testcrossed to pool B (and vice\nversa), the testcross hybrids are phenotyped, and the lines with the best mean\ntestcross performance -- the GCA estimate of Step 6 -- are recombined to found\nthe next cycle's pool. Elite lines from both pools, at the end, are crossed\ndirectly to produce the commercial hybrids. It is exactly the asymmetry\n@sec-cycles argues for: selection happens on the hybrid, recycling happens\nwithin pool.\n\n### Founding two pools with a real coalescent history\n\nThis is the one place the chapter pays for `runMacs2()` rather than\n`quickHaplo()`. `AlphaSimR::runMacs2(..., split = )` draws founder haplotypes\nfrom a population-split coalescent history: one ancestral population, then two\ndemes of equal size that stopped exchanging migrants `split` generations ago,\nwith the first half of the sampled individuals from one deme and the second\nhalf from the other. That is the realistic analogue of `simulate_lines()`'s\nBalding-Nichols draw in @sec-simulating-crosses, and between-pool divergence\nis the entire subject of @sec-subdivided, so a stylised substitute would not do.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_split_draws <- 20   # founder draws per split time, below\nn_dh_gca      <- 10   # DH lines per founder for the GCA measurement, below\nfp <- alphasimr_founder_pools(rrs_cfg)\nfounder_geno <- pullSegSiteGeno(c(fp[[\"pop_A\"]], fp[[\"pop_B\"]]), simParam = fp[[\"SP\"]])\nc(pool_A = fp[[\"pop_A\"]]@nInd, pool_B = fp[[\"pop_B\"]]@nInd,\n  markers = ncol(founder_geno),\n  heterozygous_fraction = mean(founder_geno == 1),\n  gd_A = alphasimr_gd(fp[[\"pop_A\"]], fp[[\"SP\"]]),\n  gd_B = alphasimr_gd(fp[[\"pop_B\"]], fp[[\"SP\"]])) |> fmt(3)\n#>                pool_A                pool_B               markers \n#>                12.000                12.000               750.000 \n#> heterozygous_fraction                  gd_A                  gd_B \n#>                 0.236                 0.241                 0.211\n```\n:::\n\n\nReading `alphasimr_founder_pools()` against Steps 1 and 2, it is\n`runMacs2(nInd = , nChr = , segSites = , split = )` followed by\n`SP$addTraitAD(nQtlPerChr = seg_sites, meanDD = 0.4,\nvarDD = 0.1)` -- the same dominance model as Step 2 -- and\n`SP$setVarE(h2 = 0.4)`. Two things about it must be said\nbefore any number is read. **The founders are outbred**: `runMacs2()` is called\nwithout `inbred = TRUE`, so each pool is a sample of a random-mating\npopulation, heterozygous at the fraction of sites printed above, as an\nopen-pollinated maize population would be; the inbred lines of the scheme are\nmade from them by `makeDH()` inside each cycle. And there is no separate\nmarker panel: every one of the 150 segregating sites per\nchromosome is a QTL, so the sites that carry the trait are the ones\n`pullSegSiteGeno()` reads for `X`, `f` and `fL` throughout. `alphasimr_gd()`\nis `1 - mean(f)`, the exact definition `gene_diversity()` uses, computed from\nthat pull, so the two pools are already on the same scale as every diversity\nnumber in the rest of the book.\n\nBecause these founders come from MaCS, no number in the rest of this section\nis reproducible from its seed -- see Step 1: the founders move between runs,\nand everything below is computed from them. The chapter's response is to\nreplicate every Step 8 measurement over independent founder draws and report\nthe spread.\n\n**What `split` does.** The bridge's default is `split_gen = 100`.\nThe sweep below draws 20 independent founder sets at each of four split\ntimes and measures three things on each: the Caballero & Toro partition of\n@sec-subdivided over the two pools (`ct_partition()`, the general form of\n`gd_partition()`: the $F$-statistics of their Eq. 6 and the partition\n$GD_T = GD_{WI} + GD_{BI} + GD_{BS}$ of their Eq. 7, from which\n$F_{ST} = GD_{BS} / GD_T$ follows as an identity derived in @sec-subdivided,\nnot stated in the paper), the share of expected heterosis that the divergence\nterm carries (`heterosis_partition()`, @sec-heterosis), and -- the Step 6\nquestion with divergence -- how much of a DH line's exact GCA against the\nother pool's DH lines its own genetic value can see. For that last one,\n10 DH lines are drawn from every founder, the full factorial between\nthe two DH sets is made, and the GCA of each pool-A line is split into its\nadditive and dominance parts with `heterosis_gca_sca()`; the identity behind\nthat split was asserted in Step 6. The chunk also records, per draw, an\nascertainment bookkeeping that the reading of `GD_T` will need: the fraction\nof sites monomorphic within each pool, the fraction fixed for opposite\nalleles in the two pools, and the part of `GD_T` those sites carry.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsplit_draw <- function(split, seed) {\n  cfg <- utils::modifyList(rrs_cfg, list(split_gen = split, seed = seed))\n  fp_s <- alphasimr_founder_pools(cfg)\n  SP_s <- fp_s[[\"SP\"]]\n  pool <- rep(c(\"A\", \"B\"), c(cfg[[\"n_pool_A\"]], cfg[[\"n_pool_B\"]]))\n  geno <- pullSegSiteGeno(c(fp_s[[\"pop_A\"]], fp_s[[\"pop_B\"]]), simParam = SP_s)\n  ct   <- ct_partition(geno, pool)\n  pA_s <- colMeans(geno[pool == \"A\", ]) / 2\n  pB_s <- colMeans(geno[pool == \"B\", ]) / 2\n  d_s  <- SP_s$traits[[1]]@domEff\n  a_s  <- SP_s$traits[[1]]@addEff\n  hp   <- heterosis_partition(pA_s, pB_s, d_s)\n  # Ascertainment: runMacs2() returns sites that segregate in the POOLED\n  # sample, so a site fixed for different alleles in the two pools is kept\n  # and, with equal pool sizes, sits at pooled frequency 1/2 -- the maximum\n  # of 2 p q. GD_T = mean 2 pbar qbar exactly (census weights, equal sizes),\n  # so it splits into the part those fixed differences carry and the rest.\n  mono_A <- pA_s %in% c(0, 1)\n  mono_B <- pB_s %in% c(0, 1)\n  fixed  <- mono_A & mono_B & (pA_s != pB_s)\n  pbar_s <- (pA_s + pB_s) / 2\n  h_s    <- 2 * pbar_s * (1 - pbar_s)\n  stopifnot(isTRUE(all.equal(ct[[\"diversity\"]][[\"GD_T\"]], mean(h_s))))\n  set.seed(seed)\n  dh_A <- makeDH(fp_s[[\"pop_A\"]], nDH = n_dh_gca, simParam = SP_s)\n  dh_B <- makeDH(fp_s[[\"pop_B\"]], nDH = n_dh_gca, simParam = SP_s)\n  hyb  <- hybridCross(dh_A, dh_B, crossPlan = \"testcross\", simParam = SP_s)\n  gca  <- tapply(gv(hyb)[, 1], hyb@mother, mean)[dh_A@id] - as.numeric(meanG(hyb))[1]\n  U_s  <- pullQtlGeno(dh_A, simParam = SP_s) / 2\n  hg   <- heterosis_gca_sca(U_s, pullQtlGeno(dh_B, simParam = SP_s) / 2, d_s)\n  # GCA = additive part + dominance part (the Step 6 identity), so its\n  # variance is var(add) + var(dom) + 2 cov(add, dom): three terms, not two.\n  gca_add <- as.numeric(sweep(U_s, 2, colMeans(U_s)) %*% a_s)\n  gca_dom <- as.numeric(hg[[\"gca_A\"]])\n  stopifnot(isTRUE(all.equal(as.numeric(gca), gca_add + gca_dom)))\n  data.frame(split = split, seed = seed,\n             F_ST  = ct[[\"global\"]][[\"F_ST\"]],\n             GD_T  = ct[[\"diversity\"]][[\"GD_T\"]],\n             GD_BS = ct[[\"diversity\"]][[\"GD_BS\"]],\n             mono_A = mean(mono_A), mono_B = mean(mono_B),\n             fixed_diff = mean(fixed),\n             GD_T_fixed = sum(h_s[fixed]) / length(h_s),\n             GD_T_other = sum(h_s[!fixed]) / length(h_s),\n             maf_pooled = mean(pmin(pbar_s, 1 - pbar_s)),\n             heterosis_divergence_share = hp[[\"divergence\"]] / hp[[\"total\"]],\n             GCA_var = stats::var(gca),\n             GCA_var_add = stats::var(gca_add),\n             GCA_var_dom = stats::var(gca_dom),\n             GCA_cov2 = 2 * stats::cov(gca_add, gca_dom),\n             GCA_dominance_share = stats::var(gca_dom) / stats::var(gca),\n             cor_perse_GCA = stats::cor(gv(dh_A)[, 1], gca))\n}\nsplits <- c(0, 10, 100, 1000)\nsw <- do.call(rbind, lapply(splits, function(s)\n  do.call(rbind, lapply(seq_len(n_split_draws), function(r)\n    split_draw(s, seed = 100 * s + r)))))\nsw_mean <- aggregate(sw[, -(1:2)], by = list(split = sw[[\"split\"]]), FUN = mean)\nsw_sd   <- aggregate(sw[, -(1:2)], by = list(split = sw[[\"split\"]]), FUN = stats::sd)\nrownames(sw_mean) <- rownames(sw_sd) <- paste0(\"split_\", sw_mean[[\"split\"]])\ncols_div <- c(\"split\", \"F_ST\", \"GD_T\", \"GD_BS\", \"heterosis_divergence_share\")\ncols_asc <- c(\"split\", \"GD_T\", \"mono_A\", \"mono_B\", \"fixed_diff\", \"GD_T_fixed\",\n              \"GD_T_other\", \"maf_pooled\")\ncols_gca <- c(\"split\", \"GCA_var\", \"GCA_var_add\", \"GCA_var_dom\", \"GCA_cov2\",\n              \"GCA_dominance_share\", \"cor_perse_GCA\")\nfmt(sw_mean[, cols_div], 3)\n```\n\n::: {.cell-output-display}\n\n|           | split|  F_ST|  GD_T| GD_BS| heterosis_divergence_share|\n|:----------|-----:|-----:|-----:|-----:|--------------------------:|\n|split_0    |     0| 0.022| 0.312| 0.007|                      0.021|\n|split_10   |    10| 0.047| 0.309| 0.015|                      0.045|\n|split_100  |   100| 0.259| 0.298| 0.077|                      0.203|\n|split_1000 |  1000| 0.561| 0.331| 0.186|                      0.358|\n\n:::\n\n```{.r .cell-code}\nfmt(sw_sd[, cols_div], 3)\n```\n\n::: {.cell-output-display}\n\n|           | split|  F_ST|  GD_T| GD_BS| heterosis_divergence_share|\n|:----------|-----:|-----:|-----:|-----:|--------------------------:|\n|split_0    |     0| 0.003| 0.005| 0.001|                      0.002|\n|split_10   |    10| 0.005| 0.007| 0.002|                      0.005|\n|split_100  |   100| 0.013| 0.005| 0.004|                      0.008|\n|split_1000 |  1000| 0.015| 0.005| 0.007|                      0.009|\n\n:::\n\n```{.r .cell-code}\nfmt(sw_mean[, cols_asc], 3)\n```\n\n::: {.cell-output-display}\n\n|           | split|  GD_T| mono_A| mono_B| fixed_diff| GD_T_fixed| GD_T_other| maf_pooled|\n|:----------|-----:|-----:|------:|------:|----------:|----------:|----------:|----------:|\n|split_0    |     0| 0.312|  0.069|  0.072|      0.000|      0.000|      0.312|      0.230|\n|split_10   |    10| 0.309|  0.107|  0.104|      0.000|      0.000|      0.309|      0.229|\n|split_100  |   100| 0.298|  0.326|  0.318|      0.008|      0.004|      0.295|      0.219|\n|split_1000 |  1000| 0.331|  0.564|  0.548|      0.179|      0.090|      0.241|      0.265|\n\n:::\n\n```{.r .cell-code}\nfmt(sw_mean[, cols_gca], 3)\n```\n\n::: {.cell-output-display}\n\n|           | split| GCA_var| GCA_var_add| GCA_var_dom| GCA_cov2| GCA_dominance_share| cor_perse_GCA|\n|:----------|-----:|-------:|-----------:|-----------:|--------:|-------------------:|-------------:|\n|split_0    |     0|   0.548|       0.500|       0.052|   -0.003|               0.093|         0.954|\n|split_10   |    10|   0.536|       0.484|       0.065|   -0.014|               0.113|         0.943|\n|split_100  |   100|   0.339|       0.301|       0.046|   -0.009|               0.145|         0.928|\n|split_1000 |  1000|   0.236|       0.202|       0.047|   -0.012|               0.203|         0.896|\n\n:::\n\n```{.r .cell-code}\nfmt(sw_sd[, cols_gca], 3)\n```\n\n::: {.cell-output-display}\n\n|           | split| GCA_var| GCA_var_add| GCA_var_dom| GCA_cov2| GCA_dominance_share| cor_perse_GCA|\n|:----------|-----:|-------:|-----------:|-----------:|--------:|-------------------:|-------------:|\n|split_0    |     0|   0.123|       0.130|       0.020|    0.066|               0.028|         0.014|\n|split_10   |    10|   0.186|       0.148|       0.053|    0.057|               0.051|         0.027|\n|split_100  |   100|   0.172|       0.151|       0.025|    0.057|               0.053|         0.028|\n|split_1000 |  1000|   0.136|       0.120|       0.039|    0.045|               0.079|         0.040|\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# the contrast between the two extreme split times, for the two GCA columns\ncontrast <- function(m) {\n  x <- sw[[m]][sw[[\"split\"]] == max(splits)]\n  y <- sw[[m]][sw[[\"split\"]] == min(splits)]\n  se <- sqrt(stats::var(x) / length(x) + stats::var(y) / length(y))\n  c(at_split_max = mean(x), at_split_0 = mean(y), difference = mean(x) - mean(y),\n    se = se, t = (mean(x) - mean(y)) / se)\n}\nctr <- rbind(GCA_dominance_share = contrast(\"GCA_dominance_share\"),\n             cor_perse_GCA       = contrast(\"cor_perse_GCA\"))\nfmt(ctr, 3)\n```\n\n::: {.cell-output-display}\n\n|                    | at_split_max| at_split_0| difference|    se|      t|\n|:-------------------|------------:|----------:|----------:|-----:|------:|\n|GCA_dominance_share |        0.203|      0.093|      0.109| 0.019|  5.851|\n|cor_perse_GCA       |        0.896|      0.954|     -0.058| 0.009| -6.098|\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nRead the first two tables together: the first is the mean over the\n20 draws, the second their standard deviation. What was\nmeasured: `F_ST` rises from 0.022 at\n`split = 0` to 0.561 at `split = 1000`,\nand `GD_BS` from 0.007 to\n0.186, each step many standard\ndeviations wide; the divergence share of expected heterosis rises from\n0.021 to\n0.358. `GD_T` does\nnot stay flat: it is 0.312 at `split = 0`,\n0.298 at `split = 100` and\n0.331 at `split = 1000`, and the rise\nfrom `split = 100` to `split = 1000`,\n0.033, is\n20\nstandard errors at this replication. The third table is the bookkeeping\nbehind that rise. Across the same range the fraction of sites monomorphic\nwithin pool A goes from 0.069 to\n0.564 (pool B:\n0.072 to\n0.548), the fraction of sites fixed for\nopposite alleles in the two pools from\n0 to\n0.179, the part of `GD_T` those\nsites carry (`GD_T_fixed`) from 0\nto 0.09, and the part carried by\nevery other site (`GD_T_other`) falls from\n0.312 to\n0.241.\n\nWhat is inferred from those three tables: `runMacs2()` returns the sites that\nsegregate in the *pooled* sample of the two demes, so a site fixed for\nopposite alleles in the two pools is kept and, with equal pool sizes, sits at\npooled frequency one half -- the maximum of $2\\bar p \\bar q$, which is exactly\nwhat `GD_T` averages over sites (asserted in the chunk). The rise in `GD_T`\ntherefore comes entirely from sites fixed for opposite alleles, an\nascertainment effect of how the founder sites are sampled, while diversity at\nevery other site falls with divergence. At those other sites the reading is\nthe one @sec-heterosis gives for expected heterosis: drift moves diversity\nfrom within pools to between them and does not create it. How much of `GD_T`\na marker panel shows under divergence therefore depends on how its sites were\nascertained, which is a property of the panel and not of the pools.\n\nThe fourth and fifth tables are the combining-ability side, mean and standard\ndeviation, and the sixth is the contrast between the two extreme split times,\nunpaired because the draws are independent. GCA is the sum of its additive and\ndominance parts (asserted in the chunk), so its variance is\n$\\mathrm{var}(\\mathrm{add}) + \\mathrm{var}(\\mathrm{dom}) + 2\\,\\mathrm{cov}(\\mathrm{add}, \\mathrm{dom})$,\nthree terms. What was measured, from `split = 0` to `split = 1000`: `GCA_var`\ngoes from 0.548 to\n0.236, `GCA_var_add` from\n0.5 to\n0.202, `GCA_var_dom` from\n0.052 to\n0.047, and `GCA_cov2`\n($2\\,\\mathrm{cov}$) from -0.003 to\n-0.012, the last with between-draw\nstandard deviations of 0.066 and\n0.045, so at every split it is within\n1.2 standard errors of zero. The ratio\n`GCA_dominance_share` $= \\mathrm{var}(\\mathrm{dom}) / \\mathrm{var}(\\mathrm{GCA})$\nrises from 0.093 to\n0.203\n(`t = 5.9`). Which part drives it:\nholding the dominance part at its `split = 0` value and moving only the\nadditive part to its `split = 1000` value gives a ratio of\n0.206; holding the additive part and moving only the\ndominance part gives 0.086. And the per\nse-versus-GCA correlation falls from 0.954\nto 0.896\n(`t = -6.1`). Both correlations are below the\n0.997 of Step 6's undifferentiated\nhalves, but that comparison crosses a change of founders, trait draw and\nline number, so the within-sweep contrast is the one that isolates `split`.\n\nWhat is inferred: in this render the\nfall of the *additive* part of the GCA variance accounts for more of the rise in the ratio than the growth of the dominance part;\nthe additive part falls with divergence because the sites that fix within a\npool stop contributing to it, so the ratio can rise without the dominance\npart growing at all. The ratio is a partition of $\\mathrm{var}(\\mathrm{GCA})$\nonly insofar as the covariance term is negligible; here that term is within\n1.2 standard errors of zero at every split, which is the\nonly sense in which \"share\" is used. As the pools separate, the dominance\nweights $(1 - 2 p_{Bk})$ of Step 6 move away from zero and a growing part of\na line's combining ability is invisible to its own genetic value; the evidence\nfor that at this scale is the `t` of the contrast, and nothing here separates\nhow much of the between-draw spread is the trait drawn with each founder set\nand how much is the DH sampling. The limit of the inference is the scale:\n12 individuals per pool,\n750 sites, 20\ndraws per split, and a `split` in coalescent generations that is not\ncalibrated to any named heterotic-pool pair. The direction transfers; the\nnumbers do not.\n\n### One cycle\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(11)\ncy1 <- alphasimr_rrs_cycle(fp[[\"pop_A\"]], fp[[\"pop_B\"]], fp[[\"SP\"]], rrs_cfg)\nfmt(cy1[[\"summary\"]], 4)\n```\n\n::: {.cell-output-display}\n\n| mean_tc_A| mean_tc_B|   gd_A|   gd_B|\n|---------:|---------:|------:|------:|\n|    3.1398|    2.6712| 0.2048| 0.1868|\n\n:::\n:::\n\n\n`alphasimr_rrs_cycle()` runs the same six steps for each pool, symmetrically\n(pool A tested on B, pool B tested on A), and every one is a primitive from\nabove:\n\n1. **Double haploids** (Step 5). `makeDH()` draws 3 fully\n   homozygous lines from *each* individual in the current pool -- at book scale,\n   12 parents x 3 DH each =\n   36 DH lines per pool, per cycle.\n   Because the pool is outbred, the DH lines from one parent differ from each\n   other: this is the lottery of Step 4, drawn one generation earlier than in\n   a line programme.\n2. **Pick reciprocal testers.** The first 2 individuals\n   of the *current* opposite pool are used as testers -- an arbitrary slice by\n   index, not a random or merit-based draw, outbred individuals rather than\n   inbred lines, and a different set each cycle because step 6 recreates the\n   pool. This is the RRS-defining move: a line's value is judged by its cross onto the other\n   heterotic pool, not by itself.\n3. **Testcross and phenotype** (Step 6). `hybridCross()` forms the full\n   factorial between every DH line and every tester --\n   36 DH x 2\n   testers = 72\n   testcross hybrids per pool -- and `setPheno()` adds phenotyping error sized\n   to the heritability set by `SP$setVarE(h2 = )`, at one location.\n4. **GCA estimate** (Step 6). Testcross phenotypes are grouped by DH-line\n   parent (`tapply(pheno[, 1], mother, mean)`) and averaged across the\n   2 testers each line was crossed to. Only trait 1 is\n   used for this ranking even though this chapter's config simulates\n   2 traits per line; the second trait rides along in\n   `X`/`hybrids` but plays no role in selection here. Step 7 is what it would\n   take to use both.\n5. **Keep the elites** (Step 6). The 6 DH lines per pool\n   with the highest mean testcross phenotype are kept as `elite_A`/`elite_B`.\n6. **Recombine** (Step 5). `randCross()` random-mates the elites back up to\n   12 individuals, founding the next cycle's pool A\n   (symmetrically for B).\n\n`elite_A`/`elite_B` are what step 6 mates -- and, in the *last* cycle, what\nthe final commercial cross uses instead of being recombined again. The cycle's\n`summary` mixes two different populations on purpose: `mean_tc_A`/`mean_tc_B`\naverage over *all* DH lines tested that cycle (the population's testcross\nperformance before selection), while `gd_A`/`gd_B` are gene diversity of only\nthe 6 surviving elites (the population after selection).\nThat asymmetry is exactly what the next section plots -- response measured\npre-selection, diversity measured post-selection.\n\n### The trajectory across cycles, replicated, against a paired control\n\n`alphasimr_pipeline()` runs `alphasimr_rrs_cycle()` in a loop for\n4 cycles, carrying `pop_A`/`pop_B` forward from one\ncycle's output to the next's input. Only the *last* cycle's\n`elite_A`/`elite_B` go on to found the commercial hybrid pool; every earlier\ncycle's elites are spent entirely on `randCross()`ing the next cycle's pool.\n\nOne run of that loop is an anecdote, and it would be an anecdote about one\nfounder draw. The loop is written out here instead, so that three things can\nbe added to it: a **paired no-selection control** (`random_elite = TRUE`,\nwhich draws the elites at random and leaves every other operation -- the DH\nlines, the testcrosses, the recombination -- identical, so the difference\nbetween the two arms is selection and nothing else), the between-pool\npartition of the *recombined* pools each cycle, and the genetic value of the\nactual product, the elite factorial.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrun_rrs <- function(fp, cfg, random_elite = FALSE, seed = 1) {\n  set.seed(seed)\n  SP_r  <- fp[[\"SP\"]]\n  pop_A <- fp[[\"pop_A\"]]; pop_B <- fp[[\"pop_B\"]]\n  pool  <- rep(c(\"A\", \"B\"), c(cfg[[\"n_pool_A\"]], cfg[[\"n_pool_B\"]]))\n  pools_row <- function(pop_A, pop_B) {\n    ct <- ct_partition(pullSegSiteGeno(c(pop_A, pop_B), simParam = SP_r), pool)\n    data.frame(gd_pool_A = alphasimr_gd(pop_A, SP_r),\n               gd_pool_B = alphasimr_gd(pop_B, SP_r),\n               GD_BS = ct[[\"diversity\"]][[\"GD_BS\"]],\n               F_ST  = ct[[\"global\"]][[\"F_ST\"]])\n  }\n  rows <- list(cbind(cycle = 0, mean_tc_A = NA, mean_tc_B = NA, gd_A = NA, gd_B = NA,\n                     hybrid_meanG = NA, pools_row(pop_A, pop_B)))\n  for (i in seq_len(cfg[[\"n_cycles\"]])) {\n    cy <- alphasimr_rrs_cycle(pop_A, pop_B, SP_r, cfg, random_elite = random_elite)\n    pop_A <- cy[[\"pop_A\"]]; pop_B <- cy[[\"pop_B\"]]\n    prod  <- hybridCross(cy[[\"elite_A\"]], cy[[\"elite_B\"]], crossPlan = \"testcross\",\n                         simParam = SP_r)\n    rows[[i + 1]] <- cbind(cycle = i, cy[[\"summary\"]],\n                           hybrid_meanG = as.numeric(meanG(prod))[1],   # trait 1\n                           pools_row(pop_A, pop_B))\n  }\n  do.call(rbind, rows)\n}\n\nn_rep <- 48\narms <- lapply(seq_len(n_rep), function(s) {\n  fp_s <- alphasimr_founder_pools(utils::modifyList(rrs_cfg, list(seed = s)))\n  list(sel = run_rrs(fp_s, rrs_cfg, random_elite = FALSE, seed = s),\n       ctl = run_rrs(fp_s, rrs_cfg, random_elite = TRUE,  seed = s))\n})\n# pairing check: cycle 1 is identical between arms up to the elite pick\nstopifnot(all(vapply(arms, function(a)\n  isTRUE(all.equal(a[[\"sel\"]][c(\"mean_tc_A\", \"mean_tc_B\")][2, ],\n                   a[[\"ctl\"]][c(\"mean_tc_A\", \"mean_tc_B\")][2, ])), logical(1))))\n```\n:::\n\n\n48 founder draws; each drawn once and both arms branched off it, with\nthe same seed set before each arm so that cycle 1's DH lines and testcross\nphenotypes are identical between arms (asserted) and the two only diverge at\nthe selection step. The first replicate's selected arm, cycle by cycle:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfmt(arms[[1]][[\"sel\"]], 3)\n```\n\n::: {.cell-output-display}\n\n| cycle| mean_tc_A| mean_tc_B|  gd_A|  gd_B| hybrid_meanG| gd_pool_A| gd_pool_B| GD_BS|  F_ST|\n|-----:|---------:|---------:|-----:|-----:|------------:|---------:|---------:|-----:|-----:|\n|     0|        NA|        NA|    NA|    NA|           NA|     0.222|     0.218| 0.074| 0.252|\n|     1|     1.236|     1.397| 0.164| 0.198|        1.903|     0.161|     0.198| 0.095| 0.345|\n|     2|     1.906|     1.813| 0.125| 0.127|        2.443|     0.123|     0.125| 0.120| 0.492|\n|     3|     2.206|     2.447| 0.099| 0.114|        2.618|     0.099|     0.113| 0.133| 0.555|\n|     4|     2.739|     2.737| 0.086| 0.088|        2.701|     0.085|     0.090| 0.142| 0.619|\n\n:::\n:::\n\n\n`gd_pool_A`/`gd_pool_B` are the gene diversity of the recombined pools that\nenter the next cycle, on the same `1 - mean(f)` scale as the elites' `gd_A`/\n`gd_B`; `GD_BS` and `F_ST` are the between-pool components of those two pools;\n`hybrid_meanG` is the mean genetic value of the 6 x\n6 elite factorial, the product the cycle would sell. All\nof them, over all replicates, at the last cycle, selected minus control:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlast <- rrs_cfg[[\"n_cycles\"]] + 1\n# The two pools are exchangeable by design, so their mean is a legitimate\n# pooled statistic; how much noise it removes is measured below (pool_tab).\narms <- lapply(arms, function(a) lapply(a, function(x) {\n  x[[\"gd_elite_mean\"]] <- (x[[\"gd_A\"]] + x[[\"gd_B\"]]) / 2\n  x[[\"gd_pool_mean\"]]  <- (x[[\"gd_pool_A\"]] + x[[\"gd_pool_B\"]]) / 2\n  x\n}))\nmetrics <- c(\"mean_tc_A\", \"mean_tc_B\", \"hybrid_meanG\", \"gd_A\", \"gd_B\",\n             \"gd_elite_mean\", \"gd_pool_A\", \"gd_pool_B\", \"gd_pool_mean\",\n             \"GD_BS\", \"F_ST\")\narm_last <- function(arm, m) vapply(arms, function(a) a[[arm]][[m]][last], numeric(1))\ndiffs    <- function(m) arm_last(\"sel\", m) - arm_last(\"ctl\", m)   # one per founder draw\npaired <- function(m) {\n  dd <- diffs(m)\n  c(selected = mean(arm_last(\"sel\", m)), control = mean(arm_last(\"ctl\", m)),\n    diff_mean = mean(dd), diff_sd = stats::sd(dd),\n    t = mean(dd) / (stats::sd(dd) / sqrt(length(dd))))\n}\nrep_tab  <- t(sapply(metrics, paired))\nt_paired <- rep_tab[, \"t\"]                       # named: t_paired[[\"gd_elite_mean\"]]\nt_crit   <- stats::qt(0.975, df = n_rep - 1)\nsig_paired <- abs(t_paired) > t_crit             # named logical, same names\nfmt(rep_tab, 3)\n```\n\n::: {.cell-output-display}\n\n|              | selected| control| diff_mean| diff_sd|      t|\n|:-------------|--------:|-------:|---------:|-------:|------:|\n|mean_tc_A     |    4.344|   2.073|     2.271|   1.235| 12.744|\n|mean_tc_B     |    4.321|   2.204|     2.118|   1.152| 12.733|\n|hybrid_meanG  |    4.888|   2.087|     2.801|   1.300| 14.929|\n|gd_A          |    0.097|   0.111|    -0.014|   0.024| -3.885|\n|gd_B          |    0.095|   0.111|    -0.015|   0.022| -4.752|\n|gd_elite_mean |    0.096|   0.111|    -0.015|   0.018| -5.522|\n|gd_pool_A     |    0.096|   0.110|    -0.013|   0.025| -3.753|\n|gd_pool_B     |    0.095|   0.110|    -0.015|   0.022| -4.829|\n|gd_pool_mean  |    0.096|   0.110|    -0.014|   0.018| -5.532|\n|GD_BS         |    0.145|   0.132|     0.013|   0.014|  6.665|\n|F_ST          |    0.603|   0.546|     0.057|   0.062|  6.392|\n\n:::\n\n```{.r .cell-code}\n# Pooling the two pools halves the variance only if their paired differences\n# are uncorrelated across founder draws: measured, not assumed.\npool_pair <- function(mA, mB) {\n  dA <- diffs(mA); dB <- diffs(mB)\n  c(cor_AB = stats::cor(dA, dB), sd_A = stats::sd(dA), sd_B = stats::sd(dB),\n    sd_pooled = stats::sd((dA + dB) / 2),\n    sd_if_independent = sqrt((stats::var(dA) + stats::var(dB)) / 4))\n}\npool_tab <- rbind(gd_elite = pool_pair(\"gd_A\", \"gd_B\"),\n                  gd_pool  = pool_pair(\"gd_pool_A\", \"gd_pool_B\"),\n                  mean_tc  = pool_pair(\"mean_tc_A\", \"mean_tc_B\"))\nfmt(pool_tab, 3)\n```\n\n::: {.cell-output-display}\n\n|         | cor_AB|  sd_A|  sd_B| sd_pooled| sd_if_independent|\n|:--------|------:|-----:|-----:|---------:|-----------------:|\n|gd_elite |  0.213| 0.024| 0.022|     0.018|             0.017|\n|gd_pool  |  0.182| 0.025| 0.022|     0.018|             0.017|\n|mean_tc  |  0.903| 1.235| 1.152|     1.164|             0.844|\n\n:::\n\n```{.r .cell-code}\nstopifnot(isTRUE(all.equal(pool_tab[\"gd_elite\", \"sd_pooled\"],\n                           rep_tab[\"gd_elite_mean\", \"diff_sd\"])))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nloss <- function(arm, m) vapply(arms, function(a)\n  (a[[arm]][[m]][1] - a[[arm]][[m]][last]) / a[[arm]][[m]][1], numeric(1))\nloss_tab <- rbind(\n  `pool A, selected` = c(mean = mean(loss(\"sel\", \"gd_pool_A\")), sd = stats::sd(loss(\"sel\", \"gd_pool_A\"))),\n  `pool A, control`  = c(mean = mean(loss(\"ctl\", \"gd_pool_A\")), sd = stats::sd(loss(\"ctl\", \"gd_pool_A\"))),\n  `pool B, selected` = c(mean = mean(loss(\"sel\", \"gd_pool_B\")), sd = stats::sd(loss(\"sel\", \"gd_pool_B\"))),\n  `pool B, control`  = c(mean = mean(loss(\"ctl\", \"gd_pool_B\")), sd = stats::sd(loss(\"ctl\", \"gd_pool_B\"))))\nfmt(loss_tab, 3)\n```\n\n::: {.cell-output-display}\n\n|                 |  mean|    sd|\n|:----------------|-----:|-----:|\n|pool A, selected | 0.564| 0.072|\n|pool A, control  | 0.504| 0.066|\n|pool B, selected | 0.567| 0.073|\n|pool B, control  | 0.497| 0.062|\n\n:::\n\n```{.r .cell-code}\nfig_cap <- paste0(\"Reciprocal recurrent selection over \", rrs_cfg[[\"n_cycles\"]],\n  \" cycles at book scale, \", n_rep, \" founder draws, selection (solid) against \",\n  \"the paired no-selection control (dashed); points are means over draws and \",\n  \"bars one standard deviation. Left: mean testcross phenotype per pool, \",\n  \"measured on all DH lines tested that cycle. Right: gene diversity of the \",\n  \"elite lines retained each cycle.\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Reciprocal recurrent selection over 4 cycles at book scale, 48 founder draws, selection (solid) against the paired no-selection control (dashed); points are means over draws and bars one standard deviation. Left: mean testcross phenotype per pool, measured on all DH lines tested that cycle. Right: gene diversity of the elite lines retained each cycle.](04c-alphasimr-pipeline_files/figure-typst/fig-alphasimr-cycles-1.svg){#fig-alphasimr-cycles fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nWhat was measured (@fig-alphasimr-cycles and the tables): over 48\npaired replicates, the selected arm's mean testcross phenotype at cycle\n4 differs from the control's by\n+2.27 (pool A) and\n+2.12 (pool B) trait units, with paired\nstandard deviations of 1.23 and\n1.15; the elite factorial's genetic\nvalue -- the product -- differs by +2.80\n(`t = 14.9`). Gene diversity of the elite\nlines, averaged over the two pools, differs by\n-0.015 (paired s.d.\n0.018, `t = -5.5`),\nand that of the recombined pools by\n-0.014 (`t = -5.5`).\nBetween the pools, `GD_BS` differs by +0.013\n(`t = 6.7`) and `F_ST` by\n+0.057 (`t = 6.4`).\nThe two-sided 5% point of `t` with 47 degrees of freedom is\n2.01. Against it, in this render, the response -- both pools\nand the product --\nis beyond it;\nthe pooled elite-line gene-diversity difference\nis beyond it; the pooled\nrecombined-pool difference\nis beyond it; the `GD_BS`\ndifference is beyond it; the\n`F_ST` difference is beyond it.\n\nPooling the two pools' differences is not free noise reduction, and\n`pool_tab` measures what it buys. Averaging halves the variance only if the\ntwo pools' paired differences are independent across founder draws. For the\nelite-line gene diversity they are correlated at\n0.21, and the pooled standard deviation,\n0.018, is close to the\n0.017 it would be if they were\nindependent: pooling does what it should there. For the testcross mean they\nare correlated at 0.9, and the pooled\nstandard deviation is 1.16 against\n0.84 if independent: pooling\ndoes not reduce that noise, because the founder draw moves both pools'\nresponse together. The per-pool rows are there to show the asymmetry between\ntwo exchangeable pools that any one set of 48 draws produces. The loss\ntable says how much of the pools' loss is selection: the control loses gene\ndiversity too -- 6 elites recombined into\n12 individuals is a bottleneck whether or not the\nelites were chosen -- and the selected arm's mean loss\nexceeds\nthe control's, with the pooled `t` just stated as the evidence.\n\nWhat is inferred: with real meiosis and a dominance trait behind it,\nreciprocal recurrent selection responds in both pools, and at this\nreplication the response\nis beyond\n`t_crit`. Whether it spends within-pool diversity faster than the same\nbottleneck under drift alone is what the pooled gene-diversity `t` decides,\nand in this render it does for\nthe elite lines and does for the\nrecombined pools: the selection component of the loss is of the same order as\nits paired standard deviation at this scale, so the conclusion, not only the\nnumber, is what the `t` decides. Where the sign holds, the control isolates\nthat component from the drift part, which is the distinction @sec-cycles\ndraws with the package's own faster simulator over a longer trajectory and a\ngrid of selection intensities, and @sec-programme draws a third time in an\ninbred-line programme. The between-pool rows: the `GD_BS` difference\nis beyond `t_crit`; where it is, and positive, RRS is\nmoving the pools apart faster than drift does, which is what a scheme\nselecting on the cross is expected to do. `F_ST` rises partly because `GD_T`\nfalls, so `GD_BS` is the row to read. What limits the inference is the scale\n-- 12 founders per pool, 4\ncycles, 2 testers at one location, 48 draws\n-- and the fact that the founders come from MaCS, so both the numbers in this\nparagraph and any verdict that rests on a `t` near `t_crit` may differ\nbetween renders.\n\n### The final hybrid pool through `stage2_select()`, unchanged\n\n`alphasimr_pipeline()` is the loop above without the instrumentation: founders,\n4 cycles, then `alphasimr_make_hybrids()` testcrosses\nthe final cycle's elites directly against each other -- a full factorial\nbetween the 6 pool-A elites and 6\npool-B elites, so 36 commercial\nhybrids -- and phenotypes them the same way every testcross in this chapter\nwas phenotyped. `alphasimr_to_stage1()` then does the bookkeeping that makes\nthis look like any other stage-1 output: it remaps AlphaSimR's internal line\nids into the `1..n_A`, `n_A+1..n_A+n_B` convention `hybrids$line_A`/`line_B`\nand `fL` use elsewhere in the book, and builds `fL` by stacking the elite lines\nfrom *both* pools' genotypes into one matrix and computing a single joint\ncoancestry matrix over all of them -- not two separate per-pool matrices --\nwhich is what lets `theta_pools()` and the rest of the pipeline index into pool\nA and pool B lines with one consistent numbering.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nres <- alphasimr_pipeline(rrs_cfg)\nfmt(res[[\"cycles\"]], 4)\n```\n\n::: {.cell-output-display}\n\n| cycle| mean_tc_A| mean_tc_B|   gd_A|   gd_B|\n|-----:|---------:|---------:|------:|------:|\n|     1|    2.1860|    2.5263| 0.1883| 0.1921|\n|     2|    3.7326|    3.6370| 0.1592| 0.1628|\n|     3|    4.7096|    4.8402| 0.0981| 0.1494|\n|     4|    5.5944|    5.9414| 0.0637| 0.1227|\n\n:::\n\n```{.r .cell-code}\nst1 <- res[[\"stage1\"]]\ndim(st1[[\"X\"]])\n#> [1]  36 750\nsel <- stage2_select(st1[[\"X\"]], st1[[\"f\"]], st1[[\"hybrids\"]], n_sel = 8, fL = st1[[\"fL\"]],\n                     verbose = FALSE)\nfmt(sel[[\"metrics\"]][, c(\"scenario\", \"alpha\", \"GD\", \"GD_BS\", \"F_ST\", \"index\")], 4)\n```\n\n::: {.cell-output-display}\n\n|scenario       |   alpha|     GD|  GD_BS|   F_ST|  index|\n|:--------------|-------:|------:|------:|------:|------:|\n|DE_alpha_0.00  | -0.0090| 0.2486| 0.1666| 0.6703| 1.1926|\n|DE_alpha_-0.22 | -0.0090| 0.2486| 0.1666| 0.6703| 1.1926|\n|DE_alpha_-0.45 | -0.0090| 0.2486| 0.1666| 0.6703| 1.1926|\n|DE_alpha_-0.67 | -0.0090| 0.2486| 0.1666| 0.6703| 1.1926|\n|DE_alpha_-0.90 | -0.0090| 0.2486| 0.1666| 0.6703| 1.1926|\n|ref_truncation | -0.0090| 0.2486| 0.1666| 0.6703| 1.1926|\n|ref_trunc_cap  | -0.0090| 0.2486| 0.1666| 0.6703| 1.1926|\n|ref_max_div    | -0.0305| 0.2539| 0.1590| 0.6261| 0.0855|\n|ref_random     | -0.0084| 0.2484| 0.1613| 0.6493| 0.1159|\n\n:::\n:::\n\n\nThis is one more founder draw, so its trajectory is one more replicate of the\nfigure above, not the same run. Depending on the draw, `stage2_select()` may\nwarn that the attainable `alpha` ceiling is at or below zero: with\n36 hybrids over\n12 lines, truncation on the index can pick a set no\nless diverse than a random one of the same size, and then the constraint has\nnothing to restrict and every `DE_alpha` row coincides with `ref_truncation`.\nThat is the same ceiling @sec-combinatorial computes on the book's own data,\nwhere the pool is large enough for it to be positive. Nothing here is\nAlphaSimR-specific:\n`stage2_select()` never sees where `X`, `f`, `hybrids` and `fL` came from, only\nthat they satisfy the contract stage 1 promises. `GD_BS`, the between-pool\ndivergence that carries the heterosis signal (@sec-choosing), is computed from\n`fL` exactly as it is everywhere else in the book.\n\n## Assumptions, and what this adds over @sec-simulating-crosses\n\n**What is more realistic here.** Actual recombination and linkage (a genetic\nmap per chromosome, not independent markers), a trait with directional\ndominance so that testcross selection has something real to select on and\nheterosis and inbreeding depression have a value, outbred founder pools with a\ncoalescent split behind them, and multi-generation recurrent selection with a\npaired control rather than one static pool.\n\n**What is declared, and where.** Steps 2--6 use inbred founders from\n`quickHaplo()` with every site a QTL and dominance degrees drawn at\n`meanDD = 0.4`, `varDD = 0.1`; the\n\"pools\" of Steps 4 and 6 are two undifferentiated halves of one founder set.\nStep 7 uses a separate additive founder draw. Step 8 uses outbred founders\nfrom `runMacs2(split = )`, again with every site a QTL; its DH lines are fully\ninbred, its testers are outbred individuals, and every loss of diversity is\nmeasured against the same run's founders (cycle 0) and against the paired\nno-selection control -- not against a random-subset null of the same size,\nwhich is the reference @sec-combinatorial's `alpha` uses.\n\n**What is still simplified.** Testers are the first 2\nindividuals of the *current* opposite pool, an arbitrary slice by index -- not\nchosen at random or by merit, and not the elite inbred tester a real programme\nwould use; because `randCross()` recreates each pool every cycle, the testers\nchange from cycle to cycle, so successive cycles' testcross means are not on\na common tester and are comparable only through the pools' genetic level;\nthere is one phenotyping\nenvironment (`setPheno()`'s error variance, no genotype-by-environment term --\n@sec-programme adds one); the population-split coalescent history is a\nstylised divergence process, not calibrated to a named heterotic-pool pair;\ndoubled-haploid production is instantaneous, skipping the field seasons Step 5\ncounted; and selection acts on trait 1 only -- the 2\ntraits this chapter's config simulates are all carried through `X`/`hybrids`,\nbut only the first ever enters the GCA ranking. The accuracy prediction of\nStep 6 is first order in the sample correlation -- its finite-tester-pool and\nsample-variance corrections are applied, its second-order term is not -- and\nthe selfing trajectory of Step 5 follows 400 parallel lineages from one\ncross, checked at seven generations.\n\n**Scale.** This chapter runs live at a book scale (12 +\n12 founders, 750\nmarkers, 4 cycles, 48 paired founder draws) --\nAlphaSimR is fast enough at this size that no caching is needed, unlike the\nMABC scans in @sec-backcross. Step 8's numbers may change on re-execution\nand do change between sessions, because its founders come from MaCS (Step 1);\nwhen they move, they move by about the amounts the standard deviations above\nsay, and so may a conclusion that rests on a `t` near `t_crit`: between\nsessions, the paired `t` for the selection component of gene-diversity\nerosion has been seen both above and below `t_crit` at 24 pairs, which is why\nthe chapter runs 48 pairs and writes each such inference conditionally\non the render's own `t`. A heavier, production-scale run is\n`inst/scripts/run_alphasimr.R`:\n\n```sh\nRscript inst/scripts/run_alphasimr.R --test          # smoke run, ~10 s\nRscript inst/scripts/run_alphasimr.R --out=DIR        # full run, ~2 min\n```\n\nIt runs `alphasimr_pipeline()` at a larger configuration, feeds the resulting\nhybrid pool through `stage2_select()`, and writes the cycle trajectory and\nselection metrics as CSVs.\n\n## Where this connects\n\n@sec-simulating-crosses and Step 8 build the same three-object contract\nfrom two different generative models -- the fast one and the realistic one --\nwhich is the point of drawing that seam where the book does: everything past\nit, `build_ctx()` through `stage2_select()`, cannot tell which one it is\nlooking at. @sec-heterosis is the algebra Steps 3, 4 and 6 verify against\nAlphaSimR: inbreeding depression against `genParam()`, expected heterosis\nagainst a full factorial, and the GCA/SCA decomposition against the exact\ncombining abilities. @sec-response supplies the breeder's equation Step 6\nchecks and the index theory Step 7 uses; @sec-limits is where Step 3's\n`varA`-against-`genicVarA` gap becomes the subject rather than a diagnostic.\n@sec-subdivided supplies the partition Step 8 measures across `split` and\nacross cycles. @sec-cycles runs the same diversity-erosion argument at a\nlonger horizon with the package's own faster simulator; this chapter is its\ncross-check against an engine with real meiosis behind it, and @sec-limits\nuses this chapter's linked arm for the same reason.\n\n@sec-programme is the other half of the method: the same primitives assembled\ninto an inbred-line programme with staged yield trials, where the question is\nnot which hybrids to sell but how fast a variety pipeline can run and what it\nspends to run faster.\n",
    "supporting": [
      "04c-alphasimr-pipeline_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}