<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Heterosis, dominance, and what divergence buys – Genetic Diversity in Hybrid Breeding</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-metric-catalogue.html" rel="next">
<link href="./05-genomic-era.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-37a0ccb6f5b9899fcb884e11bb6f7458.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-genomic-era.html">Metrics</a></li><li class="breadcrumb-item"><a href="./05b-heterosis-dominance.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Heterosis, dominance, and what divergence buys</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Genetic Diversity in Hybrid Breeding</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-coancestry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Coancestry, and the two matrices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-subdivided.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Diversity in a subdivided population</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Response to selection: the other half of the objective</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Simulation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-simulating-crosses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simulating lines, pools and crosses</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-population-sizing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sizing a segregating population, F1 to F4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b-backcross-introgression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introgressing several genes by backcrossing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04c-alphasimr-pipeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Simulating a breeding programme: AlphaSimR from the ground up</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04d-breeding-programme.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">A complete plant breeding programme, and what it costs in diversity</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Metrics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-genomic-era.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Diversity metrics in the genomic era</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b-heterosis-dominance.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Heterosis, dominance, and what divergence buys</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-metric-catalogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">A catalogue of metrics on <code>f</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-choosing-metrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Choosing metrics: collapse, cost, redundancy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-pipeline-stages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Metrics at each pipeline stage, and five traps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b-genomic-prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Predicting breeding values: GBLUP, BayesA, BayesB</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Optimisation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-optimal-contributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Optimal contributions and the <span class="math inline">\(\alpha\)</span> constraint</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-combinatorial-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Combinatorial selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10b-advanced-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Advanced selection: structure, bounds and scale</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence and practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-plant-literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">What the plant literature establishes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11b-diversity-across-cycles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Diversity across cycles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11c-limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">The limit, and what the metrics cannot see</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-case-study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">End to end, and the operational checklist</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./90-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Notation and glossary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-package.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The <code>hybdiv</code> package</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./92-verification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Verification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./93-corpora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">The bibliographic corpora</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-dominance-model-minimally" id="toc-the-dominance-model-minimally" class="nav-link active" data-scroll-target="#the-dominance-model-minimally"><span class="header-section-number">10.1</span> The dominance model, minimally</a>
  <ul class="collapse">
  <li><a href="#the-one-locus-scale" id="toc-the-one-locus-scale" class="nav-link" data-scroll-target="#the-one-locus-scale"><span class="header-section-number">10.1.1</span> The one-locus scale</a></li>
  <li><a href="#what-d_k-is-and-what-it-is-not" id="toc-what-d_k-is-and-what-it-is-not" class="nav-link" data-scroll-target="#what-d_k-is-and-what-it-is-not"><span class="header-section-number">10.1.2</span> What <span class="math inline">\(d_k\)</span> is, and what it is not</a></li>
  <li><a href="#the-mid-parent-difference" id="toc-the-mid-parent-difference" class="nav-link" data-scroll-target="#the-mid-parent-difference"><span class="header-section-number">10.1.3</span> The mid-parent difference</a></li>
  </ul></li>
  <li><a href="#expected-heterosis-over-a-pool-pair" id="toc-expected-heterosis-over-a-pool-pair" class="nav-link" data-scroll-target="#expected-heterosis-over-a-pool-pair"><span class="header-section-number">10.2</span> Expected heterosis over a pool pair</a></li>
  <li><a href="#sec-heterosis-identity" id="toc-sec-heterosis-identity" class="nav-link" data-scroll-target="#sec-heterosis-identity"><span class="header-section-number">10.3</span> The identity</a>
  <ul class="collapse">
  <li><a href="#a-third-form-one-minus-the-between-pool-coancestry" id="toc-a-third-form-one-minus-the-between-pool-coancestry" class="nav-link" data-scroll-target="#a-third-form-one-minus-the-between-pool-coancestry"><span class="header-section-number">10.3.1</span> A third form: one minus the between-pool coancestry</a></li>
  </ul></li>
  <li><a href="#a-second-identity-at-the-hybrid-level" id="toc-a-second-identity-at-the-hybrid-level" class="nav-link" data-scroll-target="#a-second-identity-at-the-hybrid-level"><span class="header-section-number">10.4</span> A second identity, at the hybrid level</a></li>
  <li><a href="#sec-heterosis-id" id="toc-sec-heterosis-id" class="nav-link" data-scroll-target="#sec-heterosis-id"><span class="header-section-number">10.5</span> Inbreeding depression, and why it does not price <span class="math inline">\(\alpha\)</span></a></li>
  <li><a href="#sec-heterosis-distance" id="toc-sec-heterosis-distance" class="nav-link" data-scroll-target="#sec-heterosis-distance"><span class="header-section-number">10.6</span> When genetic distance predicts heterosis exactly</a></li>
  <li><a href="#sec-heterosis-flat" id="toc-sec-heterosis-flat" class="nav-link" data-scroll-target="#sec-heterosis-flat"><span class="header-section-number">10.7</span> Divergence is not a bonus</a>
  <ul class="collapse">
  <li><a href="#the-two-terms-term-by-term" id="toc-the-two-terms-term-by-term" class="nav-link" data-scroll-target="#the-two-terms-term-by-term"><span class="header-section-number">10.7.1</span> The two terms, term by term</a></li>
  </ul></li>
  <li><a href="#sec-heterosis-alignment" id="toc-sec-heterosis-alignment" class="nav-link" data-scroll-target="#sec-heterosis-alignment"><span class="header-section-number">10.8</span> What actually buys heterosis</a>
  <ul class="collapse">
  <li><a href="#alignment-is-a-covariance" id="toc-alignment-is-a-covariance" class="nav-link" data-scroll-target="#alignment-is-a-covariance"><span class="header-section-number">10.8.1</span> Alignment is a covariance</a></li>
  <li><a href="#the-scenarios" id="toc-the-scenarios" class="nav-link" data-scroll-target="#the-scenarios"><span class="header-section-number">10.8.2</span> The scenarios</a></li>
  <li><a href="#isolating-the-divergence-channel" id="toc-isolating-the-divergence-channel" class="nav-link" data-scroll-target="#isolating-the-divergence-channel"><span class="header-section-number">10.8.3</span> Isolating the divergence channel</a></li>
  </ul></li>
  <li><a href="#reading-the-s1-panel-again" id="toc-reading-the-s1-panel-again" class="nav-link" data-scroll-target="#reading-the-s1-panel-again"><span class="header-section-number">10.9</span> Reading the S1 panel again</a></li>
  <li><a href="#sec-heterosis-gca-sca" id="toc-sec-heterosis-gca-sca" class="nav-link" data-scroll-target="#sec-heterosis-gca-sca"><span class="header-section-number">10.10</span> General and specific combining ability</a>
  <ul class="collapse">
  <li><a href="#gca-is-an-average-effect-in-the-other-pools-background" id="toc-gca-is-an-average-effect-in-the-other-pools-background" class="nav-link" data-scroll-target="#gca-is-an-average-effect-in-the-other-pools-background"><span class="header-section-number">10.10.1</span> GCA is an average effect in the other pool’s background</a></li>
  <li><a href="#sca-is-minus-twice-a-weighted-parental-inner-product" id="toc-sca-is-minus-twice-a-weighted-parental-inner-product" class="nav-link" data-scroll-target="#sca-is-minus-twice-a-weighted-parental-inner-product"><span class="header-section-number">10.10.2</span> SCA is minus twice a weighted parental inner product</a></li>
  <li><a href="#the-variance-components" id="toc-the-variance-components" class="nav-link" data-scroll-target="#the-variance-components"><span class="header-section-number">10.10.3</span> The variance components</a></li>
  </ul></li>
  <li><a href="#sec-heterosis-relocation" id="toc-sec-heterosis-relocation" class="nav-link" data-scroll-target="#sec-heterosis-relocation"><span class="header-section-number">10.11</span> Divergence destroys SCA faster than it builds GCA</a>
  <ul class="collapse">
  <li><a href="#what-this-says-about-ranking-crosses" id="toc-what-this-says-about-ranking-crosses" class="nav-link" data-scroll-target="#what-this-says-about-ranking-crosses"><span class="header-section-number">10.11.1</span> What this says about ranking crosses</a></li>
  </ul></li>
  <li><a href="#what-this-does-not-change" id="toc-what-this-does-not-change" class="nav-link" data-scroll-target="#what-this-does-not-change"><span class="header-section-number">10.12</span> What this does not change</a>
  <ul class="collapse">
  <li><a href="#what-it-would-take-to-use-d" id="toc-what-it-would-take-to-use-d" class="nav-link" data-scroll-target="#what-it-would-take-to-use-d"><span class="header-section-number">10.12.1</span> What it would take to use <span class="math inline">\(d\)</span></a></li>
  </ul></li>
  <li><a href="#where-this-connects" id="toc-where-this-connects" class="nav-link" data-scroll-target="#where-this-connects"><span class="header-section-number">10.13</span> Where this connects</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-genomic-era.html">Metrics</a></li><li class="breadcrumb-item"><a href="./05b-heterosis-dominance.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Heterosis, dominance, and what divergence buys</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-heterosis" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Heterosis, dominance, and what divergence buys</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Since <a href="02-subdivided.html" class="quarto-xref"><span>Chapter 2</span></a> this book has repeated a claim without proving it: that the divergence between the heterotic pools is the engine of heterosis, and is therefore to be maintained rather than minimised. <a href="06-metric-catalogue.html" class="quarto-xref"><span>Chapter 11</span></a> will decompose diversity on that basis and <a href="08-pipeline-stages.html" class="quarto-xref"><span>Chapter 13</span></a> will build a monitoring panel around it. The claim has carried a lot of weight for an assertion.</p>
<p>This chapter derives it, and then corrects it. The derivation is short and the identity is exact. The correction is that the usual reading of the identity – <em>push the pools apart and you will get more heterosis</em> – is false: under neutral divergence expected heterosis does not move at all, and the simulation shows it.</p>
<p>The chapter then goes one step past the mean. Expected heterosis is what a pool pair is worth on average; what a breeder selects on is how heterosis is <em>distributed</em> across the crosses of the factorial. Those are different questions with different answers, and the second one is where general and specific combining ability come from.</p>
<p>Three premises carry everything below. They are stated here once, because every result in the chapter uses all three and two of them are restrictive.</p>
<p><strong>Parents are fully inbred.</strong> Every parent line is homozygous at every locus, so an F1’s marker row is the average of its two parents’ rows and a locus is heterozygous in the F1 exactly when the parents differ. This is what makes the additive effects cancel from the mid-parent difference and what makes <code>GD_WI</code> zero. Nothing here transfers to a programme crossing non-inbred parents without re-derivation.</p>
<p><strong>The genotypic model is dominance within loci and additivity between them.</strong> There is no epistatic term anywhere below: the genotypic value is a sum over loci, <span class="math inline">\(H_i\)</span> is a sum of per-locus indicators, and the combining-ability expansion of <a href="#sec-heterosis-gca-sca" class="quarto-xref"><span>Section 10.10</span></a> is bilinear only because no term couples two loci. <span class="citation" data-cites="labroo2021">Labroo et al. (<a href="99-references.html#ref-labroo2021" role="doc-biblioref">2021</a>)</span> review epistasis alongside dominance as a proposed mechanism for heterosis; this model excludes it, and no result below should be read as evidence about it. What <span class="math inline">\(d_k\)</span> does absorb is every <em>within-locus</em> story, as the next section sets out.</p>
<p><strong>The marker panel is the set of dominance loci.</strong> <span class="math inline">\(d_k\)</span> is indexed by the same <span class="math inline">\(k\)</span> as the markers, so every locus carrying dominance is genotyped and the frequency statistics are computed on exactly the loci that generate heterosis. This is the strongest assumption of the three, and it is the one that carries the distance results of <a href="#sec-heterosis-distance" class="quarto-xref"><span>Section 10.6</span></a>. A real panel tags causal loci through linkage disequilibrium rather than containing them, which weakens every statement below about markers predicting heterosis but does not change the algebra, since the algebra is written over whatever set <span class="math inline">\(k\)</span> indexes.</p>
<section id="the-dominance-model-minimally" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="the-dominance-model-minimally"><span class="header-section-number">10.1</span> The dominance model, minimally</h2>
<section id="the-one-locus-scale" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="the-one-locus-scale"><span class="header-section-number">10.1.1</span> The one-locus scale</h3>
<p>The classical parameterisation puts the origin at the midpoint of the two homozygotes: one homozygote is worth <span class="math inline">\(+a\)</span>, the other <span class="math inline">\(-a\)</span>, and the heterozygote <span class="math inline">\(d\)</span>. Under random mating at frequency <span class="math inline">\(p\)</span>, with <span class="math inline">\(q = 1 - p\)</span>, the population mean is <span class="citation" data-cites="falconer1996">(<a href="99-references.html#ref-falconer1996" role="doc-biblioref">Falconer and Mackay 1996</a>, Eq. 7.2)</span></p>
<p><span class="math display">\[M = a\,(p - q) + 2pq\,d\]</span></p>
<p>The first term is the additive contribution, and the mid-parent of any cross already carries it. The second is the dominance contribution. It is the only part of <span class="math inline">\(M\)</span> that depends on how many heterozygotes there are, and therefore the only part a cross can add over its own mid-parent.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><span class="math inline">\(a\)</span> is a scale, not a quantity this chapter computes
</div>
</div>
<div class="callout-body-container callout-body">
<p>The symbols in that display are the textbook ones. This book’s additive marker effects are <span class="math inline">\(\beta_k\)</span> (<a href="08b-genomic-prediction.html" class="quarto-xref"><span>Chapter 14</span></a>), and its <span class="math inline">\(\alpha\)</span> is the diversity-loss statistic of <a href="06-metric-catalogue.html" class="quarto-xref"><span>Chapter 11</span></a>, not the classical average effect of a substitution. The per-locus <span class="math inline">\(a_k\)</span> reappears three times below and never as a result: in the genotypic-value model used to show that it cancels, in the definition of overdominance as <span class="math inline">\(|d| &gt; |a|\)</span>, and in the average effect of a substitution <span class="math inline">\(a + d(q - p)\)</span>. No quantity this chapter reports depends on it.</p>
</div>
</div>
</section>
<section id="what-d_k-is-and-what-it-is-not" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="what-d_k-is-and-what-it-is-not"><span class="header-section-number">10.1.2</span> What <span class="math inline">\(d_k\)</span> is, and what it is not</h3>
<p><span class="math inline">\(d_k\)</span> is <em>functional</em> dominance: the departure of the heterozygote from the homozygote midpoint at locus <span class="math inline">\(k\)</span>. It is a property of the locus. It does not move when allele frequencies move.</p>
<p>Fisher’s <em>statistical</em> dominance deviation is a different object: the residual left after projecting genotypic values onto the best additive model <strong>in a particular population</strong>. It is a property of the population as much as of the locus, and it changes when frequencies change.</p>
<p>Both appear in this chapter, and keeping them apart is the whole trick. <span class="math inline">\(d_k\)</span> is the input. The specific combining ability of <a href="#sec-heterosis-gca-sca" class="quarto-xref"><span>Section 10.10</span></a> is the statistical dominance deviation that a given <span class="math inline">\(d_k\)</span> <em>induces</em> over a given pair of pools. One is a constant; the other is an answer that depends on where the pools happen to sit.</p>
<p>The distinction also buys the model what generality it has, and marks where that generality stops. Dominance, overdominance (a heterozygote outside both homozygotes, <span class="math inline">\(|d| &gt; |a|\)</span>) and pseudo-overdominance (two dominant favourable alleles in repulsion phase, too close for any marker to separate) are three different biological stories, and <span class="citation" data-cites="labroo2021">Labroo et al. (<a href="99-references.html#ref-labroo2021" role="doc-biblioref">2021</a>)</span> review the evidence for each. At marker resolution they are the same arithmetic: a locus at which the F1 gains something the mid-parent does not. A single <span class="math inline">\(d_k\)</span> absorbs all three, and nothing below can distinguish them – nor needs to. Epistasis is the fourth story on <span class="citation" data-cites="labroo2021">Labroo et al. (<a href="99-references.html#ref-labroo2021" role="doc-biblioref">2021</a>)</span>’s list and <span class="math inline">\(d_k\)</span> does not absorb it, because a single per-locus number cannot represent a term that depends on two loci at once. That is the second premise above, and it is an exclusion rather than an approximation.</p>
</section>
<section id="the-mid-parent-difference" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="the-mid-parent-difference"><span class="header-section-number">10.1.3</span> The mid-parent difference</h3>
<p>Code a genotype by <span class="math inline">\(x_k \in \{0, 0.5, 1\}\)</span>, the frequency of the reference allele within the individual, and take the genotypic value to be the additive part plus the dominance deviation at every heterozygous locus:</p>
<p><span class="math display">\[G(\mathbf{x}) = \sum_k a_k\,(2x_k - 1) + \sum_k d_k\,\mathbb{1}\{x_k = 0.5\}\]</span></p>
<p>The parents are fully inbred, so each is homozygous at every locus and the F1’s row is the average of its two parents’ rows. The additive part is linear in <span class="math inline">\(\mathbf{x}\)</span>, so the two parents’ additive values average exactly to the F1’s own and cancel from the mid-parent difference. What survives is the dominance deviation at the loci where the F1 is heterozygous:</p>
<p><span class="math display">\[H_i = \sum_k d_k \, \mathbb{1}\{x_{ik} = 0.5\}\]</span></p>
<p>The additive effects never appear. That is the result, not an omission, and it is why <code>heterosis_value()</code> takes no additive-effect argument:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>heterosis_value</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; function (X, d) </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; {</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     stopifnot(length(d) == ncol(X))</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     drop((X == 0.5) %*% d)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; }</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; &lt;bytecode: 0xa7c96e510&gt;</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; &lt;environment: namespace:hybdiv&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Against the literal oracle of <a href="92-verification.html" class="quarto-xref"><span>Appendix C</span></a>, which loops over loci and compares the two parents’ genotypes one at a time:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">heterosis_value</span>(ctx<span class="sc">$</span>X[<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>, ], d) <span class="sc">-</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ref_heterosis</span>(L, <span class="fu">head</span>(ctx<span class="sc">$</span>ped, <span class="dv">25</span>), d)))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The cancellation is worth seeing directly. Draw additive effects at random, score a real F1 and its two parents under <span class="math inline">\(G(\mathbf{x})\)</span>, and subtract:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>a   <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(ctx<span class="sc">$</span>m, <span class="dv">0</span>, <span class="fl">0.2</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>val <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">sum</span>(a <span class="sc">*</span> (<span class="dv">2</span> <span class="sc">*</span> x <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">sum</span>(d <span class="sc">*</span> (x <span class="sc">==</span> <span class="fl">0.5</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>i   <span class="ot">&lt;-</span> <span class="dv">7</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>mid <span class="ot">&lt;-</span> (<span class="fu">val</span>(L[ctx<span class="sc">$</span>ped<span class="sc">$</span>a[i], ] <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">val</span>(L[ctx<span class="sc">$</span>ped<span class="sc">$</span>b[i], ] <span class="sc">/</span> <span class="dv">2</span>)) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mid_parent_difference =</span> <span class="fu">val</span>(ctx<span class="sc">$</span>X[i, ]) <span class="sc">-</span> mid,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">heterosis_value       =</span> <span class="fu">heterosis_value</span>(ctx<span class="sc">$</span>X[i, , <span class="at">drop =</span> <span class="cn">FALSE</span>], d))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; mid_parent_difference       heterosis_value </span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              362.3386              362.3386</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The additive effects entered the first number and cancelled out of it; they never entered the second.</p>
</section>
</section>
<section id="expected-heterosis-over-a-pool-pair" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="expected-heterosis-over-a-pool-pair"><span class="header-section-number">10.2</span> Expected heterosis over a pool pair</h2>
<p>Write <span class="math inline">\(p_{Ak}\)</span> and <span class="math inline">\(p_{Bk}\)</span> for the reference-allele frequencies at locus <span class="math inline">\(k\)</span> in the two pools, each computed over that pool’s lines. A locus is heterozygous in the F1 when the two gametes carry different alleles, which for a cross drawn at random between the pools happens with probability <span class="math inline">\(p_A(1 - p_B) + (1 - p_A)p_B\)</span>. The expected heterosis over all <span class="math inline">\(A \times B\)</span> crosses therefore follows from the pool frequencies alone:</p>
<p><span class="math display">\[\mathbb{E}[H] = \sum_k d_k \left[\, p_{A k} + p_{B k} - 2 p_{A k} p_{B k} \right]\]</span></p>
<p>The candidate pool here <em>is</em> the full factorial, every <span class="math inline">\(A \times B\)</span> pairing exactly once, and the frequencies are the means of those same lines. The closed form is then the mean of the realised values as an identity rather than an approximation, and the residual is at machine precision:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(<span class="fu">heterosis_expected</span>(pA, pB, d) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">heterosis_value</span>(ctx<span class="sc">$</span>X, d)))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1.136868e-13</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>That is a mean over <span class="math inline">\(N =\)</span> 625 crosses, and a mean is not a ranking. Hold on to the question of how the individual crosses are spread around it; <a href="#sec-heterosis-gca-sca" class="quarto-xref"><span>Section 10.10</span></a> answers it exactly.</p>
</section>
<section id="sec-heterosis-identity" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="sec-heterosis-identity"><span class="header-section-number">10.3</span> The identity</h2>
<p>Now split the bracket. Writing <span class="math inline">\(\bar p = (p_A + p_B)/2\)</span> and <span class="math inline">\(y = p_A - p_B\)</span>, the per-locus F1 heterozygosity separates exactly:</p>
<p><span class="math display">\[p_A + p_B - 2 p_A p_B \;=\; \underbrace{2 \bar p (1 - \bar p)}_{\text{shared}}
                            \;+\; \underbrace{y^2 / 2}_{\text{divergence}}\]</span></p>
<p>The first term is the heterozygosity a single merged pool at frequency <span class="math inline">\(\bar p\)</span> would produce under random mating. The second is what keeping the pools apart adds on top of it. Average both over loci with <span class="math inline">\(d_k \equiv 1\)</span>, so that the weighting does not obscure the algebra, and they are exactly the <span class="math inline">\(GD_T\)</span> and <span class="math inline">\(GD_{BS}\)</span> of the Caballero &amp; Toro partition that <a href="02-subdivided.html" class="quarto-xref"><span>Chapter 2</span></a> derived and <code>gd_partition()</code> computes:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>hp <span class="ot">&lt;-</span> <span class="fu">heterosis_partition</span>(pA, pB, <span class="fu">rep</span>(<span class="dv">1</span>, ctx<span class="sc">$</span>m)) <span class="sc">/</span> ctx<span class="sc">$</span>m</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>gp <span class="ot">&lt;-</span> <span class="fu">gd_partition</span>(<span class="fu">seq_len</span>(ctx<span class="sc">$</span>N), ctx)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fmt</span>(<span class="fu">data.frame</span>(<span class="at">term       =</span> <span class="fu">c</span>(<span class="st">"shared"</span>, <span class="st">"divergence"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">heterosis  =</span> <span class="fu">c</span>(hp[[<span class="st">"shared"</span>]], hp[[<span class="st">"divergence"</span>]]),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">partition  =</span> <span class="fu">c</span>(gp[[<span class="st">"GD_T"</span>]],   gp[[<span class="st">"GD_BS"</span>]]),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">residual   =</span> <span class="fu">c</span>(<span class="fu">abs</span>(hp[[<span class="st">"shared"</span>]]     <span class="sc">-</span> gp[[<span class="st">"GD_T"</span>]]),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">abs</span>(hp[[<span class="st">"divergence"</span>]] <span class="sc">-</span> gp[[<span class="st">"GD_BS"</span>]]))), <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">heterosis</th>
<th style="text-align: right;">partition</th>
<th style="text-align: right;">residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">shared</td>
<td style="text-align: right;">0.3280928</td>
<td style="text-align: right;">0.3280928</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">divergence</td>
<td style="text-align: right;">0.0335968</td>
<td style="text-align: right;">0.0335968</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><span class="math inline">\(GD_{BS}\)</span> weighted by dominance deviations <strong>is</strong> the divergence half of expected heterosis. “Between-pool divergence is the heterosis engine” is an identity, not a slogan.</p>
</blockquote>
<p>One thing to be clear about before reading on. <span class="math inline">\(GD_T\)</span> is the gene diversity of the <em>merged</em> population, and by <a href="02-subdivided.html" class="quarto-xref"><span>Chapter 2</span></a> it already contains <span class="math inline">\(GD_{BS}\)</span>: with inbred lines, <span class="math inline">\(GD_T = GD_{BI} + GD_{BS}\)</span>. Expected F1 heterozygosity is therefore <span class="math inline">\(GD_{BI} + 2\,GD_{BS}\)</span>, the between-pool component counted twice – once inside the shared term, once as the divergence term. That factor of two is where the classical result sits. Falconer &amp; Mackay’s heterosis of a cross between two <em>random-mating</em> populations is <span class="math inline">\(\sum_k d_k y_k^2\)</span> <span class="citation" data-cites="falconer1996">(<a href="99-references.html#ref-falconer1996" role="doc-biblioref">Falconer and Mackay 1996</a>, Ch. 14)</span>, exactly twice the divergence term here. The two do not conflict; they use different mid-parents. Theirs is two random-mating populations, each carrying its own within-pool heterozygosity, so their <span class="math inline">\(H\)</span> is the total above <span class="math inline">\(\sum_k d_k (p_{Ak}q_{Ak} + p_{Bk}q_{Bk})\)</span>. Ours is two inbred lines carrying none, so the whole F1 heterozygosity is heterosis, and the shared term is the mean of the two pools’ random-mating heterozygosities plus the half of <span class="math inline">\(\sum_k d_k y_k^2\)</span> that <span class="math inline">\(GD_T\)</span> already holds.</p>
<section id="a-third-form-one-minus-the-between-pool-coancestry" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="a-third-form-one-minus-the-between-pool-coancestry"><span class="header-section-number">10.3.1</span> A third form: one minus the between-pool coancestry</h3>
<p>The sum of the two components has a name of its own. <span class="math inline">\(\theta_{AB} = \mathbf{w}_A'
\mathbf{f}^L \mathbf{w}_B\)</span> is the between-pool coancestry of <a href="06-metric-catalogue.html" class="quarto-xref"><span>Chapter 11</span></a>: on the full factorial, where the line weights are uniform, it is the probability that an allele drawn from a pool-A line and an allele drawn from a pool-B line are identical in state. Its complement is the whole bracket:</p>
<p><span class="math display">\[GD_T + GD_{BS} \;=\; 1 - \theta_{AB}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tp <span class="ot">&lt;-</span> <span class="fu">theta_pools</span>(<span class="fu">seq_len</span>(ctx<span class="sc">$</span>N), ctx)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">shared_plus_divergence =</span> gp[[<span class="st">"GD_T"</span>]] <span class="sc">+</span> gp[[<span class="st">"GD_BS"</span>]],</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">one_minus_theta_AB     =</span> <span class="dv">1</span> <span class="sc">-</span> tp[[<span class="st">"theta_AB"</span>]])</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; shared_plus_divergence     one_minus_theta_AB </span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              0.3616896              0.3616896</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This one is algebra rather than simulation. <code>gd_partition()</code> defines <span class="math inline">\(GD_T = 1 - \bar f\)</span> and <span class="math inline">\(GD_{BS} = \tilde f - \bar f\)</span> with <span class="math inline">\(\bar f = (\theta_A + 2\theta_{AB} + \theta_B)/4\)</span> and <span class="math inline">\(\tilde f = (\theta_A + \theta_B)/2\)</span>, and the sum collapses to <span class="math inline">\(1 - \theta_{AB}\)</span>. Which is the shortest statement the chapter has to make: <strong>expected F1 heterozygosity is one minus between-pool coancestry.</strong> Everything else here is a weighting of that quantity, or a way of splitting it.</p>
</section>
</section>
<section id="a-second-identity-at-the-hybrid-level" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="a-second-identity-at-the-hybrid-level"><span class="header-section-number">10.4</span> A second identity, at the hybrid level</h2>
<p><a href="06-metric-catalogue.html" class="quarto-xref"><span>Chapter 11</span></a> reports <code>GD_WI_hyb</code>, the within-individual gene diversity actually carried by the F1s, separately from the line-level partition, because with inbred parents <code>GD_WI</code> is zero by construction and carries no signal. A hybrid’s self-coancestry is <span class="math inline">\(1 - h_i/2\)</span>, with <span class="math inline">\(h_i\)</span> its heterozygous fraction, so <code>GD_WI_hyb</code> is half the mean F1 heterozygosity and the two levels are linked:</p>
<p><span class="math display">\[2 \cdot GD_{WI\text{-}hyb} = GD_T + GD_{BS}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">lhs =</span> <span class="dv">2</span> <span class="sc">*</span> gp[[<span class="st">"GD_WI_hyb"</span>]], <span class="at">rhs =</span> gp[[<span class="st">"GD_T"</span>]] <span class="sc">+</span> gp[[<span class="st">"GD_BS"</span>]],</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">GD_WI =</span> gp[[<span class="st">"GD_WI"</span>]])</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           lhs           rhs         GD_WI </span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3.616896e-01  3.616896e-01 -4.440892e-16</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Exact on the full factorial, because every <span class="math inline">\(A \times B\)</span> pairing is present exactly once. On a <em>selected</em> subset it holds only approximately. There <span class="math inline">\(GD_T\)</span> and <span class="math inline">\(GD_{BS}\)</span> are computed from the line-usage weights, which is what a random re-pairing of the selected parents would give, while <code>GD_WI_hyb</code> scores the pairs actually chosen. The gap is the pairing structure of the subset. <code>tests/testthat/test-dominance.R</code> asserts the identity to <code>1e-12</code> on the full factorial and bounds the gap at <code>5e-3</code> on a <em>random</em> 40-hybrid subset, at one scale (12 lines per pool, 800 markers). A subset chosen by an optimiser, which concentrates line usage deliberately, is not covered by that bound and has not been measured here.</p>
</section>
<section id="sec-heterosis-id" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="sec-heterosis-id"><span class="header-section-number">10.5</span> Inbreeding depression, and why it does not price <span class="math inline">\(\alpha\)</span></h2>
<p>The same model run backwards gives inbreeding depression. A locus at frequency <span class="math inline">\(p\)</span> in a population with inbreeding coefficient <span class="math inline">\(F\)</span> is heterozygous with probability <span class="math inline">\(2pq(1-F)\)</span>, so the mean declines linearly in <span class="math inline">\(F\)</span> <span class="citation" data-cites="falconer1996">(<a href="99-references.html#ref-falconer1996" role="doc-biblioref">Falconer and Mackay 1996</a>, Ch. 14)</span>:</p>
<p><span class="math display">\[ID \;=\; 2F\sum_k d_k \, p_k q_k\]</span></p>
<p>At <span class="math inline">\(F = 1\)</span> that is exactly the <em>shared</em> term of <code>heterosis_partition()</code> evaluated at <span class="math inline">\(p_A = p_B = p\)</span>. So the depression of a pool driven to complete homozygosity and the expected heterosis of a cross made <em>within</em> that same pool are one quantity seen from two sides. <span class="citation" data-cites="mackay2020">Mackay et al. (<a href="99-references.html#ref-mackay2020" role="doc-biblioref">2021</a>)</span> treat heterosis and inbreeding depression together on that basis, alongside transgressive segregation, which this chapter does not take up. The identity needs no new machinery:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">inbreeding_depression =</span> <span class="fu">inbreeding_depression</span>(pA, d),</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">shared_term           =</span> <span class="fu">heterosis_partition</span>(pA, pA, d)[[<span class="st">"shared"</span>]],</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">deviation             =</span> <span class="fu">abs</span>(<span class="fu">inbreeding_depression</span>(pA, d) <span class="sc">-</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">heterosis_partition</span>(pA, pA, d)[[<span class="st">"shared"</span>]]))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; inbreeding_depression           shared_term             deviation </span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              288.2869              288.2869                0.0000</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The closed form is checked against simulated genotypes rather than against its own algebra, which is what <code>ref_inbreeding_depression()</code> exists for: it draws each genotype as identical by descent with probability <span class="math inline">\(F\)</span> and as two independent alleles otherwise, so the agreement is to Monte Carlo error:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">300</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">closed_form =</span> <span class="fu">inbreeding_depression</span>(pA[k], d[k], <span class="fl">0.6</span>),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">simulated   =</span> <span class="fu">ref_inbreeding_depression</span>(pA[k], d[k], <span class="fl">0.6</span>, <span class="at">n =</span> <span class="dv">20000</span>, <span class="at">seed =</span> <span class="dv">2</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; closed_form   simulated </span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    27.58563    27.57923</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now the part that matters, because the obvious next step is wrong.</p>
<p>It is tempting to argue: <span class="math inline">\(\alpha\)</span> budgets a loss of within-pool gene diversity; gene diversity is <span class="math inline">\(\sum_k p_kq_k\)</span>; inbreeding depression is <span class="math inline">\(\sum_k d_k\,p_kq_k\)</span>; therefore spending <span class="math inline">\(\alpha\)</span> costs yield in the current cycle, and <em>that</em> is the price of the budget. The algebra does not support it.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">max_dominance_contribution_of_an_inbred_line =</span> <span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">heterosis_value</span>(U, d))))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; max_dominance_contribution_of_an_inbred_line </span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                            0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Zero, exactly. A fully inbred line has no heterozygous loci, so its dominance contribution is zero <strong>whatever the pool’s allele frequencies are</strong>. In a programme whose parents are inbred lines the depression was paid in full when the lines were made; it is a constant, and it does not move when the pool subsequently loses diversity. The formula above describes the gap between a hypothetical random-mating pool and its inbred derivatives, and that gap <em>shrinks</em> as <span class="math inline">\(p_kq_k\)</span> shrinks – but nothing in the programme stands at the random-mating end of it.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Inbreeding depression is not the current-cycle price of the diversity budget
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is the same fact that makes <span class="math inline">\(GD_{WI}\)</span> exactly zero in <a href="06-metric-catalogue.html" class="quarto-xref"><span>Chapter 11</span></a>’s partition, and it has the same cause: with inbred parents there is no within-individual variation left to lose. Two consequences.</p>
<p>The cost of <span class="math inline">\(\alpha\)</span> in this system remains what <a href="11b-diversity-across-cycles.html" class="quarto-xref"><span>Chapter 19</span></a> measures – an option value, realised cycles later through the variance available to select on (<a href="02b-response.html" class="quarto-xref"><span>Chapter 3</span></a>), not a yield loss booked this season.</p>
<p>And inbreeding depression <strong>is</strong> the live quantity wherever the population is only partially inbred: F2, F3 and F4 in <a href="04-population-sizing.html" class="quarto-xref"><span>Chapter 5</span></a>, where <span class="math inline">\(F\)</span> is still climbing and the depression is still accumulating. That is the chapter it belongs to, not this one.</p>
</div>
</div>
<p>Note also what this does <em>not</em> say. Expected heterosis in the product is a separate question. <a href="#sec-heterosis-flat" class="quarto-xref"><span>Section 10.7</span></a> answers it for the neutral case: under drift the shared term lost and the divergence term gained cancel exactly, so hybrid heterosis is invariant. Under selection the frequencies move directionally, and what happens to expected heterosis is then the alignment question of <a href="#sec-heterosis-alignment" class="quarto-xref"><span>Section 10.8</span></a>, which can go either way. In neither case is the diversity loss itself an immediate dominance cost. The bill arrives later, and it arrives in the additive variance.</p>
</section>
<section id="sec-heterosis-distance" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="sec-heterosis-distance"><span class="header-section-number">10.6</span> When genetic distance predicts heterosis exactly</h2>
<p>Before the corrections start, one special case is worth having, because it is the only case in which marker distance and heterosis are the same number.</p>
<p>Set <span class="math inline">\(d_k \equiv d\)</span>, constant across loci. Then <span class="math inline">\(H\)</span> stops being a weighted count and becomes a plain one: <span class="math inline">\(d\)</span> times the number of loci at which the two parents differ. For inbred lines that count is exactly what the coancestry kernel of <a href="01-coancestry.html" class="quarto-xref"><span>Chapter 1</span></a> measures, so for a cross between lines <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span></p>
<p><span class="math display">\[H_{ab} \;=\; d\,m\,(1 - f^L_{ab}) \;=\; d\,m\,\mathrm{MRD}_{ab}^2\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>h1 <span class="ot">&lt;-</span> <span class="fu">heterosis_value</span>(ctx<span class="sc">$</span>X, <span class="fu">rep</span>(<span class="dv">1</span>, ctx<span class="sc">$</span>m))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>fL <span class="ot">&lt;-</span> <span class="fu">molecular_coancestry</span>(L <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>ab <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ctx<span class="sc">$</span>ped<span class="sc">$</span>a, ctx<span class="sc">$</span>ped<span class="sc">$</span>b)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">vs_coancestry =</span> <span class="fu">max</span>(<span class="fu">abs</span>(h1 <span class="sc">-</span> ctx<span class="sc">$</span>m <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> fL[ab]))),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">vs_mrd        =</span> <span class="fu">max</span>(<span class="fu">abs</span>(h1 <span class="sc">-</span> ctx<span class="sc">$</span>m <span class="sc">*</span> <span class="fu">mrd_matrix</span>(L <span class="sc">/</span> <span class="dv">2</span>)[ab]<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; vs_coancestry        vs_mrd </span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1.136868e-13  2.273737e-13</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Both residuals are at machine precision. Under flat dominance, heterosis and molecular coancestry are one statistic seen twice – Trap 1 of <a href="08-pipeline-stages.html" class="quarto-xref"><span>Chapter 13</span></a> read from the other side – and the diversity kernel this whole book runs on turns out to be the right object for the heterosis question as well.</p>
<p>Flat <span class="math inline">\(d\)</span> is also precisely the condition under which <span class="math inline">\(H\)</span> is a function of marker distance alone. It is a strong condition, and it fails as soon as <span class="math inline">\(d\)</span> varies: two crosses at the same distance then differ by <em>which</em> loci they differ at. With the gamma-distributed deviations used everywhere else in this chapter the relationship survives but stops being an identity:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">cor_uniform_d =</span> <span class="fu">cor</span>(h1, <span class="dv">1</span> <span class="sc">-</span> fL[ab]),</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">cor_real_d    =</span> <span class="fu">cor</span>(<span class="fu">heterosis_value</span>(ctx<span class="sc">$</span>X, d), <span class="dv">1</span> <span class="sc">-</span> fL[ab]))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cor_uniform_d    cor_real_d </span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     1.0000000     0.7809147</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A correlation of 0.78 is a useful predictor and a poor identity. Two things move it, and both are properties of the germplasm rather than of the statistic: how <span class="math inline">\(d\)</span> is spread over the loci at which the parents differ, which is what <a href="#sec-heterosis-alignment" class="quarto-xref"><span>Section 10.8</span></a> is about, and – once the third premise is relaxed – how well the panel tags the causal loci. Under flat <span class="math inline">\(d\)</span> on a panel that <em>is</em> the causal set the correlation is 1 by the identity above. Departing from either condition generally lowers it – not always, since a <span class="math inline">\(d\)</span> that varies only across loci at which no pair of parents differs changes no <span class="math inline">\(H_i\)</span> at all – and by how much is something this chapter does not attempt to predict.</p>
</section>
<section id="sec-heterosis-flat" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="sec-heterosis-flat"><span class="header-section-number">10.7</span> Divergence is not a bonus</h2>
<p>Read <code>divergence</code> as free money and you will reach for <span class="math inline">\(F_{ST}\)</span>. Do not.</p>
<p>Draw the pools further apart and watch all three terms. Nothing here is selected. Each point re-draws both pools from the <em>same</em> ancestral frequencies – the ancestral vector is fixed by <code>seed = 5</code> and shared across the sweep, while the two pool-frequency vectors are fresh Balding-Nichols draws at each <code>fst</code> (<a href="90-notation.html" class="quarto-xref"><span>Appendix A</span></a>) – so what varies along the sweep is how far the draw scatters and nothing else:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sweep_het <span class="ot">&lt;-</span> <span class="cf">function</span>(fst) {</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  cf <span class="ot">&lt;-</span> <span class="fu">modifyList</span>(book_cfg, <span class="fu">list</span>(<span class="at">fst =</span> fst, <span class="at">seed =</span> <span class="dv">5</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  Lf <span class="ot">&lt;-</span> <span class="fu">simulate_lines</span>(cf)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  pl <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="fu">c</span>(cf<span class="sc">$</span>n_pool_A, cf<span class="sc">$</span>n_pool_B))</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  Pf <span class="ot">&lt;-</span> <span class="fu">pool_freqs</span>(Lf <span class="sc">/</span> <span class="dv">2</span>, pl)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  hp <span class="ot">&lt;-</span> <span class="fu">heterosis_partition</span>(Pf[<span class="st">"A"</span>, ], Pf[<span class="st">"B"</span>, ], <span class="fu">rep</span>(<span class="dv">1</span>, cf<span class="sc">$</span>m)) <span class="sc">/</span> cf<span class="sc">$</span>m</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  cm <span class="ot">&lt;-</span> <span class="fu">pool_complementarity</span>(Lf <span class="sc">/</span> <span class="dv">2</span>, pl)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">fst =</span> fst, <span class="at">shared =</span> hp[[<span class="st">"shared"</span>]], <span class="at">divergence =</span> hp[[<span class="st">"divergence"</span>]],</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">total =</span> hp[[<span class="st">"total"</span>]],</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">frac_opposite_fixed =</span> cm[[<span class="st">"frac_opposite_fixed"</span>]],</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">mean_abs_delta_p =</span> cm[[<span class="st">"mean_abs_delta_p"</span>]],</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">mean_sq_delta_p =</span> cm[[<span class="st">"mean_sq_delta_p"</span>]])</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>sw <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">c</span>(<span class="fl">0.02</span>, <span class="fl">0.05</span>, <span class="fl">0.10</span>, <span class="fl">0.20</span>, <span class="fl">0.30</span>, <span class="fl">0.45</span>), sweep_het))</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="fu">fmt</span>(sw, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 24%">
<col style="width: 20%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">fst</th>
<th style="text-align: right;">shared</th>
<th style="text-align: right;">divergence</th>
<th style="text-align: right;">total</th>
<th style="text-align: right;">frac_opposite_fixed</th>
<th style="text-align: right;">mean_abs_delta_p</th>
<th style="text-align: right;">mean_sq_delta_p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.3549</td>
<td style="text-align: right;">0.0107</td>
<td style="text-align: right;">0.3656</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.1138</td>
<td style="text-align: right;">0.0214</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.3489</td>
<td style="text-align: right;">0.0171</td>
<td style="text-align: right;">0.3659</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.1414</td>
<td style="text-align: right;">0.0341</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.3374</td>
<td style="text-align: right;">0.0246</td>
<td style="text-align: right;">0.3620</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.1715</td>
<td style="text-align: right;">0.0493</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.3231</td>
<td style="text-align: right;">0.0433</td>
<td style="text-align: right;">0.3664</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.2252</td>
<td style="text-align: right;">0.0867</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.3042</td>
<td style="text-align: right;">0.0595</td>
<td style="text-align: right;">0.3638</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.2589</td>
<td style="text-align: right;">0.1191</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.2792</td>
<td style="text-align: right;">0.0846</td>
<td style="text-align: right;">0.3639</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">0.3012</td>
<td style="text-align: right;">0.1693</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Across the sweep the divergence term rises by a factor of 7.9. The comparison that matters is in absolute units, not in ratios: divergence gains 0.0739 per locus and the shared term loses 0.0756. The total does not move.</p>
<section id="the-two-terms-term-by-term" class="level3" data-number="10.7.1">
<h3 data-number="10.7.1" class="anchored" data-anchor-id="the-two-terms-term-by-term"><span class="header-section-number">10.7.1</span> The two terms, term by term</h3>
<p>The algebra is one line. Pool A and pool B are drawn <em>independently</em> around a common ancestral frequency <span class="math inline">\(p\)</span>, so <span class="math inline">\(\mathbb{E}[p_A] = \mathbb{E}[p_B] = p\)</span> and <span class="math inline">\(\mathbb{E}[p_A p_B] = p^2\)</span>. Therefore</p>
<p><span class="math display">\[\mathbb{E}\!\left[p_A + p_B - 2 p_A p_B\right] = 2p(1-p),\]</span></p>
<p>which contains no <span class="math inline">\(F_{ST}\)</span> at all. With ancestral frequencies drawn uniformly on <span class="math inline">\([0.05, 0.95]\)</span> the predicted level is <span class="math inline">\(\mathbb{E}[2p(1-p)] =\)</span> 0.365, against a simulated mean of 0.3646 across the whole sweep.</p>
<p>That the <em>sum</em> is flat is the headline, but the Balding-Nichols model predicts each half separately, which is the sharper statement. Under it <span class="math inline">\(\mathrm{Var}(p_A) = \mathrm{Var}(p_B) = F_{ST}\,p(1-p)\)</span>, so <span class="math inline">\(\mathrm{Var}(\bar p) = F_{ST}\,p(1-p)/2\)</span> and <span class="math inline">\(\mathrm{Var}(y) = 2F_{ST}\,p(1-p)\)</span>. Substituting:</p>
<p><span class="math display">\[\mathbb{E}\!\left[2\bar p(1 - \bar p)\right] = 2p(1-p)\left(1 - \tfrac{F_{ST}}{2}\right),
\qquad
\mathbb{E}\!\left[y^2/2\right] = F_{ST}\,p(1-p)\]</span></p>
<p>The shared term loses <span class="math inline">\(F_{ST}\,p(1-p)\)</span> and the divergence term gains <span class="math inline">\(F_{ST}\,p(1-p)\)</span>: the same expression with opposite signs, not approximately and not on average over some range. Both predictions are parameter-free once the ancestral distribution is fixed, so they can be laid straight on top of the sweep:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Ep <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fl">0.5</span> <span class="sc">-</span> (<span class="fl">0.9</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">12</span> <span class="sc">+</span> <span class="fl">0.25</span>))      <span class="co"># E[2p(1-p)] for p ~ U(0.05, 0.95)</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>sw<span class="sc">$</span>pred_shared     <span class="ot">&lt;-</span> Ep <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> sw<span class="sc">$</span>fst <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>sw<span class="sc">$</span>pred_divergence <span class="ot">&lt;-</span> Ep <span class="sc">*</span> sw<span class="sc">$</span>fst <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">fmt</span>(sw[, <span class="fu">c</span>(<span class="st">"fst"</span>, <span class="st">"shared"</span>, <span class="st">"pred_shared"</span>, <span class="st">"divergence"</span>, <span class="st">"pred_divergence"</span>)], <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">fst</th>
<th style="text-align: right;">shared</th>
<th style="text-align: right;">pred_shared</th>
<th style="text-align: right;">divergence</th>
<th style="text-align: right;">pred_divergence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.3549</td>
<td style="text-align: right;">0.3614</td>
<td style="text-align: right;">0.0107</td>
<td style="text-align: right;">0.0036</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.3489</td>
<td style="text-align: right;">0.3559</td>
<td style="text-align: right;">0.0171</td>
<td style="text-align: right;">0.0091</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.3374</td>
<td style="text-align: right;">0.3468</td>
<td style="text-align: right;">0.0246</td>
<td style="text-align: right;">0.0182</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.3231</td>
<td style="text-align: right;">0.3285</td>
<td style="text-align: right;">0.0433</td>
<td style="text-align: right;">0.0365</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.3042</td>
<td style="text-align: right;">0.3102</td>
<td style="text-align: right;">0.0595</td>
<td style="text-align: right;">0.0548</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.2792</td>
<td style="text-align: right;">0.2829</td>
<td style="text-align: right;">0.0846</td>
<td style="text-align: right;">0.0821</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sw<span class="sc">$</span>fst, sw<span class="sc">$</span>total, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#1b7837"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.40</span>),</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"target fst between pools"</span>, <span class="at">ylab =</span> <span class="st">"expected heterosis per locus (d = 1)"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(sw<span class="sc">$</span>fst, sw<span class="sc">$</span>shared, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">17</span>, <span class="at">col =</span> <span class="st">"#2166ac"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(sw<span class="sc">$</span>fst, sw<span class="sc">$</span>divergence, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">15</span>, <span class="at">col =</span> <span class="st">"#b2182b"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(sw<span class="sc">$</span>fst, sw<span class="sc">$</span>pred_shared, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"#2166ac"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(sw<span class="sc">$</span>fst, sw<span class="sc">$</span>pred_divergence, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"#b2182b"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(sw<span class="sc">$</span>total), <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"grey45"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"right"</span>, <span class="fu">c</span>(<span class="st">"total"</span>, <span class="st">"shared"</span>, <span class="st">"divergence"</span>, <span class="st">"predicted"</span>), <span class="at">bty =</span> <span class="st">"n"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">17</span>, <span class="dv">15</span>, <span class="cn">NA</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="dv">2</span>),</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#1b7837"</span>, <span class="st">"#2166ac"</span>, <span class="st">"#b2182b"</span>, <span class="st">"grey45"</span>))</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05b-heterosis-dominance_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="1050"></p>
<figcaption>Expected heterosis and its two components as the pools are driven apart by drift alone. Dashed lines are the Balding-Nichols predictions for each component separately, with no fitted parameter. Each measured component is offset from its prediction – divergence above, shared below – by sampling error in the pool frequencies; that offset narrows along the axis, and the text quantifies both it and the measured gap. The divergence term grows several-fold; the shared term pays for all of it, unit for unit; the total is flat. Nothing is selected here – this is what neutral divergence does.</figcaption>
</figure>
</div>
</div>
</div>
<p>The measured divergence sits above its prediction at every <code>fst</code>, and the measured shared term about the same distance below it. That is not drift, it is estimation. The pool frequencies are estimated from 25 and 25 sampled lines, and a frequency estimated from <span class="math inline">\(n\)</span> lines carries sampling variance <span class="math inline">\(V = pq/n\)</span>. Conditional on the true pool frequencies, <span class="math inline">\(\mathbb{E}[\hat y^2/2] = y^2/2 + (V_A + V_B)/2\)</span> and <span class="math inline">\(\mathbb{E}[2\hat{\bar p}(1 - \hat{\bar p})] = 2\bar p(1 - \bar p) - (V_A + V_B)/2\)</span>: equal and opposite, so the total estimated from sample frequencies is unbiased while each half is not.</p>
<p>The offset is not constant along the sweep. It is proportional to <span class="math inline">\(\mathbb{E}[p_Aq_A + p_Bq_B]\)</span>, which the pools themselves erode as they diverge, so it shrinks with <span class="math inline">\((1 - F_{ST})\)</span>: about 0.0072 per locus at <code>fst =</code> 0.02, down to 0.004 at <code>fst =</code> 0.45, against measured gaps of 0.007 and 0.0025.</p>
<p>Those two pairs do not agree equally well. At <code>fst =</code> 0.02 prediction and measurement are within 2% of each other; at <code>fst =</code> 0.45 the measured gap is 38% <em>below</em> the predicted offset. The formula gives an expectation; each row of the sweep is one draw of 2000 loci at one seed, and the scatter of that draw is not constant either. <span class="math inline">\(\mathrm{Var}(y)\)</span> is <span class="math inline">\(2F_{ST}\,p(1-p)\)</span>, so the per-locus divergence <span class="math inline">\(y^2/2\)</span> has a variance that grows with <span class="math inline">\(F_{ST}\)</span> while the number of loci averaging it stays fixed – the high-<code>fst</code> rows are the noisy ones, and the agreement at the bottom of the sweep is the more informative of the two. The offset is the right order and the right sign at both ends; it is not a per-point prediction, and nothing below rests on it being one.</p>
<p>What changes by an order of magnitude along the sweep is not the offset but the signal it sits on: at <code>fst = 0.02</code> the offset exceeds the predicted divergence of 0.0036, and by <code>fst = 0.45</code> it is a small fraction of it. A pool pair’s <em>apparent</em> divergence overstates its true divergence, most severely when the true divergence is small and the pools are few.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Every unit of divergence is paid for out of the shared term
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under neutral divergence the trade is exactly one for one. Drifting the pools apart does not create heterosis; it relocates it from the shared term to the divergence term. A programme that maximises <span class="math inline">\(F_{ST}\)</span> has bought nothing and spent its within-pool diversity to do it.</p>
<p>This is the mechanism behind <a href="08-pipeline-stages.html" class="quarto-xref"><span>Chapter 13</span></a> Trap 3. That section states the symptom – “<span class="math inline">\(F_{ST}\)</span> keeps rising as pools drift apart at loci that are <em>already</em> divergent, which buys no additional heterosis” – and points here for the reason. The two displays above are that reason.</p>
</div>
</div>
</section>
</section>
<section id="sec-heterosis-alignment" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="sec-heterosis-alignment"><span class="header-section-number">10.8</span> What actually buys heterosis</h2>
<p>If divergence per se is worth nothing, why do heterotic groups work?</p>
<p>Because real pools are not diverged at random with respect to <span class="math inline">\(d\)</span>. The divergence term is <span class="math inline">\(\sum_k d_k y_k^2 / 2\)</span>, a <em>weighted</em> sum. It grows when the loci that diverge are the loci that carry dominance; under drift the two are independent, which is exactly why the total was flat.</p>
<section id="alignment-is-a-covariance" class="level3" data-number="10.8.1">
<h3 data-number="10.8.1" class="anchored" data-anchor-id="alignment-is-a-covariance"><span class="header-section-number">10.8.1</span> Alignment is a covariance</h3>
<p>That sentence can be a number rather than a word. A sum of products is <span class="math inline">\(m\)</span> times a mean times a mean, plus <span class="math inline">\(m\)</span> times a covariance – the population covariance with divisor <span class="math inline">\(m\)</span>, which is why the chunk rescales <code>cov()</code>:</p>
<p><span class="math display">\[\sum_k d_k\,y_k^2 / 2 \;=\; \frac{m}{2}\Big[\, \bar d \; \overline{y^2}
  \;+\; \mathrm{cov}(d,\, y^2) \,\Big]\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> (pA <span class="sc">-</span> pB)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">divergence =</span> <span class="fu">sum</span>(d <span class="sc">*</span> y2 <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">from_parts =</span> ctx<span class="sc">$</span>m <span class="sc">/</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">mean</span>(d) <span class="sc">*</span> <span class="fu">mean</span>(y2) <span class="sc">+</span> <span class="fu">cov</span>(d, y2) <span class="sc">*</span> (ctx<span class="sc">$</span>m <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> ctx<span class="sc">$</span>m))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; divergence from_parts </span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   32.94521   32.94521</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The first bracketed term is what <span class="math inline">\(F_{ST}\)</span> can see: average divergence times average dominance. The second is what it cannot. <strong>Alignment is <span class="math inline">\(\mathrm{cov}(d, y^2)\)</span></strong>, and no statistic computed from allele frequencies alone can contain it, because <span class="math inline">\(d\)</span> does not appear in one.</p>
</section>
<section id="the-scenarios" class="level3" data-number="10.8.2">
<h3 data-number="10.8.2" class="anchored" data-anchor-id="the-scenarios"><span class="header-section-number">10.8.2</span> The scenarios</h3>
<p>Hold the pools fixed, hold <span class="math inline">\(F_{ST}\)</span> fixed, hold the multiset of dominance deviations fixed, and change only which locus gets which <span class="math inline">\(d_k\)</span>. <code>aligned</code> gives the largest <span class="math inline">\(d_k\)</span> to the largest <span class="math inline">\(y_k^2\)</span>, <code>anti-aligned</code> does the reverse, and <code>independent</code> is the draw as made:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mk <span class="ot">&lt;-</span> <span class="cf">function</span>(dec) { v <span class="ot">&lt;-</span> <span class="fu">numeric</span>(ctx<span class="sc">$</span>m); v[<span class="fu">order</span>(y2)] <span class="ot">&lt;-</span> <span class="fu">sort</span>(d, <span class="at">decreasing =</span> dec); v }</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>scen <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">`</span><span class="at">anti-aligned</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mk</span>(<span class="cn">TRUE</span>), <span class="st">`</span><span class="at">independent</span><span class="st">`</span> <span class="ot">=</span> d, <span class="st">`</span><span class="at">aligned</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mk</span>(<span class="cn">FALSE</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>al <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">names</span>(scen), <span class="cf">function</span>(n) {</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  h <span class="ot">&lt;-</span> <span class="fu">heterosis_partition</span>(pA, pB, scen[[n]])</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">scenario =</span> n, <span class="at">cor_d_y2 =</span> <span class="fu">cor</span>(scen[[n]], y2),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">shared =</span> h[[<span class="st">"shared"</span>]], <span class="at">divergence =</span> h[[<span class="st">"divergence"</span>]], <span class="at">total =</span> h[[<span class="st">"total"</span>]])</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>al<span class="sc">$</span>relative <span class="ot">&lt;-</span> al<span class="sc">$</span>total <span class="sc">/</span> al<span class="sc">$</span>total[al<span class="sc">$</span>scenario <span class="sc">==</span> <span class="st">"independent"</span>]</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">fmt</span>(al, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">scenario</th>
<th style="text-align: right;">cor_d_y2</th>
<th style="text-align: right;">shared</th>
<th style="text-align: right;">divergence</th>
<th style="text-align: right;">total</th>
<th style="text-align: right;">relative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">anti-aligned</td>
<td style="text-align: right;">-0.608</td>
<td style="text-align: right;">270.538</td>
<td style="text-align: right;">11.283</td>
<td style="text-align: right;">281.821</td>
<td style="text-align: right;">0.792</td>
</tr>
<tr class="even">
<td style="text-align: left;">independent</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">322.723</td>
<td style="text-align: right;">32.945</td>
<td style="text-align: right;">355.669</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">aligned</td>
<td style="text-align: right;">0.953</td>
<td style="text-align: right;">370.139</td>
<td style="text-align: right;">66.313</td>
<td style="text-align: right;">436.452</td>
<td style="text-align: right;">1.227</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(<span class="fu">rbind</span>(al<span class="sc">$</span>shared, al<span class="sc">$</span>divergence), <span class="at">beside =</span> <span class="cn">FALSE</span>,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">names.arg =</span> al<span class="sc">$</span>scenario, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#2166ac"</span>, <span class="st">"#b2182b"</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">ylab =</span> <span class="st">"expected heterosis"</span>, <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="fu">c</span>(<span class="st">"shared"</span>, <span class="st">"divergence"</span>), <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"#2166ac"</span>, <span class="st">"#b2182b"</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(bp, al<span class="sc">$</span>total, <span class="fu">sprintf</span>(<span class="st">"%.2fx"</span>, al<span class="sc">$</span>relative), <span class="at">pos =</span> <span class="dv">3</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">xpd =</span> <span class="cn">NA</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>(<span class="at">nx =</span> <span class="cn">NA</span>, <span class="at">ny =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05b-heterosis-dominance_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="1050"></p>
<figcaption>The same two pools, the same F_ST, and the same set of dominance deviations in all three bars – only their placement across loci differs. Expected heterosis moves by half again between the extremes. F_ST cannot see any of this, because d does not enter it.</figcaption>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(F_{ST}\)</span> is identical in all three columns – it is a function of the frequencies only, and <span class="math inline">\(d\)</span> never enters it. Expected heterosis ranges over a factor of 1.55.</p>
</section>
<section id="isolating-the-divergence-channel" class="level3" data-number="10.8.3">
<h3 data-number="10.8.3" class="anchored" data-anchor-id="isolating-the-divergence-channel"><span class="header-section-number">10.8.3</span> Isolating the divergence channel</h3>
<p>One honest qualification. Sorting <span class="math inline">\(d\)</span> against <span class="math inline">\(y^2\)</span> moves the <em>shared</em> term as well, because <span class="math inline">\(y^2\)</span> is not independent of <span class="math inline">\(2\bar p(1 - \bar p)\)</span>: a locus with a large frequency difference tends to sit at an intermediate mean frequency. Part of the effect above therefore arrives through the shared half, not the divergence half.</p>
<p>The channel can be separated. Permute <span class="math inline">\(d\)</span> only <em>within</em> groups of loci that share a value of the shared weight <span class="math inline">\(2\bar p(1 - \bar p)\)</span>. The shared term is then invariant by construction – exactly, not approximately – and whatever moves is the divergence channel alone:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>hz  <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> ((pA <span class="sc">+</span> pB) <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> (pA <span class="sc">+</span> pB) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>grp <span class="ot">&lt;-</span> <span class="fu">split</span>(<span class="fu">seq_len</span>(ctx<span class="sc">$</span>m), <span class="fu">round</span>(hz, <span class="dv">9</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>strat <span class="ot">&lt;-</span> <span class="cf">function</span>(dec) {</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">numeric</span>(ctx<span class="sc">$</span>m)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> grp) v[i[<span class="fu">order</span>(y2[i])]] <span class="ot">&lt;-</span> <span class="fu">sort</span>(d[i], <span class="at">decreasing =</span> dec)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  v</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>st <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">c</span>(<span class="at">aligned =</span> <span class="cn">FALSE</span>, <span class="st">`</span><span class="at">anti-aligned</span><span class="st">`</span> <span class="ot">=</span> <span class="cn">TRUE</span>), <span class="cf">function</span>(dec)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(<span class="fu">as.list</span>(<span class="fu">heterosis_partition</span>(pA, pB, <span class="fu">strat</span>(dec))))))</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">fmt</span>(st, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">shared</th>
<th style="text-align: right;">divergence</th>
<th style="text-align: right;">total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">aligned</td>
<td style="text-align: right;">322.7234</td>
<td style="text-align: right;">57.7211</td>
<td style="text-align: right;">380.4445</td>
</tr>
<tr class="even">
<td style="text-align: left;">anti-aligned</td>
<td style="text-align: right;">322.7234</td>
<td style="text-align: right;">14.4716</td>
<td style="text-align: right;">337.1949</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The shared column is identical to the digit; the divergence term still moves by a factor of 4 and the total by 13%. The alignment result survives its own control.</p>
</section>
</section>
<section id="reading-the-s1-panel-again" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="reading-the-s1-panel-again"><span class="header-section-number">10.9</span> Reading the S1 panel again</h2>
<p><a href="08-pipeline-stages.html" class="quarto-xref"><span>Chapter 13</span></a> logs <code>frac_opposite_fixed</code> and <code>mean_abs_delta_p</code> every cycle as stand-ins for heterosis potential. The sweep above says how good they are.</p>
<p><code>mean_sq_delta_p</code> is not a proxy at all. It is <span class="math inline">\(\overline{y^2}\)</span>, so half of it is the unweighted divergence term <span class="math inline">\(GD_{BS}\)</span>, exactly:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">half_mean_sq =</span> <span class="fu">mean</span>(sw<span class="sc">$</span>mean_sq_delta_p) <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">divergence   =</span> <span class="fu">mean</span>(sw<span class="sc">$</span>divergence))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; half_mean_sq   divergence </span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     0.039983     0.039983</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>What it cannot carry is the weighting by <span class="math inline">\(d\)</span>, which is the previous section’s point; the frequency half of the divergence term it reports without loss.</p>
<p><code>frac_opposite_fixed</code> is a different matter:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fmt</span>(sw[, <span class="fu">c</span>(<span class="st">"fst"</span>, <span class="st">"divergence"</span>, <span class="st">"frac_opposite_fixed"</span>, <span class="st">"mean_abs_delta_p"</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">"mean_sq_delta_p"</span>)], <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 28%">
<col style="width: 24%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">fst</th>
<th style="text-align: right;">divergence</th>
<th style="text-align: right;">frac_opposite_fixed</th>
<th style="text-align: right;">mean_abs_delta_p</th>
<th style="text-align: right;">mean_sq_delta_p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.0107</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.1138</td>
<td style="text-align: right;">0.0214</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.0171</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.1414</td>
<td style="text-align: right;">0.0341</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.0246</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.1715</td>
<td style="text-align: right;">0.0493</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.0433</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.2252</td>
<td style="text-align: right;">0.0867</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.0595</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.2589</td>
<td style="text-align: right;">0.1191</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.0846</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">0.3012</td>
<td style="text-align: right;">0.1693</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Up to <code>fst = 0.10</code> it is exactly zero – not one marker in 2000 qualifies – and it first exceeds 1% of markers at <code>fst = 0.30</code>, near the top of the sweep. It counts <em>near-fixed</em> opposite loci, and the divergence lives at intermediate frequency differences, which the threshold discards.</p>
<p><strong>Log <code>mean_sq_delta_p</code>.</strong> It is exact, it is monotone across the whole sweep, and it costs one squaring more than the statistic already being logged. <code>pool_complementarity()</code> and <code>s1_monitor()</code> return it.</p>
</section>
<section id="sec-heterosis-gca-sca" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="sec-heterosis-gca-sca"><span class="header-section-number">10.10</span> General and specific combining ability</h2>
<p>Everything so far has been about <span class="math inline">\(\mathbb{E}[H]\)</span>. Now the spread.</p>
<p>The same expansion that produced the shared/divergence split produces the combining-ability decomposition, with no new machinery and no model fitting. Let <span class="math inline">\(u_{ik} \in \{0, 1\}\)</span> be the genotype of pool-A line <span class="math inline">\(i\)</span> at locus <span class="math inline">\(k\)</span> and <span class="math inline">\(v_{jk}\)</span> that of pool-B line <span class="math inline">\(j\)</span>, and write each as its pool frequency plus a deviation, <span class="math inline">\(u = p_A + \delta u\)</span> and <span class="math inline">\(v = p_B + \delta v\)</span>. The per-locus heterozygosity of the cross, <span class="math inline">\(u + v - 2uv\)</span>, expands to</p>
<p><span class="math display">\[u + v - 2uv \;=\; \underbrace{p_A + p_B - 2p_Ap_B}_{\text{mean}}
  \;+\; \underbrace{(1 - 2p_B)\,\delta u}_{\text{parent A}}
  \;+\; \underbrace{(1 - 2p_A)\,\delta v}_{\text{parent B}}
  \;-\; \underbrace{2\,\delta u\, \delta v}_{\text{both}}\]</span></p>
<p>Four terms: one constant, one linear in each parent, one bilinear. Weight by <span class="math inline">\(d_k\)</span>, sum over loci, and the classical decomposition falls out,</p>
<p><span class="math display">\[H_{ij} = \mu + g^A_i + g^B_j + s_{ij}\]</span></p>
<p>with</p>
<p><span class="math display">\[g^A_i = \sum_k d_k (1 - 2p_{Bk})\,\delta u_{ik}, \qquad
  s_{ij} = -2 \sum_k d_k\, \delta u_{ik}\, \delta v_{jk}\]</span></p>
<p>and <span class="math inline">\(g^B_j\)</span> symmetrically. What is linear in one parent is general combining ability: it is carried into every cross that parent enters. What is bilinear depends on <em>which two</em> lines met, and is specific combining ability. Because the deviations are taken from each pool’s own line frequencies they sum to zero over that pool’s lines, which is what makes the three components mean zero and mutually orthogonal. <code>heterosis_gca_sca()</code> is that expansion and nothing more:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>heterosis_gca_sca</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; function (U, V, d) </span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; {</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     stopifnot(ncol(U) == ncol(V), length(d) == ncol(U))</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     pA &lt;- colMeans(U)</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     pB &lt;- colMeans(V)</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     cU &lt;- sweep(U, 2, pA)</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     cV &lt;- sweep(V, 2, pB)</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     list(mu = heterosis_expected(pA, pB, d), gca_A = drop(cU %*% </span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;         (d * (1 - 2 * pB))), gca_B = drop(cV %*% (d * (1 - 2 * </span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;         pA))), sca = -2 * (cU * rep(d, each = nrow(U))) %*% t(cV))</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; }</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; &lt;bytecode: 0xa7b6ab0a8&gt;</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; &lt;environment: namespace:hybdiv&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>It reconstructs every hybrid in the factorial exactly, and all three components are mean zero:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cs <span class="ot">&lt;-</span> <span class="fu">heterosis_gca_sca</span>(U, V, d)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>H  <span class="ot">&lt;-</span> <span class="fu">heterosis_value</span>(ctx<span class="sc">$</span>X, d)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>ia <span class="ot">&lt;-</span> ctx<span class="sc">$</span>ped<span class="sc">$</span>a</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>ib <span class="ot">&lt;-</span> ctx<span class="sc">$</span>ped<span class="sc">$</span>b <span class="sc">-</span> nA</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">max_residual =</span> <span class="fu">max</span>(<span class="fu">abs</span>(H <span class="sc">-</span> (cs<span class="sc">$</span>mu <span class="sc">+</span> cs<span class="sc">$</span>gca_A[ia] <span class="sc">+</span> cs<span class="sc">$</span>gca_B[ib] <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>                              cs<span class="sc">$</span>sca[<span class="fu">cbind</span>(ia, ib)]))),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu_vs_mean   =</span> <span class="fu">abs</span>(cs<span class="sc">$</span>mu <span class="sc">-</span> <span class="fu">mean</span>(H)),</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_gca_A   =</span> <span class="fu">mean</span>(cs<span class="sc">$</span>gca_A), <span class="at">mean_sca =</span> <span class="fu">mean</span>(cs<span class="sc">$</span>sca))</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  max_residual    mu_vs_mean    mean_gca_A      mean_sca </span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7.958079e-13  1.136868e-13 -4.796163e-16 -1.264766e-15</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This is not a decomposition that resembles the two-way analysis of variance. It <em>is</em> the two-way analysis of variance: <span class="math inline">\(\mu\)</span>, <span class="math inline">\(g^A\)</span> and <span class="math inline">\(g^B\)</span> are the grand mean and the row and column effects of the <span class="math inline">\(H_{ij}\)</span> table, and <span class="math inline">\(s_{ij}\)</span> is the interaction residual of the additive fit, to machine precision:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(<span class="fu">lm</span>(H <span class="sc">~</span> <span class="fu">factor</span>(ia) <span class="sc">+</span> <span class="fu">factor</span>(ib))) <span class="sc">-</span> cs<span class="sc">$</span>sca[<span class="fu">cbind</span>(ia, ib)]))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 6.966872e-12</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><span class="citation" data-cites="comstock1949">Comstock et al. (<a href="99-references.html#ref-comstock1949" role="doc-biblioref">1949</a>)</span> designed reciprocal recurrent selection around the distinction between these two components. The algebra above says what each one is made of – and the next section says which of the two their scheme actually selects on.</p>
<section id="gca-is-an-average-effect-in-the-other-pools-background" class="level3" data-number="10.10.1">
<h3 data-number="10.10.1" class="anchored" data-anchor-id="gca-is-an-average-effect-in-the-other-pools-background"><span class="header-section-number">10.10.1</span> GCA is an average effect in the other pool’s background</h3>
<p>Look at the weight on <span class="math inline">\(\delta u\)</span>: it is <span class="math inline">\(d_k(1 - 2p_{Bk})\)</span>, and <span class="math inline">\(1 - 2p_B\)</span> is <span class="math inline">\(q_B - p_B\)</span>. That is the frequency factor of the classical average effect of a gene substitution, <span class="math inline">\(a + d\,(q - p)\)</span> <span class="citation" data-cites="falconer1996">(<a href="99-references.html#ref-falconer1996" role="doc-biblioref">Falconer and Mackay 1996</a>, Ch. 7)</span>, with two differences: the additive part <span class="math inline">\(a\)</span> is absent, because it belongs to the parental mean and not to <span class="math inline">\(H\)</span>, and the frequencies are <strong>pool B’s</strong>, not pool A’s.</p>
<p>This is the whole reason combining ability is not a property of a line. A pool-A line’s alleles are always substituted into a pool-B background, so its general combining ability for heterosis is a dominance effect <em>evaluated at the tester pool’s frequencies</em>. Change the tester pool and every number changes. Two limits follow immediately:</p>
<ul>
<li>A locus at which the tester pool sits at <span class="math inline">\(p_B = 0.5\)</span> contributes <strong>exactly zero</strong> to <span class="math inline">\(g^A\)</span>, whatever <span class="math inline">\(\delta u_{ik}\)</span> is. It still contributes to <span class="math inline">\(g^B\)</span>, through <span class="math inline">\((1 - 2p_A)\,\delta v_{jk}\)</span>, and to <span class="math inline">\(s_{ij}\)</span>; what it cannot do is discriminate between pool-A parents.</li>
<li>A locus at which the tester pool is fixed, <span class="math inline">\(p_B \in \{0, 1\}\)</span>, has <span class="math inline">\(\delta v \equiv 0\)</span>, so it contributes <span class="math inline">\(\pm d_k\,\delta u_{ik}\)</span> to <span class="math inline">\(g^A\)</span> and nothing to either <span class="math inline">\(g^B\)</span> or <span class="math inline">\(s_{ij}\)</span>. The cross is then predictable from the pool-A parent by itself.</li>
</ul>
<p>Between those two limits sits every real programme, and <a href="#sec-heterosis-relocation" class="quarto-xref"><span>Section 10.11</span></a> is about which limit divergence pushes it towards.</p>
<p>This is also the exact sense in which <span class="citation" data-cites="comstock1949">Comstock et al. (<a href="99-references.html#ref-comstock1949" role="doc-biblioref">1949</a>)</span>’s scheme is built on the decomposition. Reciprocal recurrent selection evaluates each pool-A candidate on its cross performance against a <em>sample of the opposite pool</em>, and symmetrically for pool B. Averaging over testers removes <span class="math inline">\(s_{ij}\)</span>, so of the heterosis in the decomposition above only <span class="math inline">\(g^A_i\)</span> survives as a contrast between pool-A candidates. Note what that does <em>not</em> say: cross performance is a genotypic value, not a mid-parent difference, so it also carries the candidate’s own additive contribution – the part that cancelled out of <span class="math inline">\(H\)</span> in the mid-parent derivation above and is not in this decomposition at all. Selection on testcross means therefore acts on the additive part and <span class="math inline">\(g^A_i\)</span> together. What the algebra here delimits is the dominance share of that response, and it says the share is general combining ability against the tester pool.</p>
</section>
<section id="sca-is-minus-twice-a-weighted-parental-inner-product" class="level3" data-number="10.10.2">
<h3 data-number="10.10.2" class="anchored" data-anchor-id="sca-is-minus-twice-a-weighted-parental-inner-product"><span class="header-section-number">10.10.2</span> SCA is minus twice a weighted parental inner product</h3>
<p>The bilinear term is <span class="math inline">\(s_{ij} = -2\sum_k d_k\,\delta u_{ik}\,\delta v_{jk}\)</span>: minus twice the <span class="math inline">\(d\)</span>-weighted inner product of the two parents’ <em>centred</em> genotypes, a covariance up to the factor <span class="math inline">\(1/m\)</span>. For <span class="math inline">\(d_k &gt; 0\)</span>, two parents that deviate from their pools in the same direction have a positive inner product and therefore a <strong>negative</strong> SCA.</p>
<p>Read in words: two parents that resemble each other – after removing what is typical of each pool – cross badly, and the resemblance that counts is weighted by <span class="math inline">\(d\)</span>, not by marker count. Similarity enters negatively throughout this chapter – <span class="math inline">\(1 - \theta_{AB}\)</span>, <span class="math inline">\(d\,m\,(1 - f^L_{ab})\)</span> – but everywhere else it is similarity measured against a fixed base. Here it is measured against each pool’s own mean, which is what makes the term specific to a <em>pair</em> rather than a property either parent carries into all its crosses.</p>
<p>It is also <a href="#sec-heterosis-distance" class="quarto-xref"><span>Section 10.6</span></a> again. Since <span class="math inline">\(\mu\)</span>, <span class="math inline">\(g^A\)</span> and <span class="math inline">\(g^B\)</span> are the grand, row and column means of the <span class="math inline">\(H_{ij}\)</span> table, <span class="math inline">\(s_{ij}\)</span> is the double-centred <span class="math inline">\(H\)</span> matrix. Under flat <span class="math inline">\(d\)</span>, <span class="math inline">\(H_{ij} = d\,m\,(1 - f^L_{ij})\)</span>, and double-centring annihilates the constant and flips the sign of what remains:</p>
<p><span class="math display">\[s_{ij} \;=\; -\,d\,m \cdot \mathrm{DC}\big(f^L\big)_{ij},\]</span></p>
<p>with <span class="math inline">\(\mathrm{DC}(M)_{ij} = M_{ij} - \bar M_{i\cdot} - \bar M_{\cdot j} + \bar
M_{\cdot\cdot}\)</span> over the <span class="math inline">\(A \times B\)</span> block. The factor <span class="math inline">\(-dm\)</span> is not cosmetic: <span class="math inline">\(s_{ij}\)</span> is on the trait scale and <span class="math inline">\(f^L\)</span> is a probability, and the minus is the same minus as in <span class="math inline">\(-2\sum_k d_k \delta u\, \delta v\)</span> – more coancestry than the two margins predict means <em>less</em> SCA. So the coancestry kernel determines SCA under exactly the condition it determines heterosis, up to that constant, and stops doing so under exactly the same condition: a <span class="math inline">\(d\)</span> that varies across loci.</p>
</section>
<section id="the-variance-components" class="level3" data-number="10.10.3">
<h3 data-number="10.10.3" class="anchored" data-anchor-id="the-variance-components"><span class="header-section-number">10.10.3</span> The variance components</h3>
<p>Because the three components are orthogonal, the variance of heterosis over the factorial splits with them. Under the sampling model of the simulation – each line’s genotype an independent Bernoulli(<span class="math inline">\(p_{Ak}\)</span>) draw at every locus, so unrelated lines and linkage equilibrium within each pool – each piece has a closed form in the pool frequencies:</p>
<p><span class="math display">\[\sigma^2_{GCA_A} = \sum_k d_k^2\,(1 - 2p_{Bk})^2\,p_{Ak}q_{Ak},
\qquad
\sigma^2_{SCA} = 4 \sum_k d_k^2\,p_{Ak}q_{Ak}\,p_{Bk}q_{Bk}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>qa <span class="ot">&lt;-</span> pA <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pA)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>qb <span class="ot">&lt;-</span> pB <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pB)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fmt</span>(<span class="fu">data.frame</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">component =</span> <span class="fu">c</span>(<span class="st">"GCA_A"</span>, <span class="st">"GCA_B"</span>, <span class="st">"SCA"</span>),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">observed  =</span> <span class="fu">c</span>(<span class="fu">var</span>(cs<span class="sc">$</span>gca_A), <span class="fu">var</span>(cs<span class="sc">$</span>gca_B), <span class="fu">var</span>(<span class="fu">as.vector</span>(cs<span class="sc">$</span>sca))),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">closed_form =</span> <span class="fu">c</span>(<span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pB)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> qa),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pA)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> qb),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                  <span class="dv">4</span> <span class="sc">*</span> <span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> qa <span class="sc">*</span> qb))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">component</th>
<th style="text-align: right;">observed</th>
<th style="text-align: right;">closed_form</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GCA_A</td>
<td style="text-align: right;">32.00</td>
<td style="text-align: right;">35.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCA_B</td>
<td style="text-align: right;">35.63</td>
<td style="text-align: right;">38.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCA</td>
<td style="text-align: right;">70.38</td>
<td style="text-align: right;">71.48</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The closed forms take the sample frequencies as the pool frequencies; the observed column is one realisation of them. The GCA rows are variances over 25 lines, whose relative sampling error is about <span class="math inline">\(\sqrt{2/n} \approx\)</span> 28%, and the agreement is within that.</p>
<p>Note what each one requires. <span class="math inline">\(\sigma^2_{SCA}\)</span> carries <span class="math inline">\(p_Aq_A\,p_Bq_B\)</span>: it needs <strong>both</strong> pools to be polymorphic. Fix either pool at a locus and that locus contributes no specific combining ability at all, whatever its <span class="math inline">\(d_k\)</span>. Within-pool diversity is not merely something the diversity constraint defends; it is the raw material of SCA.</p>
</section>
</section>
<section id="sec-heterosis-relocation" class="level2" data-number="10.11">
<h2 data-number="10.11" class="anchored" data-anchor-id="sec-heterosis-relocation"><span class="header-section-number">10.11</span> Divergence destroys SCA faster than it builds GCA</h2>
<p>Put the two closed forms next to the drift argument of <a href="#sec-heterosis-flat" class="quarto-xref"><span>Section 10.7</span></a> and the variance tells a different story from the mean. The mean was flat; the variance is not, and it does not merely change shape.</p>
<p>Under Balding-Nichols, <span class="math inline">\(\mathbb{E}[p_Aq_A] = p(1-p)(1 - F_{ST})\)</span> and <span class="math inline">\(\mathbb{E}[(1 - 2p_B)^2] = (1-2p)^2 + 4F_{ST}\,p(1-p)\)</span>, and <span class="math inline">\(p_A\)</span> and <span class="math inline">\(p_B\)</span> are independent given the ancestral <span class="math inline">\(p\)</span>. Per locus, in expectation over the draw,</p>
<p><span class="math display">\[\mathbb{E}\big[\sigma^2_{SCA,k}\big] = 4d_k^2\,p^2(1-p)^2\,(1 - F_{ST})^2,
\qquad
\mathbb{E}\big[\sigma^2_{GCA_A,k}\big] = d_k^2\,p(1-p)\,(1 - F_{ST})
  \left[(1-2p)^2 + 4F_{ST}\,p(1-p)\right]\]</span></p>
<p>Read the two expressions before reading the sweep, because they already say what it will show.</p>
<p>Both carry the erosion factor <span class="math inline">\((1 - F_{ST})\)</span>, and both are <strong>zero at <span class="math inline">\(F_{ST} = 1\)</span></strong>: a pool fixed at every locus has no two lines that differ, so it has no combining-ability variance of either kind. Divergence therefore cannot transfer variance from one component to the other indefinitely; it destroys both in the limit. SCA carries the factor twice, because it needs both pools polymorphic at the same locus. GCA carries it once, multiplied by the tester factor <span class="math inline">\((1 - 2p_B)^2\)</span>, whose expectation <em>grows</em> with <span class="math inline">\(F_{ST}\)</span>.</p>
<p>The two expressions therefore behave differently in <span class="math inline">\(F_{ST}\)</span>. The SCA expression is convex and decreasing on <span class="math inline">\([0, 1]\)</span>: it is a positive constant times <span class="math inline">\((1 - F_{ST})^2\)</span>, so it only ever falls. The GCA expression is a <em>concave</em> parabola, its <span class="math inline">\(F_{ST}^2\)</span> coefficient being <span class="math inline">\(-4d_k^2p_k^2(1-p_k)^2\)</span>, and differentiating it gives the only turnover in this section. GCA variance rises from <span class="math inline">\(F_{ST} = 0\)</span> at a locus if and only if <span class="math inline">\(8p(1-p) &gt; 1\)</span>, that is <span class="math inline">\(\tfrac12(1 - 1/\sqrt2) &lt; p &lt; \tfrac12(1 + 1/\sqrt2)\)</span>, and turns over at</p>
<p><span class="math display">\[F^\star_k = \frac{8p_k(1-p_k) - 1}{8p_k(1-p_k)},\]</span></p>
<p>which is negative outside that interval – at such loci GCA variance falls from the start. A sum of concave parabolas is a concave parabola, and its maximum works out to the <span class="math inline">\(d_k^2\,(p_kq_k)^2\)</span>-weighted mean of the <span class="math inline">\(F^\star_k\)</span>. Whether that mean lands inside <span class="math inline">\([0, 1]\)</span> is a property of the ancestral frequency distribution, not a theorem: pools founded mostly at extreme frequencies would put it below zero and GCA variance would decline monotonically. Under the <span class="math inline">\(U(0.05, 0.95)\)</span> ancestral draw used here enough loci sit in the interval to place it inside the range, which is why the sweep below straddles a peak. The sweep’s grid can show that the peak is interior; it cannot locate it.</p>
<p>What is monotone is the ratio,</p>
<p><span class="math display">\[\frac{\mathbb{E}[\sigma^2_{SCA,k}]}{\mathbb{E}[\sigma^2_{GCA_A,k}]}
  = \frac{4p(1-p)\,(1 - F_{ST})}{(1-2p)^2 + 4F_{ST}\,p(1-p)},\]</span></p>
<p>which falls in <span class="math inline">\(F_{ST}\)</span> at every locus. So the defensible statement is about the <em>share</em>, not about a transfer. Expected heterosis, we already know, does not move at all. Sweeping the pools apart – same ancestral frequencies, fresh Balding-Nichols draws at each <code>fst</code>, as in <a href="#sec-heterosis-flat" class="quarto-xref"><span>Section 10.7</span></a> – and evaluating the closed forms on the realised frequencies:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>reloc <span class="ot">&lt;-</span> <span class="cf">function</span>(fst) {</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  cf <span class="ot">&lt;-</span> <span class="fu">modifyList</span>(book_cfg, <span class="fu">list</span>(<span class="at">fst =</span> fst, <span class="at">seed =</span> <span class="dv">5</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  Pf <span class="ot">&lt;-</span> <span class="fu">pool_freqs</span>(<span class="fu">simulate_lines</span>(cf) <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="fu">c</span>(cf<span class="sc">$</span>n_pool_A, cf<span class="sc">$</span>n_pool_B)))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> Pf[<span class="st">"A"</span>, ]; b <span class="ot">&lt;-</span> Pf[<span class="st">"B"</span>, ]</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  va <span class="ot">&lt;-</span> <span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> b)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> a <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> a))</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  vb <span class="ot">&lt;-</span> <span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> a)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> b <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> b))</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  vs <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">*</span> <span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> a <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> a) <span class="sc">*</span> b <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> b))</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">fst =</span> fst, <span class="at">var_GCA =</span> va <span class="sc">+</span> vb, <span class="at">var_SCA =</span> vs,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">frac_SCA =</span> vs <span class="sc">/</span> (va <span class="sc">+</span> vb <span class="sc">+</span> vs))</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>rl <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">c</span>(<span class="fl">0.02</span>, <span class="fl">0.05</span>, <span class="fl">0.10</span>, <span class="fl">0.15</span>, <span class="fl">0.20</span>, <span class="fl">0.30</span>, <span class="fl">0.45</span>), reloc))</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="fu">fmt</span>(rl, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">fst</th>
<th style="text-align: right;">var_GCA</th>
<th style="text-align: right;">var_SCA</th>
<th style="text-align: right;">frac_SCA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">60.047</td>
<td style="text-align: right;">91.807</td>
<td style="text-align: right;">0.605</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">62.025</td>
<td style="text-align: right;">87.941</td>
<td style="text-align: right;">0.586</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">68.630</td>
<td style="text-align: right;">75.503</td>
<td style="text-align: right;">0.524</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">71.230</td>
<td style="text-align: right;">67.599</td>
<td style="text-align: right;">0.487</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">77.956</td>
<td style="text-align: right;">63.166</td>
<td style="text-align: right;">0.448</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">80.630</td>
<td style="text-align: right;">45.875</td>
<td style="text-align: right;">0.363</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">77.894</td>
<td style="text-align: right;">27.767</td>
<td style="text-align: right;">0.263</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rl<span class="sc">$</span>fst, rl<span class="sc">$</span>var_GCA, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#1b7837"</span>,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">range</span>(<span class="dv">0</span>, rl<span class="sc">$</span>var_GCA, rl<span class="sc">$</span>var_SCA),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"target fst between pools"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"variance of heterosis over the factorial"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(rl<span class="sc">$</span>fst, rl<span class="sc">$</span>var_SCA, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">15</span>, <span class="at">col =</span> <span class="st">"#b2182b"</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"right"</span>, <span class="fu">c</span>(<span class="st">"GCA (both pools)"</span>, <span class="st">"SCA"</span>), <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">15</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#1b7837"</span>, <span class="st">"#b2182b"</span>))</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05b-heterosis-dominance_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="1050"></p>
<figcaption>The same neutral divergence sweep, read through the combining-ability decomposition rather than through the mean. Expected heterosis is flat across this entire range (previous figure); its decomposition is not. Specific combining ability falls steeply throughout. General combining ability rises, by much less than SCA loses, and itself turns over inside the range – both components vanish at F_ST = 1. The two curves do not sum to a constant: most of the SCA variance lost is destroyed rather than relocated, and the exact percentages are in the text.</figcaption>
</figure>
</div>
</div>
</div>
<p>Take the three columns in order, because the headline is in the arithmetic between them.</p>
<p>SCA variance falls by 70% across the sweep, a drop of 64 units. GCA variance ends 30% above where it started, a gain of 17.8 units, and peaks at an <code>fst</code> of 0.3 – interior, as the ancestral distribution used here leads one to expect, though a grid whose neighbouring points are 0.2 and 0.45 locates the peak only to that interval and cannot resolve it further. So the GCA gain recovers about 28% of what SCA lost. The rest is gone: total variance in heterosis over the factorial falls from 151.9 to 105.7, a 30% decline, while the mean stays fixed throughout.</p>
<p>Read those four percentages as one realisation, not as constants. They come from a single pair of seeds – <code>seed = 5</code> for the pool frequencies, <code>set.seed(4)</code> for <span class="math inline">\(d\)</span> – with no replication and no dispersion reported, and they will move if either changes. What does not depend on the seed is the direction, which is already in the two closed forms above: <span class="math inline">\(\sigma^2_{SCA}\)</span> is a positive multiple of <span class="math inline">\((1 - F_{ST})^2\)</span> and can only fall, and both components vanish at <span class="math inline">\(F_{ST} = 1\)</span>, so no amount of neutral divergence can hold the total up. The ordering of the columns is algebra; their magnitudes are this draw.</p>
<p>The share of that variance which is specific falls from 0.605 to 0.263. That statement – about the share – is the one the sweep supports; “the dominance expressed as SCA reappears as GCA” is not, and the two columns above are why.</p>
<p>The share result itself is not new. <span class="citation" data-cites="reif2007">Reif et al. (<a href="99-references.html#ref-reif2007" role="doc-biblioref">2007</a>)</span> prove that the ratio of dominance to additive variance in a hybrid population falls as its two parent populations diverge, and conclude that superior hybrids then become predictable from general combining ability effects. That half of this section is theirs. What the sweep adds is the denominator, which a ratio hides: a ratio can fall because its numerator falls, because its denominator rises, or both, and the columns above say which. Here the numerator collapses and the denominator recovers only part of it, so the share falls and the total falls with it.</p>
<blockquote class="blockquote">
<p><em>Neutral</em> divergence – drift, the only kind on this sweep – does not buy expected heterosis, and it does not move heterosis from one combining-ability component into the other. It <strong>shrinks the part of hybrid variation that only a cross can reveal</strong>, destroying SCA variance faster than it builds GCA variance. An additive model looks better against diverged pools mainly because there is less left for it to miss. Divergence that is <em>aligned</em> with dominance is a different matter and <a href="#sec-heterosis-alignment" class="quarto-xref"><span>Section 10.8</span></a> is where it is measured; the sweep here holds alignment at zero by construction.</p>
</blockquote>
<p>This sharpens a question <a href="08b-genomic-prediction.html" class="quarto-xref"><span>Chapter 14</span></a> had to leave open. That chapter fits one additive effect per marker and notes that such a model cannot represent SCA at all. The sweep says how large the unrepresentable share is, and how it moves: against poorly separated pools most of the variance in heterosis is specific; against well separated ones a minority is. These are shares of the variance in <em>heterosis</em>, not of total hybrid value, whose parental-mean part is additive at every <span class="math inline">\(F_{ST}\)</span>. <span class="citation" data-cites="technow2014">Technow et al. (<a href="99-references.html#ref-technow2014" role="doc-biblioref">2014</a>)</span> report high accuracy for additive hybrid prediction in established, clearly separated dent and flint pools, which is the regime where this model puts the specific share at its lowest – consistent with the mechanism, though a single observational study in one crop cannot test it.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>A smaller SCA share is not a better programme, and this is not a licence to maximise <span class="math inline">\(F_{ST}\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Three things stay true at every point on that sweep. Expected heterosis does not change. The within-pool diversity spent to buy the divergence is spent for good. And <span class="math inline">\(\sigma^2_{SCA} \to 0\)</span> is the limit in which no cross is better than its parents predict – there is nothing left to <em>find</em> by testing combinations, which is the activity the whole factorial exists to support. Past the peak of the GCA curve even the predictable half shrinks: at <span class="math inline">\(F_{ST} = 1\)</span> there is no combining-ability variance of either kind, because no two lines in a pool differ.</p>
<p>The falling SCA share is therefore a fact about what a predictor can express, not a gain. A programme reading it as one would be congratulating itself on having less to predict.</p>
<p>So this is a second, independent reason for <a href="08-pipeline-stages.html" class="quarto-xref"><span>Chapter 13</span></a> Trap 3’s prescription to hold <span class="math inline">\(F_{ST}\)</span> in a band rather than at a maximum. <a href="#sec-heterosis-flat" class="quarto-xref"><span>Section 10.7</span></a> gave the diversity-side reason. This is the prediction-side one, and it points the same way.</p>
</div>
</div>
<section id="what-this-says-about-ranking-crosses" class="level3" data-number="10.11.1">
<h3 data-number="10.11.1" class="anchored" data-anchor-id="what-this-says-about-ranking-crosses"><span class="header-section-number">10.11.1</span> What this says about ranking crosses</h3>
<p>The F1 of two fixed lines is genetically uniform, so the progeny-variance term that drives the usefulness criterion at <a href="08-pipeline-stages.html" class="quarto-xref"><span>Chapter 13</span></a> S2 is zero for the hybrid itself, and cross ranking reduces to ranking means. That is true, and it is why this book ranks hybrids on an index rather than on <span class="math inline">\(\mu + i h \sigma\)</span>.</p>
<p>It does not follow that the ranking is easy. The <em>mean</em> of an F1 contains an SCA term that an additive <span class="math inline">\(\mathbf{G}\)</span> omits entirely, and <a href="#sec-heterosis-relocation" class="quarto-xref"><span>Section 10.11</span></a> sized its share of the variance in heterosis: a majority of it against weakly separated pools, a minority against well separated ones, and zero only at the degenerate limit where one pool is fixed at every locus. The progeny variance collapses; the dominance deviation does not.</p>
</section>
</section>
<section id="what-this-does-not-change" class="level2" data-number="10.12">
<h2 data-number="10.12" class="anchored" data-anchor-id="what-this-does-not-change"><span class="header-section-number">10.12</span> What this does not change</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The diversity constraint stays additive
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nothing in this chapter reopens the optimisation. <span class="math inline">\(\theta\)</span>, <span class="math inline">\(GD\)</span> and <span class="math inline">\(\alpha\)</span> are computed on molecular coancestry and are functions of the frequencies alone; no dominance term enters them, and <a href="09-optimal-contributions.html" class="quarto-xref"><span>Chapter 15</span></a>, <a href="10-combinatorial-selection.html" class="quarto-xref"><span>Chapter 16</span></a> and <a href="10b-advanced-selection.html" class="quarto-xref"><span>Chapter 17</span></a> are untouched. The combining-ability split of <a href="#sec-heterosis-gca-sca" class="quarto-xref"><span>Section 10.10</span></a> sits outside the constraint for the same reason: it is a statement about the objective, not about the feasible set.</p>
<p>A dominance model changes the <strong>mean-performance ranking</strong>, not the diversity term. <a href="12-case-study.html" class="quarto-xref"><span>Chapter 21</span></a> states the same separation from the other side. Do not conflate them, and do not read this chapter as licence to put a heterosis term inside the constraint.</p>
</div>
</div>
<p>What it does change is the interpretation of the constraint’s output. Two plans with the same <span class="math inline">\(\alpha\)</span> and the same <span class="math inline">\(GD_{BS}\)</span> can differ in expected heterosis by half again, if one of them concentrated its divergence on the dominance loci – that is the scenario table of <a href="#sec-heterosis-alignment" class="quarto-xref"><span>Section 10.8</span></a>, whose three columns share every frequency-based statistic. The partition cannot distinguish them. Only an estimate of <span class="math inline">\(d\)</span> can.</p>
<section id="what-it-would-take-to-use-d" class="level3" data-number="10.12.1">
<h3 data-number="10.12.1" class="anchored" data-anchor-id="what-it-would-take-to-use-d"><span class="header-section-number">10.12.1</span> What it would take to use <span class="math inline">\(d\)</span></h3>
<p><a href="06-metric-catalogue.html" class="quarto-xref"><span>Chapter 11</span></a> leaves a weight <span class="math inline">\(\lambda\)</span> undetermined between within- and between-pool diversity and observes that the ratio of the two heterosis terms is what <span class="math inline">\(\lambda\)</span> is trying to express. This chapter can now say what would have to be estimated to set it, and it is not much:</p>
<ul>
<li><strong><span class="math inline">\(\lambda\)</span> needs two covariances, not <span class="math inline">\(d\)</span> itself.</strong> Each heterosis term is <span class="math inline">\(m\)</span> times a mean times a mean plus a covariance, so their ratio needs <span class="math inline">\(\mathrm{cov}(d, y^2)\)</span> and <span class="math inline">\(\mathrm{cov}(d, 2\bar p(1 - \bar p))\)</span>, each relative to <span class="math inline">\(\bar d\)</span>, on top of what the frequencies already give. A programme does not need per-locus dominance deviations to weight the two diversity terms against each other; it needs to know whether its divergence is landing on its dominance loci.</li>
<li><strong>Ranking crosses needs more.</strong> <span class="math inline">\(s_{ij}\)</span> is a <span class="math inline">\(d\)</span>-weighted inner product between two specific parents, so it needs the deviations locus by locus. This is the extension <a href="12-case-study.html" class="quarto-xref"><span>Chapter 21</span></a> names and the book does not attempt.</li>
<li><strong>Fitting it needs a factorial, and a testcross file is not one.</strong> The decomposition above is the two-way layout with <em>identified</em> rows and columns: each pool-A line crossed to several named pool-B lines and each pool-B line to several named pool-A lines, which is what makes <span class="math inline">\(g^A\)</span>, <span class="math inline">\(g^B\)</span> and <span class="math inline">\(s_{ij}\)</span> separately estimable and what the <code>lm()</code> above fits. Testcrosses against a single common tester give only a column of <span class="math inline">\(\mu + g^A_i + \text{(one tester's
contribution)}\)</span> – no SCA is identifiable, because there is no second tester to contrast against. Programmes that already cross two pools in a partial factorial for hybrid evaluation have the layout; programmes that testcross against one inbred tester per pool do not.</li>
</ul>
</section>
</section>
<section id="where-this-connects" class="level2" data-number="10.13">
<h2 data-number="10.13" class="anchored" data-anchor-id="where-this-connects"><span class="header-section-number">10.13</span> Where this connects</h2>
<p><a href="02-subdivided.html" class="quarto-xref"><span>Chapter 2</span></a> supplied the partition and <a href="06-metric-catalogue.html" class="quarto-xref"><span>Chapter 11</span></a> will use it; this chapter supplies the reason the <span class="math inline">\(GD_{BS}\)</span> component is singled out for protection, and the reason protecting it is not the same as maximising it. <a href="08-pipeline-stages.html" class="quarto-xref"><span>Chapter 13</span></a> Trap 3 already recommended holding <span class="math inline">\(F_{ST}\)</span> in a band: <a href="#sec-heterosis-flat" class="quarto-xref"><span>Section 10.7</span></a> is why a band, and <a href="#sec-heterosis-alignment" class="quarto-xref"><span>Section 10.8</span></a> is what to watch instead of the band. <a href="#sec-heterosis-distance" class="quarto-xref"><span>Section 10.6</span></a> closes the loop with the coancestry kernel of <a href="01-coancestry.html" class="quarto-xref"><span>Chapter 1</span></a>: under flat dominance, the diversity matrix and the heterosis prediction are the same object.</p>
<p><a href="08b-genomic-prediction.html" class="quarto-xref"><span>Chapter 14</span></a> is the chapter this one supplies a missing term to. It predicts breeding values with an additive model on a trait that is additive by construction, and lists specific combining ability first among what it does not model. <a href="#sec-heterosis-gca-sca" class="quarto-xref"><span>Section 10.10</span></a> is where that term comes from and <a href="#sec-heterosis-relocation" class="quarto-xref"><span>Section 10.11</span></a> is what share of the variance in heterosis it holds; both are derived here rather than fitted, because on a simulated <span class="math inline">\(d\)</span> they can be.</p>
<p>It also gives a reason why a heterotic <em>pattern</em> – which pool crosses well onto which – is not recoverable from how far apart the pools have drifted: <a href="#sec-heterosis-alignment" class="quarto-xref"><span>Section 10.8</span></a>’s three scenarios share every frequency-based statistic and differ by half again in expected heterosis. <span class="citation" data-cites="white2020">White et al. (<a href="99-references.html#ref-white2020" role="doc-biblioref">2020</a>)</span> describe heterotic patterns and diversity separately in North American proprietary dent germplasm; this chapter says why the two need describing separately.</p>
<p>Forward, the alignment result is the argument for <a href="11b-diversity-across-cycles.html" class="quarto-xref"><span>Chapter 19</span></a>. Drift moves frequencies independently of <span class="math inline">\(d\)</span>, and selection on a line’s own performance cannot respond to <span class="math inline">\(d\)</span> either, because an inbred line’s dominance contribution is exactly zero (<a href="#sec-heterosis-id" class="quarto-xref"><span>Section 10.5</span></a>) – which leaves selection on <em>cross</em> performance as the only process in this model that can move frequencies in a way that depends on where the dominance is. The alignment between divergence and dominance is therefore something each cycle either builds or erodes, not a standing asset. A one-cycle constraint cannot see that, and neither can <span class="math inline">\(F_{ST}\)</span>. <a href="04c-alphasimr-pipeline.html" class="quarto-xref"><span>Chapter 7</span></a> runs that loop on a dominance trait and is the pipeline this chapter’s algebra describes.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-comstock1949" class="csl-entry" role="listitem">
Comstock, R. E., H. F. Robinson, and P. H. Harvey. 1949. <span>“A Breeding Procedure Designed to Make Maximum Use of Both General and Specific Combining Ability.”</span> <em>Agronomy Journal</em> 41 (8): 360–67. <a href="https://doi.org/10.2134/agronj1949.00021962004100080006x">https://doi.org/10.2134/agronj1949.00021962004100080006x</a>.
</div>
<div id="ref-falconer1996" class="csl-entry" role="listitem">
Falconer, Douglas S., and Trudy F. C. Mackay. 1996. <em>Introduction to Quantitative Genetics</em>. 4th ed. Longman.
</div>
<div id="ref-labroo2021" class="csl-entry" role="listitem">
Labroo, M. R., A. J. Studer, and J. E. Rutkoski. 2021. <span>“Heterosis and Hybrid Crop Breeding: A Multidisciplinary Review.”</span> <em>Frontiers in Genetics</em> 12. <a href="https://doi.org/10.3389/fgene.2021.643761">https://doi.org/10.3389/fgene.2021.643761</a>.
</div>
<div id="ref-mackay2020" class="csl-entry" role="listitem">
Mackay, Ian J., James Cockram, and Phil Howell. 2021. <span>“Understanding the Classics: The Unifying Concepts of Transgressive Segregation, Inbreeding Depression and Heterosis and Their Central Relevance for Crop Breeding.”</span> <em>Plant Biotechnology Journal</em> 19 (1): 26–34. <a href="https://doi.org/10.1111/pbi.13481">https://doi.org/10.1111/pbi.13481</a>.
</div>
<div id="ref-reif2007" class="csl-entry" role="listitem">
Reif, Jochen C., Franz-Michael Gumpert, Sandra Fischer, and Albrecht E. Melchinger. 2007. <span>“Impact of Interpopulation Divergence on Additive and Dominance Variance in Hybrid Populations.”</span> <em>Genetics</em> 176 (3): 1931–34. <a href="https://doi.org/10.1534/genetics.107.074146">https://doi.org/10.1534/genetics.107.074146</a>.
</div>
<div id="ref-technow2014" class="csl-entry" role="listitem">
Technow, F., T. A. Schrag, W. Schipprack, E. Bauer, H. Simianer, and A. E. Melchinger. 2014. <span>“Genome Properties and Prospects of Genomic Prediction of Hybrid Performance in a Breeding Program of Maize.”</span> <em>Genetics</em> 197 (4): 1343–55. <a href="https://doi.org/10.1534/genetics.114.165860">https://doi.org/10.1534/genetics.114.165860</a>.
</div>
<div id="ref-white2020" class="csl-entry" role="listitem">
White, M. R., M. A. Mikel, N. de Leon, and S. M. Kaeppler. 2020. <span>“Diversity and Heterotic Patterns in <span>North</span> <span>American</span> Proprietary Dent Maize Germplasm.”</span> <em>Crop Science</em> 60. <a href="https://doi.org/10.1002/csc2.20050">https://doi.org/10.1002/csc2.20050</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-genomic-era.html" class="pagination-link" aria-label="Diversity metrics in the genomic era">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Diversity metrics in the genomic era</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-metric-catalogue.html" class="pagination-link" aria-label="A catalogue of metrics on `f`">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">A catalogue of metrics on <code>f</code></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>